### ISSUE TITLE
Quoted trigger doesn't work with non word characters

### ISSUE THREAD

**Issue by hl037** [SirVer/ultisnips#1000]
(Tested on vim and neovim)

Quoted triggers don't work if there are characters such as `(`, `[` and certainly others. For example, let's say this snippet (a python one) :

```
snippet ( "gen_comp" i
( $3 for $1 in $2 ) $4
endsnippet
```

It works fine, you press `(` then `<tab>` and it expends to a list comprehension. However, if you put it between quotes (or any other character) : 

```
snippet '(' "gen_comp" i
( $3 for $1 in $2 ) $4
endsnippet
```

Then, it won't work (at least with my setup).

note, this won't work either : 

```
snippet !(! "gen_comp" i
( $3 for $1 in $2 ) $4
endsnippet
```

I need this feature because I would like this snippet : 

```
snippet '( ' "gen_comp" i
( $3 for $1 in $2 ) $4
endsnippet
```

**Comment by hl037** [comment]
...That is what I ended up with... But it's still a bug or a misdocumentation ;)

**Comment by SirVer** [comment]
Actually, this is working as documented as I can read it: quoting can only be used for multiword trigger and is taken as part of the trigger for single word trigger (this seems as documented to me).

Also, even multiword trigger cannot end with a space, so you need to use a regular expression trigger.
