### ISSUE TITLE
Make box not working with * comment

### ISSUE THREAD

**Issue by PavelDvorak** [SirVer/ultisnips#1003]
In SAS language, you may comment with * at the beginning of a line, or with /* text */.

Output of "echo &comments":
`s1:/*,mb:*,ex:*/,://,b:#,:%,:XCOMM,n:>,fb:-`

Output of "echo &commentstring":
`/*%s*/`

**Expected output:**
```
**************
*  make box  *
**************
```

**Actual behavior:**
```
--------------
-  make box  -
--------------
```

**Steps to reproduce**
open any .SAS file and try to make a box.

1.
2.
3.

-----

- **Operating System**: win 7
- **Vim Version**: VIM - Vi IMproved 8.1 (2018 May 18, compiled May 18 2018 18:36:07)
MS-Windows 32-bit GUI version with OLE support

- **UltiSnips Version**: last one
- **Python inside Vim**: 3.6.6
- **Docker repo/vimrc**: using let g:UltiSnipsUsePythonVersion = 3

**Comment by SirVer** [comment]
This is a bug for `vimssnippets`: https://github.com/honza/vim-snippets/blob/master/pythonx/vimsnippets.py#L61. I assume the function to parse the comment string is broken.
