### ISSUE TITLE
add a lowecase to a variable

### ISSUE THREAD

**Issue by xavierartot** [SirVer/ultisnips#1005]
**Expected behavior:**
1/I have a template to build a class/React/Javascript and I would like to have className='$1' in lowercase 
```snippet rcc
	import React, { Component } from 'react';

	class ${1:ClassName} extends Component {
		render() {
			return (
				<div className='$1'>
					$1
				</div>
			);
		}
	}
	export default $1
```

2/the element inside should have the class with a space between the class name:
exemple: if I typing NewTweet in the declaration, I would like to have "new tweet"
```				
<div>
	$1
</div>
	
```

**Actual behavior:**
exemple with my template:
```
import React, { Component } from 'react';

class TweetPage extends Component {
  render() {
    return (
      <div className="TweetPage">
        TweetPage
      </div>
    );
  }
}
export default TweetPage;
```

**Comment by lacygoill** [comment]
Try the following snippet:

    snippet foo "some description"
    import React, { Component } from 'react';

    class ${1:ClassName} extends Component {
            render() {
                    return (
                            <div className='`!p snip.rv = re.sub(r"(\w)([A-Z])", r"\1 \2", t[1]).lower()`'>
                                    $1
                            </div>
                    );
            }
    }
    export default $1
    endsnippet

If you need the transformation of `NewTweet` to be reflected in the next two `$1` mirrors, then try this snippet instead:

    snippet foo "some description"
    import React, { Component } from 'react';

    class ${1:ClassName} extends Component {
            render() {
                    return (
                            <div className='`!p name = re.sub(r"(\w)([A-Z])", r"\1 \2", t[1]).lower(); snip.rv = name`'>
                                    `!p snip.rv = name`
                            </div>
                    );
            }
    }
    export default `!p snip.rv = name`
    endsnippet

In both snippets, the tab trigger is `foo`, but you can replace it with whatever you like.

For more information, see:

    :h UltiSnips-python

If you have other usage questions, try to visit https://vi.stackexchange.com/ and tag your question with [plugin-ultisnips](https://vi.stackexchange.com/questions/tagged/plugin-ultisnips).
