### ISSUE TITLE
`snip.buffer` prints unwanted debug info

### ISSUE THREAD

**Issue by Maelan** [SirVer/ultisnips#1014]
**Steps to reproduce**

 1. Save the snippet provided below in `~/.vim/UltiSnips/all.snippets`.
 2. Open Vim with a new buffer.
 3. Assuming default key bindings, type `itest<Tab><C-j>`; during the jump triggered by the last key, the message `('I', 0, 0, 'prepended') (0,9)` is displayed at the bottom of Vim, and in the `:messages` window.

```
global !p
def test_snippet():
	snip.buffer[snip.cursor[0]] = "prepended" + snip.buffer[snip.cursor[0]]
	snip.cursor.set(snip.cursor[0], snip.cursor[1] + 9)
endglobal

post_jump "if snip.tabstop == 0: test_snippet()"
snippet test
[${1}][${0}]
endsnippet
```

-----
- **Operating System**: Archlinux, kernel 4.17.2, x86_64
- **Vim Version**: 8.1 (2018 May 17), included patches: 1-22
- **UltiSnips Version**: git revision 6fdc3647f72e0a1f321ea6bd092ecd01f7c187ba
- **Python inside Vim**: 2.7.15 / 3.6.5

**Comment by lacygoill** [comment]
It seems that the printed message comes from these lines:

https://github.com/SirVer/ultisnips/blob/6fdc3647f72e0a1f321ea6bd092ecd01f7c187ba/pythonx/UltiSnips/_diff.py#L207-L209.

It's just an assignment, so I don't know why Vim prints its contents.

I know that initially, UltiSnips runs these lines:

https://github.com/SirVer/ultisnips/blob/6fdc3647f72e0a1f321ea6bd092ecd01f7c187ba/pythonx/UltiSnips/snippet/definition/_base.py#L432-L434.

Then:

https://github.com/SirVer/ultisnips/blob/6fdc3647f72e0a1f321ea6bd092ecd01f7c187ba/pythonx/UltiSnips/snippet/definition/_base.py#L195

And finally:

https://github.com/SirVer/ultisnips/blob/6fdc3647f72e0a1f321ea6bd092ecd01f7c187ba/pythonx/UltiSnips/snippet/definition/_base.py#L170

I've tried to capture the output of `:messages` to see at which point UltiSnips made Vim print the unwanted message, with these commands:

    import vim
    vim.command('let g:msg = execute("messages", "")')

But, I wasn't able to find a relevant location. The message can be captured after `exec(code, {'snip': snip})`, but at that point the jump has been performed, so it's not relevant.

**Comment by SirVer** [comment]
Confirmed to still happen at dc9d8f5e16a0a0727a47309e6c9e9ded26bc3e0e. I believe the culprit to be in https://github.com/SirVer/ultisnips/blob/master/pythonx/UltiSnips/buffer_proxy.py, but I was unable to pinpoint where it actually sends a log message to Vim.

**Comment by Maelan** [comment]
#1178 likely fixed it, I think. :-) I cannot reproduce with current master, and the removed `print` statement looks pretty much like one that would have produced the observed output.

**Comment by SirVer** [comment]
great! Thanks for comfirming.
