### ISSUE TITLE
Placeholders are missing content with umlauts

### ISSUE THREAD

**Issue by the-isz** [SirVer/ultisnips#1015]
Hi all,

first of all: Thanks for this great plugin! I'm using it on a daily basis and can't imagine working without it anymore :smile: 

Now, I found that placeholders only contain lines of text until the first line with an umlaut inside. Consider the following simple example snippet:

```
snippet foo "Reproduce issue" b
${1:MultiLine}
$1
endsnippet
```

Now typing
```
foo<Tab>First<CR>Secönd<CR>Third<C-J>
```
should give
```
First
Secönd
Third
First
Secönd
Third
```

but instead, the `Third` line - or anything after the `Secönd` line for that matter - doesn't get mirrored anymore.

Environment:

- **OS**: Ubuntu 16.04
- **Vim Version**:
```
NVIM v0.3.1
Build type: Release
```
- **UltiSnips Version**: 6fdc3647f72e0a1f321ea6bd092ecd01f7c187ba
- **Python inside Vim**:
```
2.7.12 (default, Dec  4 2017, 14:50:18)
[GCC 5.4.0 20160609]
```

**Comment by SirVer** [comment]
Can't reproduce at 4f4d500e21b307894490b24413d663c1c124307f with Vim 8 on MacOS. See recording here: https://asciinema.org/a/5fyjdEgssX5NE3yMDZOFivTYl
