### ISSUE TITLE
Ultisnip not using g:UltiSnipsJumpForwardTrigger?

### ISSUE THREAD

**Issue by huangzonghao** [SirVer/ultisnips#1018]
**Expected behavior:**
Setting `g:UltiSnipsJumpForwardTrigger` should give us the key-binding for jump forward function.

**Actual behavior:**
`g:UltiSnipsJumpForwardTrigger` is not actually being used by the plugin?

**Steps to reproduce**
Just global search the code base of the plugin and look for the keyword `UltiSnipsJumpForwardTrigger`, it seems the plugin never actually map it to anything.

-----

- **Operating System**: 
- **Vim Version**: 
- **UltiSnips Version**: 
- **Python inside Vim**: 
- **Docker repo/vimrc**:

**Comment by dimbleby** [comment]
Your searching is bad.

See [here](https://github.com/SirVer/ultisnips/blob/6fdc3647f72e0a1f321ea6bd092ecd01f7c187ba/pythonx/UltiSnips/snippet_manager.py#L864) and [here](https://github.com/SirVer/ultisnips/blob/6fdc3647f72e0a1f321ea6bd092ecd01f7c187ba/pythonx/UltiSnips/snippet_manager.py#L348-L351)

Did you try setting the forward trigger and see something not work?

**Comment by SirVer** [comment]
I believe this patch is incorrect. The triggers are correctly used as pointed out by @dimbleby. Closing.
