### ISSUE TITLE
Python2 syntax when vim with python 3

### ISSUE THREAD

**Issue by leksito** [SirVer/ultisnips#1020]
Hello, I have some problem.
Vim uses python 3.5.2
I defined `let g:UltiSnipsUsePythonVersion = 3`
`has('python3')` returns 1. (it returns 0 for 'python')
But the plugin complements the python2 syntax.
![image](https://user-images.githubusercontent.com/13941862/46690080-2195ba00-cc0a-11e8-9fd0-30338cf179b3.png)

I used Vundle plugin to install Ultisnips and vim-snippets.

**Expected behavior:**
In my case the python3 syntax should be used.

**Actual behavior:**
python2 used

-----
- **Operating System**: Ubuntu 16.04.5 LTS
- **Vim Version**: 
![image](https://user-images.githubusercontent.com/13941862/46688798-f78ec880-cc06-11e8-993e-c2486838c7f0.png)

- **UltiSnips Version**: `6fdc3647f72e0a1f321ea6bd092ecd01f7c187ba`
- **Python inside Vim**: 3.5.2.
- **Vimrc**: 
```
set nocompatible 
filetype off    

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'kien/ctrlp.vim'
Plugin 'Valloric/YouCompleteMe'

Plugin 'jpalardy/vim-slime'

Plugin 'eugen0329/vim-esearch'

Plugin 'flazz/vim-colorschemes'
Plugin 'easymotion/vim-easymotion'

" Track the engine.
Plugin 'SirVer/ultisnips'

" Snippets are separated from the engine. Add this if you want them:
Plugin 'honza/vim-snippets'

call vundle#end()            " required
filetype plugin indent on    " required

let g:UltiSnipsUsePythonVersion = 3
let g:UltiSnipsExpandTrigger="<C-Space>"
let g:UltiSnipsJumpForwardTrigger="<c-z>"
let g:UltiSnipsJumpBackwardTrigger="<c-x>"

let g:ycm_python_binary_path = 'python3'


```

**Comment by SirVer** [comment]
I think the problem here is that `vim-snippets` ships snippets in Python2 syntax. UltiSnips does no magic on the content of your snippets, it just expands them.
