### ISSUE TITLE
Strange behavior of UltiSnips#Anon() when inside a "snippet block"

### ISSUE THREAD

**Issue by elythyr** [SirVer/ultisnips#1028]
**Expected behavior:**
Being able to call UltiSnips#Anon() after expanding a snippet without interference from this previous snippet.

**Actual behavior:**
Some text is added above the expanded snippet, after the one generated with Anon()

**Steps to reproduce**

In the repro case there is a snippet and an issue.php file allowing to reproduce the issue.

1. Use a snippet with option "r" and match groups.
2. Expand it, don't go to the ${0}
3. Leave insert mode and execute:
```vim
:put! =nr2char(10) | call UltiSnips#Anon("test")
```
-----

I know that until we leave the snippet "block" or reach ${0}, UltiSnips consider that we are still inside the snippet.
But I don't get why a python interpolation, which has already been executed, still have impact.

Of course, if you leave the snippet "block" or reach to ${0} there is no issue.
But it's not really optimizing the workflow to be force to go threw all the tabstops or to move you cursor in order to move it back where it was, just to be able to do something :)

So, I was wondering if it was possible to provide a function or command allowing us to explicitly leave a snippet after expansion ?

-----

- **Operating System**: Ubuntu 18.04
- **Vim Version**: VIM 8.0 - Included patches: 1-586
- **UltiSnips Version**: 6fdc3647f72e0a1f321ea6bd092ecd01f7c187ba
- **Python inside Vim**: no py (repro docker) / 3.6.7
- **Docker repo/vimrc**: https://github.com/elythyr/ultisnips/tree/regexp_match_group_issue

**Comment by SirVer** [comment]
Fantastic repro case! Thanks for the report!

I think there is a bug here, namely that the complex edit of using put confuses UltiSnips change tracking. A simpler repro is to use `:put! =nr2char(10) | normal itest` which also results in `public` being put into the file in the wrong place. This is captured in other bugs in this tracker already, so I consider this a duplicate. As for your other questions:

>  But I don't get why a python interpolation, which has already been executed, still have impact.

Every Python block keeps getting executed until the snippet is exited. But this is not the underlying cause for the issue at hand.

> So, I was wondering if it was possible to provide a function or command allowing us to explicitly leave a snippet after expansion ?

Yes, currently you can call `:py3 UltiSnips_Manager._leaving_buffer()` to exit all snippets. I have considered adding a command for this, but did not see the appeal yet so far.

Closing as the bug mentioned is a duplicate.

**Comment by elythyr** [comment]
> Yes, currently you can call :py3 UltiSnips_Manager._leaving_buffer() to exit all snippets. I have considered adding a command for this, but did not see the appeal yet so far.

Thanks for that it fixes my issue.
