### ISSUE TITLE
Get name of current file in snippet

### ISSUE THREAD

**Issue by theonlygusti** [SirVer/ultisnips#1029]
For expanding out Java classes I want to get the currently-being-edited file's base name.

**Comment by lacygoill** [comment]
Try to use `snip.basename` in a python interpolation.

As an example, write this snippet in your `java.snippets` file:

    snippet foo ""
    `!p snip.rv = snip.basename`
    endsnippet

Insert `foo` in your `.java` file and press the key to expand the snippet; the result should be the basename of the current file.

![gif](https://user-images.githubusercontent.com/8505073/50942849-51af5c00-148a-11e9-95b0-44e48dce2b57.gif)

For more information, see `:h Ultisnips-python`.

If you have other usage questions, try to visit https://vi.stackexchange.com/ and tag your question with [plugin-ultisnips](https://vi.stackexchange.com/questions/tagged/plugin-ultisnips).
