### ISSUE TITLE
path does not expand to the absolute path to the current file

### ISSUE THREAD

**Issue by theonlygusti** [SirVer/ultisnips#1030]
My reading of the help documentation:

```
path - The complete path to the current file
```

Lead me to believe that `path` was a string containing the absolute path to the currently-edited file.

Looks like it's actually the relative path from the directory in which VIM was opened.

So how can I get the absolute path?

**Comment by lacygoill** [comment]
In a python interpolation, use the `os.path.abspath()` method:

    snippet foo "" bm
    `!p snip.rv = os.path.abspath(path)`
    endsnippet

In a VimL interpolation, use the `expand()` function:

    snippet foo "" bm
    `!v expand('%:p')`
    endsnippet

If you have other usage questions, try to visit https://vi.stackexchange.com/ and tag your question with [plugin-ultisnips](https://vi.stackexchange.com/questions/tagged/plugin-ultisnips).

**Comment by franciscoj** [comment]
Your question is answered here too https://github.com/SirVer/ultisnips/issues/788

the recommended solution there is to use `vim.eval('expand("%:p")')` I've been using it as so far it works as expected :)
