### ISSUE TITLE
:help topic UltiSnips-snippet-search-path has gone missing

### ISSUE THREAD

**Issue by JESii** [SirVer/ultisnips#1033]
Help topic (`:h UltiSnips-snippet-search-path`) does not work; it gives error 
`E149: Sorry, no help for UltiSnips-snippet-search-path`

**Expected behavior:**
Should get a help panel

**Actual behavior:**
No help; `E149` error

**Steps to reproduce**
```
:h UltiSnips
Navigate to UltiSnipsEdit topic by placing curson on UltiSnipsEdit link; place cursor on UltiSnips-snippet-search-path link and press <CTRL-}>

Also fails with:
:h UltiSnips-snippet-search-path
```

1.
2.
3.

-----

- **Operating System**: 
MacOS 10.13.6
- **Vim Version**: 
VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 29 2018 06:56:05)
macOS version
- **UltiSnips Version**: 
3.1
- **Python inside Vim**: 
3.7.0 (default, Jun 29 2018, 20:14:27)
[Clang 9.0.0 (clang-900.0.39.2)]

- **Docker repo/vimrc**:

**Comment by lacygoill** [comment]
The section `UltiSnips-snippet-search-path` was removed in [this commit](https://github.com/SirVer/ultisnips/commit/30e651fb1f342f8a185e7df638d6dd9a72cd6c73). You can still read it [here](https://github.com/SirVer/ultisnips/blob/4eac9798885f508d388d07847946a925dea583a5/doc/UltiSnips.txt#L368-L406).

The new one is `UltiSnips-how-snippets-are-loaded`.

The current help has probably forgotten to replace this remaining occurrence of `UltiSnips-snippet-search-path` with `UltiSnips-how-snippets-are-loaded`.
