### ISSUE TITLE
snip.visual_content snip.visual_text snip.v

### ISSUE THREAD

**Issue by dylnmc** [SirVer/ultisnips#1034]
What is going on with `snip.visual_content`, `snip.visual_text`, and `snip.v`?

* `snip.visual_content` and `snip.visual_text` are referenced in the help, but do **not** exist in the snippet

* `snip.v` is **not** mentioned in the help (and therefore I have to guess how it operates), but it does seem to exist in the snippet.
    - The only way I found out about it was via a github issue that was all over the place.

I just want to snip and snap 👀

**Comment by SirVer** [comment]
I do not understand your confusion. Could you go into more details of what you actually wanted to achieve?

- There is `snip.visual_content` or `snip.visual_text`, but only in custom context snippets: https://github.com/SirVer/ultisnips/blob/8ff301c651d6df806c0f9305273a6c62a693bc48/doc/UltiSnips.txt#L1411

- There is `snip.v` inside of python interpolation of a snippet: https://github.com/SirVer/ultisnips/blob/8ff301c651d6df806c0f9305273a6c62a693bc48/doc/UltiSnips.txt#L937
