### ISSUE TITLE
Export snippet string with format of textmate snippet

### ISSUE THREAD

**Issue by chemzqm** [SirVer/ultisnips#1044]
I would like to have a funcion which accept key of snippet, and return the snippet string as format of textmate snippet.

**WHY?**

The LSP specification use textmate snippet https://microsoft.github.io/language-server-protocol/specification#snippet-syntax, if I could get the textmate formated snippet from ultisnips I can just insert it as textmate snippet without using different keystroks for jump previous and jump next.  The placeholder format is almost the same, so I think make the function return snippet body with placeholders and injected script resolved would be enough.

**Comment by SirVer** [comment]
UltiSnips snippets have more featured than textmate, hence it is not always possible to express it as a textmate snippet. Even if it is possible, it is a complex feature that seems out of scope for UltiSnips to me.
