### ISSUE TITLE
is it somehow possible to expand a snippet when the cursor is in a string/word?

### ISSUE THREAD

**Issue by divramod** [SirVer/ultisnips#1045]
Hey, 

i have the problem, that my snippets wont expand, when i am in the middle of a word/string.
See demonstration here, where i have to insert a space to get the completion for a link in html.
[Youtube Demonstration of the problem](https://www.youtube.com/embed/zhMZa9HVOsI)

So my question is, is it somehow possible to complete even from within a string?

Thx for the awesome plugin and any hints!

**Comment by lacygoill** [comment]
Try to define your snippet with the `i` option.

For more information, see `:h UltiSnips-snippet-options`:

If you have other usage questions, try to visit https://vi.stackexchange.com/ and tag your question with [plugin-ultisnips](https://vi.stackexchange.com/questions/tagged/plugin-ultisnips).
