### ISSUE TITLE
Conflict with coc.nvim tab action.

### ISSUE THREAD

**Issue by LinArcX** [SirVer/ultisnips#1052]
If you install [coc.nvim](https://github.com/neoclide/coc.nvim) plugin and enable it for auto-completion and after that install ultisnips, the tab does not work any more and you can not cycle through items from autocomplete list.
I use these settings for coc.nvim to cycle through items in autocomplete list:
```
" Use <Tab> and <S-Tab> for navigate completion list                            
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"                        
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
```

**Expected behavior:**
Get back again to work with coc.nvim and choose items from list.

**Actual behavior:**
When you hit tab, it does not work and you can not cycle through items in autocomplete list.

**Steps to reproduce**

1. Install [coc.nvim](https://github.com/neoclide/coc.nvim) plugin.
2. enable these settings for it:
```
" Use <Tab> and <S-Tab> for navigate completion list                            
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"                        
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
```
3. Install ultisnips plugin and don't use any configuration for it.

-----

- **Operating System**: Arch Linux
- **Vim Version**: NVIM v0.3.4
- **UltiSnips Version**: 3.1
- **Python inside Vim**: 2.7.15 / 3.7.2
- **Docker repo/vimrc**: https://github.com/LinArcX/Blogit/tree/master/Packages/Vim/config

**Comment by LinArcX** [comment]
Up.

**Comment by chemzqm** [comment]
It's not bug, ultisnips maps your `<tab>` by default.
You can configure it other key.

**Comment by danihodovic** [comment]
For anyone that runs into this issue and is using coc.nvim and Ultisnips plugin (https://github.com/neoclide/coc-sources/tree/master/packages/ultisnips)

you can disable the default Ultisnips tab mapping to free up coc.nvim
```
let g:UltiSnipsExpandTrigger = "<nop>"
```

**Comment by againxx** [comment]
> For anyone that runs into this issue and is using coc.nvim and Ultisnips plugin (https://github.com/neoclide/coc-sources/tree/master/packages/ultisnips)
> 
> you can disable the default Ultisnips tab mapping to free up coc.nvim
> 
> ```
> let g:UltiSnipsExpandTrigger = "<nop>"
> ```

Thoughtful comment! However, after testing it in neovim 0.5, I found that this map will actually map these `<` `n` `o` `p` `>` five keys to expand snippets and therefore slows down a normal insert of `<`.

**Comment by againxx** [comment]
https://github.com/SirVer/ultisnips/blob/c270950492d71bac0317d47d42cd0884eefe6490/autoload/UltiSnips/map_keys.vim#L64

Maybe disabling `UltiSnipsExpandTrigger` will also disable the ability to use `Visual` placeholder
