### ISSUE TITLE
[Question] Can we expand a snippet when entering file

### ISSUE THREAD

**Issue by AdrienLemaire** [SirVer/ultisnips#1062]
**Expected behavior:**
When opening a file, a snippet is auto-triggered and I'm  placed in insert mode on the first tag.

**Actual behavior:**
When opening a file, my snippet keyword is written and I'm on view mode. I need to navigate to the end of the keyword, enter insert mode, then press tab for it to expand.

**Steps to reproduce**
I suppose it looks like `echo "keyword" > /tmp/jrnl12345.txt && vim /tmp/jrnl12345.txt `

**More background**
I'm using the `jrnl` tool to write journal entries, and it opens nvim (doesn't matter if it's vim or nvim) for me automatically.
The command is something like `jrnl "keyword" && jrnl -1 --edit`. 

The end goal is for me to complete a vim template every time I start `jrnl`, using the Ctrl-j mapping to go from question to question easily.
I investigated for some time how to do this without ultisnips, eg via jumps or tags, but I they don't seem to do what I'm looking for, while ultisnips does it perfectly. 
Do you have any suggestion on auto-expanding a snippet on file enter, or to reproduce this insert mode Ctrl-j mapping without ultisnips ?

**Bonus question**
I'd like to generate dynamic snippets. In my case, I would randomly select 5 questions from a large list of questions, and I'd send the questions to the snippet generator, which would format them and add placeholders for answers in between.
Can we do that with some function without needing to override the related snippets file ?

-----

- **Operating System**:  Arch Linux
- **Vim Version**: 
NVIM v0.3.4
Build type: Release

- **UltiSnips Version**: 5352d98f212e273b3e8b1d84efdbe2d6a6d557e9
- **Python inside Vim**: 
2.7.15 (default, Jan 10 2019, 23:20:52)                                             
[GCC 8.2.1 20181127]

- **Docker repo/vimrc**:

**Comment by 9999years** [comment]
You might be interested in my [boilerplate-ultisnips](https://github.com/9999years/boilerplate-ultisnips) library for this; it supports expanding snippets when opening a new file.

**Comment by SirVer** [comment]
See @9999years answer for using ultisnips for templating. 

> I'd like to generate dynamic snippets.

See here for this:
https://github.com/SirVer/ultisnips/blob/master/doc/examples/tabstop-generation/README.md
