### ISSUE TITLE
Popup menu is not stable, when using mirrors

### ISSUE THREAD

**Issue by fimmind** [SirVer/ultisnips#1063]
**Expected behavior:**
Stable popup menu

**Actual behavior:**
Unstable popup menu, when using mirrors

**Steps to reproduce**

1. Use YouCompleteMe (but, may be, you only need a large popup menu. I'm not sure)
2. Expand snippet with mirrors (*UltiSnips-mirrors* in documentation)
3. Type something in "mirroring" paceholder

Video: <https://youtu.be/GOeK3eDy77U>

-----

- **Operating System**: Linux Mint 19.1 Tessa
- **Vim Version**: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 21:31:58)
- **UltiSnips Version**:  6fdc3647f72e0a1f321ea6bd092ecd01f7c187ba
- **Python inside Vim**:

`:py import sys; print(sys.version)`
```
this command is unavailable in this version
```

`:py3 import sys; print(sys.version)`
```
3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0]
```
- **Docker repo/vimrc**:  <https://github.com/fimmind/.vim>

**Comment by SirVer** [comment]
Can't reproduce. Works for my with YCM. I need a minimal Vim config to reproduce this.
