### ISSUE TITLE
AttributeError: 'SnippetUtil' object has no attribute 'path'

### ISSUE THREAD

**Issue by junliu** [SirVer/ultisnips#1065]
I'm getting above exception with a customized snippet which inquries the path of the working script. The snippet looks like
```
snippet foo
#`!p snip.rv = snip.path`
endsnippet
```
In chap 4.4.3 of the [UltiSnips documentation](https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt), it said `path` is automatically defined yet yet I get an `AttributeError` exception thrown. 

As a workaround, I just manaully define `path` in the `class SnippetUtil`, which looks like
```
    @property
    def path(self):
        """The path to the file"""
        return _vim.eval('expand("%")') or ''
```
I would wonder if there's a simpler way to make it work.

**Comment by majidmohsenifar** [comment]
path is not the property of snip it is, you should use  it like this
`snippet foo
#`!p snip.rv = path`
endsnippet`

**Comment by junliu** [comment]
> path is not the property of snip , you should use it like this
> `snippet foo `!p snip.rv = path` endsnippet`

Thanks. But I need the full path to the working script, rather than just a file name.

**Comment by majidmohsenifar** [comment]
> > path is not the property of snip , you should use it like this
> > `snippet foo `!p snip.rv = path` endsnippet`
> 
> @majidmohsenifar Thanks. But I need the full path to the working script, rather than just a file name.

you can use vim variable in your snippet 
for example `snippet `!p snip.rv = vim.eval("expand('%:p')")` endSnippet`
will give you the absolute path to the file.

**Comment by junliu** [comment]
@majidmohsenifar Thanks, the problem is solved.
