### ISSUE TITLE
Ultisnips keeps using tab

### ISSUE THREAD

**Issue by benmezger** [SirVer/ultisnips#1067]
**Expected behavior:**
I have disabled tab map for Ultisnips, since I use tab with Deoplet, however, it seems that tab is still being mapped for Ultisnip. How can I disable this?

**Actual behavior:**
Use `C-i` for ultisnip snippet completion instead of tab.

**Steps to reproduce**
Add this to your vim, create a snippet, if you try to C-i to add a snippet it works, same with tab.

```vim
" ultisnips
let g:UltiSnipsExpandTrigger="<C-i>"
let g:UltiSnipsJumpForwardTrigger="<C-f>"
let g:UltiSnipsJumpBackwardTrigger="<C-z>"
let g:UltiSnipsEditSplit="vertical"

let g:UltiSnipsSnippetDirectories=[$HOME.'/.vim/UltiSnips']
```
-----
- **Operating System**: Darwin Kernel Version 18.2.0
- **Vim Version**: NVIM v0.3.4
- **UltiSnips Version**: 6fdc3647f72e0a1f321ea6bd092ecd01f7c187ba
- **Python inside Vim**: 
                              `:py import sys; print(sys.version)`: `2.7.16 (default, Mar  4 2019, 09:01:38)`
                              `:py3 import sys; print(sys.version)`: `3.7.0 (default, Jan 14 2019, 13:54:28)`

**Comment by Freedzone** [comment]
In vim <Ctrl-i> and <Tab> are attached to the same key code, in other words, you cannot separately map to different commands. You can see all the equivalent keys with `help keycodes`.
