### ISSUE TITLE
UltiSnips crashes when using snippets with asciidoc files.

### ISSUE THREAD

**Issue by AlexanderThaller** [SirVer/ultisnips#1069]
UltiSnips crashes when using snippets with asciidoc files.

**Expected behavior:**
UltiSnips should not crash and expand the snippet.

**Actual behavior:**
UltiSnips crashes and does not expand the snippet.

**Steps to reproduce**

1. Create snippet file `asciidoc.snippets` with following content:

```
snippet test "Test"
This is a test
endsnippet
```
2. Open a new file called `test.asciidoc`. The filetype in vim should be `asciidoc` (`echo &ft`).
Start writing in file and try to write `test`.

UltiSnips will crash with following error:

```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new
Please read and follow:
https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs

Following is the full stack trace:
Traceback (most recent call last):
  File "/home/athaller/.local/share/nvim/plugged/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 16, in wrapper
    return func(self, *args, **kwds)
  File "/home/athaller/.local/share/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 848, in _track_change
    self._try_expand(autotrigger_only=True)
  File "/home/athaller/.local/share/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 694, in _try_expand
    snippets = self._snips(before, False, autotrigger_only)
  File "/home/athaller/.local/share/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 574, in _snips
    source.ensure(filetypes)
  File "/home/athaller/.local/share/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 32, in ensure
    self._load_snippets_for(ft)
  File "/home/athaller/.local/share/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 54, in _load_snippets_for
    self._parse_snippets(ft, fn)
  File "/home/athaller/.local/share/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 69, in _parse_snippets
    raise SnippetSyntaxError(filename, line_index, msg)
UltiSnips.snippet.source.file._base.SnippetSyntaxError: Invalid line 'This is a test' in .config/nvim/snippets/asciidoc.snippets:2
```

Only happens in asciidoc files.

-----

- **Operating System**:  ArchLinux `5.0.0-zen1-1-zen`
- **Vim Version**:  NVIM v0.3.4
- **UltiSnips Version**:  6fdc3647f72e0a1f321ea6bd092ecd01f7c187ba
- **Python inside Vim**: 3.7.2 (default, Jan 10 2019, 23:51:51) [GCC 8.2.1 20181127]
- **Docker repo/vimrc**: 
```
Plug 'sirver/ultisnips'
let g:UltiSnipsExpandTrigger = '<tab>'
let g:UltiSnipsJumpForwardTrigger = '<tab>'
let g:UltiSnipsJumpBackwardTrigger = '<s-tab>'
let g:UltiSnipsSnippetDirectories=[$HOME.'/.config/nvim/snippets']
```

**Comment by AlexanderThaller** [comment]
Apparently it happens for all files that are concrete filetypes. If I put the definition into `all.snippets` instead of the filetype one it works.

**Comment by grelkin** [comment]
@AlexanderThaller : try to rename the snippets directory to something other than "snippets", for it is "reserved for snipMate snippets and cannot be used" (see :h ultisnips)

So, not
```
let g:UltiSnipsSnippetDirectories=[$HOME.'/.config/nvim/snippets']
```
but
```
let g:UltiSnipsSnippetDirectories=[$HOME.'/.config/nvim/my-snippets']
```

**Comment by SirVer** [comment]
Just stick with `UltiSnips` as the snippet directory and this should not happen. You are trying to feed snipMate snippets to UltipSnips (due to `snippets`) as directory, but your files are not snipMate files.
