### ISSUE TITLE
Why the snippet for [] not work as expected?

### ISSUE THREAD

**Issue by vanabel** [SirVer/ultisnips#1071]
I have the following snippets
```
snippet [] "[]" iA
[${1:${VISUAL}}]$0
endsnippet

snippet {} "{}" iA
{${1:${VISUAL}}}$0
endsnippet
```
The behavior of `[]` and `{}` is not work for visual mode?

**Comment by SirVer** [comment]
Works for me: https://asciinema.org/a/ZsiiJSVYyqMdqobextKEqKT8s
