### ISSUE TITLE
Error detected while processing function UltiSnips#Edit

### ISSUE THREAD

**Issue by maindolaamit** [SirVer/ultisnips#1072]
**Expected behavior:**
Ultisnips should not error out and should open the snippets list to edit

**Actual behavior:**
Ultisnips is getting error out with below message
Error detected while processing UltiSnips#Edit
line 8:
E121: Undefined variable : file
E116: Invalid argument for function len
E15: Invalid expression !len(file)

**Steps to reproduce**

1. Install NeoVim from https://github.com/neovim/neovim/releases 
2. Create a init.vim in ~/Appdata/Local/nvim/ 
3. Paste the content my init.vim(Pasted below) in the newly created init.vim

-----

- **Operating System**: Windows 10
- **Vim Version**: NVIM v0.4.0-529
- **UltiSnips Version**: 2 
- **Python inside Vim**: 3.7.1 
- **Docker repo/vimrc**
![image](https://user-images.githubusercontent.com/19851324/55780505-bc8e2480-5ac5-11e9-9d85-9cd6d7d390fc.png)

: 
Below is the complete init.vim file
" Automatic reloading of init.vim change to init.vim for windows
autocmd! bufwritepost init.vim source %

" ============================================================
" =                  Set path                               = 
" ============================================================
let g:python_host_prog = '/c/Program Files/Python/Python27/'
let g:python3_host_prog = '/c/Program Files/Python/Python37/'
let $PYTHONCASEOK=""
"set rtp+=~/AppData/Local/nvim/bundle/vim-snippets         " Ultisnips Snippets folder 
"set rtp+=~/AppData/Local/nvim/bundle/vim-snippets          " Ultisnips Snippets folder 
set rtp+=~/.vim/bundle/vim-snippets                        " Ultisnips Snippets folder 
"set rtp+=~/AppData/Local/nvim/bundle/youcompleteme        " YouCompleteMe folder 

" ============================================================
" =          Configure settings for vundle and Plugins       = 
" ============================================================
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim                         " set path for Vundle
"set rtp+=~/AppData/Local/nvim/bundle/Vundle.vim           " set path for Vundle

"call vundle#begin('~/AppData/Local/nvim/bundle')
call vundle#begin()
" ***** All of your Plugins must be added after the following line *****
Plugin 'VundleVim/Vundle.vim'               " let Vundle manage Vundle, required
Plugin 'scrooloose/nerdtree'    	        " NERDTree - File Navigator
Plugin 'easymotion/vim-easymotion' 	        " EasyMotion - fast Jump
Plugin 'somini/vim-autoclose'    	        " Autoclose - Auto close pairs
Plugin 'AutoComplPop'			            " Popup - Autocomplete 
Plugin 'scrooloose/syntastic'               " Python and other languages code checker
Plugin 'tpope/vim-surround'		            " Surround - add/delete/change surroundings
Plugin 'tpope/vim-repeat'		            " Repeat plugin actions
Plugin 'tpope/vim-abolish'		            " Repeat plugin actions
Plugin 'matze/vim-move'			            " Move lines up or down
Plugin 'mattesgroeger/vim-bookmarks' 	    " Bookmark Plugin
Plugin 'bling/vim-airline'		            " Airline - Beautiful Status line 
Plugin 'vim-airline/vim-airline-themes'     " Airline themes
Plugin 'kien/ctrlp.vim'			            " Code and files fuzzy finder
Plugin 'vim-ctrlspace/vim-ctrlspace'	    " ctrlspace - Tabs and Workspace Manager
Plugin 'scrooloose/nerdcommenter'    	    " NerdCommenter - Not so good for nested comments
Plugin 'ervandew/supertab'                  " Supertab plugin
Plugin 'honza/vim-snippets'                 " Honza Vim snippets
Plugin 'SirVer/ultisnips'		            " Ultisnips - Snippets manager 
"Plugin 'valloric/youcompleteme'             " Autocomplete 
 if has('python')
     Plugin 'pignacio/vim-yapf-format'      " YAPF formatter for Python
 endif
 Plugin 'mbbill/undotree'                   " Visualize vim undo tree
" Plugin 'matchit.zip'                        " Extended comment symbols
" Plugin 'nathanaelkane/vim-indent-guides'    " Indentation Plugin
" Plugin 'junegunn/vim-easy-align'	        " Alignment Plugin - Worth trying
" Plugin 'tacahiroy/ctrlp-funky'
" "Plugin 'altercation/vim-colors-solarized'   " Solarized color scheme
" 
" ***** All of your Plugins must be added before the following line *****
call vundle#end()                        " required
filetype plugin indent on                " required

" ============================================================
" =                Settings for Programming                  = 
" ============================================================
syntax on                               " turn syntax highlighting on by default
syntax enable  
set ai                                  " set auto-indenting on for programming
set vb                                  " turn on the "visual bell" - which is much quieter than the "audio blink"
set noerrorbells visualbell t_vb=       " no annoying sound on errors
set smartcase 
set ignorecase                          " Case insensetive search
set showmatch                           " automatically show matching brackets. works like it does in bbedit.
set autoread                            " Set Auto read on, silent update
set complete+=kspell                    " Enable word completion
set backspace=indent,eol,start          " make that backspace key work the way it should
set clipboard=unnamed                   " set clipboard to unnamed to access the system clipboard under windows
set history=50                          " Kepp 50 files in recent menu
set incsearch                           " incremental search
set hlsearch                            " highlighted search results
set hidden                              " Set for crrlspace, to show hidden buffers "
set showtabline=0                       " Hide the tabline, better compatibility with CtrlSpace "
" set diffopt+=iwhite
" set diffexpr=""
" 
"set mouse=a                            " automatically enable mouse usage
"set autowrite

" ============================================================
" =                   Display settings                       = 
" ============================================================
colorscheme codedark
"set termguicolors                       " Set true colors in the terminal
set showmode                            " show the current mode
set number relativenumber               " Show Hybrid Line number in file
set ruler                               " Show the Line and Col position of cursor
set rulerformat=%30(%=\:b%n%y%m%r%w\ %l,%c%V\ %P%) " A ruler on steroids
set laststatus=2                        " make the last line where the status is two lines deep so you can see status always
set viewoptions=folds,options,cursor,unix,slash " Better Unix / Windows compatibility
set encoding=utf-8                      " Required by youcompleteme and ctrlspace
"set matchtime=3
set wrap                                " Wrap text
set autoindent                          " Enable autoindentation
set linebreak
" Show EOL type and last modified timestamp, right after the filename
 set statusline=%<%F%h%m%r\ [%{&ff}]\ (%{strftime(\"%H:%M\ %d/%m/%Y\",getftime(expand(\"%:p\")))})%=%l,%c%V\ %P
 
" ========== Display unprintable chars
set list
"set listchars=tab:›\ ,trail:•,extends:#,nbsp:.
"set showbreak=···
"set listchars=tab:▸\ ,trail:·,extends:❯,precedes:❮
"set showbreak=↪"
 
" ============================================================
" =          Tab settings                                    = 
" ============================================================
set smarttab		                " On smartab
set tabstop=4		                " Set space count for tab
set expandtab		                " <Replace> tab with spaces, if not set vim will use tab
set softtabstop=4	                " spaces to be used when hit tab in Insert mode
set shiftwidth=4	                " set columns to shift on reindent << or >>
set foldmethod=indent
set foldlevel=99
set path+=** 		                " Search down into subfolders, Provide tab completion for all file related tasks
set wildmenu 		                " Display all matching files when tab complete
set completeopt=longest,menuone    " Set Auto completion
set wildmode=list:longest           " autocompletion of files and commands behaves like shell, list the options that match
 
" ============================================================
" =          Better backup, swap and undos storage           = 
" ============================================================
"set backup                          " make backup files
" "set nobackup		                " Disable backup files
"set writebackup                     " Write backup "
" "set nowritebackup 	                " Do not write backup
"set noswapfile 	                    " Disable swap files
"set undofile                       " persistent undos - undo after you re-open the file
"set undolevels=100
"set backupdir=~/.vim/tmp/bkp        " where to put backup files
"set directory=~/.vim/tmp/swap       " directory to place swap files in
"set undodir=~/.vim/tmp/undos
" "set viminfo+=n~/.vim/dirs/viminfo
" 
" ============================================================
" =                  Custom shortcuts                        = 
" ============================================================

" Open help in new tab
cabbrev help tab help
cabbrev h tab h
" Tab Navigation mapping
inoremap <C-Left> <Esc>:tabp<CR>
inoremap <C-Right> <Esc>:tabn<CR>
nnoremap <C-Left> :tabp<CR>
nnoremap <C-Right> :tabn<CR>
nnoremap <leader>t :tabm -1<CR>
nnoremap <leader>T :tabm +1<CR>
nn <C-n> :tabnew<CR>                                " Open a new empty tab
"map tn :tabn<CR>
"map tp :tabp<CR>
"map tm :tabm 
"map tt :tabnew 
"map ts :tab split<CR>
"
" Map Alt-A and Alt-X to map for increment and decrement of values
":nnoremap <A-a> <C-a>
":nnoremap <A-x> <C-x>

no <Leader>w :w<CR>				                    " Type <Leader>w to save file (a lot faster than :w<Enter>):"
no <Leader>ft :set ft=plsql<CR>                     " Set file type to plsql (a lot faster than typing)"
nnoremap gR :grep "\<<cword>\>" *<CR>               " Search current word
nnoremap GR :grep "\<<cword>\>" %:p:h/*<CR>

no <Leader>U gUiW                                   " UPPERCASE the word
no <Leader>u guiW                                   " lowercase the word
no <Leader>i guiW~                                  " Initcap the word

nnoremap <CR> :noh<CR><CR>							" Unhighlight the search word after hitting ENTER
vnoremap // y/<C-R>"<CR>                            " Search Visual selection
" Replace word under cursor
nn <Leader>r :%S/<C-r><C-w>/<c-r><c-w>/g<left><left>
" Replace whole word under cursor case sensetive
nn <Leader>R :%s/\<<C-r><C-w>\>/<c-r><c-w>/g<left><left>
" Replace word under cursor with Null/Blank
nn <Leader>rn :%S/<C-r><C-w>//g<left><left>
" Replace whole word under cursor with Null/Blank case sensetive
nn <Leader>Rn :%s/\<<C-r><C-w>\>//g<left><left>
" Replace visual selection 
vn <Leader>r "hy:%s/<C-r>h/<C-r>h/g<left><left>
" Replace visual selection with NUll
vn <Leader>rn "hy:%s/<C-r>h//g<left><left>
" Replace/Substitute highlighted word with word under cursor
nn <Leader>rs :%s//<c-r><c-w>/g

" key bindings for quickly moving between windows - h left, l right, k up, j down
noremap <leader>h <c-w>h
noremap <leader>l <c-w>l
noremap <leader>k <c-w>k
noremap <leader>j <c-w>j
" 
" Shortcut for executing scripts
nnoremap <buffer> <F9> :exec '!python' shellescape(@%, 1)<cr>
" ============================================================
" =                 Plugin shortcuts and parameters          = 
" ============================================================
" 
nnoremap <F5> :UndotreeToggle<CR>                      " Show undo Tree"
" 
" vmap <Enter> <Plug>(EasyAlign)						" Start interactive EasyAlign in visual mode (e.g. vip<Enter>)
" nmap ga <Plug>(EasyAlign)							" Start interactive EasyAlign for a motion/text object (e.g. gaip)
" 
" NERDTree
 nn <F2> :NERDTreeToggle<CR>  						" Toggle Nerd Tree
 ino <F2> <esc>:NERDTreeToggle<cr>

" CtrlP
 nn <F3> :CtrlPMRUFiles<CR>                          " Show recent files edited in CtrlP Plugin
 let g:ctrlp_cmd='CtrlP :pwd'         " Change path to CWD in CtrlP"

" CtrlSpace
let g:CtrlSpaceSaveWorkspaceOnExit = 1              " Save Workspace in CtrlSpace on exit "
" "let g:CtrlSpaceUseMouseAndArrowsInTerm = 1          " Use Arrow keys and Mouse in the plugin"
" " Load and save Workspace from CtrlSpace Plugin
" nn <Leader>csl :CtrlSpaceLoadWorkspace<cr>
" nn <Leader>css :CtrlSpaceSaveWorkspace<cr>
" 
" Syntastic
nmap <leader>e :Errors<CR>           " show list of errors and warnings on the current file
let g:syntastic_check_on_open = 1    " check also when just opened the file
let g:syntastic_enable_signs = 0     " don't put icons on the sign column (it hides the vcs status icons of signify)
" 
" UltiSnips, set ultisnips trigger, better key bindings for UltiSnipsExpandTriggers
" " inoremap <expr> <tab> pumvisible() ? "<C-R>=UltiSnips#ExpandSnippetOrJump()<CR>" : "\<tab>"
 let g:UltiSnipsExpandTrigger="<tab>"
 let g:UltiSnipsJumpForwardTrigger="<c-j>"
 let g:UltiSnipsJumpBackwardTrigger="<c-k>"
 "let g:UltiSnipsDirectories = ['UltiSnips']
 "let g:UltiSnipsSnippetsDir = $HOME.'\AppData\Local\nvim\bundle\ultisnips'
 let g:UltiSnipsUsePythonVersion = 3
" 
" make YCM compatible with UltiSnips (using supertab)
"let g:ycm_keep_logfiles = 1
"let g:ycm_log_level = 'debug'
"let g:ycm_key_list_select_completion = ['<C-n>', '<Down>']
"let g:ycm_key_list_previous_completion = ['<C-p>', '<Up>']
"let g:SuperTabDefaultCompletionType = '<C-n>'

" AirlineTheme Change airplane UI
let g:airline_powerline_fonts = 1
let g:airline_exclude_preview = 1
"let g:airlie_theme = 'badwolf'  
"let g:airline_symbols.space = "\ua0"
" To use fancy symbols for airline, uncomment the following lines and use a patched font (more info on the README.rst
if !exists('g:airline_symbols')
      let g:airline_symbols = {}
endif

**Comment by pmarsceill** [comment]
I had the same issue.. It is was a problem with my Python configuration and NeoVim

run `:checkhealth` and see what python version NeoVim is using and where potential errors may be.

**Comment by maindolaamit** [comment]
> I had the same issue.. It is was a problem with my Python configuration and NeoVim
> 
> run `:checkhealth` and see what python version NeoVim is using and where potential errors may be.

Thank you,
I have corrected the Path for Python host programs, 
let g:python_host_prog = 'C:\Program Files\Python\Python27\python.exe'
let g:python3_host_prog = 'C:\Program Files\Python\Python37\python.exe'

but getting different issue now

**Comment by maindolaamit** [comment]
After restarting the machine Issue got fixed, Snippets are working like breeze now.. Thank you
