### ISSUE TITLE
How to insert parts of a snippet at the top or bottom of the file?

### ISSUE THREAD

**Issue by danijar** [SirVer/ultisnips#1076]
I'm using the following snippet to expand the boilerplate for a main function in Python:

```
snippet main "Python Main" b
import argparse

def main(args):
  ${0:${VISUAL}}

if __name__ == '__main__':
  parser = argparse.ArgumentParser()
  main(parser.parse_args())
endsnippet
```

While this inserts all the necessary code, I would like to further specify at what positions in the file the different parts are inserted. Specifically,

- the `import argparse` should always be inserted at the top of the file,
- the `def main(args): ${0:${VISUAL}}` should be where the snippet is triggered,
- the `if __name__ ...` block should be inserted at the very end of the file.

Does ultisnips support this functionality?

I know this could be done using a complicated Vim map that replicates the necessary key strokes for this, but to me, one of the benefits of using snippets is that it is much easier to maintain.

**Comment by SirVer** [comment]
Yes, it can do something like this, but it is slightly awkward: https://github.com/SirVer/ultisnips/blob/00_plug_mappings/doc/UltiSnips.txt#L1607

**Comment by Dangandy** [comment]
`global !p
def insert_top(name):
    vim.command('normal gg')
    snip.expand_anon(name)
    snip.cursor.set(snip.line+1,0)
endglobal

post_jump "if snip.tabstop == 0: insert_top('from sklearn.model_selection import train_test_split\n')
snippet tts "train_test_split" b
X_train, X_${1:${VISUAL:test}}, y_train, y_$1 = train_test_split(
    ${2:${VISUAL:X}},
    y,
    test_size=0.2,
    random_state=42
)

endsnippet`

Hi, I'm trying to do this same action and here is what I came up with. Let me know if there is a better way
