### ISSUE TITLE
"Beginning of line" (b) snippet expands when not at beginning of line

### ISSUE THREAD

**Issue by stephentalley** [SirVer/ultisnips#1083]
Given this snippet:

    snippet "o " "bullet" Abr
    • 
    endsnippet

(Note the space after "•".)

The "r" qualifier is to include the space in the trigger.

**Expected behavior:**

When I type "o " at the beginning of the line, the "o" should turn into a bullet ("•") and the space afterward should be preserved.  It does, yay!

If I type "So " or "To " or "No " at the beginning of the line, this snippet should **not** expand since the trigger is not at the beginning of the line.

**Actual behavior:**

If I type "So " or "To " or "No " at the beginning of the line, this snippet incorrectly expands the "o" to a "•", leaving me with "S• "/"T• "/"N• ".

If I add another character to the mix (e.g. "Too "), then the snippet (correctly) does not expand.

**Steps to reproduce**

Include the above snippet in any vim configuration.

-----
- **Operating System**:

  Ubuntu 18.04

- **Vim Version**:

    VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr  3 2019 10:21:45)
    Included patches: 1-1103

- **UltiSnips Version**:

  1a99766b73783bafb08cfa07d7e29e5387c55189

- **Python inside Vim**:

    :py3 import sys; print(sys.version)
    3.6.7 (default, Oct 22 2018, 11:32:17)
    [GCC 8.2.0]

**Comment by SirVer** [comment]
Regex trumps everything else. Include in your regex that this should be beginning of line:

```
snippet "^o " "bullet" Ar
• 
endsnippet
```

**Comment by stephentalley** [comment]
The regular expression approach isn't sufficient, unfortunately.

A key feature of the "b" modifier is that the snippet should expand *after* any whitespace at the beginning of the line, and keep that whitespace intact after expansion.  Your solution doesn't allow for this.

**Comment by SirVer** [comment]
How about this?
```
snippet "^(\W*)o " "bullet" Ar
`!p snip.rv = match.group(1)`• 
endsnippet
```

**Comment by stephentalley** [comment]
That seems to work.  Thanks!
