### ISSUE TITLE
Rewriting documentation in markdown

### ISSUE THREAD

**Issue by R0flcopt3r** [SirVer/ultisnips#1087]
Are there any specific reasons to why the documentation is written as a regular `.txt` file?

I would be more than glad to rewrite it in markdown if that is of interest.

**Comment by elihunter173** [comment]
Vim and vim plugins normally use plaintext `.txt` files for the `:help` documentation with the standard format you see in ultisnips documentation, with a table of contents, keywords in the headings, horizontal rules, etc.

**Comment by SirVer** [comment]
That is exactly right, we follow Vim convention for the documentation, not GitHubs.
