### ISSUE TITLE
custom snippet extander

### ISSUE THREAD

**Issue by rudrab** [SirVer/ultisnips#1090]
Hi,
Suppose I have a snippet:

```
snippet prg 
	!This is file : `!v expand('%:t:r')`
	! Author= `!v expand($USER)`
	! Started at: `date +%d.%m.%y`
	! Last Modified : Sun 16 Jun 2019 12:30:58 IST
	!
	Program  ${1:<++`!v expand('%:t:r')`}
	Implicit None
	${2}
	End Program  ${1/([^\n$]+).*/$1/}
endsnippet
...
```
and in vimrc, i have: `let g:UltiSnipsExpandTrigger="<c-a>"`

which is working fine.

Now, besides this, I am trying to have a keymap, like say, `"prg` in `insertmode`, which will expand this snippet for me. 
eg:
`inoremap "prg :some_magic_(expand_snippet_prg)`

any idea how to do this?

**Comment by SirVer** [comment]
I am not sure what the ask is, but if you want automatic expansion of a trigger on a certain condition (like typing `prg`) you probably want an autotrigger: https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L1707
