### ISSUE TITLE
Multiple trigger keys

### ISSUE THREAD

**Issue by cuppajoeman** [SirVer/ultisnips#1092]
When I'm using ultisnips, sometimes my snippets require me to enter many single numbers at a time, this can get tiring for the finger that uses the trigger key, I was wondering if it's possible to define more than one trigger/triggerforward/backward keys? If not could I help add this functionality?

**Comment by SirVer** [comment]
Currently not supported, could be added. It seems a very fringe feature though, so I would be hestitant to put it into the plugin proper.
