### ISSUE TITLE
Are nested snippets possible?

### ISSUE THREAD

**Issue by CyberMango** [SirVer/ultisnips#1093]
Hi, this is merely a question so i dont follow the template.

Is it possible to nest templates, so they expand together at once?
for example:
say I have 2 snippets called ba and ap:

snippet ba
banana
endsnippet

snippet ap
apple
endsnippet

is it possible to create a third snippet that will expand to "banana apple" by using the above snippets?
Im talking about something like this:

snippet fruits
snippet(ba) snippet(ap)
endsnippet

so that when i expand "fruits" i will get "banana apple".

p.s.
I know some issues about nesting were opened before, but the ones I found were either very old or not referring to the kind of nesting Im looking for.

thanks!

**Comment by SirVer** [comment]
No, this is not supported. No plans for adding it currently either.
