### ISSUE TITLE
Use FZF when multiple snippets available

### ISSUE THREAD

**Issue by Jab2870** [SirVer/ultisnips#1095]
This is not really an issue, I am curious as to whether this is possible.

Currently, if there are multiple snippets available that can be expanded, with the same priority, I am presented with a list of options. For example, the following screenshot is from when I try to expand `margin` with the vim-snippets plugin installed.

![2019-08-19_17:18:50_953x238](https://user-images.githubusercontent.com/1909202/63281877-91061c80-c2a5-11e9-99a9-6c26657a7ade.png)

Is it possible to pipe this into the fzf utility?

**Comment by SirVer** [comment]
No, not currently. It is also outside of the scope of UltiSnips to support this. There are various completion engines available for vim that support ultisnips and provide other means of completion though, for example deoplete.
