### ISSUE TITLE
it seems "set expandtab" works better in python code?

### ISSUE THREAD

**Issue by hyaray** [SirVer/ultisnips#1096]
```
set shiftwidth=4
set softtabstop=4
```
I press `<tab>` once, result is `4 space`
I press `<tab>` twice, 8 space auto change to `a tab`
so python error 

> "inconsistent use of tabs and spaces in indentation"

**Comment by SirVer** [comment]
I cannot parse what the request or the bug report here is. Closing until further information and a repro case is provided.
