### ISSUE TITLE
Compatibility with vscode snippets?

### ISSUE THREAD

**Issue by kaihendry** [SirVer/ultisnips#1097]
Are there tools to convert VScode snippets to ultisnips?

e.g. https://raw.githubusercontent.com/tj/vscode-snippets/master/go.json

**Comment by mg979** [comment]
@kaihendry try this:

```vim
command! -nargs=1 -complete=file ConvertVSCodeSnippets call ConvertVSCodeSnippets(<q-args>, 1)

fun! ConvertVSCodeSnippets(file, to_buffer)
  let file = join(readfile(expand(a:file)), "\n")
  let data = json_decode(file)
  
  let snippets = keys(data)
  let converted = {}

  if a:to_buffer
    new
    setfiletype snippets
  endif

  for snip in snippets
    let trigger = data[snip]['prefix']
    let body = data[snip]['body']
    let converted[snip] = ['snippet '.trigger] + body + ['endsnippet', '']
    if a:to_buffer
      silent put =converted[snip]
    endif
  endfor
  return converted
endfun
```

You run it with `:ConvertVSCodeSnippets <filename>`

**Comment by SirVer** [comment]
Thanks for the answer, @mg979!

Closing, as this is not actionable anymore.

**Comment by roachsinai** [comment]
Well, the code provide by @mg979 not works for some snippets: https://github.com/SvenBecker/vscode-pytorch/blob/master/snippets/pytorch.json

Such as snippet: `pytorch:init`.
