### ISSUE TITLE
snip.rv can't remove $1 self?

### ISSUE THREAD

**Issue by hyaray** [SirVer/ultisnips#1098]
I want replace input by dict, a -> AA, b -> BB
```
snippet a
${1:a}`!p snip.rv = {"a":"AA","b":"BB"}.get(t[1], "")`
endsnippet
```
result is `aAA` or `bBB`
if move `'}'` to the end, error
${1`!p snip.rv = {"a":"AA","b":"BB"}.get(t[1], "")`}

I use `t[1]` instead of `snip.rv`, it worked.
```
snippet b "description" b
`!p t[1] = {"a":"AA","b":"BB"}.get(t[1], "")`$1
endsnippet
```
I want check my thinking is right? 
I didn't find this infomation in UltiSnips.txt, may be you can update this file for mor infomation.
Thanks for you great ultisnips, I love it indeed!!

**Comment by SirVer** [comment]
UltiSnips cannot replace the text of existing tabstops (i.e. placeholders).
