### ISSUE TITLE
how to make snippets type " ` "

### ISSUE THREAD

**Issue by neulbo-187** [SirVer/ultisnips#1099]
**Expected behavior:**
I wanted to make a quotation mark snippet in LaTeX. I thought it was very easy

snippet qk "blah" iA
``$1" 
endsnippet

**Actual behavior:**

but the snippet just become " even though that i wanted is `` ".
I think in UltiSnips, ` is not a just a character so It could happen.
But I don't know how to fix it. please help me....

**Steps to reproduce**

1.
2.
3.

-----

- **Operating System**:  Ubuntu 18.04
- **Vim Version**: 8.0
- **UltiSnips Version**: The latest one at 19.09.11 (I updated it with vim-plug)
- **Python inside Vim**: python 3.6.8, GCC 8.3.0 (cf. the first command doen't work and makes error in my vim)
- **Docker repo/vimrc**:

**Comment by neulbo-187** [comment]
problem solved.

I changed my snippet as;

snippet qk "blah" iA
\`\`$1"
endsnippet

then it works. 

But I want to know why it works. Could you explain the reason or suggest something for studying about this language?

**Comment by SirVer** [comment]
~~~
snippet foo "Description" b
\`$1"
endsnippet
~~~

See https://github.com/SirVer/ultisnips/blob/2e727431f676e7ab9a8ec09ee680c0cd28f79846/doc/UltiSnips.txt#L731
