### ISSUE TITLE
can't jump to placeholder inside another placeholder

### ISSUE THREAD

**Issue by verandah** [SirVer/ultisnips#1101]
For example, it sucks when I have a snippet with command alike the following:
${2: abc $3 } $4
or ${2: abc ${3: def}} $4
my jumpforward key is  \<c-j\>, when I at 2nd placeholder and press \<c-j\>, it just skips the 3rd place holder and jump to the next ($4)

**Steps to reproduce**
for example, in txt.snippets I have
(example in ultisnips help)
snippet a
\<a href="$1"${2: class="${3:link}"}\>
    $0
\</a\>
endsnippet

in a txt file,
press the following:
a\<tab\>http://www.google.com \<c-j\> \<c-j\>visited \<c-j\> Google 

I expect to yield
\<a href="http://www.google.com" class="visited"\>
    Google
\</a\>

but instead, I yield:
\<a href="http://www.google.com" class="link}"\>
    visited
\</a\> Google

When at the 2nd placeholder, press \<c-j\>will jump to $0 and skip the 3rd place holder.
It behaves properly in other cases, like ${2:dfd} ${3:ccc}

.vimrc

behave mswin

set fileencodings=utf-8,ucs-bom,shift-jis,latin1,big5,gb18030,gbk,gb2312,cp936
set fileencoding=utf-8
set encoding=utf-8
set termencoding=utf-8

set nocompatible
set number
set foldmethod=manual

function! ToggleVerbose()
    if !&verbose
        set verbosefile=~/.log/vim/verbose.log
        set verbose=15
    else
        set verbose=0
        set verbosefile=
    endif
endfunction

let g:UltiSnipsExpandTrigger="\<tab\>"

set rtp+=$HOME\\vimfiles\\bundle\\Vundle.vim
set rtp+=$USERPROFILE\\vimfiles\\ultisnip

call vundle#begin('$USERPROFILE\vimfiles\bundle\')
Plugin 'VundleVim/Vundle.vim'
Plugin 'SirVer/ultisnips'
Plugin 'ryanoasis/vim-devicons'
Plugin 'scrooloose/nerdtree'
Plugin 'honza/vim-snippets'
Plugin 'lervag/vimtex'
Plugin 'khzaw/vim-conceal'
Plugin 'morhetz/gruvbox'
call vundle#end()

let g:UltiSnipsSnippetsDir = '$USERPROFILE\vimfiles\UltiSnips'
let g:UltiSnipsEnableSnipMate= 0

-----

- **Operating System**: Windows 10 Home
- **Vim Version**: vim8.1 (2018 May 18,compiled Sep 6 2019)
MS-Windows 64-bit GUI version with OLE support  (gvim)
- **UltiSnips Version**: use vundle and update to the newest version. 
- **Python inside Vim**: 3.7.4 64 bits
- **Docker repo/vimrc**:

**Comment by SirVer** [comment]
Cannot reproduce with latest master:

See here
https://asciinema.org/a/4BQVb8xcYodPCNY5LxQfYXR1Q
