### ISSUE TITLE
<Plug> mappings?

### ISSUE THREAD

**Issue by blueyed** [SirVer/ultisnips#1102]
What happended to this commit?  https://github.com/SirVer/ultisnips/commit/1e5c19a
(I've found it when looking at dangling commits, searching for something else that I had in a stash)

I am using the following myself, to allow for easier lazy loading via vim-plug, where "<Plug>" maps can be used in "on" triggers:

```vim
inoremap <silent> <Plug>UltiSnipsExpandSnippetOrJump <C-R>=UltiSnips#ExpandSnippetOrJump()<cr>
```

**Comment by SirVer** [comment]
> What happended to this commit? 1e5c19a

I don't know. It is not in master, but its parent is. I do not know why that patch is not in master.

**Comment by SirVer** [comment]
@blueyed See #1114. Apparently the indirection of mappings gives trouble when `langmap` is not empty. Feel free to fix the broken tests and I will gladly merge.

**Comment by blueyed** [comment]
@SirVer 
I'll not fix the tests likely soon, so feel free to drop / close it.

**Comment by SirVer** [comment]
This seems to be a problem inside Vim. I filed https://github.com/vim/vim/issues/5147 for upstream to investigate. Since this is not actionable for us atm, I'll close this.
