### ISSUE TITLE
Ultisnips not expanding snippets on MacVim (vim-plug as manager)

### ISSUE THREAD

**Issue by thrsam005** [SirVer/ultisnips#1104]
**Expected behavior:** Ultisnips expands snippets written to aid in TeX documents.

**Actual behavior:** Ultisnips does not expand snippets written to aid in TeX documents.

**Steps to reproduce:** Write a snippet using :UltiSnipsEdit. Whenever the name is entered into a TeX document, it does not expand (tab is the current bound key).

**NOTE:** If this problem is solved/easy to solve, sorry. I just haven't had any luck finding anything online to help with it.

-----

- **Operating System**:  macOS 10.14.6
- **Vim Version**:  8.1, macOS version
- **UltiSnips Version**:  3.1
- **Python inside Vim**:  2.7.10
- **Docker repo/vimrc**:  https://github.com/thrsam005/satprojects/blob/master/thrsam005vimrc.txt

**Comment by AamodJ** [comment]
Check out @bartekb81 comment #948 
It should resolve your issue

**Comment by thrsam005** [comment]
> Check out @bartekb81 comment #948
> It should resolve your issue

Thank you so much, everything works great.
