### ISSUE TITLE
multiple absolute paths in g:UltiSnipsSnippetDirectories

### ISSUE THREAD

**Issue by Konfekt** [SirVer/ultisnips#1117]
One question came up regarding the documentation on `g:UltiSnipsSnippetDirectories`:

> If the list has only one entry that is an absolute path, UltiSnips will not
iterate through &runtimepath but only look in this one directory for snippets.

Why iterate if there are, say, two absolute paths, listed? Is this forbidden?

**Comment by Konfekt** [comment]
May be related to https://github.com/SirVer/ultisnips/issues/815

**Comment by SirVer** [comment]
This variable is not meant to point to directories, it is meant to give names to snippet files inside a runtimepath. So let's say your `runtimepath` includes: `[ "~/.vim", "~/.vim_plugins/A", "~/.vim_plugins/B" ]`.

At its default value of `g:UltiSnipsSnippetDirectories = ["UltiSnips"]`, UltiSnips will search for snippets inside
~~~
~/.vim/UltiSnips
~/.vim_plugins/A/UltiSnips
~/.vim_plugins/B/UltiSnips
~~~

If you'd set it to `:UltiSnipsSnippetDirectories = ["foo", "bar"], UltiSnips would search:

~~~
~/.vim/foo
~/.vim/bar
~/.vim_plugins/A/foo
~/.vim_plugins/A/bar
~/.vim_plugins/B/foo
~/.vim_plugins/B/bar
~~~

This is how this variable was meant to be used. The idea is that third party plugins (like https://github.com/honza/vim-snippets) could ship snippets simply by adding an `UltiSnips` folder in their repo that contained snippets for their filetype. If the user did not want to use third party snippets, they could change this variable to not include `UltiSnips` but something like `OnlyMySnippetsPlease` which would allow them to ignore third party snippets. Note that in this logic, no behavior change of `UltiSnipsEdit` has happened.

I dimly remember the details of the developments here, but I do remember that users complained about slowness of stating so many directories in their `rtp` on snippet expansion. At this point the fatal design mistake was made that if (and only if) `g:UltiSnipsSnippetDirectories` would contain a single full path (like `$HOME/.vim/UltiSnips)`, only this directory would be searched for snippets. This continues to create a ton of confusion for users, and frankly myself.

So to answer your question: 
> Why iterate if there are, say, two absolute paths, listed? Is this forbidden?

Yes, it sorta is. I am not sure without looking at the code what UltiSnips would do in this case though.

**Comment by SirVer** [comment]
Closing, since this answered the question and this is no longer actionable. I believe it would make a ton of sense to redesign `UltiSnipsSnippetDirectoies` and `UltiSnipsSnippetDir`.
