### ISSUE TITLE
let g:UltiSnipsExpandTrigger="<C-b>" not working

### ISSUE THREAD

**Issue by cxwx** [SirVer/ultisnips#1122]
let g:UltiSnipsExpandTrigger           = '<c-b>'
let g:UltiSnipsJumpForwardTrigger      = '<C-b>'

not working

verbose imap <C-b>
nothing there

still <tab> keyblingding .
verbose imap <tab>
<Tab>       * <C-R>=UltiSnips#ExpandSnippet()<CR>

g:UltiSnipsExpandTrigger  <c-b> already

install plugin with 'VundleVim/Vundle.vim'

-----

- **Operating System**:  Mac OS catalina
- **Vim Version**:  homebrew lastest 8.1
- **UltiSnips Version**: 9b0d5fa4f756232cc0392706a5643a5b5148affd
- **Python inside Vim**: 3.7.4 (default, Sep  7 2019, 18:27:02)[Clang 10.0.1 (clang-1001.0.46.4)]

**Comment by SirVer** [comment]
Insufficient information to reproduce. Please provide your full `vimrc`.
