### ISSUE TITLE
Supertab && UltiSnips

### ISSUE THREAD

**Issue by Cherrry9** [SirVer/ultisnips#1126]
I read [here](https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L1785) that ultsnipst has [supertab](https://github.com/ervandew/supertab) support. But something is not working for me, when i press \<tab\> i don't see auto completion (pattern not found). When I used [deoplete](https://github.com/Shougo/deoplete.nvim) for auto completion everything worked and I saw the proposed snips. I'm doing something wrong?

- **Operating System**: Arch Linux
- **Kernel**:  5.3.8-arch1-1
- **Vim Version**: NVIM v0.4.2 Build type: Release
- **UltiSnips Version**: `44a73c1df201546a11e45461c84b84b1e7039d28`
- **Python inside Vim**: 3.7.4 
- **My vimrc**: https://github.com/Cherrry9/Dotfiles/blob/master/config/.config/nvim/init.vim

**Comment by SirVer** [comment]
Your problem is here:

https://github.com/Cherrry9/Dotfiles/blob/master/config/.config/nvim/init.vim#L279

You need to set your expand trigger to `<tab>`, otherwise UltiSnips will not even detect that it clashes with Supertab.
