### ISSUE TITLE
Make sure snip.rv's return value is "str" type

### ISSUE THREAD

**Issue by ashfinal** [SirVer/ultisnips#1134]
Please provide an explanation of the issue below this line. 

**Expected behavior:**

Snippet `uuid` can be expanded correctly

**Actual behavior:**

UltiSnips's debug window pops up, complainting:

``` shell
  File "C:\Users\ashfinal\.vim\plugged\ultisnips\pythonx\UltiSnips\text_objects\base.py", line 22, in _replace_text
    lines = text.split("\n")
AttributeError: 'UUID' object has no attribute 'split'
```

**Steps to reproduce**

1. Use lastest honza/vim-snippets@efecc996

2. Type `uuid` then `Tab` (UltiSnips's expand trigger)

``` python
snippet uuid "Random UUID" w
`!p if not snip.c: import uuid; snip.rv = uuid.uuid4()`
endsnippet
```

------------------------------------------------------------------------------

After a little investigation, I find snip.rv's return value should be "str" type(?). But here for this snippet the type is `uuid.UUID`.

Wrapping the value with `str()` solves the problem. I'm not quite sure if this is a bug.

------------------------------------------------------------------------------

- **Operating System**: Windows 10.0.14393
- **Vim Version**: NVIM v0.5.0-nightly-1-g471427d04
- **UltiSnips Version**: 84c84d5
- **Python inside Vim**: 3.7.4

**Comment by chiphogg** [comment]
I think I ninja'd you by filing #1132. :laughing:

**Comment by ashfinal** [comment]
It seems we run into almost same issue here? Such a coincidence. :)

**Comment by SirVer** [comment]
Closing as dupe.
