### ISSUE TITLE
":UltiSnipsAddFiletypes" not working

### ISSUE THREAD

**Issue by Kreest** [SirVer/ultisnips#1139]
**Expected behavior:**
":UltiSnipsAddFiletypes [filetype]" allows usage of "[filetype].snippets" snippets in other type of files. 

**Actual behavior:**
It doesn't seem to do anything. Using ":set filetype=cpp" works as expected, loads snippets.

**Steps to reproduce**

0. Clone my branch, make the docker image.
1. Open non-cpp file, e.g.: "vim testfile"
2. Use ":UltiSnipsAddFiletypes cpp"
3. Try to use a snippet from that snippets file, in the docker image: "cpptest<TAB>"
4. Nothing happens.

-----

- **Operating System**: Parabola Linux
- **Vim Version**: 8.0 (docker image) and 8.1 (my machine)
- **UltiSnips Version**: 3.2
- **Python inside Vim**: 3.6.9 (docker) 2.7.17 / 3.7.4 (my machine)
- **Docker repo**: https://github.com/Kreest/ultisnips/tree/addfiletypes-issue

**Comment by Kreest** [comment]
After a bit of messing around I found the solution, in `autoload/UltiSnips.vim` after dropping python2 support in #1129 a couple of function arguments ended up inside python strings and thus not being replaced by vim. I'll submit a quick pull request for this specific issue, but probably the whole commit should be rechecked for similiar errors. (basically all lines now matching `py3.*a:`)

**Comment by SirVer** [comment]
@Kreest Ah, good find. Thanks for reporting. I just grepped real quick and it seems to be the only wrong case.

**Comment by Kreest** [comment]
After looking it over I think so too. I made a pull request with what I think should be a good fix.
