### ISSUE TITLE
Autotrigger `[` then backspacing inserts stray characters

### ISSUE THREAD

**Issue by dadaurs** [SirVer/ultisnips#1141]
Hi everyone,

Let me start by saying that this is a pretty awesome vim plugin, it really does make writing with latex a breeze.

There is one little thing that has been bugging me lately, I use ultisnips to insert matching braces in neovim.
Until now, I had this line under ~/.config/nvim/ultisnips/tex.snippets:
~~~
snippet [ "Match square braces" A
[ $1] $0
endsnippet
~~~
.

Notice the space in front of the $1, if I don't ad it, I can't tab through it, since it only ads more braces.
This basically allows me to automatically create matching braces and then tab through them, which is really convenient.

However, there are two issues that come with this.
The first one is that, if I do not insert anything into the braces, it simply ads another ] in front of the cursor when pressing backspace, here is how:
[ ||] =========> (press tab) [ ||]],
where || represents the cursor.
If I press backspace multiple times, it simply ads more braces.

Here is another scenario in which this occurs, if I have two matching braces containing text, like:
[ This is a phrase ], then place my cursor into them and do 'ci[ ', it also inserts an extra closing brace like the example above.
It does the same, when I substitute (press s in normal mode) right in front of the opening brace.

And finally this happens with any type of brace wether it is a square one, a curly one or the normal ones.
I guess this has to do with ultisnips checking for the previously inserted character when it goes back to insert mode from normal mode, but I really don't know this. 

I know this is somewhat more of a feature request than a bug report, but I found it weird and was wondering if there were any easy workarounds for this.

This happens on all  my machines wether it is my gentoo system or my macos system, so I don't believe that the (neo)vim version is relevant, if it somehow is, it is 0.4.2 for my neovim.

I'm really not sure about my ultisnips version, but it should be the latest one, e.g. 3.1, I just did :PlugUpdate a few minutes before posting this.

My python version inside vim is 2.7.16 and 3.6.9.

I've tried this with no .vimrc (or init.vim in my case) at all, so I dare say it isn't necessary to provide one.
If someone knows a workaround for this, please let me know, it would be greatly appreciated.

**Comment by SirVer** [comment]
Confirmed this first issue, it also happens with vanilla Vim.

I cannot parse the rest of your bug report/feature request, i.e. what is your second issue? I suggest opening a new bug report for it (one report per issue).

**Comment by dadaurs** [comment]
Oh, sorry for being unclear,

The two issues are somewhat related, they really probably are manifestations of the same bug, once triggered by the backspace key and once by doing ci[ .

**Comment by piperfw** [comment]
I also find the fact that autotrigger attempts to match on _any_ change in insert mode to be an issue, for example, with the snippet
```
snippet ( "parentheses" iA
(${1:${VISUAL}})$0
endsnippet
```

Suppose I want to type `(abc)` and accidentally start by writing `(b` which creates `(b|)` where `|` is the cursor. Instinctively, I backspace to remove the `b`, leading to `(|))` as the cursor hits the first parenthesis and the snippet is triggered for a second time.

Is it possible to have autotrigger work only when characters are inserted? Or only to be activated at most once perhaps?

**Comment by SirVer** [comment]
@piperfw This is a separate issue that you are mentioning. There is already a bug for this somewhere, do I am unable to find it right now. Please either find that one or open a new issue, but let's keep this one on topic.

**Comment by piperfw** [comment]
@SirVer Understood - I had a good search but couldn't find an issue (open or closed) for my problem, so I created a new one  (#1157) as suggested.

**Comment by dadaurs** [comment]
@seletskiy  seems to have submitted a patch which fixes this issue, any chance this will get merged into master?
