### ISSUE TITLE
Error Persists.  Updating with all information, including screen shots of my directories.

### ISSUE THREAD

**Issue by sgarrison05** [SirVer/ultisnips#1143]
Expected behavior:

No Error

Actual behavior:
~~~
**Error detected while processing function UltiSnips#Edit:
line 6:
Traceback (most recent call last):
File "", line 1, in
File "/home/sgarrison/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 848, in _file_to_edit
return _select_and_create_file_to_edit(potentials)
File "/home/sgarrison/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 73, in _select_and_creat
e_file_to_edit
file_to_edit = potentials.pop()
KeyError: 'pop from an empty set'**
~~~

Steps to reproduce

1.) Install vim-pathogen and put pathogen infect lines in .vimrc to infect.  Then, go into vim directory: ~/.vim/

2.) mkdir bundle && git clone https://github.com/sirVer/ultisnips; git clone https://github.com/honza/vim-snippets

3.) Go into Vim 

4.) type :UltiSnipsEdit

I have copies the lines from the quick start to my .vimrc file.

1. Start vim
2. :UltiSnipsEdit
3. Error Occurs

Operating System: Ubuntu 16.04.6 LTS (Xenial), XUbuntu 18.10 LTS (Bionic), & Ubuntu Mate 18.10 LTS (Bionic)

Vim Version: 8.0.1453

UltiSnips Version: Current Version 3.0 I pulled it from github through git clone command.

Python inside Vim: Python Installed Versions 2.7.12 / 3.5.2

----------------------------------------------------------------------------------------------------------------
~~~vim
" .vimrc file start

"========================= My Settings ========================={{{

" Set the window’s title, reflecting the file currently being edited
set title

set t_Co=256

" Turn on Syntax highlighting
syntax on
syntax enable

" Show incomplete commands at the bottom
set showcmd

" colorscheme
colorscheme colorful256

" Set font for cmd line
set guifont=Meslo\ LG\ S\ DZ\ Regular\ for\ Powerline

" Sets parameters for gvim
if has ('gui_running')
"set guifont=Monospace\ 12
set guifont=Droid\ Sans\ Mono\ for\ Powerline\ 14
set guioptions-=T "removes toolbar
endif

" Sets the intial path of my Text Folder
:cd ~/Documents/Text

" Sets backup folder
set backup
set backupdir=/home/sgarrison/Documents/VBak
set directory=/home/sgarrison/Documents/VBak

"ups history from default 20
set history=200

"Sets filetypes
autocmd BufNewFile,BufRead .md,.mkd,.mkdn,.markdown set filetype=markdown

" Sets advanced encryption
set cryptmethod=blowfish

" Set Wildmode menu
set wildmode=longest,list
set wildmenu
set showmode
set wildignore+=/tmp/,.so,.swp,*.zip 

" Invisible character colors
highlight NonText guifg=#4a4a59
highlight SpecialKey guifg=#4a4a59

" sets autoindent feature
set autoindent

" set line numbering"
set nu
set relativenumber

" sets linebreak
set linebreak

" wraps text
set wrap

" set ruler
set ruler

" turns off highlight search
set nohlsearch
set incsearch " searches characters as they are entered
set smartcase "Automatically switch search to case-sensitive when search query contains an uppercase letter

" Beautify display of hidden characters (tabs and line breaks)
" (:set list! to toggle)
set listchars=tab:▸\ ,eol:¬

" sets tabstop, softtabstop, shiftwidth and expandtab settings
" set ts=8 sts=0 sw=8 noexpandtab - default settings
set ts=4 sts=4 sw=4 expandtab

" Set region to USA English
set spelllang=en_us

" Allows you to change buffer w/o saving
set hidden

" Sets maximum textwidth
"set colorcolumn=80
set textwidth=97

" Moving up and down as you would expect
nnoremap j gj
nnoremap k gk

" jk is escape
inoremap jk <esc>

" The number of screen lines/columns to keep beside/above/below the cursor
set scrolloff=1
set sidescrolloff=5

"========================= Mappings ============================{{{

" Changes the leader key from \ (defaut)
let mapleader = ","

" see file explorer in tree style - Vimbits.com
let g:netrw_liststyle=3

" Sets ,v to open tab edit of my .vimrc file
nmap v :tabedit $MYVIMRC

" If .vimrc is the file open, it automatically writes and sources any
" changes
if has("autocmd")
autocmd bufwritepost .vimrc source $MYVIMRC
endif

"}}}
"========================= Printing ==========================={{{

"Takes out header in print options
set popt=header:0

"}}}
"========================= Plugins ============================{{{

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Airline
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

set encoding=utf-8 " Necessary to show Unicode glyphs
set nocompatible " Disables vi-compatibility
set laststatus=2 " Always show the statusline
let g:airline_powerline_fonts=1
let g:Powerline_symbols = 'fancy'

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" NERDTree
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

map n :NERDTree
" Close NERDTree after file is open
let g:NERDTreeQuitOnOpen=1

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" CtrlP
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

let g:ctrlp_map = ''
let g:ctrlp_cmd = 'CtrlP'

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Pathogen
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

execute pathogen#infect()
syntax on
filetype plugin indent on

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" UltiSnips
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" Trigger configuration.
let g:UltiSnipsExpandTrigger=""
let g:UltiSnipsJumpForwardTrigger=""
let g:UltiSnipsJumpBackwardTrigger=""

" If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit="vertical"

" Some versions I have done has this added to the .vimrc
let g:UltiSnipsSnippetDirectories=['~/.vim/UltiSnips/', 'UltiSnips']

"}}}
~~~

![bundle_directory_Screenshot 2019-11-16 15:23:26](https://user-images.githubusercontent.com/6225458/68999404-3c167a00-0885-11ea-9256-094c4308cc80.png)
![vimfile_Screenshot 2019-11-16 15:22:38](https://user-images.githubusercontent.com/6225458/68999405-3c167a00-0885-11ea-978b-a13c60a79514.png)

**Comment by sgarrison05** [comment]
I have discovered that having a link in the main .vim directory to bundle/vim-snippets/snippets and bundle/vim-snippets/UltiSnips will throw a different error.  I removed the links and copies the directories to the main .vim directory.

**Comment by sgarrison05** [comment]
I solved this problem.  It had to do with my directories and how they were set up.  I am still playing with settings, but it is working.  Therefore, this can be closed.

**Comment by SirVer** [comment]
> I solved this problem. It had to do with my directories and how they were set up. I am still playing with settings, but it is working. Therefore, this can be closed.

Could you outline what the underlying issue was? I am unconvinced if there is not really a bug in UltiSnips here, i.e. a setup that UltiSnips should be more resilient against.

**Comment by sgarrison05** [comment]
It was the settings in my .vimrc and they way I had my bundle directories set up.  It would throw when I attempted to point the ,vimrc UltiSnippets directories to bundle/vim-snippets/UltiSnips though (let g:UltiSnipsSnippetDirectories=['~/.vim/bundle/vim-snippets/UltiSnips/']). I disovered that by changing that to a backup directory (renaming it UltiSnips.bak) and copying it to the .vim folder as UltiSnips, the error ceased to show.  I used a combination of Google and UltiSnips documentation to solve the problem.  Thank you for this wonderful plugin.  I really like it and I think it's going to save me a lot of typing.

**Comment by SirVer** [comment]
@sgarrison05 That sounds quite non-standard indeed. I suggest to try the following: do not have any symlinks or .bak copies, instead just clone vim-snippets and UltiSnips into `~/.vim/bundle`. Now, remove the line `let g:UltiSnipsSnippetDirectories=['~/.vim/UltiSnips/', 'UltiSnips']` in your vimrc. Now try `:UltiSnipsEdit!` and I assume things should work as expected.

**Comment by sgarrison05** [comment]
Thank you. I will try that.

-- 
Shon Garrison 

     On Tuesday, November 19, 2019, 1:51:10 PM CST, Holger Rapp <notifications@github.com> wrote:  
 
 
@sgarrison05 That sounds quite non-standard indeed. I suggest to try the following: do not have any symlinks or .bak copies, instead just clone vim-snippets and UltiSnips into ~/.vim/bundle. Now, remove the line let g:UltiSnipsSnippetDirectories=['~/.vim/UltiSnips/', 'UltiSnips'] in your vimrc. Now try :UltiSnipsEdit! and I assume things should work as expected.
