### ISSUE TITLE
Snippets not loading

### ISSUE THREAD

**Issue by ettom** [SirVer/ultisnips#1144]
After updating UltiSnips, my custom snippets aren't loaded any more and `:UltiSnipsEdit` gives this error:
```
Error detected while processing function UltiSnips#Edit:
line    6:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ettom/.config/vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py",
 line 836, in _file_to_edit
    dot_vim_dir = Path(vim_helper.get_dot_vim())
  File "/home/ettom/.config/vim/bundle/ultisnips/pythonx/UltiSnips/vim_helper.py", line
 228, in get_dot_vim
    "Unable to find user configuration directory. I tried '%s'." % candidates
RuntimeError: Unable to find user configuration directory. I tried '['/home/ettom/.vim'
]'.
```

The problem seems to be that UltiSnips is searching for snippets in `~/.vim`, but my vim config folder resides in `~/.config/vim`.
I have set the env var `VIMINIT=let $MYVIMRC="/home/ettom/.config/vim/vimrc" | source $MYVIMRC`
Ultisnips is in `~/.config/vim/bundle/ultisnips`, custom snippets are in `~/.config/vim/UltiSnips`.
 I could just set `let g:UltiSnipsSnippetDirectories
= ['/home/ettom/.config/vim/UltiSnips']`, but doing this, the snippets from `vim-snippets` are not loaded any more. Custom snippets and `:UltiSnipsEdit` work however.

Related to #711, #1138?

**Expected behavior:**
Custom snippets and `:UltiSnipsEdit` work.

**Actual behavior:**
Described above.

**Steps to reproduce**
Unfortunately, I couldn't set up a minimal vimrc without using Vundle, as running
UltiSnips with `:set rtp` statements caused `ImportError: No module named
'UltiSnips'`.

Minimal vimrc
```
set nocompatible
set rtp=~/.config/vim,$VIM,$VIMRUNTIME
set rtp+=~/.config/vim/bundle/Vundle.vim
let $MYVIMRC="~/.config/vim/vimrc"
call vundle#begin(expand('~/.config').'/vim/bundle')
Plugin 'gmarik/Vundle.vim'
Plugin 'SirVer/ultisnips'
call vundle#end()
filetype plugin indent on
```

1. Create ~/.config/vim/vimrc with the content above
2. `export "VIMINIT=let \$MYVIMRC=\"$HOME/.config/vim/vimrc\" | source \$MYVIMRC"`
3. Install Vundle - `git clone https://github.com/VundleVim/Vundle.vim.git ~/.config/vim/bundle/Vundle.vim`
5. Install UltiSnips with `:PluginInstall`
6. Restart vim and run `:UltiSnipsEdit`

-----

- **Operating System**: Ubuntu 16.04
- **Vim Version**: `VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov  8 2019 15:29:07)
Included patches: 1-2108`
- **UltiSnips Version**: `f7b9b3b1100b3b2883ed2d0ac3627708a10dc469`
- **Python inside Vim**:
```
2.7.12 (default, Oct  8 2019, 14:14:10)
[GCC 5.4.0 20160609]
3.5.2 (default, Oct  8 2019, 13:06:37)
[GCC 5.4.0 20160609]
```

**Comment by sgarrison05** [comment]
This is the same error I was throwing and just solved.  If I understand it correctly, once you have UltiSnips installed(I used pathogen). The problem becomes UltiSnips cannot find your snippets directory.  It either does not exist or has not been created yet.  You should include SirVer's Quick Start settings in your .vimrc ---->" 

Trigger configuration. 
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"

" If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit="vertical"

"Directories
let g:UltiSnipsSnippetDirectories=["UltiSnips", "or your directory name for personal snippets"] 

The last statement looks for snippet file named "UltiSnips" or "your directory name" in your .vim folder.  Create it after completing the .vimrc file if it does not exist.  You can also download honza/vim-snippets for third party snippets.  If you do this, you have to move or copy your UltiSnips file up a couple of levels from that directory to the main .vim folder. That is what worked for me.

You can also look at https://codefor.life/ultisnips/ and https://stackoverflow.com/questions/31844014/trying-to-change-directory-for-ultisnips-snippets for help.

**Comment by SirVer** [comment]
@ettom Thanks for the bug report! I could follow it quite easily and reproduce. In general I think you are living on the edge with this non-standard place of vim directory and the hack you are using to satisfy Vim will likely not work for most plugins. Is this all just to avoid a `~/.vim` directory? Why not make a symlink `ln -s ~/.config/vim ~/.vim` instead? No matter, I added a fix that should work for you in #1146. 

@sgarrison05 I do not understand how your comment relates to OPs. I think you might have misdiagnosed or I am misunderstanding your post.

**Comment by Ram-Z** [comment]
I'm running into this issue still. Steps to reproduce are the same as above but with

```bash
export XDG_CONFIG_HOME="$HOME/.config"
export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'
```

I guess the main difference is that OP lets the shell expand his `$HOME` variable where I pass it to vim to be expanded there.

It's an easy fix on my side, it just raises the question wether this plugin should attempt to expand environment variables in `$MYVIMRC` or not. It would make it consistent with the way vim handles it.

**Comment by SirVer** [comment]
@Ram-Z Could you try out #1162 and report back?

**Comment by Ram-Z** [comment]
That does indeed work.

It brings up a new unexpected behaviour though. Note the change it case.

```
  1: /home/ramsi/.config/vim/UltiSnips/vim.snippets
* 2: /home/ramsi/.config/vim/ultisnips/vim.snippets
Type number and <Enter> or click with mouse (empty cancels):
```
`vim/UltiSnips` does not exist and I have no desire to use it, everything else in that folder is lower case.

I suppose this is a result of my vimrc.

```vim
let g:UltiSnipsSnippetsDir = expand("$XDG_CONFIG_HOME/vim/ultisnips")
if has('fname_case')
  let g:UltiSnipsSnippetDirectories = ["UltiSnips", "ultisnips"]
endif
```

Until recently(?) `:UltiSnipsEdit` would use `g:UltiSnipsSnippetsDir` to decide where to put/edit private snippets, so there was only one choice and it would open that directly. This is not the case anymore.

IMO the setting for where to look for public snippets and where to edit private snippets should be separate as it was before (maybe with a better name though ;) )

**Comment by SirVer** [comment]
> IMO the setting for where to look for public snippets and where to edit private snippets should be separate as it was before (maybe with a better name though ;) )

This setting let to a lot of confused users and some subtle bugs, so it was nixed.

I also consider the option in your case as simple: just use `UltiSnips` instead of `ultisnips` and you are all set. I am going ahead and merge #1162 and consider this bug here as closed. Feel free to open a new issue if you want to discuss your new issue further.
