### ISSUE TITLE
Feature request: global regex variable

### ISSUE THREAD

**Issue by tbrazel** [SirVer/ultisnips#1147]
I was wondering if it would be possible to define a regular expression globally, which can be called for each snippet.

I have a tex.snippets file with a few hundred unique snippets, and most of them start out with exactly the same regex code `([\s\d\",._=:\$\/\(\)\|\{\}\[\]\\]|^)`, so that I can expand math commands in many situations without typing a space before the previous command.

Instead of rewriting this regex at the start of every snippet, would it be possible to define a global regex variable at the top of my snippets file, e.g. `var regex = '([\s\d\",._=:\$\/\(\)\|\{\}\[\]\\]|^)'` and then call this string for each snippet?

I apologize if this has been asked before, I couldn't find this in the documentation. Thanks!

**Comment by SirVer** [comment]
Uhhh.... While I feel your pain, I am very hesitant making the snippets DSL more complicated than it already is, as it stands it is already too complicated for most users. I wonder if snippet contexts can make your life easier: https://github.com/SirVer/ultisnips/blob/c309637e0243b71f7e3265ebe3cffdfe9674cfbc/doc/UltiSnips.txt#L1371?

It would also help if you spell out more precisely what you need, i.e. clarify: 

> so that I can expand math commands in many situations without typing a space before the previous command.

**Comment by tbrazel** [comment]
Ah that's understandable - no problem :)


> It would also help if you spell out more precisely what you need, i.e. clarify:

> >    so that I can expand math commands in many situations without typing a space before the previous command.

What I meant was that, for instance instead of typing `= frac` and then hitting tab to expand a fraction command in LaTeX, I instead type `=frac` to save time having to type a space. As a result, I have a regex which matches
```
snippet '([\s\d\",._=:\$\/\(\)\|\{\}\[\]]|^)fr' "fraction" r
\\frac{$1}{$2}$0
endsnippet
```

I am aware of snippet contexts, and often use them to detect being inside a math environment, although in this particular instance I think sticking with regex will work best. Thanks for your help!

**Comment by SirVer** [comment]
I assume you are also familiar with inword expansion, but my guess is that it is too general for this case. Sorry, mate, I feel I do not have a great suggestion here otherwise.
