### ISSUE TITLE
How do you prevent snippet expansion on backspace / deletion?

### ISSUE THREAD

**Issue by ColinKennedy** [SirVer/ultisnips#1152]
This is more of a "user question" than an issues.

I have a snippet that looks roughly like this

```
global !p
def only_sometimes_expand():
    # This function is (in reality) more complex
    return True

context "only_sometimes_expand()"
snippet " " "Auto-add ' = ' if beginning of a line" rbA
 = $1
endsnippet
```

It's a nice and fairly harmless snippet that saves some typing while assigning variables. Of course, `only_sometimes_expand()` is prevents the snippet from expanding whenever it shouldn't. It's basically perfect currently. If I have a line like 

"foo |cursor|"

it auto-expands to

"foo = |cursor|"

There's a minor issue though. If I try to backspace after an expansion, like this:

"foo = |cursor|"
"foo =|cursor|"
"foo |cursor|"

Once it hits "foo |cursor|", the snippet auto-expands again. Is there a way to make sure the snippet doesn't expand when I'm trying to backspace/delete/revert the text?

**Steps to reproduce**

n/a. See snippet above.

-----
- **Operating System**: CentOS Linux 7 (Core)
- **Vim Version**: VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 27 2019 12:28:27)
Included patches: 1-2226
- **UltiSnips Version**: 3.2
- **Python inside Vim**: 2.7.5

**Comment by SirVer** [comment]
No, there is not really currently. Maybe you could model something in your `only_sometimes_expand` function by tracking `vim.current.line` in a static/global variable and see if it got shorter vs longer.
