### ISSUE TITLE
`:UltiSnipsEdit` fails when `~/.vim/UltiSnips` is a symlink

### ISSUE THREAD

**Issue by BojanStipic** [SirVer/ultisnips#1153]
`:UltiSnipsEdit` fails to open a snippets file, but only when `~/.vim/UltiSnips` is a symlink.

**Expected behavior:**
Calling `:UltiSnipsEdit` should open up the snippets file.

**Actual behavior:**
I get the following error:
```
Error detected while processing function UltiSnips#Edit:
line    6:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/bojan/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 848, in _file_to_edit
    return _select_and_create_file_to_edit(potentials)
  File "/home/bojan/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 73, in _select_and_create_file_to_edit
    file_to_edit = potentials.pop()
KeyError: 'pop from an empty set'
```

**Steps to reproduce**

1. `ln -s /some/other/path ~/.vim/UltiSnips`
2. Open vim
3. `:UltiSnipsEdit`

-----

- **Operating System**: GNU/Linux
- **Vim Version**: `VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov  7 2019 22:30:47)
Included patches: 1-2268`
- **UltiSnips Version**: `43b059bf1c20a1d328b7499c45332d367620c541`
- **Python inside Vim**: 
```
2.7.17 (default, Oct 22 2019, 09:14:09)
[GCC 9.2.0]
3.8.0 (default, Oct 23 2019, 18:51:26) 
[GCC 9.2.0]
```

**Comment by SirVer** [comment]
Thanks for the report. I was able to come up with a quick fix for this.
