### ISSUE TITLE
How to call into ultisnips to start its tab handling?

### ISSUE THREAD

**Issue by bhcleek** [SirVer/ultisnips#1155]
**Expected behavior:**
As a plugin author, I would like to be able to trigger ultisnip's tab handling (e.g. jumping to placeholders) when a snippet is inserted via language server based autocompletion.

**Actual behavior:**
I can't figure out how to do it, maybe it's possible already?

**Steps to reproduce**
1.  Install vim-go
1. Add `let g:go_gopls_use_placeholders=1` to vimrc
1. Edit a go file
1. Trigger autocompletion using `<C-x><C-o>`

The placeholders are included, but they don't come from a configured snippet, they're being dynamically generated and inserted. Is there something that I can do from within vim-go (I'm the maintainer) to a function in ultisnips to act as if ultisnips had inserted the text and therefore start allow users to jump to the placeholders just as they would if it were a statically defined snippet or an anonymous snippet that was triggered.

-----

- **Operating System**:  any, but I'm using macOS 10.15.1
- **Vim Version**: 
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov  6 2019 08:27:51)
macOS version
```
- **UltiSnips Version**: 
I'm not sure, but it's probably a little stale
- **Python inside Vim**: 
```
3.7.5 (default, Nov 24 2019, 13:13:03)
[Clang 11.0.0 (clang-1100.0.33.8)]
```
- **Docker repo/vimrc**:

**Comment by SirVer** [comment]
I do not understand the question, I think... Or maybe I do: How about using feedkeys to type: `<trigger><C-R>=UltiSnips#ExpandSnippet()<cr>`? Would that solve your issue?

Otherwise the API allows for expansion of anonymous snippets only, not by tab trigger.

**Comment by bhcleek** [comment]
After more carefully reviewing the documentation for `UltiSnips#Anon`, I think that's what I need to use, but I'm having a hard time getting it work as I expect.

I have a `CompleteDone` autocmd handler that calls `call UltiSnips#Anon(v:completed_item.word, v:completed_item.word)`, but it doesn't seem to put me in the snippet. Here's a screen recording to demonstrate what I'm seeing:
![recording](https://user-images.githubusercontent.com/1958864/70850283-6dab4280-1e3d-11ea-8567-7e41e6a25991.gif)

Any help you can provide about the proper way to call `UltiSnip#Anon` is appreciated.

**Comment by bhcleek** [comment]
I discovered the the solution to the problem I was having. I simply needed to call `UltiSnips#Anon` with the `'i' option to allow expansion in the middle of word.
