### ISSUE TITLE
Have Autotrigger trigger only execute by typing in insert mode

### ISSUE THREAD

**Issue by piperfw** [SirVer/ultisnips#1157]
To me, the expected behaviour of the snippet
```
snippet ( "parentheses" iA
(${1:${VISUAL}})$0
endsnippet
```
would be to create a closing parenthesis only when _inserting_ an opening parenthesis `(`  (such a  snippet is very useful as it pairs parentheses and allows you to jump quickly out of them). 

However, with the snippet as defined, if I type `(a` (producing `(a|)` where `|` is the cursor position) then realise the `a` was a mistake, backspacing to delete the `a` results in the snippet triggering a second time, leaving the awkward `((|)` (instinctively one then backspaces again in an attempt to remove the extraneous `(`, and the whole situation escalates!).

Similarly, the snippet is also triggered if from normal mode I use substitute (default binding `s`) to replace the `a`.

Firstly we should determine whether it is the intended behaviour to have the `A` option produce snippets which can repeatedly fire in this way (as I said, I would expect not, but others may have a different view on this). If it is intended behaviour, perhaps this could be tagged as a feature request: Automatic snippets which trigger on insert only (or even, trigger a maximum of on time only).

**Comment by SirVer** [comment]
I do think that it is reasonable that autotriggers only fire in insert mode after an insertion, everything else seems not intuitive to me. However implementing a heuristic that detects this in a stable way is probably not too easy. I'd suggest going with checking if the line got longer since the last edit, but this would not capture replacements.

**Comment by mg979** [comment]
@SirVer you could keep track of the buffer size on TextChangedI events

    let size = line2byte(line('$') + 1) - 1

and then autotrigger only if the new size is bigger than the previous one.

**Comment by IsaacElenbaas** [comment]
Arrow keys also trigger it - I make `lim` auto-expand to `lim_($1)^($2)` for AsciiMath. If I move left to change something without switching modes, it triggers again. I'm looking into `context` to just not trigger it if there's an underscore following, but it's going to be ugly and I'll need to copy it for all my similar snippets.
