### ISSUE TITLE
Windows: duplicate snippets paths

### ISSUE THREAD

**Issue by mg979** [SirVer/ultisnips#1158]
Since commit https://github.com/SirVer/ultisnips/commit/3a8b0548b3efd01bff0393f8f32228786149806c this happens when trying to expand any snippet in Windows:

![immagine](https://user-images.githubusercontent.com/26169924/71154047-f4e02800-223a-11ea-9bf4-d7dcd7862f1b.png)

**Comment by SirVer** [comment]
Ohh.. that sucks. It seems that the difference is `\` vs `/` in those two paths. I also notice that back and front slashes are wildly mixed in these paths. I have no explanation how this comes about. I assume that `os.path.realpath` removes this and makes all paths the same. I'll have a quick look if we can do something without reverting the full commit.

Could you give #1159 a whirl and report back?

**Comment by SirVer** [comment]
Closing optimistically after #1159 got merged. @mg979 please test and report back if the problem persists.

**Comment by mg979** [comment]
Fixed, thanks.
