### ISSUE TITLE
Insert mode lags

### ISSUE THREAD

**Issue by habamax** [SirVer/ultisnips#1165]
In insert mode I can see quite a lag especially when I do enter Russian letters. 

**Expected behavior:**
Should be no lag

**Actual behavior:**
Lag

![ultisnips-issue1](https://user-images.githubusercontent.com/234774/72271345-c4bc5700-3637-11ea-98f2-ec21a0c098f6.gif)

**Steps to reproduce**

Well, not sure. I just had it installed for quite a long time

Settings that I had regarding ultisnips
```
	let g:UltiSnipsExpandTrigger = '<tab>'
	let g:UltiSnipsJumpForwardTrigger = '<tab>'
	let g:UltiSnipsJumpBackwardTrigger = '<s-tab>'
	let g:UltiSnipsListSnippets = '<c-tab>'
```

My snippets were:

https://github.com/habamax/.vim/tree/03dce7b57131e993b5ccdc88775196c2f5fe7ef6/UltiSnips

If I remove Ultisnips (use vsnips instead):
![ultisnips-issue3](https://user-images.githubusercontent.com/234774/72272415-a192a700-3639-11ea-836c-4eece02682eb.gif)

PS

If I remove `au! Ultisnips_AutoTrigger` it becomes way faster. But only for english. Russian lags the same.

![ultisnips-issue2](https://user-images.githubusercontent.com/234774/72272038-026daf80-3639-11ea-8608-75c4057febae.gif)

-----

- **Operating System**: Win10 
- **Vim Version**: 8.2.114 
- **UltiSnips Version**: current master
- **Python inside Vim**: 3.8.1

**Comment by lacygoill** [comment]
> Steps to reproduce

> Well, not sure.

Without a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example) there's no way to know what causes your issue.  Bisect your config until you find one, then post it here.

Here's what a MWE could look like:

    " in `/tmp/vimrc`
    let g:UltiSnipsSnippetDirectories = ['/tmp/snippets']
    let g:UltiSnipsExpandTrigger = '<tab>'
    set rtp-=$HOME/.vim
    set rtp^=$HOME/.vim/plugged/ultisnips
    set rtp+=$HOME/.vim/plugged/ultisnips/after
    set rtp^=$HOME/.vim
    filetype plugin on

    # in `/tmp/snippets/vim.snippets`
    snippet trigger
    my snippet has been expanded
    endsnippet

    " start Vim like this:
    $ vim -Nu /tmp/vimrc /tmp/vim.vim

    " type those keys: ....

See also [reproducing-bugs](https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs).

---

Just a guess, but in your gifs, the text is folded; folding can introduce lags.
Check whether you can reproduce after temporarily setting `'foldmethod'` to `manual` (`:setl fdm=manual`), or try [`vim-fastfold`](https://github.com/Konfekt/FastFold).

**Comment by lacygoill** [comment]
Also, try to get a profile:

    :prof start /tmp/profile.log
    :prof! file /path/to/ultisnips/**/*.vim
    :ru! /path/to/ultisnips/**/*.vim
    " reproduce the issue, then quit Vim; the profile should be written in `/tmp/profile.log`

**Comment by habamax** [comment]
> Just a guess, but in your gifs, the text contains fold markers; folding can introduce lag.
> Check whether you can reproduce after temporarily setting `'foldmethod'` to `manual` (`:setl fdm=manual`), or try [`vim-fastfold`](https://github.com/Konfekt/FastFold).

That is not the case:

1. without ultisnips it doesn't lag with the same file, same folding settings
2. folding is `marker`
3. it lags the same on a new file without folding at all (`set fdm=manual`)

**Comment by lacygoill** [comment]
Ok, then you'll have to bisect your config to find a minimal reproducible example.

**Comment by habamax** [comment]
> Ok, then you'll have to bisect your config to find a minimal reproducible example.

Busy at work, will try to do it when I have time. Thx.

**Comment by habamax** [comment]
Well, I've spent last 1.5 hour bisecting my config, removing/reinstalling plugins and couldn't find the exact thing that makes ultisnips slow.

without any plugins installed next lines in my vimrc makes ultisnips slower (not THAT slow as in my previous gifs but I can see it):

```
func! SetDefaultFiletype()
	if @% == "" && &filetype == ""
		setfiletype txt
	endif
endfunc
augroup default_filetype
	autocmd!
	autocmd BufEnter * call SetDefaultFiletype()
augroup END
```

When I start adding other plugins one by one, ultisnips become slightly more laggy with each plugin I install until the result u see in gifs. I couldn't find single plugin that adds all the laggines fo far.

I think you can close the issue and reopen it when there will be other reports on it (I will continue using vsnip for now as I don't have time at the moment to investigate root cause)

Thank you!

**Comment by SirVer** [comment]
This is very unfortunate behavior and I am deeply sorry that it bothered your editing experience. Windows support is traditionally the poorest in UltiSnips. The reason is that I do not have access to a Windows machine and have in fact not worked on any Windows machine for ten years or so. 

traditionally, the Python <-> Vim bridge in Windows was not very performant. My hunch (without any data) is that string conversions (Vim uses UTF8, while Windows traditionally uses Unicode 16 or so, which I *think* python on Windows also uses internally) are expensive and that could be the reason you see slow downs. However, I do not have the means to investigate this.

I'll leave this open for a while to see if somebody else jumps on it and can add additional data.

@habamax Thanks for investing so much time and energy into this bug report!

**Comment by jperrett256** [comment]
Just wanted to say I have experienced this on both Linux and Windows.

**Comment by ws051682** [comment]
> Just wanted to say I have experienced this on both Linux and Windows.

Indeed, i'm using ubuntu and I do have similar issue.

**Comment by mnemster** [comment]
I can confirm that I have the same issue on GVIM on Windows (but not on GVIM on KDE Linux, though). The lag is specially noticeable when editing text files (perhaps because I type prose much faster than code?) and creating a new snippet file for texts with :UltiSnipsEdit seamed to alleviate the lag a little (any snippet will do, just need to create the file).

**Comment by skywind3000** [comment]
Same issue for GVim+win10

**Comment by SirVer** [comment]
@skywind3000 Thanks for investing time into this issue, I highly appreciate it.

TrackChanges is doing a diff between the buffer as it was before the last cursor move and after the current cursor move. This is needed to understand how the buffer change to update tabstops, mirrors and therelike. It is a potentially very expensive function if the buffer has changed tremendously (e.g. if you paste a lot of text while a snippet is active), however it is surprising to me that it would depend on the runtime path. 

It also calls `try_expand` which will try to expand autotrigger snippets on cursor move. This function will once load the snippets for the current file type - [this will indeed traverse all runtimepaths](https://github.com/SirVer/ultisnips/blob/master/pythonx/UltiSnips/snippet_manager.py#L679) - but [then only ever reload](https://github.com/SirVer/ultisnips/blob/master/pythonx/UltiSnips/snippet/source/file/base.py#L31) them when a .snippets file is saved in the current vim session. I just verified this with some quick debug printf that this indeed works as intended (on my system).

I think a bit more digging is required on your end - I cannot reproduce lag in simple buffers even with 300 entries in my runtimepath.

**Comment by AlxHnr** [comment]
I doubt this depends on the amount of paths in the rtp. But rather on the latency of the underlying filesystem. When using neovim inside a linux VM to edit files on a virtiofs mount, the delay while typing makes it barely usable. The only current workaround is to delete the augroup `UltiSnips_AutoTrigger` as described [here](https://github.com/SirVer/ultisnips/issues/593#issuecomment-361338769) back in 2018. But even outside a VM, the difference is perceivable without this augroup when you pay attention.

**Comment by SirVer** [comment]
I do not get where this would come from though - UltiSnips does not access the filesystem unless reloading snippets, which only happens on the first expand or after a .snippet file was edited inside Vim.

**Comment by skywind3000** [comment]
appreciated
