### ISSUE TITLE
[Feature-request] Implement choices

### ISSUE THREAD

**Issue by hikerpig** [SirVer/ultisnips#1166]
Would be useful if this kind of syntax and interaction is supported. 

Found it in TextMate manual, `${«int»|«choice 1»,…,«choice n»|}` .

For example:

```vim-snippet
color: ${1|red,green,blue|}
```

And a demo in VSCode:

![2020-01-18 22 54 57](https://user-images.githubusercontent.com/2259688/72665677-a85c5800-3a45-11ea-9e35-5cb44df0b3a5.gif)

**Comment by lacygoill** [comment]
Try this:

    snippet cc "color property" bm
    color: $1`!p snip.rv = complete(t[1], ['red', 'green', 'blue'])`
    $0
    endsnippet

For more info, see `:h UltiSnips-python` and/or watch [this video](https://www.youtube.com/watch?v=JJQYwt6Diro&t=200).

---

If you have other usage questions, visit [vi.stackexchange](https://vi.stackexchange.com), and tag your question with [plugin-ultisnips](https://vi.stackexchange.com/questions/tagged/plugin-ultisnips).

**Comment by SirVer** [comment]
I thought about supporting this syntax before. While @lacygoill implementation actually gives you the exact feature, it seems a common enough use case to me that might make sense to actually support it inside of the engine. The proposed syntax also does not clash with any already existing one, so it should be rather easy to actually pull this in.

What do you think, @lacygoill ?

**Comment by lacygoill** [comment]
I think it would be a worthy addition, because the current way of implementing this feature can lead to an unexpected motion of the cursor (when you nest a tabstop inside another one).

Consider this snippet:

    snippet test ""
    foo ${1:bar$2`!p snip.rv = complete(t[2], ['a', 'b', 'c'])` baz}
    endsnippet

Insert `test`, then press the key to expand the snippet; you get this:

    foo bar[a | b | c] baz
        ^^^^^^^^^^^^^^^^^^
        selected

Now press the key to jump to the second tabstop; the cursor jumps right before the opening square bracket:

    foo bar|[a | b | c] baz
           ^

Finally, press `a` to select the `a` match in the list; you get this:

    foo bara baz

Which is correct and expected; what is not expected is the cursor jumping 3 characters forward.
It went from here:

    foo bara| baz
            ^

To there:

    foo bara ba|z
               ^

The number of characters and the direction of the jump is variable; for example, if you add 4 spaces in front of `test`, and repeat the same experiment, then this time the cursor jumps 11 characters backward.

![gif](https://user-images.githubusercontent.com/8505073/72670605-9a0b3d80-3a3f-11ea-9c89-69aca34dcdcc.gif)

**Comment by ashfinal** [comment]
I did a little improvement in https://github.com/honza/vim-snippets/pull/1168. 
Some use cases can be found [here](https://github.com/honza/vim-snippets/blob/master/UltiSnips/rst.snippets#L237).

It's not perfect though. If we could have built-in choices syntax and implementation, that will really cheer me up.

**Comment by SirVer** [comment]
If anybody is interested in working on this, I'd be enthusiastic about a tested patch!

**Comment by hikerpig** [comment]
I think the parsing part is not difficult, but I'm not quite familiar with vim's plugin ui api.  

Is there a reference of example for the dropdown menu like UI component in vim ? Or maybe we can use a easymotion like interface for selection ?

**Comment by lacygoill** [comment]
A simple and probably naive approach would be to invoke [`complete()`](https://vimhelp.org/eval.txt.html#complete()):

    let s:matches = ['red', 'green', 'blue']
    function s:complete_words() abort
        call complete(col('.') - len(matchstr(getline('.')[:col('.')-2], '\S\+$')), s:matches)
        return ''
    endfunction
    inoremap <silent> <f5> <c-r>=<sid>complete_words()<cr>

If you press `F5`, Vim should open a popup menu containing the matches `red`, `green` and `blue`.

It may start the completion from a wrong position when invoked while writing a match containing whitespace...

**Comment by hikerpig** [comment]
I have added the parsing and setup Choices text object. [here are the commits](https://github.com/SirVer/ultisnips/compare/master...hikerpig:feature_choices)

 But still don't have a clue about integrating selection UI with ultisnips text object evaluation. 

I tried what @lacygoill mentioned, vim native `complete()`, but it seems to be interrupted by ultisnips evaluation, the completion dropdown just flash out.

![2020-01-27 21 32 35](https://user-images.githubusercontent.com/2259688/73178681-b8162380-414c-11ea-9b37-e408af05c6dd.gif)

I am considering using quickfix window for selection UI. Is it a bad idea ?

**Comment by lacygoill** [comment]
> I am considering using quickfix window for selection UI. Is it a bad idea ?

I don't think the quickfix window is a good fit; it alters the stack of quickfix lists and the window layout.
The location window would be slightly better, but the best UI is Vim's own completion menu (the pum).

---

> I tried what @lacygoill mentioned, vim native complete(), but it seems to be interrupted by ultisnips evaluation, the completion dropdown just flash out.

I think you made a mistake on [this line](https://github.com/SirVer/ultisnips/compare/master...hikerpig:feature_choices#diff-f374d175ba04ab040c79e01421709225R29):

    vim_helper.eval('complete(col("." - %s), %r)' % (len(self._initial_text), self.choice_list))
                                     ^^^^^^

The negative offset should be outside `col()`:

    vim_helper.eval('complete(col(".") - %s, %r)' % (len(self._initial_text), self.choice_list))
                                      ^^^^^

But you are right, even like this the pum does not stay open.
Maybe UltiSnips does something later which causes the pum to close...
In any case, it stays open if you delay the invocation of `complete()` with a timer:

    vim_helper.eval('timer_start(0, {-> complete(col(".") - %s, %r)})' % (len(self._initial_text), self.choice_list))

But it looks like a hack; it would probably be better to evaluate `complete()` later, without a timer.

I can't help further, as I don't know Python nor UltiSnips internals.

**Comment by SirVer** [comment]
UltiSnips moves the cursor using normal mode commands, I guess that they interfere with the completion window. My suggestion would be to go with a completion inline, similar to how it is implemented in vim-snippets `complete` macro. 

there is a whole rabid hole here about integrating with the various completion engines out there too (deoplete, ycm and so on).

**Comment by hikerpig** [comment]
I've implemented a text-based inline selection, don't require vim's new fancy features. 

I think the term 'popup' in vim is releated to gui interface, like the nav menu or some contextmenu when you clicked right mouse button, and before vim 8.2's floating window, there is no easy way of customizing a popup menu. Correct me if I'm mistaken.

Anyway, current implementation looks [like this](https://github.com/hikerpig/ultisnips/commit/19d08bd633fa2bd5881e88faee2b52f7ed3e5a64):

![2020-01-28 22 31 57](https://user-images.githubusercontent.com/2259688/73273712-67232f80-421f-11ea-8238-e93033c3686e.gif)

But I think altering text while inputting is kind of hacky and error prone (myself failed to find an elegant way to do this 😢).

Also considering create a readonly scratch buffer for selection (like Denite?), would that be to costly?

**Comment by SirVer** [comment]
> Also considering create a readonly scratch buffer for selection (like Denite?), would that be to costly?

I think there is the danger that we'd need to provide more and more completion features over time, which is feature creep I'd like to avoid. I.e. I do not want UltiSnips to become a deoplete competitor.

I think your solution is good and instead of improving upon it, we should try to provide hooks so that completer engines can be hooked in as an alternative. I.e. users should be able to inject a python or vimL function that is used instead of our naive completer workflow. Can you spent some brain cycles on how that could look?

**Comment by SirVer** [comment]
Also, I forgot to send this earlier, but UltiSnips already asks selections from Users in case of ambiguity with `:UltiSnipsEdit`. The code is here: https://github.com/SirVer/ultisnips/blob/96026a4df27899b9e4029dd3b2977ad2ed819caf/pythonx/UltiSnips/snippet_manager.py#L31, it uses Vim's `inputlist` to ask for a selection.

**Comment by ashfinal** [comment]
The pum has been overloaded by various async completion engines. Basically, before entering choices snippets we need to disable these completion engines first, then enable them again, that brings lots of trouble. I'm afraid inline completion may be our best shot before Vim have feature like "namespaced" popup menu or something else.

As for providing hooks, I think it's a good idea. We can expose UltiSnips's current status, including whether it is running, what trigger word, which tabstop, so completion engines's UltiSnips source can retrieve corresponding choices, and give the source top priority, or completely disable other sources except for UltiSnips source. It will need good design.

**Comment by hikerpig** [comment]
I've tried calling vim's 'inputlist()', but found it too heavy for this completion, forcing user to another buffer while inputting is kind of annoying.

I would like this choice list to be a suggestion instead of compulsory selection.

I improved the inline selection solution a little bit, and I think this is enough for me.

![2020-01-30 17 41 21的副本](https://user-images.githubusercontent.com/2259688/73438317-cea8be80-4388-11ea-85e7-c59662325d62.gif)

As for exposing hooks, I'm afraid it's beyond my ability, since it requires more knowledge on ultisnips and vim script. If current solution looks good to you, I would like to create a PR and add some tests for it.

**Comment by SirVer** [comment]
+1 for going with your current UI. Please add some tests and open a PR, looking forward to reviewing!

**Comment by yangshuairocks** [comment]
Wow I just noticed ultisnips already has the choice feature. The document didn't mention this completely. Any chance to update the docs?

**Comment by SirVer** [comment]
@yangshuairocks That is on me. I said I would write the docs, but my new job didn't give me a ton of time lately, that is why it was not written yet.

**Comment by yangshuairocks** [comment]
@SirVer I added this new feature to the doc. Could you review the pull request when you get a chance?

**Comment by roachsinai** [comment]
Hi, how to escape `,` comma when using choices?

```
snippet q
${1:result} = nn.${2|fun1(,fun2(param1\, ,fun3(param1\, param2\, |}prarm_end)
endsnippet
```

Does ultisnips support it for now? Didn't found it in doc.

Thanks in advance!

**Comment by roachsinai** [comment]
And if the choice is more than ten like `1,...,11`, the first one can't show when input `1` as `1` and `11` has same prefix.

**Comment by hikerpig** [comment]
> And if the choice is more than ten like `1,...,11`, the first one can't show when input `1` as `1` and `11` has same prefix.

@roachsinai  Could you provide a buggy example? I tested the code below and can input `j` .

```
snippet alpha
${1|a,b,c,d,e,f,g,h,i,j,k,m,n|}
endsnippet
```

**Comment by roachsinai** [comment]
@hikerpig input `j` works, but input `1` not work.

![image](https://user-images.githubusercontent.com/9500049/88265830-c2cb0300-cd00-11ea-8872-39463243a4c6.png)

Input `10` got `j`, if want to got `a` must input `a` as input `1` returan a number `1`.

**Comment by hikerpig** [comment]
@roachsinai I see. I will look into it and open a bugfix PR then, might take several days. Thank you for your feedback. 😃

**Comment by roachsinai** [comment]
Great!

What's more, 🤩

https://github.com/SirVer/ultisnips/blob/e83c82099d9bd43dc7895e3cb5b114ee5a2a07c6/doc/UltiSnips.txt#L691-L695

@hikerpig is there a plan for escape comma you contributors, as it could enable different fucntion(with different parameters) as snippet choices. And as ultisnips use `,` to split choices, it will be better to support escape `,` same with bash support escape space.

**Comment by hikerpig** [comment]
@roachsinai Yeah I see your example above 👍, will keep that in mind as well.

**Comment by roachsinai** [comment]
@hikerpig waohhh! Thanks!

**Comment by hikerpig** [comment]
@roachsinai I came up with a solution that uses space as the selection terminator. So we can type `1 ` to select the first one and `11` to select the eleventh one.
It pretty much covers my usual cases. Is it feasible for you guys ?

![Kapture 2020-07-28 at 21 25 49](https://user-images.githubusercontent.com/2259688/88671576-0c5c8900-d119-11ea-87d7-fa64c6551046.gif)

**Comment by roachsinai** [comment]
> @roachsinai I came up with a solution that uses space as the selection terminator. So we can type `1 ` to select the first one and `11` to select the eleventh one.
> It pretty much covers my usual cases. Is it feasible for you guys ?
> 
> ![Kapture 2020-07-28 at 21 25 49](https://user-images.githubusercontent.com/2259688/88671576-0c5c8900-d119-11ea-87d7-fa64c6551046.gif)

Yes, sure! Thanks!

**Comment by roachsinai** [comment]
> Hi, how to escape `,` comma when using choices?
> 
> ```
> snippet q
> ${1:result} = nn.${2|fun1(,fun2(param1\, ,fun3(param1\, param2\, |}prarm_end)
> endsnippet
> ```
> 
> Does ultisnips support it for now? Didn't found it in doc.
> 
> Thanks in advance!

Hi @hikerpig I think it's only related to `ChoicesToken` when escape comma is needed. So maybe no need to support escape comma for all Token. Just start to reading related code, but very new to lexer...

**Comment by roachsinai** [comment]
I'v add several lines arround
```
        self.choice_list = choices_text.split(",")
```

to

```
        choices_text = choices_text.replace("\,", "\__")
        self.choice_list = choices_text.split(",")
        for idx, choice in enumerate(self.choice_list):
            self.choice_list[idx] = self.choice_list[idx].replace("\__", ",")
        choices_text = choices_text.replace("\__", ",")
```

But the code above not support change parameters in function:

![ultisnip_choice](https://user-images.githubusercontent.com/9500049/92297947-f2fbf780-ef76-11ea-95de-25bed4fa2672.gif)

If <kbd>tab</kbd> to select next and change parameter is enabled will be great.
