### ISSUE TITLE
 When I execute `: ultisnipsedit` ,I should be allowed to edit.

### ISSUE THREAD

**Issue by kjhuanhao** [SirVer/ultisnips#1170]
**Expected behavior:**
When I execute `: ultisnipsedit` ,I should be allowed to edit.

**Actual behavior:**
When I execute: `: ultisnipsedit` the following error occurs
```
function provider#python3#Call[9]..remote#host#Require[10]..provider#pythonx#Require[13]..provider#Pol
l, line 4
Vim(if):Error invoking 'poll' on channel 4:^@ch 4 was closed by the client
Failed to load python3 host. You can try to see what happened by starting nvim with $NVIM_PYTHON_LOG_F
ILE set and opening the generated log file. Also, the host stderr is available in messages.
Error detected while processing function UltiSnips#Edit:
line    8:
E121: Undefined variable: file
E116: Invalid arguments for function len
E15: Invalid expression: !len(file)
```

**Steps to reproduce**

1.
Settings that I had regarding ultisnips
```
let g:UltiSnipsExpandTrigger="<c-b>"                                                              
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"
"let g:UltiSnipsSnippetDirectories = [$HOME.'/.config/nvim/Ultisnips/', 'UltiSnips']
"silent! au BufEnter,BufRead,BufNewFile * silent! unmap <c-r>
```
2.
Demonstration:
![](https://cdn.jsdelivr.net/gh/kjhuanhao/cdn/blog/22.gif
)

-----

- **Operating System**: ArchLinux
- **Vim Version**: NVIM v0.4.3

- **UltiSnips Version**: 3.2
- **Python inside Vim**: 3.8
- **Docker repo/vimrc**: [My init.vim](https://github.com/kjhuanhao/nvim/blob/master/init.vim)

**Comment by lacygoill** [comment]
What is the output of these 2 commands?:

    :echo has('python3')
    :py3 import sys; print(sys.version)

What's the output of `:CheckHealth`?

Does it help if you execute the Ex command `:UpdateRemotePlugins` in Nvim, then restart?

**Comment by lacygoill** [comment]
Try to update your python client:

    git clone https://github.com/neovim/pynvim
    cd pynvim
    git stash; git clean -d -f . ; git checkout master; git pull
    python3 -m pip install --user --upgrade pynvim

**Comment by lacygoill** [comment]
And try to add this to your `init.vim`:

    let g:python3_host_prog = '/usr/bin/python3'

Replace the path `/usr/bin/python3` with whatever path is output by the shell command `type python3`.

**Comment by kjhuanhao** [comment]
Thank you for your advice.I successfully solved the problem after executing python3 -m pip install --user --upgrade pynvim
