### ISSUE TITLE
Error Detected while processing /home/username/.vim/bundle/ultisnips/autoload/UltiSnips.vim

### ISSUE THREAD

**Issue by landermkerbey** [SirVer/ultisnips#1176]
**Expected behavior:** Open a text file in Vim and entering insert mode allows me to type in characters normally.

**Actual behavior:**  Since installing UltiSnips, every keystroke entered in insert mode results in the following error text: 

```
Error detected while processing /home/username/.vim/bundle/ultisnips/autoload/UltiSnips.vim:
line   7:
E319: Sorry, the command is not available in this version: py3 import vim
Press ENTER or type command to continue
```

Hitting ENTER then prompts the following:

```
Error detected while processing /home/username/.vim/bundle/ultisnips/autoload/UltiSnips.vim:
line   8:
E319: Sorry, the command is not available in this version: py3 from UltiSnips import UltiSnips_Manager
Press ENTER or type command to continue
```

An additional ENTER prompts the following:

```
Error detected while processing function UltiSnips#TrackChange:
line   1:
E319: Sorry, the command is not available in this version:      py3 UltiSnips_Manager._track_change()
Press ENTER or type command to continue
```

Hitting ENTER again displays the same error, and yet another time clears the error and lets me see the change made by my kestroke in Insert mode. An additional edit in insert mode will prompt the last error to appear again.

This has happened since I've installed UltiSnips even though I did not set up any snippets at all.

**Steps to reproduce**

.vimrc:

```
execute pathogen#infect()

filetype plugin indent on
syntax on

set shiftwidth=2
set number
```
There are no snippets. I am using Vim 8.1 (18th May, 2018 release), Python 3.7.3 on Debian 10.2. I have just installed UltiSnips by cloning it from Git using

`git clone git://github.com/SirVer/ultisnips.git` in my `.vim/bundle` directory.

1. Open any text file in Vim.
2. Enter insert mode.
3. Type any text character. You will see the errors described above.

-----

- **Operating System**: 
- **Vim Version**: 
- **UltiSnips Version**: 
- **Python inside Vim**: 
- **Docker repo/vimrc**:

**Comment by lacygoill** [comment]
What is the output of these 2 commands?:

    :echo has('python3')
    :py3 import sys; print(sys.version)

If the output of the first command is 0, it means your Vim binary was not compiled with the python 3 interface.  In that case, your issue is not related to UltiSnips.
You may need to install a Vim package which includes a python 3 interface; read [`:h UltiSnips-requirements`](https://github.com/SirVer/ultisnips/blob/96026a4df27899b9e4029dd3b2977ad2ed819caf/doc/UltiSnips.txt#L89-L106), as well as [`:h 90.2`](https://vimhelp.org/usr_90.txt.html#90.2) (and more generally [`:h install`](https://vimhelp.org/usr_90.txt.html#install)).

If you have other usage questions, visit [vi.stackexchange.com](https://vi.stackexchange.com), and tag your question with [plugin-ultisnips](https://vi.stackexchange.com/questions/tagged/plugin-ultisnips).

**Comment by SirVer** [comment]
It seems that your Vim only has python2, but not support for python3. UltiSnips will not work wtih that anymore, i.e. you need a Vim with python3.

**Comment by lockerfish** [comment]
I experienced this issue with NeoVim and UltiSnips. Solved by running the following commands:

`:echo has('python3')` returned 0 even though `python3 -m pip install --user --upgrade pynvim` didn't show errors.

`brew upgrade python3` showed I was in the latest version

running `brew link --overwrite python@3.8` **fixed** the issue for me. 

`:echo has('python3')` returned 1 now and UltiSnips did not break with errors.

Writing it here to hopefully help someone running into the same issue.

**Comment by akashayatet** [comment]
> I experienced this issue with NeoVim and UltiSnips. Solved by running the following commands:
> 
> `:echo has('python3')` returned 0 even though `python3 -m pip install --user --upgrade pynvim` didn't show errors.
> 
> `brew upgrade python3` showed I was in the latest version
> 
> running `brew link --overwrite python@3.8` **fixed** the issue for me.
> 
> `:echo has('python3')` returned 1 now and UltiSnips did not break with errors.
> 
> Writing it here to hopefully help someone running into the same issue.

Recently ran into the very same issue, and this post was able to resolve it. Note: i did also take the extra step of trying to update with `pyenv` as well before the `brew link ...` step. Whether or not that made a different is unknown but the issue was resolved.

**Comment by lockerfish** [comment]
Also added this to my vim settings

`" python
let g:python_host_prog = trim('/usr/bin/' . system('readlink /usr/bin/python'))
let g:python3_host_prog = trim('/usr/local/bin/' . system('readlink /usr/local/bin/python3'))
`
Now, I don't need to worry about `brew upgrade` breaking the link anymore

**Comment by Brannua** [comment]
`brew uninstall vim`, `brew install macvim` saved me.
