### ISSUE TITLE
Is it possible to replace tabstop value on postjump, or move after?

### ISSUE THREAD

**Issue by Corey-Keller** [SirVer/ultisnips#1177]
I have the following code (extraneous bits removed) :

```
post_jump "if snip.tabstop == 0: snip.expand_anon('LicenseHeader' + snip.tabstops[4].current_text)"
snippet fhead "File Header" b
...
snip.rv += ' License: '`${4:MPL2}
$0
endsnippet
```

Right now this will add the value of 'LicenseHeader' + t[4] at $0, below the existing snippet 4 (at $0), which leaves the value of t[4] there and unwanted.

Alternatively, I can do:

~~~
post_jump "if snip.tabstop == 0: snip.expand_anon('LicenseHeader')"
snippet fhead "File Header" b
...
snip.rv += ' License: '`$0${4:MPL2}
endsnippet
~~~

Which will give me the desired text where I want it, but puts the cursor in between 'LicenseHeader' and t[4]. In that case, can I move to snip.tabstops[4].end[0] after the text is inserted at $0 (or insert the text at  snip.tabstops[4].start[0] before moving to $0)?

**Comment by SirVer** [comment]
I do not fully understand what you want to achieve here, but to answer your question: it is not currently possible to replace a tabstop value in ultiSnips, however postjump allows you to run arbitrary functions that modify the current buffer, so I assume you could use that to do a search & replace on the lines in the buffer.
