### ISSUE TITLE
[Question] How can snip.buffer be used in place of vim.command, as documentation implies?

### ISSUE THREAD

**Issue by Corey-Keller** [SirVer/ultisnips#1179]
Under 'UltiSnips-buffer-proxy'

>Note: special variable called 'snip.buffer' should be used for all buffer modifications. Not 'vim.current.buffer' **_and not 'vim.command("...")_'**, because in that case UltiSnips will not be able to track changes to the buffer correctly

I made the relevant bit **_bold italic_** for visibility. 

To me that makes it sound as if there is a way to run vim commands in a buffer safe way.

Specifically I'm trying to format (normal command gqq or gww) each line in the snip.

**Comment by SirVer** [comment]
No, that statement is more to underline that it is *not* safe to use vim.command in any form inside a snippet.
