### ISSUE TITLE
[QUESTION] [not an issue] How to use UltiSnips jump function with custom vim filter

### ISSUE THREAD

**Issue by jagjordi** [SirVer/ultisnips#1180]
I have some custom functions that insert text on a file from another file that is passed as an argument. I would like this inserted code to have tabstops so then I can quickly jump to specific positions in the inserted text and edit it if necessary. Is it possible to do this using ultisnips functions?

**Comment by SirVer** [comment]
Probably using https://github.com/SirVer/ultisnips/blob/master/doc/examples/tabstop-generation/README.md. It will likely be quite a bit of work to get this right.
