### ISSUE TITLE
UltiSnips should pass through any mapping that it currently can't execute as the trigger key

### ISSUE THREAD

**Issue by Hritik14** [SirVer/ultisnips#1184]
Ultisnips plays very good with <Tab> for selection but when I map <CR> for selection, <CR> no longer triggers newline in insert mode. It would be nice to have <CR> do both as <tab> does because it feels natural to step through the completion suggestions (YCM here) using <tab> and ultisnips stops at the first snip suggestion and starts the snip while using <tab>

1. `let g:UltiSnipsExpandTrigger = "<CR>"`
2. in insert mode, some text `<CR>`
3. no newline

PS: There seems to be one possible solution on stackoverflow: https://vi.stackexchange.com/questions/2757/triggering-ultisnips-with-enter but it would be nice to have that in-built.
-----

- **Operating System**:  Archlinux
- **Vim Version**: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 26 2020 11:45:38)    
Included patches: 1-148 
- **UltiSnips Version**: 129d33fc34a72ced857f3cfb72ff10caf10f0020 
- **Python inside Vim**: 3.8.1

**Comment by SirVer** [comment]
Seems to me that the linked solution is perfectly viable. It is unfeasible for UltiSnips to play around any potential combination of behaviors people want to overload. Coding your own binding seems the correct approach. Do you disagree?

**Comment by Hritik14** [comment]
True but it is the default behavior of `<tab>` to trigger the snip and that causes problems with popular completion engines like YCM. If we could choose a default that works out of the box, it would be better for newcomes to just *change* what they want to be changed yet the plugin works unchanged.

**Comment by SirVer** [comment]
So to understand correctly, the suggested feature request here is that UltiSnips passes through whatever mapping it has if it cannot fullfill an action. In this case, if it cannot expand at the current position, it should actually insert a literal `<cr>`, right?

**Comment by Hritik14** [comment]
Yes, absolutely.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by SirVer** [comment]
That sounds reasonable. No idea how hard that is to implement though. Patch is always welcome!
