### ISSUE TITLE
Nested snippet expansion

### ISSUE THREAD

**Issue by Kyle-Thompson** [SirVer/ultisnips#1186]
Would it be possible to expand a snippet A and then while filling out A, expand a snippet B, complete B and then continue completing A? For instance if you have a function foo and bar that  each take two parameters, while expanding the function definition of foo, could you call the function bar such that it's return value will be a parameter to foo and have snippet expansion continue to work with foo after completing bar?

```
int foo(int a, int b);
int bar(int a, int b);

int baz(int a, int b) {
  return foo|  // <- trigger foo snippet
  return foo(|[int a], [int b])
  return foo(bar|, [int b])   // <- trigger bar snippet
  return foo(bar(|[int a], [int b]), [int b])  // <- from here two snippets are expanded.
}
```

My understanding is that currently you'd be able to complete the bar snippet but the foo snippet would not resume afterwards. Is this possible?

**Comment by SirVer** [comment]
UltiSnips already supports expanding nested snippets, i.e. when A is currently active, you can expand B. Once you reach the $0 tabstop in B and continue jumping forward, the next tabstop in A will be activated.
