### ISSUE TITLE
JumpForwardTrigger stops working if snippets are used in two or more buffers

### ISSUE THREAD

**Issue by pjio** [SirVer/ultisnips#1187]
![image](https://user-images.githubusercontent.com/6034781/76103464-092df880-5fd2-11ea-94bc-4a55ed034fa0.png)

**Expected behavior:**
Pressing the key for JumpForwardTrigger jumps to next variable

**Actual behavior:**
The value of **g:UltiSnipsJumpForwardTrigger** is inserted

**Steps to reproduce**

1. Use the recommended docker container: https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs
2. Add variables to the example snippet `/root/.vim/UltiSnips/all.snippets`
```
snippet example "Repro case example"
This $1 is $2 a $3 simple $4 snippet $5 example
endsnippet
```
3. start `vim`
4. Expand the snippet by typing `example` and pressing `<tab>`
5. Fill the variables and jump to the next one by typing `2`
6. Open new buffer: `:new<cr>`
7. Repeat steps 4. and 5. in the new buffer. Now the `2` gets inserted literally

-----

- **Operating System**: Recommended Docker container
- **Vim Version**: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar  6 2020 16:11:23) Included patches: 1-586
- **UltiSnips Version**: e910b4fb9e276d18ed140fc492f30967ef9ace59
- **Python inside Vim**: 3.6.10
- **Docker repo/vimrc**: https://github.com/pjio/ultisnips/blob/repro-branch/docker/snippets/all.snippets

**Workaround**: In `ultisnips/pythonx/UltiSnips/snippet_manager.py` go to `def _setup_inner_state(self)` and remove the lines:
```
        if self._inner_state_up:
            return
```
I assume, the flag `_inner_state_up` doesn't get set to false which then causes this problem.

**Comment by SirVer** [comment]
What a beautiful bug report! Thank you very much for taking the time and effort to do this.

Problem confirmed at e91b4f.
