### ISSUE TITLE
when use signature help of YCM , ultisnips can not jump next tabstops. YCM: set completeopt+=popup

### ISSUE THREAD

**Issue by shiqf** [SirVer/ultisnips#1188]
filetype: python

config: 
    let g:UltiSnipsExpandTrigger       = "\<tab>"
    let g:UltiSnipsJumpForwardTrigger  = "\<c-j>"
    let g:UltiSnipsJumpBackwardTrigger = "\<c-k>"

snippet: 
snippet for "for loop" b
for ${1:item} in ${2:iterable}:
	${3:${VISUAL:pass}}
endsnippet

**Expected behavior:**

press \<c-j>enumerate()\<c-j> =>

for item in enumerate(): 
    pass|

**Actual behavior:**
 after type enumerate()  \<c-j> or \<c-k> cursor can not move

for item in enumerate()|: 
    pass

**Steps to reproduce**

1. for\<tab>.  =>
2. for item| in iterable: 
    pass
3. \<c-j>
4. for item in enumerate()|: 
    pass|
5. \<c-j>

![image](https://user-images.githubusercontent.com/41278084/76114178-7cf6f200-6020-11ea-93d5-1dda5626eb77.png)

-----

- **Operating System**:  
Mac OS 10.5 
- **Vim Version**: 
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar  4 2020 22:41:50)
macOS version
包含补丁: 1-350
- **UltiSnips Version**: 
e910b4fb9e276d18ed140fc492f30967ef9ace59
- **Python inside Vim**: 
3.7.6 (default, Dec 30 2019, 19:38:26)
[Clang 11.0.0 (clang-1100.0.33.16)]
- **Docker repo/vimrc**:

call plug#begin(get(g:, 'bundle_home', '~/.vim/bundles'))

    Plug 'ycm-core/YouCompleteMe', { 'do': 'python3 install.py --clangd-completer --ts-completer' }

        " 触发快捷键设置
        let g:ycm_key_list_select_completion   = ['<c-n>']
        let g:ycm_key_list_previous_completion = ['<c-p>']
        let g:ycm_key_list_stop_completion = ['<c-y>']
        let g:ycm_key_invoke_completion = '<c-z>'
        " 当用户的光标位于诊断行上时用于显示完整诊断文本。默认 <leader>d
        let g:ycm_key_detailed_diagnostics = '<leader>d'
        set completeopt+=popup

        " noremap <c-z> <NOP>

        let g:ycm_server_log_level = 'info'
        " 禁用诊断功能：我们用前面更好用的 ALE 代替
        let g:ycm_show_diagnostics_ui = 1
        " 禁用预览功能：扰乱视听
        let g:ycm_add_preview_to_completeopt = 0
        let g:ycm_global_ycm_extra_conf='~/.ycm_extra_conf.py'
        " 不显示load python 提示
        let g:ycm_confirm_extra_conf=0
        " 通过ycm语法检测显示错误符号和警告符号
        let g:ycm_error_symbol   = '✗'
        let g:ycm_warning_symbol = '⚠'
        let g:ycm_always_populate_location_list = 1

        " 输入最少字符开启字符补全功能 默认 2
        " let g:ycm_min_num_of_chars_for_completion = 2
        " 显示字符候选标识符最少的字符数 默认 0
        let g:ycm_min_num_identifier_candidate_chars = 4
        " 最大语义补全符数量 默认 50
        " let g:ycm_max_num_candidates = 50
        " 最大标识符数量 默认 10
        let g:ycm_max_num_identifier_candidates = 3
        " 设置为 0 时，不再触发语义补全
        " let g:ycm_auto_trigger = 1
        " c 语言中的 #include 会自动补全文件
        let g:ycm_complete_in_strings=1
        " 设置为 1 时，补全标识符信息会从注释中获取 默认为 0
        " let g:ycm_collect_identifiers_from_comments_and_strings = 1
        " 当此选项设置为1时，YCM的标识符完成器还将从标记文件中收集标识符
        " let g:ycm_collect_identifiers_from_tags_files = 1

        " 两个字符自动触发语义补全
        let g:ycm_semantic_triggers =  {
                    \ 'c,cpp,python,java,go,erlang,perl': ['re!\w{2}'],
                    \ 'cs,lua': ['re!\w{2}'],
                    \ 'javascript,typescript': ['re!([A-Z]\w|\w[A-Z]|\w{2}[A-Z]|\w{4})'],
                    \ }

    Plug 'SirVer/ultisnips'
    Plug 'honza/vim-snippets'
    let g:UltiSnipsSnippetDirectories  = [ 'UltiSnips', 'mysnippets' ]
    let g:UltiSnipsExpandTrigger       = '<c-i>'
    let g:UltiSnipsJumpForwardTrigger  = '<c-j>'
    let g:UltiSnipsJumpBackwardTrigger = '<c-k>'
    let g:UltiSnipsListSnippets        = '<c-l>'
    let g:UltiSnipsEditSplit           = 'vertical'

"----------------------------------------------------------------------
" 结束插件安装
"----------------------------------------------------------------------
call plug#end()

**Comment by SirVer** [comment]
Yes, this is unfortunate, but working as intended. The background is that the popup is opening a new buffer which confuses UltiSnips change tracking. So whenever a new buffer is created, UltiSnips actually terminates all currently running snippets. I do not know how to work around this issue currently.

**Comment by bloop132435** [comment]
I'm not sure if this violates some edge cases, but I think I've found a solution, at least with nvim-compe.
I changed the Ultisnips#LeavingBuffer() function in autoload/Ultisnips.vim to this:
```
function! UltiSnips#LeavingBuffer() abort
    let from_preview = getwinvar(winnr('#'), '&previewwindow')
    let to_preview = getwinvar(winnr(), '&previewwindow')

	if "ic" == mode()
		return
	endif
    if !(from_preview || to_preview)
        py3 UltiSnips_Manager._leaving_buffer()
    endif
endf

```
Not sure if this will help for ycm though.

**Comment by shiqf** [comment]
Sorry for not replying for a long time.
Thanks, it looks like it works for me.

**Comment by SirVer** [comment]
@bloop132435 This has similar issues to what I described here: https://github.com/SirVer/ultisnips/pull/1417#issuecomment-1006733824
