### ISSUE TITLE
Enter button does not work in insert mode

### ISSUE THREAD

**Issue by Burlter** [SirVer/ultisnips#1191]
Nothing happens when i press Enter button in Insert mode.

-----

- **Operating System**:  gentoo 17 with kernel linux-4.19.97-gentoo
- **Vim Version**: VIM - Vi IMproved 8.1.1486 (2018 May 18, compiled Feb  8 2020 08:30:54)
[minimal vimrc](https://github.com/SirVer/ultisnips/files/4307300/testvimrc.txt)

- **UltiSnips Version**: 3.2
- **Python inside Vim**: 3.6.10

**Comment by SirVer** [comment]
> let g:UltiSnipsExpandTrigger = "<C-M>"

`<ctrl-m>` and Enter both translate to the same thing in the unix terminal. Every time you press enter, ultisnips tries to expand a snippet. since there is nothing to be done in most cases, your cursor is not moving further.
