### ISSUE TITLE
Provide arbitrary arguments to a snippet 

### ISSUE THREAD

**Issue by hugwi** [SirVer/ultisnips#1192]
There are numerous occasions where you might want to have another optional argument in your snippet.  Lets say I want to have a numbered list for example. Preferably I'd call something like enum3 which would
generate this: 
```
begin{enumerate} 
    \item  $1 
    \item  $2
    \item  $3
\end{enumerate}
$0
```

I'm able to get generate vim conventional placeholders like this: 

```
\begin{enumerate} 
	\item <++> 
	\item <++>
	\item <++>
\end{enumerate}
```

However is there any more elegant way in ultisnips to give an arbitrary number of placeholders?

**Comment by tbrazel** [comment]
What you're looking for is [dynamic tabstop generation](https://github.com/SirVer/ultisnips/blob/master/doc/examples/tabstop-generation/README.md).

I took the liberty of writing this for you (I've been working on some dynamic snippets for LaTeX myself recently). In your global python section, add the following function:
```
def enum(snip):
	item_count = int(snip.buffer[snip.line].strip())
	snip.buffer[snip.line]= ''
	output = '\\begin{enumerate}\n\t\\item '
	output = output+'\n\t\\item '.join(['$' + str(i+1) for i in range(item_count)])
	output = output + '\n\\end{enumerate}\n$0'
	snip.expand_anon(output)
```
Then you can write the snippet using a post_jump:

```
post_jump "enum(snip)"
snippet 'enum(\d+)' "enumerate environment of custom length" rb
`!p snip.rv = match.group(1)`
endsnippet
```
I tested this on my computer and it worked for me 👍
