### ISSUE TITLE
Automatically insert import if does not exist

### ISSUE THREAD

**Issue by jasonkena** [SirVer/ultisnips#1200]
Say I have the following prefix
```
snippet test "Test"
std::cout << std::fixed << std::setprecision(3) << a;
endsnippet
```
This snippet requires the following header `#include <iomanip>`
Is there a way to automatically insert this header (if it doesn't exist already), when the trigger is activated?

**Comment by SirVer** [comment]
Yes, you could do that through a post_expand action. https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L1567
