### ISSUE TITLE
UltiSnipEdit command does not work

### ISSUE THREAD

**Issue by Qiguang** [SirVer/ultisnips#1201]
**Expected behavior: UltiSnipEdit command from vim command mode will open a snippet file**

**Actual behavior: error prompt:**

> Error detected while processing function UltiSnips#Edit:
> line    6:
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/robin/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 851, in _file_to_edit
>     _get_potential_snippet_filenames_to_edit(snippet_dir, filetypes)
>   File "/home/robin/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 94, in _get_potential_snippet_filenames_to_edit
>     ft_snippets_files = find_snippet_files(ft, snippet_dir)
>   File "/home/robin/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/ulti_snips.py", line 26, in find_snippet_files
>     directory = os.path.expanduser(directory)
>   File "/usr/lib/python3.5/posixpath.py", line 228, in expanduser
>     if not path.startswith(tilde):
> AttributeError: 'PosixPath' object has no attribute 'startswith'

**Steps to reproduce**

1.the vimrc that I use can be found [here](https://github.com/Qiguang/.vim/blob/master/vimrc)
2.install ultisnip by vim-plug command :PlugInstall
3.open a *.c file in vim then type :UltiSnipsEdit<CR>

-----

- **Operating System**: Windows 10 WSL Ubuntu-16.04
- **Vim Version**: VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 07 2019 15:35:43)
- **UltiSnips Version**: ee31ea1c7d08ced8577120b4c1d55c5a05351a75
- **Python inside Vim**: no python, python3 version:3.5.2 (default, Oct  8 2019, 13:06:37)
[GCC 5.4.0 20160609]

- **Docker repo/vimrc**:

**Comment by SirVer** [comment]
UltiSnips required python >= 3.6, 3.5 is not supported.
