### ISSUE TITLE
Extends not work well, show only part of snippets.

### ISSUE THREAD

**Issue by roachsinai** [SirVer/ultisnips#1204]
**Expected behavior:**

I want to extend markdown.snippets, and my snip directory setting is:

```
let g:UltiSnipsSnippetsDir="~/.vim/snips"
let g:UltiSnipsSnippetDirectories=["snips", "UltiSnips"]
```

I create a `markdown.snippets` at `~/.vim/snips` and add a single line:`extends tex`.

And I wish after I input `ali` I can trigger `aligned` as same as pic below which is a screenshot when I input `ali` in a tex file, `tt.latex`.

![image](https://user-images.githubusercontent.com/9500049/78920664-50724200-7ac6-11ea-95dc-b8c7a2654eb9.png)

**Actual behavior:**

Can't find `ali` snippet! Below is when I edit a markdown file the snip of `ali` didn't show though I extends tex at my self markdown.snippets.

![image](https://user-images.githubusercontent.com/9500049/78921085-f45bed80-7ac6-11ea-820d-a8ac704ca688.png)
---

But if I add `extends tex` to the markdown.snippets supported by plugin vim-snippet, it works.

-----

- **UltiSnips Version**: b62dfce8449d8a8196720ddd3cfecbca8bb7fe45

**Comment by michaelPotter** [comment]
I'm having a similar issue. I'm trying to extend javascriptreact snippets with javascript snippets, but it only picks up my main javascripts.snippets file and not any from `javascript/*` or from runtimepath snippets.

I haven't changed any `g:UltiSnips...` variables.

my `~/.vim/UltiSnips/javascriptreact.snippets` file just has this line: `extends javascript`.

I can run snippets defined in `~/.vim/UltiSnips/javascript.snippets` , but no snippets from `~/.vim/UltiSnips/javascript/default.snippets` or `~/.vim/bundle/vim-snippets/UltiSnips/javascript.snippets`

**Comment by roachsinai** [comment]
I copy `tex.snippets` from vim-snippets to `~/.vim/snips` rename it to `markdown.snippets`.

When I use vim open a markdown file, I got an error:

```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new
Please read and follow:
https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs

Following is the full stack trace:
Traceback (most recent call last):
  File "/home/roach/.vim/plugged/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 18, in wrapper
    return func(self, *args, **kwds)
  File "/home/roach/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 198, in snippets_in_current_scope
    snippets = self._snips(before, True)
  File "/home/roach/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 668, in _snips
    source.ensure(filetypes)
  File "/home/roach/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/base.py", line 31, in ensure
    self._load_snippets_for(ft)
  File "/home/roach/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/base.py", line 53, in _load_snippets_for
    self._parse_snippets(ft, fn)
  File "/home/roach/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/base.py", line 70, in _parse_snippets
    raise SnippetSyntaxError(filename, line_index, msg)
UltiSnips.snippet.source.file.base.SnippetSyntaxError: Invalid multiword trigger: 'nc \newcommand' in ~/.vim/snips/markdown.snippets:4
```

**Comment by michaelPotter** [comment]
Hey @roachsinai  that actually looks like a different issue now. The `vim-snippets` package has two sets of snippets. The snippets under the `snippets` folder are incompatible (looks like that's the tex.snippets you copied over). Try copying `vim-snippets/UltiSnips/tex.snippets` over to `~/.vim/snips/markdown.snippets`

**Comment by roachsinai** [comment]
@michaelPotter thanks for your reply! Yeah, copy `vim-snippets/UltiSnips/tex.snippets` to `~/.vim/snips/markdown.snippets` no error.

**Comment by roachsinai** [comment]
What's more, when I edit markdown file I can't trigger the snips, after I press ExpandTrigger key.

**Comment by primercuervo** [comment]
I was facing this earlier today and arrived on this issue while looking for a solution. It seems to me that the `extends markdown` does its job, but extends only the snippets from `UltiSnips`, as they are the ones that are actually compatible. The support given to the `snipmate` type of snippets seems to be only for a smooth transition of other users (improved UX, as I understand), but appear not to be expected to work out of the box with all the functionalities of `UltiSnips`.  See #785 and #312  (and probably many other issues) stating that this is expected.

The way I took around it was just porting the snippet I wanted/needed from the snipmate version to a Ultisnip version (as it is suggested in #312) in the base that I wish to extend and work on from there.

**Comment by SirVer** [comment]
@roachsinai I am unable to repro your problems, since you have not provided your snippets or your vimrc.

@michaelPotter It sounds to me like your problem is actually a (slightly?) different one. Could you please file another bug for it?

@primercuervo yes, you are right about extends only working for UltiSnips. The background is one of effort of implementation and also unclear overwrite behaviour. I think porting your snippets into UltiSnips is ultimately the easiest way to getting this to work consistently. 

Closing as I am unable to repro the original problem.
