### ISSUE TITLE
snippets for ejs files

### ISSUE THREAD

**Issue by douglas86** [SirVer/ultisnips#1205]
**Expected behavior:**

**Actual behavior:**

**Steps to reproduce**

1.
2.
3.

-----

- **Operating System**: 
- **Vim Version**: 
- **UltiSnips Version**: 
- **Python inside Vim**: 
- **Docker repo/vimrc**: 

Hi, I would like to contribute to creating a snippets file for ejs, files.
What would be the best way of doing that.

**Comment by SirVer** [comment]
UltiSnips is just the engine, snippets are maintained here: https://github.com/honza/vim-snippets

Please contribute there.
