### ISSUE TITLE
Subprocess opens 3 instances of Inkscape from python interpolator

### ISSUE THREAD

**Issue by gustavobat** [SirVer/ultisnips#1211]
Hi, first of all I would like to thank you for this awesome plug in. I am having an issue running UltiSnips with Neovim.
I am trying to make a LaTeX snippet that uses python interpolation to do the following:
- Copy a Inkscape figure template I have in my tree to a new file named after 'match.group(1)'.
- Trigger a subprocess to run inkscape on this new file, so I can edit the drawing

Once I exit Inkscape the python interpolation is finished and the snippet proceeds to writing the boiler plate tex code to include the figure document.

The problem I am having is that subprocess somehow reopens inkscape the first two times I close it. At the third time it goes back to vim and it finishes running the snippet.

I tried opening inkscape likewise from python externally and it works fine.

The minimal steps to reproduce it are:

~/.config/nvim/init.vim
```
call plug#begin()
" Snippets
Plug 'SirVer/ultisnips'
call plug#end()
```
~/.config/nvim/UltiSnips/deleteme.snippets:
```
snippet test "test" A
`!p
import subprocess
subprocess.call('inkscape')
snip.rv = 'subprocess called'
`
endsnippet
```
Now typing 'test' in any '.deleteme'  file should trigger the behaviour.

The problem also happened when I tried opening evince and zathura. So it shouldn't be a problem if you don't have inskcape in your system.

- **Operating System**: Ubuntu 20.04 LTS
- **Vim Version**: NVIM v0.4.3 Build type: Release 
- **UltiSnips Version**: Up-to-date with master (on 23/04/2020)
- **Python inside Vim**: 3.8.2 (default, Mar 13 2020, 10:14:16) [GCC 9.3.0]

**Comment by lacygoill** [comment]
Check the value of `snip.c`. If the latter is not empty, it means that the python interpolation has already been performed at least once.

    snippet test "test" A
    `!p
    if not snip.c:
            import subprocess
            subprocess.call('zathura')
            snip.rv = 'subprocess called'
    `
    endsnippet

For more info, see https://github.com/SirVer/ultisnips/issues/1021.

**Comment by gustavobat** [comment]
It worked! Thanks, @lacygoill. I'm closing the issue.
