### ISSUE TITLE
Is it possible to load snippets based on file extension, not file type?

### ISSUE THREAD

**Issue by m-kru** [SirVer/ultisnips#1213]
I have some configuration files, which are `yaml` files, however I have to use `.core` extension for them. So basically, I have a lot of `foo.core, bar.core ...` files. To get syntax highlight I had to set their type to yaml in `filetype.vim` (neovim)
```vim
augroup filetypedetect
au BufNewFile,BufRead *.core     setf yaml
augroup END
```
I have defined some snippets that make sense only for `.core` files. However to make them work I had to put them in `yaml.snippets`. This has at least 2 drawbacks.  Firstly, `.core` specific snippets are triggered in all `yaml` files, not only the ones with `.core` extension. Secondly, snippets shortcuts must have longer names to avoid name collisions. Is there any way to make snippets load based on the file extension? The best solution probably would be, if I could define them in `core.snippets`.

**Comment by ParamagicDev** [comment]
I haven't had the chance to test this but you could try:

`setfiletype=core.yaml` 

you get syntax highlighting for yaml while still being able to use `core.snippets`

**Comment by SirVer** [comment]
That solution will work and you will have access to both yaml and core snippets like that.
