### ISSUE TITLE
i can't run the plugins

### ISSUE THREAD

**Issue by juand07** [SirVer/ultisnips#1218]
**Expected behavior:**

I hope when I press the keys to run UltinSnipsExpandTrigger it will show the snippet

**Actual behavior:**

Install the plugin, but when I start it it doesn't work for me, I don't know what happens

-----

- **Operating System**:  Mnjaro Linux 
- **Vim Version**:  8.2.510
- **UltiSnips Version**:  3.2 use version git
- **Python inside Vim**:  3.8.2
- **Docker repo/vimrc**:

**Comment by rodhash** [comment]
Not sure whether this is your case but... I just installed and had the very same issue however I noticed the keybinding was conflicting with YCM, in my case I use <C-l> so I just fixed them.

This was my issue and now it's working as expected, I've just tested Python and HTML.

Does the command ":Snippets" works for you? If it does perhaps it's worth checking your keybinding.
