### ISSUE TITLE
Unexpected tabstop behaviour when one snippet is used inside another

### ISSUE THREAD

**Issue by oyasin** [SirVer/ultisnips#1219]
**Expected behavior:**

pressing tab should put me outside my defined brackets in latex

**Actual behavior:**

The actual behavior varies if I entered one or more characters inside the snippet. 
![Screen-Recording-2020-05-06-at-8](https://user-images.githubusercontent.com/50802294/81304347-a0243900-9085-11ea-9bc3-dd6606569306.gif)

**Steps to reproduce**

1. use the following snippets 
`snippet mm "Math" wA`
 `\(${1}\)$0`
`endsnippet`

2. `context "math()"`
  `snippet sr "^2" iA`
  `^2`
  `endsnippet`

you should get the behaviour described in the gif.

-----

- **Operating System**:  Mac OS 10.5
- **Vim Version**: NVIM v0.4.3

**Comment by SirVer** [comment]
`math()` is not a defined function when i try to repro this. Could you post a minimal Vimrc to reproduce this problem?
