### ISSUE TITLE
Enable extensions for filetypes only

### ISSUE THREAD

**Issue by ichirou2910** [SirVer/ultisnips#1222]
Hi, firstly thanks for the awesome extensions. Since using this I can write assignment using markdown faster. But there is this one issue that I map both expand trigger and coc.nvim's pumvisible jumping to Tab, and that leads to conflict. I don't mind not using snippets for coding. I want Ultisnips to work only with my markdown files. Is that possible? I know I can still use ctrl-n / p but that's quite uncomfortable for me.

**Expected behavior:**
Tab key will only trigger snippet inside markdown files while trigger pumvisible jump inside other file types

**Actual behavior:**
pumvisible's Tab was overridden by Ultinips and cannot auto complete without ctrl-n/p

**Steps to reproduce**
Type words then press Tab

-----

- **Operating System**:  Arch Linux x86_64
- **Vim Version**: 
NVIM v0.4.3
Build type: Release
- **UltiSnips Version**: e35158de39767ef887a4d1e2a83786576d5a8477
- **Python inside Vim**: 3.8.2
- **Docker repo/vimrc**: 
![image](https://user-images.githubusercontent.com/51302893/81585027-c0355e80-93dd-11ea-92e4-e3d16111f417.png)
Hope that I gave clear explanation. Please tell me if you need any more details.

**Comment by nathan72419** [comment]
I think it can be done by your plugin manager.

**Comment by SirVer** [comment]
@ichirou2910 I agree with @longErste. For example VimPlug offers this functionality: 

https://github.com/junegunn/vim-plug/blob/master/doc/plug.txt#L164
