### ISSUE TITLE
freezing neovim in 4 keystroke when ultisnips loaded

### ISSUE THREAD

**Issue by pierreganty** [SirVer/ultisnips#1227]
**Expected behavior:**

Neovim not freezing

**Actual behavior:**
Neovim freezes when ultisnips is loaded after a few keystroke

**Steps to reproduce**
i // insert
CTRL-K // digraph
^
\<BS\> // backspace

a short `init.vim` to reproduce the error

```
packadd minpac

call minpac#init()

call minpac#add('k-takata/minpac', {'type': 'opt'})

call minpac#add('SirVer/ultisnips')

let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsListSnippets="<C-q>"
let g:UltiSnipsJumpForwardTrigger="<C-j>"
let g:UltiSnipsJumpBackwardTrigger="<S-tab>"
```
-----

- **Operating System**: macOS 10.14.6 
- **Vim Version**: neovim 0.4.3 
- **UltiSnips Version**: latest as installed and updated by minpac 
- **Python inside Vim**: 
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Python version: 3.7.7
  - INFO: pynvim version: 0.4.1
  - OK: Latest pynvim is installed.

I first posted an issue on the neovim's repo https://github.com/neovim/neovim/issues/12293 together with a backtrace. After some investigation I found it was ultisnips.

**Comment by lacygoill** [comment]
Does it help if you upgrade pynvim so that it includes [this commit](https://github.com/neovim/pynvim/commit/3791b2581eac4d2f1a829ab6792a122a0bb914fc)?

**Comment by bobogei81123** [comment]
I have a similar problem. Neovim hangs when smashing <F6> a few times with ultisnips.
Can confirm that upgrading pynvim to include that commit solves the issue. Thank you all :+1:

**Comment by pierreganty** [comment]
that solves it for me.
