### ISSUE TITLE
Is it possible to set a context for all snippets in a file?

### ISSUE THREAD

**Issue by owd2** [SirVer/ultisnips#1228]
I have a file in which I keep all my math snippets. I have a context function for them, but I'd rather not write `context "math()"` for every one of them. Instead, I'd like to declare that once at the top and be done with it. Is this possible? Thanks.

**Comment by xilefsensei** [comment]
Any update (or at least a workaround) for this?
I am also interested in easily applying a context function to all snippets in one file.

**Comment by hl037** [comment]
I don't think there are many use cases for this, I mean, tecnically, a snippet is written once, and applied many times.

But you could try to write a snippet to.... well, write snippet.

**Comment by xilefsensei** [comment]
Yes, writing a snippet for snippets is probably a good idea here. :D
Just for completeness: for me, snippets on a filetype-level are too broad. I want to use snippets for .c-files, but they should only apply inside comments (as I use the snippets for grading code-submissions). Therefore, I defined a context that only applies within a multiline-comment that should be used for many snippets.
Apparently there is no real demand for this (judging by this issue), so I will just use meta-snippets.

**Comment by hl037** [comment]
Maybe you can look at it another way : 

Suppose you are coding some kind of C functional library, and you know that all your functions will return some kind of "FunctionnalResult" and take a single parameter of type "FunctionnalResultList". Will you ask the the iso C Committee to put add some syntax to to say "I want something to tell the compiler all my functions have the same signature" ? ...I may ask you too, will you even bother defining a macro to do it ?

I agree with you, filetype only might not be "enough", but it's not the job of a snippet engine/plugin to figure out you are in a C comment, and I think this is why context where added : to be more than just filetype. Honestly, don't you think typing just `context "in_comment()"` is not quite short and simple for doing  such a specific thing ? It's even clear and readable : this way, you can even mix snippet only with in-comments ? This even allow you to do whatever context detection you want !

...There are a few things that could indeed be improved : I think that `global !p`  scope should be accessible when including from another definition.

**Comment by SirVer** [comment]
I also feel that context handling should be on the editor, not the snippet engine. Other editors do this much better than Vim, for example Sublime or TextMate did not have the idea of a "filetype", instead all configuration was on the context level. Context could be nested, so if you were for example in a python text snippet within a markdown file, all of your python shortcuts, snippets and commands were available. Much better design.

I do not know if any modern editor did repeat this, but for sure Vim did not. Adding it through a plugin is a tad overkill in my opinion.

**Comment by xilefsensei** [comment]
I think my comment was slightly misunderstood: I agree that the "am I inside of a comment"-detection should not be the job of a snippet-engine itself.

> Honestly, don't you think typing just `context "in_comment()"` is not quite short and simple for doing such a specific thing ?

This is a simple and good solution, but writing this for 100 snippets is not short anymore, as it adds 100 lines. If, instead, there was something like `global_context "in_comment()"`, which applied the context to every snippet in the file, then I could save 99 lines. Of course, with a meta-snippet I would not actually type this myself, but it still is a redundancy that I (and the author of this issue) could avoid with something like `global_context`.
If you feel that the additional complexity that this syntax would bring is not worth it, then I can of course live with that as well. :)

**Comment by SirVer** [comment]
I tend to say it is not worth it. It also adds complexity: there is more state to keep track of when reading a snippet file. There is already a piece of state which is the priority (and in some sense `global`), so this is not really adding something entirely new, but the semantics of a snippet would now also depend on a global state, which makes them harder to digest.

I am on the fence about this though.

**Comment by SirVer** [comment]
It seems there was not enough interest in pushing this forward, going ahead and closing this for now.
