### ISSUE TITLE
What's the cleanest way of skipping placeholders should nothing be provided?

### ISSUE THREAD

**Issue by leeren** [SirVer/ultisnips#1230]
For example, say I want to make a function doc snippet for sh that contains:
- A description
- A list of arguments
- What the function returns

```
########################
# ${1:Description}
# Arguments 
#   ${2: Argument}
# Returns
#   ${3: Return value}
########################
```

However, I'd want lines 3-4 to be completely removed from the snippet if I skipped filling in the $2 placeholder. The same would apply for the return value ($3).

That is, the following key presses:
`This is a function doc`**`<tab><tab>`**`0 if true, else 1.`

Would result in:
```
########################
# This is a function doc
# Returns
#   0 if true, else 1
########################
```

Clearly, this involves python interpolation but I can't wrap my head around how to do this without adding an extra key-stroke and keeping the pre-defined templating  (the whole argument / return block) shown until after actually hitting `<tab>`.

**Comment by ParamagicDev** [comment]
You honestly dont even need python interpolation here. Skipping predefined text isnt what Ultisnips is intended for but heres an easy work around:

```vim
snippet doc "create a doc block" b
########################
# ${1:Description}
${2:# Arguments
#   ${3:Argument}}
${4:# Returns
#   ${5:Return value}}
########################
endsnippet
```

So now if you decide you dont want `# Arguments`, you can just hit `<Backspace>` and you will clear out that whole section. However, if you do want it, you can just hit `<tab> and it will let you write in the `Argument` sections and skip the `Arguments` definite above it.

**Comment by leeren** [comment]
Thanks, I wasn't aware you could embed placeholders like that. This makes perfect sense!

**Comment by leeren** [comment]
By the way, one more quick question - in your example above, if I do hit `<Backspace>` I am left with an unwanted blank line. Is there any way to get around this?
