### ISSUE TITLE
How to prevent shell commands from expanding while xpanding a snippet.

### ISSUE THREAD

**Issue by TanishBansal** [SirVer/ultisnips#1236]
if I have snippet as follows:

snippet new
echo "`date`"
endsnippet

**Expected behavior:**
echo "`date`"

**Actual behavior:**
echo "Sat May 30 01:08:10 IST 2020"

-----

- **Operating System**: 
- **Vim Version**: 
- **UltiSnips Version**: 
- **Python inside Vim**: 
- **Docker repo/vimrc**:

**Comment by SirVer** [comment]
Try 

    echo \`date\`

i.e. escape the backticks with a backslash.
