### ISSUE TITLE
:UltiSnipsEdit problem when using both Vim and Neovim

### ISSUE THREAD

**Issue by bpj** [SirVer/ultisnips#1246]
I use both Vim and Neovim alternately because there are things which can be done, more easily or not at all, in one of them but not the other. Naturally I want to use the same snippets in both.  I've followed instructions and put

``````VimL
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath
source ~/.vimrc
``````

in `~/.config/nvim/init.vim` and so far so good: in nvim UltiSnips finds the snippets in `~/.vim/UltiSnips/`. However `:UltiSnipsEdit` insists on creating and opening `~/.config/nvim/UltiSnips/{filetype}.snippets`

My first attempt at a workaround was to make  `~/.config/nvim/UltiSnips/` a symlink to `~/.vim/UltiSnips/` but that made me have to "choose" between the same snippet in the two locations all the time, which I found intolerable.

I do now have a workaround, having put this mapping in my `.vimrc`:

``````VimL
nnor ,eu :exe printf(':tabe ~/.vim/UltiSnips/%s.snippets<cr>', &ft)
``````

(`printf()` may not be necessary but makes the
thing way more readable IMO)

which lets me use the mapping `,eu` to open the right file in both branches.  However I do keep forgetting this, so I wonder if there is a way to make `:UltiSnipsEdit` do the right thing in my situation?

**Comment by saddankiSFDC** [comment]
I have similar problem too!

**Comment by lieryan** [comment]
Thirded

**Comment by kaladin-syl** [comment]
@bpj Have you tried setting the path in `g:UltiSnipsSnippetStorageDirectoryForUltiSnipsEdit`?

**Comment by SirVer** [comment]
> I use both Vim and Neovim alternately because there are things which can be done, more easily or not at all,

I would be interested in that statement. I never found use for NeoVim, can somebody tell me why they use both Vim flavors interchangably?

I second @kaladin-syl solution, which is pretty new but should solve this use case well.

**Comment by bpj** [comment]
Yeah, I have pretty much given up on Neovim not only because of this issue
but mainly because what advantages there seemed to be tended to evaporate
on closer inspection, and most of all because I find running external
commands in the actual terminal more convenient.
I'll certainly try the suggested fix next time I'm on desktop, and then
I'll probably close this issue.

-- 
Better --help|less than helpless

Den mån 14 dec. 2020 21:16Holger Rapp <notifications@github.com> skrev:

**Comment by SirVer** [comment]
Closing this as answered. Feel free to provide more information and I can reopen.
