### ISSUE TITLE
How to fix InsertLeave event when triggering a snippet?

### ISSUE THREAD

**Issue by gergap** [SirVer/ultisnips#1254]
This is not directly and Ultisnips issue, but a conflict with clang-format.

I installed the clang-format plugin to reformat my source code automatically.
Typically this is invoked manually or when saving files.

but I configured vim to reformat the buffer using the LeaveEnter event,
so whenever you finished coding a part and press <Esc> it reformats it.
This is very convenient.

```vim
" Automatic reformat when exiting insert mode
augroup clang-format
    autocmd!
    autocmd InsertLeave * :ClangFormat
augroup END
```
 
However when typing `Inc<tab>` which expands to `#include <.h>` with the cursor at the location before `.h`,
where you normally just need to type the header filename, it triggers LeaveEnter and reformats the code,
which can change to order the includes, hence the entering the filename does not work. It's the wrong (old) cursor location.

I did not expect InsertLeave here, because normally you just keep typing. The shot InsertLeave and InsertEnter is normally not noticeable.

I don't know if or why this is necessary. So the question is: can this be disabled or does somebody know a workaround like
inhibiting clang-format while triggering snippets?

**Comment by Z5483** [comment]
vim will enter `Select Mode` when user expands a snippet, hence why it triggers `InsertLeave`.

**Comment by SirVer** [comment]
@Z5483 is exactly right. Unfortunately there is no programmatic way of avoiding the LeaveEnter event that I know of. However, what you could do is overwrite the UltiSnips expansion key with your own function that disables LeaveEnter and reenables it after expansion or jump within ultisnips.
