### ISSUE TITLE
 An error occured after update VIM from7.4 to 8.2

### ISSUE THREAD

**Issue by Shaiya2688** [SirVer/ultisnips#1256]
**Steps to reproduce**
An error occurred when I entered insert mode at position of string "yourname" in vimrc

422 "Plugin 'SirVer/ultisnips'
423 let g:UltiSnipsExpandTrigger="<c-k>"    "<tab>/<c-i> be used to insert a \t character
424 let g:UltiSnipsListSnippets="<c-l>" 
425 let g:UltiSnipsJumpForwardTrigger="<c-f>"
426 let g:UltiSnipsJumpBackwardTrigger="<c-b>"
427 let g:UltiSnipsSnippetDirectories=["UltiSnips", "."] "custom all.snippets in root of runtimepath: .vim/
428 let g:snips_author= "Huanhuan Zhuang"
429 let g:snips_email = "yourname@email.com" 

error information:
  1 An error occured. This is either a bug in UltiSnips or a bug in a
  2 snippet definition. If you think this is a bug, please report it to
  3 https://github.com/SirVer/ultisnips/issues/new
  4 Please read and follow:
  5 https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs                                                                                                                                                                                     
  6 
  7 Following is the full stack trace:
  8 Traceback (most recent call last):
  9   File "/home/shaiya/.vim/bundle/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 18, in wrapper
 10     return func(self, *args, **kwds)
 11   File "/home/shaiya/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 897, in _track_change
 12     self._try_expand(autotrigger_only=True)
 13   File "/home/shaiya/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 789, in _try_expand
 14     snippets = self._snips(before, False, autotrigger_only)
 15   File "/home/shaiya/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 669, in _snips
 16     source.ensure(filetypes)
 17   File "/home/shaiya/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/base.py", line 31, in ensure
 18     self._load_snippets_for(ft)
 19   File "/home/shaiya/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/base.py", line 53, in _load_snippets_for
 20     self._parse_snippets(ft, fn)
 21   File "/home/shaiya/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/base.py", line 70, in _parse_snippets
 22     raise SnippetSyntaxError(filename, line_index, msg)
 23 UltiSnips.snippet.source.file.base.SnippetSyntaxError: Invalid line '$ !' in vim/vimtutor.com:1

**Comment by Shaiya2688** [comment]
The error occurs only if the VIM source code is located at ~/.vim and is named vim:

git clone https://github.com/vim/vim.git ~/.vim/vim

**Comment by Shougo** [comment]
You should not clone Vim source code in `~/.vim`.
It is for Vim plugins directory.

**Comment by Shougo** [comment]
>23 UltiSnips.snippet.source.file.base.SnippetSyntaxError: Invalid line '$ !' in vim/vimtutor.com:1

UltiSnips load your Vim source code as snippet file...  Oh.

**Comment by Shaiya2688** [comment]
Thanks, I have removed the vim source code.
