### ISSUE TITLE
Request for fortran snippets

### ISSUE THREAD

**Issue by rudrab** [SirVer/ultisnips#1258]
Dear all, 
Though `fortran` is still a very popular language, and actively developed, fortran snippets is not included in `Ultisnips`. 
I develop and maintain a fortran plugin [vimf90](https://github.com/rudrab/vimf90) which includes Ultisnips support and few snippets. Please check the file [here](https://github.com/rudrab/vimf90/blob/master/UltiSnips/fortran.snippets).

I want to submit the file for ultisnips (its obviously better to have a core repository). It works for my purpose and those who are using it. Can somebody kindly have a look? (The process of creating a pull request is bit confusing to me.)

**Comment by hikerpig** [comment]
I think the actual snippets repo is [honza/vim-snippets](https://github.com/honza/vim-snippets) .
And creating a pull request is generally not that bothering, what's blocking you @rudrab  ?
Is this article helpful? https://guides.github.com/activities/hello-world
