### ISSUE TITLE
Ultisnips stops working after <c-x><c-o>

### ISSUE THREAD

**Issue by sin2384** [SirVer/ultisnips#1260]
When I open Vim everything works well and as expected, until I call <c-x><c-o> to autocomplete PHP function.
After that, I can't expand snippets anymore.

**Expected behavior:**
Snippets should expand.

**Actual behavior:**
Snippets not expanding.

**Steps to reproduce**
Type any snippet, expand it, do any omni completion and try to run any other snippet again.

This is my config in .vimrc. I'm using YouCompleteMe, Supertab too. Loading order in Vundle - Supertab, YouCompleteMe and Ultisnips.

let g:UltiSnipsSnippetDirectories = ['~/.vim/UltiSnips', 'UltiSnips']
let g:UltiSnipsEditSplit = "vertical"

" make YCM compatible with UltiSnips (using supertab)
let g:ycm_key_list_select_completion = ['<C-n>', '<Down>']
let g:ycm_key_list_previous_completion = ['<C-p>', '<Up>']
let g:SuperTabDefaultCompletionType = '<C-n>'

" better key bindings for UltiSnipsExpandTrigger
let g:UltiSnipsExpandTrigger = "<c-j>"
let g:UltiSnipsJumpForwardTrigger = "<tab>"
let g:UltiSnipsJumpBackwardTrigger = "<s-tab>"

-----

- **Operating System**:  Ubuntu 18.04
- **Vim Version**:  8.2.1185
- **UltiSnips Version**:  e83c82099d9bd43dc7895e3cb5b114ee5a2a07c6
- **Python inside Vim**:  and command not available and 3.6.9
- **Docker repo/vimrc**:

**Comment by sin2384** [comment]
Nevermind, found the problem. It was a plugin conflict with https://github.com/shawncplus/phpcomplete.vim. Once I disabled it, it all started to work.

**Comment by Shougo** [comment]
The issue should be closed.

**Comment by TornaxO7** [comment]
@sin2384 could you please close this issue?
