### ISSUE TITLE
[help] Can this be done with UltiSnips?

### ISSUE THREAD

**Issue by noib3** [SirVer/ultisnips#1264]
I created this snippet to insert an `itemize` environment when editix LaTeX documents:

````
snippet item "Itemize environment" b
\begin{itemize}
  \item $1
  \item $2
\end{itemize}
$0
endsnippet
````

I put two tabstops since one usually has at least two items per list. However once I get to `$2`, if I want to have a new item I have manually create a new line and write `\item`.

I'd like to modify this snippet in some way to get the following behaviour: by default there's just one tabstop after the first `\item` and everytime I press the trigger key (`<tab>` for me) a new line is created with `\item` already inserted.

This continues indefinitely until I press `<tab>` in a line that only contains a single `\item`. Once that happens, that line gets deleted and I jump to `$0`.

So it should work something like this (`_` indicates the cursor position):

````
item<tab>

-->

\begin{itemize}
  \item _
\end{itemize}
````

````
\begin{itemize}
  \item this is a test<tab>
\end{itemize}

--> 

\begin{itemize}
  \item this is a test
  \item _
\end{itemize}
````

````
\begin{itemize}
  \item this is a test
  \item _<tab>
\end{itemize}

--> 

\begin{itemize}
  \item this is a test
\end{itemize}
_
````

I hope I've been sufficiently clear. Any help is greatly appreciated.

**Comment by ricardokl** [comment]
Not sure, this will work, but you can try to use another snippet, using regular expressions:
The trigger would be something like `"(\item .+)"`
So, `.+` matches anything one or more times (an empty item wouldn't expand)
The `()` captures the hole thing in a group, so you can use it later.

I'm not sure how to use captured groups without python interpolation.... was coming here to write a post :D

Something like:
```
snippet "(\item .+)" "one more item"
`!p snip.rv = match.group(1)`
\item $1
endsnippet
```

I think you might loose you last tabstop for the original snippet though. Test and report here!

**Comment by rddunphy** [comment]
The snippet solution works pretty well (except you need to escape the backslash), but I couldn't figure out a way to cleanly get the last tabstop. In the end I've gone with a vimscript solution instead, inspired by [this Stackoverflow answer](https://stackoverflow.com/a/10532655/8326544):

```vim
setlocal formatoptions+=ro
setlocal comments+=s:\\item,m:\\item,e:\\item
```

This has to be executed after the filetype plugin is loaded, so it should go in `.vim/after/ftplugin/tex.vim`. Now when your typing an item, <kbd>Enter</kbd> will open a new line starting with `\item`, and <kbd>Tab</kbd> will jump after the the environment.

**Comment by SirVer** [comment]
I agree that `comments` is better suited for this use case.
