### ISSUE TITLE
Remove trigger key for 'A' option

### ISSUE THREAD

**Issue by dadaurs** [SirVer/ultisnips#1265]
As of now, if I create a snippet with the auto trigger flag, like this
```
snippet ( "( )" A
( $1 )$0
endsnippet
```
And use it, here is what happens. I'll use | for the cursor.
```
(      ==>     ( | )   ==> (| ))
                        ^
                    Press Tab
```
Ideally, if autotrigger is set, the expand trigger should not be used, and pressing tab would jump to the outside of the parentheses.
This, at least to me, seems to be a more natural alternative to the current behaviour.

Of course, this example is reliant on having the expand trigger as well as the jump forward trigger being mapped to the same key, but it doesn't have to be, the following snippet gives similar behaviour:
```
snippet sirver "sirver" A
sirver sirver
endsnippet
```

**Comment by tbrazel** [comment]
I can't reproduce this, it behaves as expected for me.

When you are at the $1 tabstop and hit "delete" it would produce the behavior you are describing (which I think is detailed in another issue) but hitting tab should move you outside the right parenthesis.

**Comment by SirVer** [comment]
I cannot reproduce this either.

Please provide a fully reproducible example, ideally using the approach explained in https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs or if not possible with a minimal `vimrc` and snippets files and an exact sequence of key strokes that trigger the bug.
