### ISSUE TITLE
Support character escape in choices item

### ISSUE THREAD

**Issue by hikerpig** [SirVer/ultisnips#1268]
More specifically, escape comma - which is the separator of choices but also very common as function parameter separator - by `\,` .

An example:

```
snippet q
${1:result} = nn.${2|fun1(,fun2(param1\, ,fun3(param1\, param2\, |}prarm_end)
endsnippet
```

Mentioned by @roachsinai in [a comment in issue 1166](https://github.com/SirVer/ultisnips/issues/1166#issuecomment-662567427).

**Comment by hikerpig** [comment]
@roachsinai You can try this out.

**Comment by roachsinai** [comment]
@hikerpig Works well. Thank you very much!

**Comment by SirVer** [comment]
Thanks for this feature!
