### ISSUE TITLE
E319: Sorry, the command is not available in this version: py3 import vim

### ISSUE THREAD

**Issue by winkee01** [SirVer/ultisnips#1269]
Problem:
when I use `git rebase -i a158o15` to modify the commit history, it pops up errors saying 
```
Error detected while processing ~/.vim/plugged/UltiSnips/autoload/UltiSnips.vim:
line    7:
E319: Sorry, the command is not available in this version: py3 import vim
```

My setup:
OS: Mac OS X
Vim: 8.2
Python: 3.7.3

my local py3 is a softlink to /usr/local/bin/python3

**Comment by winkee01** [comment]
sorry this is because my git's `core.editor` uses an old version of vim. problem is solved.

**Comment by HanwenJin16** [comment]
How did you change the core.editor to a newer version of vim?

**Comment by nburns** [comment]
ran into this same issue on a raspberry pi and installing the version of vim from `vim-nox` fixed it.
```sh
sudo apt install vim-nox
```
