### ISSUE TITLE
[Question] Adding a row in LaTeX

### ISSUE THREAD

**Issue by TornaxO7** [SirVer/ultisnips#1272]
**Expected behavior:**
So let's say I want to create a matrix in LaTeX like this:
```latex
\begin{document}
\begin{align*}
	\left(
	    \begin{array}{cc}
			10 & 10
	    \end{array}
	\right)
\end{align*}
\end{document}
```
Now I want to keep adding rows but I don't want to type `<number> & <number>` for each row. <br>
I want to create a snippet which adds a tabstop at each column like this:
```latex
<tabstop> & <tabstop>
```
That's what I have currently:
```python
def create_row_placeholders(snip):
	"""
	It will get the amount of columns and creates the placeholders.
	"""
	
	# get the amount of placeholders
	placeholders_amount = int(snip.buffer[snip.line].strip())

	# how big is the indentation?
	snip.buffer[snip.line] = "\t" * snip.buffer[snip.line].count("\t")
	
	# create anonymous snippet with expected content and number of tabstops
	placeholders = ' & '.join([f"${placeholder_index + 1}" for placeholder_index in range(placeholders_amount)])
	
	# expand anonymous snippet
	snip.expand_anon(placeholders)

post_jump "create_row_placeholders(snip)"
snippet "r(\d+)" "latex table row variable" br
`!p snip.rv = match.group(1)`
endsnippet
```

**Actual behavior:**
I can't get the first indentation.

**Question**
Do yo have an idea how I can achieve this?

**Comment by SirVer** [comment]
@TornaxO7, see the wonderful example of @marklcrns in #1298 (now also in master). Does that solve your issue?

**Comment by TornaxO7** [comment]
Well I have changed my style how to write a table, but it looks like that it's pretty useful. So thank you for mentioning it ;)
