### ISSUE TITLE
What is your personal snippet for print ?

### ISSUE THREAD

**Issue by edi9999** [SirVer/ultisnips#1274]
In the readme, you talk about your "personal snippet for print debugging", which apparently does allow you to print multiple variable names quickly.

I wish to implement something similar for Javascript to print multiple variables in JSON format.

For example, typing : 

* "print"
* <tab>
* "user, company, a == true"

would generate : 

```
console.log(JSON.stringify({"user": user, "company": company, "a == true" : a == true}));
```

How is that feasible ?

Could you share your personal "print" snippet, since I think I could do it similarly ?

**Comment by SirVer** [comment]
The snippet in python looks like this: 

```
snippet echo  "A better version of the echo snippet" b
print("#`whoami` ${2}`!p snip.rv = echo_vals(t)`" % (${1}))
endsnippet
```

the interesting function that is used here is `echo_vals`, which I import in the same snippet file further up like this:

```
global !p
from ushelper import *
endglobal
```

The implementation is in `~/.vim/pythonx/ushelper.py`:

```
from collections import defaultdict

def echo_vals(t, placeholder="%r", itemsep = ", "):
   cnt = defaultdict(int)
   vals = []
   cw = ""
   t = t[1].replace("  ", ",")
   for c in t:
      if c == ',' and sum(cnt.values()) == 0:
         cw = cw.strip()
         if cw:
            vals.append(cw)
         cw = ""
      else:
         if c in '([{':
            cnt[c] += 1
         elif c in ')]}':
            cnt[c] -= 1
         cw += c
   vals.append(cw.strip())
   vals = filter(lambda a: a.strip(), vals)

   return itemsep.join("%s: %s" % (a, placeholder) for a in vals)
```

So not the most straightforward snippet out there I think.
