### ISSUE TITLE
[Question] Does Ultisnips handle multiline triggers?

### ISSUE THREAD

**Issue by Melandel** [SirVer/ultisnips#1280]
I've posted on gitter but it seems empty, hence me posting here.

For example, say I want to expand

```
a
b|
```
, `|` being the position of the cursor, into:

```
expanded|
```

I've tried `snippet "a\r\nb" "Description" r`, `snippet "^a\n^b" "Description" rm` and `snippet "^a$^b" "Description" rm` but fear I am too ignorant about python and python's regex syntax, hence me showing up here

**Comment by SirVer** [comment]
No, it does not at this point in time.
