### ISSUE TITLE
No Completion dialogue.

### ISSUE THREAD

**Issue by AnshulKanwar** [SirVer/ultisnips#1294]
**Actual behavior:**
Typing any snippet doesn't show Completion dialogue but pressing `<tab>` expands it as normal.

**init.vim**
`Plug 'SirVer/ultisnips'`
`Plug 'honza/vim-snippets'`

Everything else is default.

- **Operating System**: Manjaro 20.2
- **Neovim Version**: NVIM v0.4.4
- **UltiSnips Version**: 3.2
- **Python inside Vim**: 3.8.6

**Comment by SirVer** [comment]
UltiSnips does not have a completion dialogue on its own, but other plugins like YouCompleteMe and others have support for completing UltiSnips snippets.
