### ISSUE TITLE
Using regex groups

### ISSUE THREAD

**Issue by ricardokl** [SirVer/ultisnips#1296]
If I capture a group using regex in the trigger, like 
```
snippet "something (captured) more" "name" r
mysnippet
endsnippet
```

I use it in the snippet through python interpolation:
```
`!p snip.rv = match.group(1)`
```
From what I've seen, in regex you can use the group with just "\1".
I'm not that familiar with regex, so i could be wrong.

Is there a way to use the captured group without having to call on python interpolation?

**Comment by SirVer** [comment]
No, there is not.
