### ISSUE TITLE
Duplicated snippets

### ISSUE THREAD

**Issue by cuppajoeman** [SirVer/ultisnips#1304]
Snippets folder: 
math.snippets  proof.snippets  proof_words.snippets  tex.snippets

# math.snippets
extends proof_words
extends proof

# tex.snippets
extends math

proof_words and proof have no snippets in common.

When I try to expand a word in proof_words it shows two instances of the same word as suggestions. I believe it is intepreting proof as (proof.snippets & proof_words.snippets) causing the duplication. Can someone tell me if this is expected behavior?

**Comment by SirVer** [comment]
This is working as intended and mirrors how vim is looking for filetypes: https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L542.

TL;DR: `ft_*.snippets` is taken by vim to be the same as `ft.snippets`. Rename your `proof_words` to `proofwords` to make it a truly independent filetype.
