### ISSUE TITLE
Custom Context: re.match('^\s+') is never matching, though it theoretically should.

### ISSUE THREAD

**Issue by lazyshawn** [SirVer/ultisnips#1308]
**Expected behavior:**
Custom context snippets.

**Actual behavior:**
All custom context snippets in [documentation](https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt) don't work.
The snippests will not expand.

**Steps to reproduce**

1. For the first demo, even the previous line started with `if err`, the snippet won't expand.
```
snippet r "return" "re.match('^\s+if err ', snip.buffer[snip.line-1])" be
return err
endsnippet
```

2. I tried to print out `snip.buffer`, using following snippet. It does return a SnippetUtil object.
```
snippet buf "foo" "1" be
`!p snip.rv = snip.buffer`
endsnippet
```

3. But when I tried to print `snip.line` or `snip.column`, using
```
snippet line "foo" "1" be
`!p snip.rv = snip.line`
endsnippet
```
It returns error:
```
AttributeError: 'SnippetUtil' object has no attribute 'line'

Executed snippet code:
  1 > snip.rv = snip.line
```

The UltiSnips documentation (chapter 4.9) states `snip` has the property `line` and `column`, yet I got a AttributeError exception thrown.

-----

- **Operating System**: Ubuntu 20.04 
- **Vim Version**: NVIM v0.4.3
- **UltiSnips Version**: 
- **Python inside Vim**:3.8.5  
- **Docker repo/vimrc**: [my vimrc](https://github.com/lazyshawn/config/blob/master/nvim/init.vim)

**Comment by SirVer** [comment]
Indeed, this is not working as intended. Useful for debugging such things is `snip.context`, i.e.

```
snippet r "return" "snip.line" be
`!p snip.rv = snip.context`
return err
endsnippet
```

While looking through this, it seems that the `\s` in the regular expression is not matching, presumably due to some messup with escaping of `\`.  This is indeed a bug. 
for your case you can work around it by trimming whitespace before doing the match and making your regex simpler:

```
snippet r "return" "re.match(r'^if err', snip.buffer[snip.line - 1].strip())" be
return err
endsnippet
```

Thanks for reporting!

**Comment by lazyshawn** [comment]
Thanks, it works.
