### ISSUE TITLE
Snippet not expanding without spaces

### ISSUE THREAD

**Issue by rudrab** [SirVer/ultisnips#1310]
This is probably not an issue, but a problem in my snippet,  so I am not following the report structure. Hope, this is ok.
I have created my snippets in texmath.snippets as:

```
priority -50 

snippet \d "dot" Aw
\dot{$1}
endsnippet

snippet ^^ "superscript" A
^{$1}
endsnippet

snippet __ "subscript" A 
_{$1}
endsnippet
```

The problem is, `^^` and `__` works only when preceeded by a space, like w options in Ultisnips. But, as you can see, there is no w, so this should not be in word limit.

But, still, in latex, `$H__$ `doesn't expands to `$H_{}$`, while `$H __$` does properly.

What I am doing wrong here?

I am using Ultisnips as snippet engine. This texmath.snippets structure is following honza/snippets, both installed using  `junegunn/vim-plug`

**Comment by SirVer** [comment]
Have you tried using the `i` option, i.e. inword expansion? I.e. this should work:

```
snippet __ "subscript" Ai
```

**Comment by rudrab** [comment]
Thanks....its working
