### ISSUE TITLE
Snippets with leader variables 

### ISSUE THREAD

**Issue by rudrab** [SirVer/ultisnips#1312]
Hi,
Is it possible to define snippets with leader variables, eg
    snippet `b:fort_leader`int 'integer' b

**Comment by SirVer** [comment]
Do you want to use this variable in the trigger of the snippet or in its body? The first one is not possible currently, the second one is.

Well, the first one might be hackable using https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L402, but it is probably fairly fragile.

**Comment by SirVer** [comment]
Feel free to reopen if you have more questions.
