### ISSUE TITLE
Tab unexpectedly jumps forward

### ISSUE THREAD

**Issue by Kagia001** [SirVer/ultisnips#1313]
**accidentaly pressed send, dont read this yet!**

I want tab to be exclusive to supertab, and ctrl-q to expand the snippet. For some reason, pressing tab while in a snippet sends me to the next place to fill in code. I removed all my plugins except for ultisnippets, honza-vimsnippets, and my colour scheme, and the problem persists

**Expected behavior:**
Tab doesn't do anything

**Actual behavior:**
Tab puts the cursor at the next place in the snippet where I can fill in code

**Steps to reproduce**
My init.vim is split between a few different files, only the three on top should be relevant, but I have included the rest in case that makes a difference.

---- init.vim ----
source $HOME/.config/nvim/plugins.vim
source $HOME/.config/nvim/deoplete.vim
source $HOME/.config/nvim/nerdtree.vim
source $HOME/.config/nvim/snippets.vim
source $HOME/.config/nvim/other.vim
source $HOME/.config/nvim/vim.vim
source $HOME/.config/nvim/keymap.vim

---- plugins.vim ----
call plug#begin('~/.config/nvim/plugins')
"Plug 'deoplete-plugins/deoplete-jedi'
"Plug 'tbodt/deoplete-tabnine', { 'do': './install.sh' }
"Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
"Plug 'preservim/nerdtree'
Plug 'chriskempson/base16-vim'
Plug 'honza/vim-snippets'
Plug 'SirVer/ultisnips'
"Plug 'ervandew/supertab'
"Plug 'Raimondi/delimitMate'
call plug#end()

---- snippets.vim ----
let g:UltiSnipsExpandTrigger="<c-q>"
let g:UltiSnipsListSnippets="<c-k>"
let g:UltiSnipsJumpForwardTrigger="<c-i>"
let g:UltiSnipsJumpBackwardTrigger="<c-m>"

---- deoplete.vim ----
let g:deoplete#enable_at_startup = 1

---- keymap.vim ----
noremap m h|
noremap n j|
noremap k n|
noremap K N|
noremap e k|
noremap f e|
noremap i l|
noremap t a|
noremap T A|
noremap a i|
noremap A I|
noremap o :|
noremap h o|
noremap H O|

---- nerdtree.vim ----
let NERDTreeMapOpenExpl='\e'
let NERDTreeMapMenu='h'
noremap <F2> :NERDTreeToggle<CR>
autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() |
    \ quit | endif

---- other.vim ----

---- vim.vim ----
colorscheme base16-solarflare
set clipboard+=unnamedplus
set relativenumber
set number
set undofile

1.
2.
3.

-----

- **Operating System**: 
- **Vim Version**: 
- **UltiSnips Version**: 
- **Python inside Vim**: 
- **Docker repo/vimrc**:

**Comment by Kagia001** [comment]
fuck it this docker stuff is to much effort

**Comment by SirVer** [comment]
@Kagia001 Ctrl+i and Tab are identical in unix shells and you have that configured as jump trigger.

**Comment by Kagia001** [comment]
Thanks, I guessed it would be something obvious.
