### ISSUE TITLE
Simple snippet is evaluated three times

### ISSUE THREAD

**Issue by thorlucas** [SirVer/ultisnips#1317]
**Expected behavior:**
A snippet is evaluated only once

**Actual behavior:**
A snippet is actually evaluated three times, which can produce 3x the side effects

**Steps to reproduce**
On macOS, we have the `say` shell command. So,

```
snippet test "Test" w
`!p
vim.command('silent! !say "Hello"')
snip.rv = 'foo'
`
endsnippet
```

This actually says hello *three* times. This is a problem because I'd like to use a snippet that actually runs a shell command that produces side effects. The reason I'd like to not use just a keymapping is because I'd like to take advantage of the regex capabilities to send certain parameters to the function.

**Comment by SirVer** [comment]
This can be worked around using the `snip.c` variable, for example https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L929.

**Comment by thorlucas** [comment]
@SirVer There still appears to be problems with this:

```
snippet test "Test" w
`!p
if snip.c != '':
    vim.command('silent! !say "Hello"')
    snip.rv = 'foo'
`
endsnippet
```

Says hello no times and the resulting snippet is empty. While,

```
snippet test "Test" w
`!p
if snip.c != '':
    vim.command('silent! !say "Hello"')

snip.rv = 'foo'
`
endsnippet
```

Says hello twice (and the resulting snippet is correctly foo).

The issue is that this command returns what `snip.rv` should be, but also has side effects.

**Comment by SirVer** [comment]
I see and you are right. UltiSnips cannot give better guarantees, but there is yet another way you should be able to achieve what you want:

```
snippet test "Test" w
`!p
if not getattr(snip, "mydone", False):
	snip.mydone = True
        vim.command('silent! !say "Hello"')
snip.rv = 'foo'
`
endsnippet
```
