### ISSUE TITLE
Error detected while processing function UltiSnips#TrackChange[1]..provider#python3#Call

### ISSUE THREAD

**Issue by Racle** [SirVer/ultisnips#1322]
Neovim produces error after editing and saving + quitting vimwiki file.

I got vimwiki at `~/vimwiki` path and it's private git repo.
I use [vimwiki-sync](https://github.com/michal-h21/vimwiki-sync/) to pull/commit/push my changes automatically and [vim-prettier](https://github.com/prettier/vim-prettier) to clean my file formatting.

This combination seems to be source of this error.

**Expected behavior:**
Close neovim without errors after saving vimwiki file and syncing changes (automatically) to git.

**Actual behavior:**
Error on exit when removing any line
``` 
Error detected while processing function UltiSnips#TrackChange[1]..provider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 15 (python3-script-host):
Traceback (most recent call last):
  File "/home/myuser/.local/share/nvim/plugged/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 18, in wrapper
    return func(self, *args, **kwds)
  File "/home/myuser/.local/share/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 935, in _track_change
    self._last_change = (inserted_char, vim_helper.buf.cursor)
  File "/home/myuser/.local/share/nvim/plugged/ultisnips/pythonx/UltiSnips/vim_helper.py", line 54, in cursor
    col = byte2col(line, nbyte)
  File "/home/myuser/.local/share/nvim/plugged/ultisnips/pythonx/UltiSnips/compatibility.py", line 37, in byte2col
    line = vim.current.buffer[line - 1]
  File "/usr/lib/python3/dist-packages/pynvim/api/buffer.py", line 45, in __getitem__
    return self.request('nvim_buf_get_lines', i, i + 1, True)[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/myuser/.local/share/nvim/plugged/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 52, in wrapper
    vim_helper.new_scratch_buffer(msg)
  File "/home/myuser/.local/share/nvim/plugged/ultisnips/pythonx/UltiSnips/vim_helper.py", line 155, in new_scratch_buffer
    vim.command("botright new")
  File "/usr/lib/python3/dist-packages/pynvim/api/nvim.py", line 287, in command
    return self.request('nvim_command', string, **kwargs)
  File "/usr/lib/python3/dist-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/pynvim/msgpack_rpc/session.py", line 104, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: Vim(new):E523: Not allowed here

"index.md" "index.md" 13L, 90C written
``` 

Error on exit when only adding any line:

``` 
Error detected while processing function UltiSnips#TrackChange[1]..provider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 10 (python3-script-host):
Invalid channel: 10"index.md" "index.md" 14L, 95C written
``` 

**Steps to reproduce**

minimial rc file which causes error (plugins are all latest versions):
```vim
call plug#begin(stdpath('data') . '/plugged')
  Plug 'prettier/vim-prettier', { 'do': 'npm install && npm install -g @prettier/plugin-xml @prettier/plugin-php' }
  Plug 'SirVer/ultisnips'
  Plug 'vimwiki/vimwiki'
  Plug 'michal-h21/vimwiki-sync'
call plug#end()


let g:vimwiki_global_ext = 0
let g:vimwiki_list = [{'path': '~/vimwiki/',
                      \ 'syntax': 'markdown', 'ext': '.md'}]
let g:prettier#autoformat = 1
``` 

1. edit vimwiki file (got .md ending) add or remove line
2. :wq

-----

- **Operating System**: pop_os 20.10 (very close to ubuntu 20.10)
- **Vim Version**: NVIM v0.4.4 Build type: Release 
- **UltiSnips Version**: Latest to date (66d81fc2c0bda30be69fffa46da0932ee8d5ddd5)
- **Python inside Vim**: python 3.8.6
- **pynvim**: 0.4.3
- **prettier/vim-prettier**: 6999016a0b0c6b5304b6956cbba472c1784d8039
- **vimwiki/vimwiki**: 619f04f89861c58e5a6415a4f83847752928252d
- **michal-h21/vimwiki-sync**: 965bfd20c65accc92a4e69018f6849a6abf7ad4c

**Comment by tpoliaw** [comment]
I had the same problem as this in plain (non-.neo) vim Going to the ultisnips repo (by default vim-plug puts it in ~/.vim/plugged/ultisnips) and checking out the 3.2 tag instead of master worked for me.

**Comment by Racle** [comment]
I went little different route. I stopped using `ultisnips` and I'm using `coc-snippets` instead :P

But good solution if someone else has this issue.

**Comment by webmandman** [comment]
I get this error as soon as I go into INSERT mode with typescript files. I'm on WSL Ubuntu and NVIM 0.6. 
```
1. error while processing function UltiSnips trackchange line 1
2. no python3 provider found.
```

**Comment by SirVer** [comment]
@webmandman You do not seem to have python3 installed or configured for NeoVim.

**Comment by webmandman** [comment]
@SirVer yup. I installed python 3.  I dont have python 2 installed and :checkhealth complains about it, I should say it says it optional. What added benefit is there if I had python 2 installed?

**Comment by SirVer** [comment]
No benefit. Only python3 is required, python2 is not needed.
