### ISSUE TITLE
Search first in local path

### ISSUE THREAD

**Issue by AndreaDiPietro92** [SirVer/ultisnips#1326]
Hi, I'm using ultisnip for my LaTeX projects. Every project has different snippets (ex: in math project I need a lot of snippets for integral and sum, in the physics project i need snippets for partial derivative and so on). 

It's possible to set UltiSnip to search te tex.snippets first in a local path and later on Ultisnip folder?

By doing so I would have a file with the common snippets and, for each project, the dedicated snippets.

Thank you for the support

-----

- **Operating System**: Kubuntu 20.10 
- **Vim Version**:  NeoVIM 0.4.4

**Comment by SirVer** [comment]
I can think of two options here: You can probably hack something using  `b:UltiSnipsSearchPath` for each buffer, it will be used with priority. So you could have something in `~/.vim/ftplugin/tex.vim` that looks something like this:


```
 let b:UltiSnipsSnippetDirectories=[expand('%:h') + 'UltiSnips']
```

See docs:
https://github.com/SirVer/ultisnips/blob/52ccebb67ff10607a4720a0e5382b3bd7a9b8c89/doc/UltiSnips.txt#L549

Alternatively, you could just have a UltiSnips directory in your project root and add your project directory to your vim runtimepath when you start working on it. A tool to do that might be https://github.com/krisajenkins/vim-projectlocal.

**Comment by AndreaDiPietro92** [comment]
Hi, first of all thanks for the help.

I've tried the first one solution but 
``` 
let b:UltiSnipsSnippetDirectories=[expand('%:h') + 'UltiSnips']
```
works only if i insert directly from NVIM (from the init.vim doesn't works) and not with ``` expand('%:h') + 'UltiSnips'``` but inserting manually the path. The second problem is, if I dont have a tex.snippets in my local directory, UltiSnips doesen't use the global one. 

Most probably is my fault in the config files.

**Comment by SirVer** [comment]
> The second problem is, if I dont have a tex.snippets in my local directory, UltiSnips doesen't use the global one.

Yes, that is the issue with that. It will only take the non-local ones. What about the other option, i.e.

1. add a UltiSnips directory into your project path
2. Add your project path to the runtime when you want to work on it: `set rtp+=<path to your project root>`.

**Comment by AndreaDiPietro92** [comment]
Nothing, I did not succeed in my intent, I will use only the global `tex.snippets`. Thank you very much for your support, I hope that maybe, in a future update, this feature will be implemented more directly.

**Comment by AndreaDiPietro92** [comment]
UPDATE 🎉🎉🎉🎉: 
I've done it! I just  `set rtp+=~/path/project` in my `init.vim` and create a `UltiSnip` directory in my root project.  In this way I've the local tex for the project and the global one for the other file.tex.

And again, Thank you so much!!
