### ISSUE TITLE
Could not load python36.dll (screenshot provided)

### ISSUE THREAD

**Issue by Karvalian** [SirVer/ultisnips#1349]
![image](https://user-images.githubusercontent.com/42641723/116973363-d797e680-acd5-11eb-988b-85f628a5021d.png)

**Comment by SirVer** [comment]
Seems to be a problem about how you have installed your Vim or your Python. This has nothing to do with UltiSnips and since I cannot reproduce, I fear I cannot help.

**Comment by piush-terminalwitchcraft** [comment]
Is  there any other option? I have installed latest version of python (3.11) as well as vim (9.0) from official website , 64 bit executable installer

**Comment by piush-terminalwitchcraft** [comment]
Is there any method to disable python?

**Comment by piush-terminalwitchcraft** [comment]
Got the issue @SirVer 

Solution @Karvalian 
please check python as well as vim version 
Ensure that both python as well as vim is 32 bit or 64 bit. 

Then check what version of python does vim supports 
run `vim --version`

check the flag 
` -DDYNAMIC_PYTHON3_DLL=\"python3x.dll\"`
You should have that version of python installed in the computer 
Mine was python311.dll , so python3.11 should be there and ensure path is provided in system environment 

I think the issue should be resolved
