### ISSUE TITLE
error:E117: Unknown function: UltiSnips#TrackChange

### ISSUE THREAD

**Issue by JackTJC** [SirVer/ultisnips#1352]
**Expected behavior:**
the plugin ultisnips can be used while vim editing

**Actual behavior:**
error message:
Error detected while processing TextChangedI Autocommands for "*":
E117: Unknown function: UltiSnips#TrackChange
the plugin is unavailable

**Steps to reproduce**
add 2 row to my .vimrc
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
and use ":PlugInstall" to install plugin in my vim

this is my vimrc:
https://github.com/JackTJC/vimrc/blob/master/.vimplus/.vimrc

-----
- **Operating System**:    
Linux n227-070-016 4.14.81.bm.15-amd64 #1 SMP Debian 4.14.81.bm.15 Sun Sep 8 05:02:31 UTC 2019 x86_64 GNU/Linux
- **Vim Version**:   
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 10 2021 10:14:37) 
- **UltiSnips Version**:     
currently newest
- **Python inside Vim**:     
Python 3.6.5
- **Docker repo/vimrc**:

**Comment by SirVer** [comment]
Your Link to your vmirc is broken. Also, I cannot reproduce with this limited information. 

Please provide a fully reproducible example, ideally using the approach explained in https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs or if not possible with a minimal `vimrc` and snippets files and an exact sequence of key strokes that trigger the bug.

**Comment by JackTJC** [comment]
the reason of this bug is that I write a wrong configuration in my .vimrc ,now it is resloved ,thanks a lot
