### ISSUE TITLE
Editing `.gitignore` files with `gisphm/vim-gitignore` plugin always errors on edit

### ISSUE THREAD

**Issue by bravoecho** [SirVer/ultisnips#1354]
**Expected behavior:**

With the `vim-gitignore` plugin (<https://github.com/gisphm/vim-gitignore>), be able to edit `.gitignore` files as usual.

**Actual behavior:**

Upon entering any new text, a split window opens, showing the following error:

<details>
  <summary>Expand to see error trace</summary>
  
<pre>
Traceback (most recent call last):
  File "/src/UltiSnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 18, in wrapper
    return func(self, *args, **kwds)
  File "/src/UltiSnips/pythonx/UltiSnips/snippet_manager.py", line 933, in _track_change
    self._try_expand(autotrigger_only=True)
  File "/src/UltiSnips/pythonx/UltiSnips/snippet_manager.py", line 794, in _try_expand
    before, snippets = self._can_expand(autotrigger_only)
  File "/src/UltiSnips/pythonx/UltiSnips/snippet_manager.py", line 790, in _can_expand
    return before, self._snips(before, False, autotrigger_only)
  File "/src/UltiSnips/pythonx/UltiSnips/snippet_manager.py", line 671, in _snips
    source.ensure(filetypes)
  File "/src/UltiSnips/pythonx/UltiSnips/snippet/source/file/base.py", line 31, in ensure
    self._load_snippets_for(ft)
  File "/src/UltiSnips/pythonx/UltiSnips/snippet/source/file/base.py", line 53, in _load_snippets_for
    self._parse_snippets(ft, fn)
  File "/src/UltiSnips/pythonx/UltiSnips/snippet/source/file/base.py", line 70, in _parse_snippets
    raise SnippetSyntaxError(filename, line_index, msg)
UltiSnips.snippet.source.file.base.SnippetSyntaxError: Invalid line '        .ensime' in ~/.vim_plugged/vim-gitignore/snippets/gitignore/Ensime.snippets:4
</pre>
</details>

The specific snippet file reported is different every time, apparently random, but the error is always the same.

**Steps to reproduce**

1. edit a new file `# vim ~/.gitignore`
2. enter `insert` mode
3. start typing any character

-----

- **Operating System**: macOS Big Sur, Intel, v 11.3.1
- **Vim Version**: `VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 20 2021 19:14:20)`, `macOS version - x86_64`
- **UltiSnips Version**: `b3fd9022bdc3472dac114a8b2aa85b845189514b`
- **Python inside Vim**: py: `E319: Sorry, the command is not available in this version`, py3: `[Clang 12.0.0 (clang-1200.0.32.29)]`
- **Docker repo/vimrc**: `master` on the fork <https://github.com/bravoecho/ultisnips>

**Comment by SirVer** [comment]
The problem is mentioned here in your stacktrace:

> UltiSnips.snippet.source.file.base.SnippetSyntaxError: Invalid line '        .ensime' in ~/.vim_plugged/vim-gitignore/snippets/gitignore/Ensime.snippets:4

This leads me to believe that you configured your snippets source path to interpret this as an UltiSnips snippet (which you should not, since it seems to be a snipMate snippet). Please look through the UltiSnips documentation for `snippets` and why you should not use it as UltiSnips search path.
