### ISSUE TITLE
Two snippets probably interfere with one another

### ISSUE THREAD

**Issue by sourav-majumdar-math** [SirVer/ultisnips#1356]
I have two snippets "bracket2" and "\bracket2"
**Expected behavior:**
 I want the "\bracket2" snippet to expand as `\{ \}`

**Actual behavior:**
However the "\bracket2 snippet expands as `\{}`

**Steps to reproduce**

1.
```
call plug#begin('~/.vim/plugged')

Plug 'sirver/ultisnips'
let g:UltiSnipsExpandTrigger = '<tab>'
let g:UltiSnipsJumpForwardTrigger = '<tab>'
let g:UltiSnipsJumpBackwardTrigger = '<s-tab>'

call plug#end()

map <Leader>ue :UltiSnipsEdit<cr>
```
2. 
```
  priority 11
   snippet { "bracket2" iA
   {$1}$0
   endsnippet
  
   priority 10
   snippet \{ "\bracket2" iA
   \{$1\}$0
   endsnippet
```
3. On pressing `\{` it expands as `\{}`

-----

- **Operating System**: Ubuntu 20.04
- **Vim Version**:  Vim 8.1
- **UltiSnips Version**: UltiSnips 3.2
- **Python inside Vim**: Python 3.8.8

**Comment by SirVer** [comment]
You have your prioritizes reversed and you need to escape the `\` in your second snippet. This should work:

```
priority 11
snippet { "bracket2" iA
{$1}$0
endsnippet

priority 12
snippet \{ "\bracket2" iA
\\{$1\\}$0
endsnippet
```
