### ISSUE TITLE
Can I expand a snippet while inside another snippet?

### ISSUE THREAD

**Issue by Giatroo** [SirVer/ultisnips#1358]
This is just a question, so I didn't follow the template.

I use Ultisnips a lot with LaTeX and in many times I catch myself trying to expand a snippet while I'm not done with the current snippet I'm expanding.

I'll give an example and it should be easy to understand.

Suppose I have the two following snippets:

```
snippet bf "Textbf snippet" w
\textbf{$1} $0
endsnippet

snippet it "Textit snippet" w
\textit{$1} $0
endsnippet
```

So them I type bf and hit Ctrl+L to expand it to
`\textbf{$1}`
 with my cursor where the $1 is. But now, many time I want to combine bold font and italics, so I would type it and hit Ctrl + L again to expand it. But the result will be:
`\textbf{it} $0`
with my cursor where the $0 is. But instead I want this:
`\textbf{\textit{$1}}`
with my cursos where the $1 is.

Can I achieve that using some configuration of Ultisnips? I tried searching in the documentation and in the issue section, but I haven't found anything.

Thanks!

**Comment by leogama** [comment]
Hi. Nested snippet triggers should work out-of-the-box. What is `Ctrl+L` mapped to? This is not a default UltiSnips mapping. Do you set this:
```
let g:UltiSnipsExpandTrigger = '<C-L>'
```
in your `vimrc` file? Please share the relevant in your VIM settings.

**Comment by Giatroo** [comment]
Ops, I'm sorry. I said `Ctrl+L` but I actually use `Ctrl+J`.

The only configurations related to Ultisnips in my `vimrc` is:
```
let g:UltiSnipsExpandTrigger="<C-j>"

nmap <leader>u :UltiSnipsEdit<CR>
```

**Comment by Giatroo** [comment]
Did you try reproducing my example?

**Comment by Giatroo** [comment]
Oh, I just figured out the problem was exactly because I remapped `g:UltiSnipsExpandTrigger` to `Ctrl+J` and `g:UltiSnipsJumpForwardTrigger` also uses `Ctrl+J`.

I changed `g:UltiSnipsJumpForwardTrigger` to another key and now it's working.

Thanks for helping.
