### ISSUE TITLE
Tabbing our of a snippet doesn't work

### ISSUE THREAD

**Issue by L1szt** [SirVer/ultisnips#1368]
Consider the following snippet:
```lua
snippet "bar" "bar" riA
\overline{$1}$0
endsnippet
```
The snippet expands normally as one would expect but when I hit tab it doesn't jump to `$0` but makes a normal tab in the curly brackets. What could the reason for this issue be?

**Comment by SirVer** [comment]
Please provide your vimrc.

**Comment by L1szt** [comment]
This is a bit complicated because  I installed it with lua based neovim, but I didn't add any additional configuration, only installed the plugin.

**Comment by L1szt** [comment]
Lua specific issue
