### ISSUE TITLE
Some selection of snippets does not work. Many other works.

### ISSUE THREAD

**Issue by mukuntharajaa** [SirVer/ultisnips#1370]
**Expected behavior:**
1) vim someheader.h
2) Type #ifndef , now it should automatically show snippet for ifndef macro.
3) Select the one and hit "ctrl-space". 
4) Snippet should be inserted

**Actual behavior:**

Nothing happens, no matter how many time i hit "ctrl-space"

**Steps to reproduce**

1) vim someheader.h
2) Type #ifndef , now it should automatically show snippet for ifndef macro.
3) Select the one and hit "ctrl-space". 
4) Snippet should be inserted

-----

- **Operating System**: Fedora 33
- **Vim Version**: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 21 2021 00:00:00)
                              Included patches: 1-2875
- **UltiSnips Version**: aec91caefec10741722927cf073703a528fe7a8f

- **Python inside Vim**: 3.9.5 (default, May 14 2021, 00:00:00)
[GCC 10.3.1 20210422 (Red Hat 10.3.1-1)]

- **Docker repo/vimrc**: 
call plug#begin()
Plug 'Valloric/YouCompleteMe', { 'do': './install.py' }
Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets'
call plug#end()
let g:UltiSnipsExpandTrigger="<c-space>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"

Selection window pops up while typing:
![Screenshot from 2021-06-22 11-04-21](https://user-images.githubusercontent.com/19199981/122870855-d4bb8880-d34b-11eb-9912-a76e4a21f436.png)

After making selection using arrow on keyboard:
![Screenshot from 2021-06-22 11-04-31](https://user-images.githubusercontent.com/19199981/122870905-e6049500-d34b-11eb-8a0d-9ecf73e85fc0.png)

After this, no matter how many times I enter "ctrl-space" nothing happens. Whereas for other snippets, it works fine.
So far I have found out that this snippet is not working.

**Comment by SirVer** [comment]
I cannot reproduce this without YouCompleteMe. Looking at your screenshot it seems that an extra `#` was inserted, which seems to be a bug my YouCompleteMe and not UltiSnips.

**Comment by SirVer** [comment]
Closing for lack of feedback.
