### ISSUE TITLE
[QUESTION] Do not trigger snippets in comments ? custom-context-snippets

### ISSUE THREAD

**Issue by AndreSouzaAbreu** [SirVer/ultisnips#1371]
Hi! How to make ultisnips do not trigger snippets if the cursor is on a comment section in languages such as C, Java, Javascript, Python, PHP ?

This article https://castel.dev/post/lecture-notes-1/ how to trigger Tex snippets when the context is math or comments.. 

```
global !p
def math():
    return vim.eval('vimtex#syntax#in_mathzone()') == '1'

def comment(): 
    return vim.eval('vimtex#syntax#in_comment()') == '1'
endglobal

context "math()"
snippet sr "^2" iA
^2
endsnippet
```

But it works only with LaTeX. I was wondering how to do similar thing but for Java, C, CPP, PHP, JS, etc.
I tried the following:

```
global !p
def code(): 
    return vim.eval('vimjava#syntax#in_comment()') == '0'
endglobal

context "code()"
snippet fori "for loop" iA
for (int i = 0; i < $1; i++) {
  $2
}
$0
endsnippet
```

It seems `vimjava` does not work. Anyone has an idea?

**Comment by AndreSouzaAbreu** [comment]
I was able to solve it for any language, here is how:

Add those lines to your vimrc:
```vimrc
function IsCursorWithinComment()
    let hg = join(map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")'))
    return hg =~? 'comment' ? 1 : 0
endfunction
```
Add those lines to the beginning of any `.snippet` file

```
global !p
def comment(): 
    return vim.eval('IsCursorWithinComment') == '1'

def code():
    return vim.eval('IsCursorWithinComment()') == '0'
endglobal
```

Then just add `context "code()"` before any snippet:

```
context "code()"
snippet while "while block" A
while ($1) {
  $2
}
$0
endsnippet
```

**Comment by ayushxx7** [comment]
@AndreSouzaAbreu I am trying to activate snippets in markdown file when the text is inside `$$`. Not able to figure it out. Can you help?

**Comment by AndreSouzaAbreu** [comment]
@ayushxx7 install the vimtex plugin and add the following to the beginning of your `.snippet` files

```
global !p
def math():
    return vim.eval('vimtex#syntax#in_mathzone()') == '1'

def comment(): 
    return vim.eval('vimtex#syntax#in_comment()') == '1'
endglobal

# a sample snippet
context "math()"
snippet sr "^2" iA
^2
endsnippet
```

If that doesn't work with markdown, you may need to change filetype like `set filetype=tex` or `autocmd BufEnter *.md set filetype=tex`

**Comment by ayushxx7** [comment]
then markdown syntax highlighting and preview won't work.
