### ISSUE TITLE
option to disable ultisnips

### ISSUE THREAD

**Issue by Hritik14** [SirVer/ultisnips#1372]
**Expected behavior:**
Able to disable ultisnips with a variable like `g:loaded_ultisnips = 1`

**Actual behavior:**
No such mention in documentation

**Steps to reproduce**
Search for `disable` in ultisnips docs

**Why do I need this**
I use `vimpager` and I really don't want ultisnips to load there. One reason being, when switch to insert mode in vimpager, ultisnips start throwing errors like
```
Error detected while processing InsertCharPre Autocommands for "*"..function UltiSnips#TrackChange:
line    1:
E837: This Vim cannot execute :py3 after using :python
Press ENTER or type command to continue
```
I get that going into insert mode is not the ideal thing in a pager service but sometimes - by mistake - I press the insert mode key and then ultisnips keeps throwing these errors and spams the entire page.

- **Operating System**: Archlinux  
- **Vim Version**: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 28 2021 06:58:52)
Included patches: 1-2891

- **UltiSnips Version**:  8554371b57c8989cf73f73f288c456fb3f2a3a3a 
- **Python inside Vim**:  3.9.5 (default, May 24 2021, 12:50:35)

**Comment by SirVer** [comment]
The functionality to enable or disable plugins is part of the affordances of plugin managers. For example, VimPlug can conditionally enable plugins using:

```
Plug 'SirVer/UltiSnips', { 'for': 'python' }
```

I do not think it wise to add shaky support for this into UltiSnips.

**Comment by Hritik14** [comment]
@SirVer I'm using vim8's inbuilt plugin manager and unfortunately, there's isn't a way to disable plugin in vimrc files :(

**Comment by SirVer** [comment]
@Hritik14 time to switch plugin managers then? 

I have to be resisting feature creep in an already very complex project like UltiSnips. Adding a feature that disables the plugin, though it is really enabled globally is not a feature within the scope of the plugin itself - even more so since there are awesome plugin managers which support this just nicely.
