### ISSUE TITLE
ultisnips doesn't print \ for multiple times

### ISSUE THREAD

**Issue by AvSaba** [SirVer/ultisnips#1375]
**Expected behavior:** ‍‍‍‍‍‍‍Print `\left\{`
‍‍

**Actual behavior:** It prints `\left{`

**Steps to reproduce** Here is my snip:
```
snippet { "{" i
\left\{
endsnippet
```

-----

- **Operating System**:Debian Testing 
- **Vim Version**: 8.2
- **UltiSnips Version**: 3.2
- **Python inside Vim**: 3.9.2

**Comment by SirVer** [comment]
```
Expected behavior: Print \left{
Actual behavior: It prints \left{
```


Where is the bug?

**Comment by AvSaba** [comment]
Sorry for the typo in my first comment. I fixed it. the expected behavior is print `\left\{` not `\left{`

**Comment by SirVer** [comment]
You are escaping the `{` with adding the backslash in front. You need to escape the `/` and the `{`:

```
snippet { "{" i
\left\\\{
endsnippet
```
