### ISSUE TITLE
wierd snippets content did not converge error

### ISSUE THREAD

**Issue by vifm9** [SirVer/ultisnips#1392]
wish i knew

**Expected behavior:**
make everything upper ccase

**Actual behavior:**
the snippets content did not converge

**Steps to reproduce**
snippet ifndef
#ifndef ${1:`!p snip.rv = t[1].upper()`}
#define $1
$0
#endif /* $1 */
endsnippet

and trying to use it

1.  just trying to use the regular snippet above and have no clue why im getting
2. 
3. 
4. --

- **Operating System**: 
- arch linux 5.14
- **Vim Version**: 
- neovim 0.5.0
- **UltiSnips Version**: 

- **Python inside Vim**: 
3.9.7
- **Docker repo/vimrc**:

**Comment by SirVer** [comment]
You are trying to edit the snippet you are currently typing. UltiSnips cannot do this. There is no way to change the typed text with ultisnips will the snippet is still active.
