### ISSUE TITLE
Error with `snippets.vim`

### ISSUE THREAD

**Issue by L1szt** [SirVer/ultisnips#1398]
OS: macOS Big Sur

When I open a `.snippets` file I get the error
```
Error detected while processing BufRead Autocommands for "*.snippets"..FileType Autocommands for "*"..function <SNR>14_LoadFTPlugin[17]..script /Users/me/.v
im/plugged/ultisnips/ftplugin/snippets.vim:
line   13:
E363: Pattern uses more memory than 'maxmempattern'
```

**Comment by ZachariahPang** [comment]
I recently started to see this exact same error as well. I'm using neovim 0.6.1. Any suggestions what this might related to?

**Comment by SirVer** [comment]
@ZachariahPang please try with vanillavim to rule out it is a problem with neovim. If that works, report the bug to neovim instead.

**Comment by ZachariahPang** [comment]
> @ZachariahPang please try with vanillavim to rule out it is a problem with neovim. If that works, report the bug to neovim instead.

I think it's probably because I wrote a too complicated regex pattern. I have streamlined it a little bit and there's no more warnings. Thank you.
