### ISSUE TITLE
Timestamp keeps changing with cursor moving in Neovim

### ISSUE THREAD

**Issue by kartik-pant-23** [SirVer/ultisnips#1410]
**Expected behavior:** I have added timestamp using `!v strftime("%d.%m.%y %H:%M:%S")` inside a snippet. I want the timestamp to have the time of the creation of the file (or the time when I first used this snippet, as this snippet is the first thing I do when creating a new file)

**Actual behavior:** The timestamp gets added but it keeps changing as I move my cursor around(Even if I type something). Unless I save and quit the file, this issue remains there.

**Steps to reproduce**

1. Inside a `.cpp` file, type the following command `:UltiSnipsEdit` and add the following snippet - 
```snippets
snippet minimal "Minimal template"
/**
 *      author:  kartikPant23
 *      created: `!v strftime("%d.%m.%y %H:%M:%S")`
**/

#include <bits/stdc++.h>
using namespace std;

int main () {
        $1
        return 0;
}
endsnippet
```
2. Inside a `.cpp` file, trigger this snippet using `minimal`, the timestamp is added.
3. Now either type anything or move around the cursor, you will see the timestamp keeps changing.

-----

- **Operating System**: Ubuntu 20.04
- **Vim Version**: NVIM v0.6.0-dev
Build type: RelWithDebInfo
- **UltiSnips Version**: 53e1921e3ef015ef658e540c0aa9c4835f9c18a6
- **Python inside Vim**: 3.8.10
- **Docker repo/vimrc**: [vimrc](https://codedump.xyz/ruby/YY_CQrN_1bylw7yS)

**Comment by SirVer** [comment]
This is expected behaviour, as long as the snippet is live (i.e. you have not hit the $0 tabstop or navigated outside of the scope of the snippet) it will update with every cursor move. Very easy and appropriate fix in your case it to replace `$1` with `$0` - you should do this anyways, because otherwise the snippet is live forever while you code away, meaning that UltiSnips will track any change to your buffer to keep the snippet objects position correct - which is unnecessary processing you really do not need to do.

**Comment by kartik-pant-23** [comment]
Thanks a lot, I did not know that already... this works!!

**Comment by BertrandSim** [comment]
This may already be resolved, but I'd like to chime in with a more robust approach: check if the snippet is already expanded with `snip.c`. This would be preferred if the snippet has multiple tabstops. From the docs,

https://github.com/SirVer/ultisnips/blob/1914ef242a5b6fc095abc4b2c7702d6697c69324/doc/UltiSnips.txt#L944-L948

Thus, replace the lines
```
/**
 *      author:  kartikPant23
 *      created: `!v strftime("%d.%m.%y %H:%M:%S")`
**/
```

with 
```
/**
 *      author:  kartikPant23
 *      created: `!p if not snip.c:
           snip.rv = vim.eval("strftime('%d.%m.%y %H:%M:%S')")`
**/
```
