### ISSUE TITLE
semicolon and comma trigger the wrong snippets

### ISSUE THREAD

**Issue by licq** [SirVer/ultisnips#1411]
I don't know whether I made wrong configuration. When I write rust code, comma after ) trigger the "pri!" snippet and semicolon after ) trigger "dbg!" snippet.

I use the default configuration of ultisnips and the rust snippets contains:

snippet pri, "print! with format param"
	print!("${1}{${2}}", ${3});

snippet d; "dbg! debugging macro statement"
	dbg!(&${1});
	${0}
<img width="733" alt="Screen Shot 2021-11-15 at 12 06 12 AM" src="https://user-images.githubusercontent.com/26323/141688898-2a389894-bc93-4c09-b718-8f31397a0ed4.png">

**Comment by SirVer** [comment]
I cannot reproduce this without understanding your configuration. Please provide a fully reproducible example, ideally using the approach explained in https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs or if not possible with a minimal `vimrc` and snippets files and an exact sequence of key strokes that trigger the bug.
