### ISSUE TITLE
Python interpolation not working?

### ISSUE THREAD

**Issue by jeetsukumaran** [SirVer/ultisnips#1412]
**Expected behavior:**

Python interpolation should return the comment string.

**Actual behavior:**

It does not.

**Steps to reproduce**

Given the following definition:

```
global !p
def get_commentstring():
    import vim
    s = vim.eval("&commentstring")
    s = s.replace("%s", "")
    return s
endglobal

snippet {1 "Fold 1"
`!v split(&l:commentstring, '%s')[0]`${1}{{{1
${VISUAL}
`!p get_commentstring()`}}}1$1
$0
endsnippet
```

I get the following expansion:
```
// {{{1
}}}1
```

For some reason, the Python return value is not used.

Same obtains with even simpler Python, e.g.:
```
def get_commentstring():
    return "//"
```

-----

- **Operating System**: Ubuntu 21.04
- **Vim Version**:  
    - VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov 08 2021 14:21:34) Included patches: 1-2269
    - NVIM v0.5.1
- **UltiSnips Version**:  2c83e40ce66814bf813457bb58ea96184ab9bb81
- **Python inside Vim**: 
  - :py import sys; print(sys.version)`: not found
  - :py3 import sys; print(sys.version)': 3.8.10 (default, Sep 28 2021, 16:10:42)

**Comment by SirVer** [comment]
`!p get_commentstring()` should be `!p snip.rv = get_commentstring()`

**Comment by jeetsukumaran** [comment]
Ah, of course! So sorry for the confusion.

And sooooooo truly appreciate an INCREDIBLE plugin. It's not only saved me hours over the last year alone, it's made so much development and writing I do (in LaTeX) so much more pleasant. THANK YOU.
