### ISSUE TITLE
Easily Get Ultisnips Working on Windows Machine

### ISSUE THREAD

**Issue by ghost** [SirVer/ultisnips#1418]
Hello,

I would like to find whether I might quickly resolve this problem that I am having.

I have a windows machine, and I can't use ultisnips because I am unable to install python in a way that vim can find it on my machine, even after adding the location of the library to my path.

Not sure why this is so difficult?

**Comment by hadjiabc** [comment]
When I do `:version`, it tells me `python3/dyn`

Why did I even so confusedly need to have to add library location to my path, if I am already supposed to have python?

It complains, when I try to do the very first completion snip thing, that I don't have python39.dll, but that is in the folder that I added to my path. Can someone just tell me how to fix this I know that it must be something simple.

**Comment by hadjiabc** [comment]
I did `:version`, and then I got that I am already `python3/dyn`.

This seems like some kind of unnecessary humiliation, that I can't do the very first completion, because it will complain about some python39.dll missing. I have already vim with python. 

Does someone want to help me close this issue?

**Comment by hadjiabc** [comment]
I am going to change my name to allah ackbar if it takes any longer to fix this.

**Comment by hadjiabc** [comment]
I have read that there are people suggesting to add the python library to my vim folder, which to be honest I have no idea where it is, and this just seems unnecessarily difficult.

How can there not be someone around to just quickly explain to me how to fix this problem

**Comment by SirVer** [comment]
I do not have access to a windows machine and have not had this for the last 15 years, hence I cannot really advise or help. A quick search pointed me to this: https://stackoverflow.com/questions/4718122/how-to-enable-python-support-in-gvim-on-windows, maybe that works for you. 

I'll leave this open for a while, maybe somebody passes by that knows windows better.
