### ISSUE TITLE
My Python Installation Is Still Broken

### ISSUE THREAD

**Issue by ghost** [SirVer/ultisnips#1419]
My python installation is "still broken."

Why does it complain to me that I need python39.dll?

I added python to my path, does anyone have a clue how to fix it,

Where does the python dll need to be in order for the ultisnips to find it,

I have never had so much trouble with vim finding things for plugins

It is almost appearing that I am *not allowed* to use your plugin

**Comment by SirVer** [comment]
I have no means of reproducing your issue, I have no idea how your configuration looks. If you really need help here, please provide your setup a minimal reproducible example and we can have looks.

Please provide a fully reproducible example, ideally using the approach explained in https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs or if not possible with a minimal `vimrc` and snippets files and an exact sequence of key strokes that trigger the bug.
