### ISSUE TITLE
Snippet option `r` seems to imply option `i`

### ISSUE THREAD

**Issue by ces42** [SirVer/ultisnips#1420]
**Expected behavior:**
If I define a snippet
```
snippet "abc" r
abcdefghijkl...
endsnippet
```
I would expect this to be equialent to the snippet defined with `snippet abc`.

**Actual behavior:**
The first snippet will trigger on `sabc` while (in-word) the second one won't. It seems that option `r` automatically implies option `i`

**Steps to reproduce**
as described above

This is not a terrible thing because if I'm already defining a regex trigger I can just do the word-checking myself. But it would be good to have this described in the documentation

-----
- **Operating System**: Ubuntu 21.10
- **Vim Version**: neovim 0.6.1
- **UltiSnips Version**: current (`2c83e40ce66814bf813457bb58ea96184ab9bb81`)
- **Python inside Vim**: 3.9.7

**Comment by hl037** [comment]
I guess to "disable" the i flag, you should use the '\b' as described in python's `re`. to me, it was quite implicit that regex implies it can be matched in-word, since it kid of replace the default search

**Comment by SirVer** [comment]
Yes, this is working as intended - regex kinda unlocks complete new power. If this is not clear in the docs, we should improve the docs though. Patch is welcome!
