### ISSUE TITLE
Custom snippets for file without extension, but with recognized type

### ISSUE THREAD

**Issue by Sid110307** [SirVer/ultisnips#1436]
How do I add custom snippets for files without extensions? For example, I have a `Makefile`, Vim recognizes it as `make`. How do I add a custom snippet for that? I tried to use `make.snippets`, but for some reason, it doesn't work.

My `init.lua` (I'm using neovim):
```lua
vim.g['UltiSnipsExpandTrigger'] = "<tab>"
vim.g['UltiSnipsJumpForwardTrigger'] = "<c-]>"
vim.g['UltiSnipsJumpBackwardTrigger'] = "<c-[>"
vim.g['UltiSnipsSnippetDirectories'] = { "UltiSnips", "~/.config/nvim/snippet" }
```

Steps to reproduce:
1. Create a `Makefile`.
1. `:set ft` returns `ft=make` when executed.
1. Create a `make.snippets` file in the snippet directory.
1. Add a snippet in the snippet file.
Example:
```
snippet makec "Makefile Template for C"
CFLAGS=-Wall -Wextra -std=c11 -pedantic
LIBS=$0

${1:targetName}: ${2:sourceFiles}
        mkdir -p bin
        $(CC) $(CFLAGS) -o bin/$@ $< $(LIBS)
        ./bin/$<

clean:
        rm -rf bin/*

endsnippet
```
5. As the snippet is called `makec`, type `makec` in the Makefile.
6. Result is that no completion dropdown appears.

**Comment by SirVer** [comment]
@Sid110307 `:set ft` shows you the filetype that is needed. So make.snippets should work. Please try to reproduce with Vanilla Vim, NeoVim is not officially supported.

**Comment by Sid110307** [comment]
When I type `:set ft` for a makefile, it says ft=make. I have a file called `make.snippets`, that doesn't give the snippets

**Comment by hl037** [comment]
You can also simply try to do `:UltisnipsEdit` to automatically edit the right snippet file

**Comment by SirVer** [comment]
> Please try to reproduce with Vanilla Vim, NeoVim is not officially supported.

Please provide a fully reproducible example, ideally using the approach explained in https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs or if not possible with a minimal `vimrc` and snippets files and an exact sequence of key strokes that trigger the bug.
