### ISSUE TITLE
Error when I insert.

### ISSUE THREAD

**Issue by draftman9** [SirVer/ultisnips#1442]
I will give you the Error Warning by image.
The Warning is:
 Error detected while processing TextChangedI Autocommands for "*"..script C:\Users\Administrator\vimfiles\plugged\ultisnips\autoload\UltiSnips.vim:
line	7:
<string>:1:DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

**Steps to reproduce**
1. Open gvim
2. Open my file like test.md
3. Press "o" to open a new line then the "Error" display.
![2022-02-24_172513](https://user-images.githubusercontent.com/99490289/155499506-f22fefa5-c0de-48e5-8b5b-0b5e1c9da371.png)

And the "Error" just display once. When I press "o" secondly, it works well. BTW, pressing "i" to insert or pressing "a" to append then typing any a char can lead to the same "Error",too.  It confused me a lot...
I did not modify anything about ultisnips.

Operating System: Windows 10
Vim Version: gvim 8.2 (32bit)
UltiSnips Version: https://github.com/SirVer/ultisnips  (just default installed on 2/24/2022)
Python inside Vim: 3.9.10 (32bit)

**Comment by SirVer** [comment]
No idea where that is coming from. UltiSnips is not using the `imp` or the `importlib` module directly. My hunch is that there is a mismatch between the python modules loaded within your Vim and the interpretor it is using. I can guarantee that this is not a UltiSnips bug, but UltiSnips might uncover it.

**Comment by draftman9** [comment]
> No idea where that is coming from. UltiSnips is not using the `imp` or the `importlib` module directly. My hunch is that there is a mismatch between the python modules loaded within your Vim and the interpretor it is using. I can guarantee that this is not a UltiSnips bug, but UltiSnips might uncover it.

Yes I also think it is not coming from UltiSnips' bug because it can work well though it still displays "Error Warning". I added ` let $PYTHONWARNINGS="ignore"` into the first line of vimrc, which ignores the "Warning". Maybe it can be the method of the problem I meeted.

**Comment by SirVer** [comment]
@draftman9 Glad that this is solved for you. I am still very curious where the bug originated from, if somebody can reliably reproduce this, please speak up.
