### ISSUE TITLE
Snippets don't jump from $1 to $# in nvim Lua

### ISSUE THREAD

**Issue by AndresMpa** [SirVer/ultisnips#1451]
I moved to nvim Lua, I'm moving my snippets to Lua... But they don't work

**Expected behavior:**
```
fn<tab>

local function $1()
  $2
end
```

**Actual behavior:**
```
fn<tab>

local function $1()
  -- Nothing here it does not jump
end
```
**Steps to reproduce**
Just type some snippet then tab 

**Reference**
Here is my repo: https://github.com/AndresMpa/nvim-configuration/blob/main/lua/setUp/ultisnipt.lua

-----

- **Operating System**:

Output of `hostnamectl`

 Static hostname: arch
       Icon name: computer-laptop
         Chassis: laptop 💻
Operating System: Arch Linux                      
          Kernel: Linux 5.16.15-zen1-1-zen
    Architecture: x86-64
 Hardware Vendor: HP
  Hardware Model: HP Pavilion Laptop 15-cw0xxx

- **Vim Version**:

NVIM v0.6.1
Build type: Release

- **UltiSnips Version**: 

This commit ca21d30c7a72e0e18ad95f25ded5a5f820052685

**Comment by smjonas** [comment]
I don't think this issue belongs here. You should ask on the [LuaSnip repo](#https://github.com/L3MON4D3/LuaSnip) instead.
