### ISSUE TITLE
Issues with space in snippet

### ISSUE THREAD

**Issue by vikomen** [SirVer/ultisnips#1452]
I would like to have some of my snippets executing only if they are followed by space. A temporary fix is to set my expansion key as space and put these snippets on trigger mode and the others on automatic but I would like a more permanent solution. When using hypersnips on VsCode I had the following snippet

snippet `td ` "to the power" iA
^{$1}$0
endsnippet

**Expected behavior:**
The expected behaviour is that the snippet is executed after I press "t" "d" "space",  to get  ^{$1}$0.

**Actual behavior:**
I get "td ", as if the snippet didn't exist.

**Steps to reproduce**
1)Add the following code to your snippets

snippet `td ` "to the power" iA
^{$1}$0
endsnippet

2) Open a document an press "t" "d" "space"

**Comment by SirVer** [comment]
Should be doable using a regular expression trigger.

**Comment by smjonas** [comment]
Change the snippet to the following:
```snippets
snippet "td " "to the power" riA
^{$1}$0
endsnippet
```
(Notice the `r` option and quotes).

**Comment by vikomen** [comment]
That fixes it!
