### ISSUE TITLE
How to view UltiSnips help in Vim?

### ISSUE THREAD

**Issue by EmilySeville7cfg** [SirVer/ultisnips#1458]
`:help UltiSnips` or `:help UltiSnips.txt` doesn't work. 🤔 I've just cloned this repo under `/home/emilyseville7cfg/.vim/pack/other/start`.

**Comment by SirVer** [comment]
You probably need to run `:helptags`, see `:help helptags`. If you use a plugin manager it should do that work for you.

**Comment by EmilySeville7cfg** [comment]
Thanks! That worked. 😸
