### ISSUE TITLE
feature ask - can we achieve this?

### ISSUE THREAD

**Issue by qixiao986** [SirVer/ultisnips#1459]
**Expected behavior:**
![output](https://user-images.githubusercontent.com/3962171/166613212-6a553a6f-79cc-4eae-9463-16311afdbcfa.gif)

The snippet can take user input, according to the input, the snippet can be generated.

**Comment by SirVer** [comment]
You can get something similar by using a regular expression trigger to parse the parameters and then using tabstop generation as described here: https://github.com/SirVer/ultisnips/tree/master/doc/examples/tabstop-generation. It is probably tedious.
