### ISSUE TITLE
Word boundary not considered for regex snippet trigger

### ISSUE THREAD

**Issue by chemzqm** [SirVer/ultisnips#1461]
**Expected behavior:**

Snippet triggered in word.

**Actual behavior:**

Snippet should not trigger in word when using `w` option.

**Steps to reproduce**

Minimal vimrc:
``` vim
set nocompatible
set runtimepath^=/Users/chemzqm/.vim/bundle/ultisnips
filetype plugin indent on
syntax enable
```

Snippet:
```
snippet '(\w|(\\\w+)+)\.dot' "\dot{...}" rwA
\dot{`!p snip.rv = match.group(1)`}
endsnippet
```
When write `abc.dot` the snippet is expanded as `ab\dot{c}`

**Comment by hl037** [comment]
`w` option is just a sugar to avoid writing a regex. When writing regex, you are in "god mode" (if I'm not mistaking), you should manually add the `\b` : [file:///usr/share/doc/python/html/library/re.html?highlight=re#module-re](https://docs.python.org/3/library/re.html)
