### ISSUE TITLE
Empty lines from snippet get replaced with tabs when expanded on tabbed line

### ISSUE THREAD

**Issue by SingularisArt** [SirVer/ultisnips#1476]
Here's an example environment snippet:

```vim
snippet enum "Enumerate Environment" bAi
\begin{enumerate}
	\label{enum:$1}

	\item ${VISUAL}$2
\end{enumerate}$0
endsnippet
```

But when I expand the snippet on a line that's tabbed in, the empty lines from the snippet are replaced with tabs. Here's an example file after expanding the snippet:

```tex
\begin{document}
  \begin{enumerate}
    \label{enum:}
  
    \item 
  \end{enumerate}
\end{document}
```

As you can see, there's a tab that's replacing the empty line.
How can I get rid of this and just keep the empty lines from the snippet empty without any spaces/tabs?

- **Operating System**: 5.15.53-1 Manjaro
- **Vim Version**: 9.0
- **UltiSnips Version**: 1edcb40ce749c47d5da42ab02dcdf21f9279bfbb
- **Python inside Vim**: python3.10

**Minimal Vimrc**:

```lua
call plug#begin()
  Plug 'SirVer/ultisnips'
  Plug 'lervag/vimtex'
call plug#end()

" make YCM compatible with UltiSnips (using supertab)
let g:ycm_key_list_select_completion = ['<C-j>', '<Down>']
let g:ycm_key_list_previous_completion = ['<C-k>', '<Up>']
let g:SuperTabDefaultCompletionType = '<C-n>'

" better key bindings for UltiSnipsExpandTrigger
let g:UltiSnipsExpandTrigger = "<Enter>"
let g:UltiSnipsJumpForwardTrigger = "<C-j>"
let g:UltiSnipsJumpBackwardTrigger = "<C-k>"

" open the file in a new tab
let g:UltiSnipsEditSplit='tabdo'

" the location of the snippets
let g:UltiSnipsSnippetDirectories=[$HOME."/.vim/UltiSnips", "UltiSnips"]
```

I opened [this](https://github.com/SirVer/ultisnips/issues/1475) issue, but I forgot to mention that it also is a problem on vim.

**Comment by pilgrimlyieu** [comment]
```snippets
snippet enum "Enumerate Environment" bAi
\begin{enumerate}
	\label{enum:$1}`!p snip.reset_indent(); snip.rv = '\n'`
	\item ${VISUAL}$2
\end{enumerate}$0
endsnippet
```

Hope this works.

**Comment by pilgrimlyieu** [comment]
If you want to remove all indentation in the empty line, here is a more efficient solution.

```snippets
snippet enum "Enumerate Environment" bAim
\begin{enumerate}
    \label{enum:$1}

    \item ${VISUAL}$2
\end{enumerate}$0
endsnippet
```

Reference

> ```
>    m   Trim all whitespaces from right side of snippet lines. Useful when
>        snippet contains empty lines which should remain empty after expanding.
>        Without this option empty lines in snippets definition will have
>        indentation too.
> ```
