### ISSUE TITLE
Any way to get lookaheads working?

### ISSUE THREAD

**Issue by alkim0** [SirVer/ultisnips#1481]
This isn't a bug, and more of a question. I was wondering if there was any way to get lookaheads to work in regular expression triggers.

My use case is this. I have as a snippet:
```
snippet $ "Inline Math" A
\$$1\$$0
endsnippet
```
which works pretty well when I'm writing new text.

However, sometimes I want to go back and retroactively put things in math mode.

So, I will have already written in a tex file:
```
My apple
```
but later I decide I want to wrap `apple` in $'s, so I put the cursor over `a`, enter insert mode, then press `$`, and it expands the snippet to:
```
My $$apple
```
which is expected. However, I really only want `$apple` in this case.

Is there a way to achieve this? I tried using regexp triggers such as:
```
snippet '(^|\s)\$(?!\w)' "Inline Math" rA
`!p snip.rv=match.group(1)`\$$1\$$0
endsnippet
```
but that doesn't quite do what I want it to either.

**Comment by SirVer** [comment]
You could try to use a python snippet and inspect the current line. I have not tried that, but this might work:

```
snippet '$$' "Inline Math" rA
`!p
if snip.buffer[snip.line][snip.column:].strip():
    snip.rv = "$"
else:
   snip.rv = "$$`
endsnippet
~~~

**Comment by alkim0** [comment]
Thanks. This exact snippet didn't work out, but pointed me in the right direction. I ended up with:
```
snippet $ "Inline Math" A
\$$1`!p
#if vim.current.line[vim.current.window.cursor[1]:].strip():
if not snip.c:
    (line, column) = vim.current.window.cursor
    if not vim.current.window.buffer[line-1][column:].strip():
       snip.rv = "$"`$0
endsnippet
```
