### ISSUE TITLE
ultisnips not working

### ISSUE THREAD

**Issue by notwidow** [SirVer/ultisnips#1485]
Hi, I just installed ultisnips with vim-snippets and tried to use it but i get the following error whenever i type a single letter in any file using vim. 
```
Error detected while processing InsertCharPre Autocommands for "*"..script /home/user/.vim/plugged/ultisnips/autolo
ad/UltiSnips.vim:                                                                                                   
line    7:                                                                                                          
E319: Sorry, the command is not available in this version: py3 import vim 
```
```
Error detected while processing TextChangedI Autocommands for "*"..function UltiSnips#TrackChange:                  
line    1:                                                                                                          
E319: Sorry, the command is not available in this version:     py3 UltiSnips_Manager._track_change()  
```
**Expected behavior:**
It should popup the snippets when i start typing.

**Actual behavior:**
but my vim is now not usable to use this. When i type a single letter let it be a or i it will show the above error....

**Steps to reproduce**
idk what to write.. just start typing and it won't let you by thses errors.

OS: Kali-linux latest rolling release
vim: 9.0.242

**Comment by bhataktaBhai** [comment]
I am facing the same problem. This was discussed a long time ago in issue #850, but none of the solutions work for me.

**Comment by SirVer** [comment]
@notwidow Your vim is not supporting python 3. Have you installed a version that should support it?

**Comment by notwidow** [comment]
> @notwidow Your vim is not supporting python 3. Have you installed a version that should support it?

haha.. not only python3 but also html and other languages. and for your question so i have all  the latest version. i have mentioned in the issue my vim version is latest . vim: 9.0.354

**Comment by notwidow** [comment]
> @notwidow Your vim is not supporting python 3. Have you installed a version that should support it?

but anyways i migrated to helix-editor... and now helix is my favorite editor.....

**Comment by SirVer** [comment]
@notwidow You misunderstood. Your Vim was not compiled with python support, hence UltiSnips was not working. It does not matter that you can type Python code within the editor. You could have checked by running `:py3 import sys` and see if that throws an error.
