### ISSUE TITLE
 cannot jump from $1 to $2 after using the tab key

### ISSUE THREAD

**Issue by Timemanagerplus** [SirVer/ultisnips#1486]
![image](https://user-images.githubusercontent.com/74964404/188568420-033fa9dd-ca0a-4d90-8eb5-71528f4aa5b5.png)

**Expected behavior:**
I expect that when I press tab, it can jump from 1 to 2

**Actual behavior:**
After pressing tab, exit directly into normal mode.

**Steps to reproduce**

![image](https://user-images.githubusercontent.com/74964404/188568913-b6a94ae0-e38e-4b8a-8b0a-885dc8825597.png)

1.  put "ultisnips" and  "vim-snippets-master" folders into my "~/.vim/pack"
2.
3.

-----

- **Operating System**: centos 7
- **Vim Version**:  vim 8.2
- **UltiSnips Version**: 
- **Python inside Vim**: python3.10
- **Docker repo/vimrc**:

**Comment by FedericoStra** [comment]
According to `:h UltiSnips-trigger-key-mappings`, you cycle through insert points with `CTRL-j` and `CTRL-k` by default, not `TAB`.

**Comment by SirVer** [comment]
I believe, @FedericoStra mentions the correct problem. Does this fix it for you @Timemanagerplus ?
