### ISSUE TITLE
invalid multiword trigger

### ISSUE THREAD

**Issue by cnut1648** [SirVer/ultisnips#1487]
**Expected behavior:**
I have one snippet to add a subscript in latex:
```
def math():
	return vim.eval('vimtex#syntax#in_mathzone()') == '1'

context "math()"
snippet ([a-zA-Z])ii "xi" rwA
`!p snip.rv=match.group(1)`_{i}
endsnippet
```
`math` is just to check if I am in math mode or not. What I intended to do is that when I type `aii` it will be expanded to `a_{i}`, so as `yii`, `lii`, `xii` etc.

But when I type it Ultisnips throws the following error
```
Invalid multiword trigger: '([a-zA-Z])ii'
```
I am not sure why there is an error here. Any help is greatly appreciated! Thanks!

-----

- **Operating System**:  Manjaro
- **Vim Version**:  Neovim 0.8
- **UltiSnips Version**:  latest commit
- **Python inside Vim**:  python 3.10.6

**Comment by SirVer** [comment]
@cnut1648 regex triggers and multiword triggers need to start and end with the same character, so this should work:

```
snippet "([a-zA-Z])ii" "xi" rwA
```

**Comment by cnut1648** [comment]
Hi @SirVer , you are right! This solves my issue. Thanks!
