### ISSUE TITLE
UltiSnips always loads snippets from `snippets` folder even if `g:UltiSnipsSnippetDirectories` is set otherwise

### ISSUE THREAD

**Issue by FedericoStra** [SirVer/ultisnips#1489]
UltiSnips loads snippets located in the `/home/<my-username>/.vim/plugged/vim-snippets/snippets` even if `g:UltiSnipsSnippetDirectories` is configured to look only in `/home/<my-username>/.vim/UltiSnips`.

**Expected behavior:**

Only snippets located in `/home/<my-username>/.vim/UltiSnips` should be active.

**Actual behavior:**

Snippets located under `/home/<my-username>/.vim/plugged/vim-snippets/snippets` are expanded as well.

**Steps to reproduce:**

1. Install `UltiSnips` and `vim-snippets`.

2. Configure UltiSnips to only look in a specific folder, following the instructions from `h UltiSnips-how-snippets-are-loaded`.
   `.vimrc`:
   ```vim
   let g:UltiSnipsSnippetDirectories  = [$HOME.'/.vim/UltiSnips']
   ```
   The folder `~/.vim/UltiSnips` is currently empty, so no snippets should be available.

3. Open a TeX file (or `:set syntax=tex`).
4. On a new line, type `dcl<Tab>`.
5. It will expand to `\documentclass{class}`.

**Explanation:**

The `dcl` is a snippet defined by `vim-snippets` in `snippets/tex.snippets`:

```bash
$ rg 'snippet dcl' ~/.vim
/home/fstra/.vim/plugged/vim-snippets/snippets/tex.snippets
4:snippet dcl \documentclass{}
7:snippet dclo \documentclass[]{}

/home/fstra/.vim/plugged/vim-snippets/snippets/python.snippets
68:snippet dcl dataclass

/home/fstra/.vim/plugged/vim-snippets/UltiSnips/python.snippets
346:snippet dcl "dataclass" b
```

It shouldn't be available though, since UltiSnips has been configured to only look in a single folder.

Moreover, notice that snippets located under `/home/fstra/.vim/plugged/vim-snippets/UltiSnips` are correctly ignored, for instance `beg<Tab>` does not expand to `\begin{...} ... \end{...}`, although it is defined in `/home/fstra/.vim/plugged/vim-snippets/UltiSnips/tex.snippets`.

-----

- **Operating System**: Fedora 35 Workstation Edition
- **Vim Version**: VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Sep 08 2022 00:00:00)
Included patches: 1-412
- **UltiSnips Version**: 4f5249b2a6f6308377cb2bf734974a4e6f8a960e
- **Python inside Vim**: 3.10.6 (main, Aug  2 2022, 00:00:00) [GCC 11.3.1 20220421 (Red Hat 11.3.1-2)]
- **Docker repo/vimrc**: described above

**Comment by FedericoStra** [comment]
After *much* wasted time, I found out about `g:UltiSnipsEnableSnipMate`. I think it should be mentioned in the section `4.1.1 How snippets are loaded` of the help because it can be very confusing.

**Comment by SirVer** [comment]
@FedericoStra A patch would be very welcome how you would have wanted to see it mentioned!
