### ISSUE TITLE
Unnamed variable in docs for "4.1.1 How snippets are loaded"

### ISSUE THREAD

**Issue by joaoandreporto** [SirVer/ultisnips#1493]
On line 555, in the documentation section [4.1.1 How snippets are loaded](https://github.com/SirVer/ultisnips/blob/1914ef242a5b6fc095abc4b2c7702d6697c69324/doc/UltiSnips.txt#L555#L560), it's mentioned that:

> There is an additional variable which does not control the search path for
> snippets at expansion time, but controls where :UltiSnipsEdit is looking for
> snippets. If this variable is set to a single absolute path it will only
> affect where the edit command is looking for and writing snippets too. This is
> useful if you want to use third party snippets, but have all your self created
> snippets in a single place without being asked where to put the file on edit.

Yet, it doesn’t inform how the variable is called.

**Comment by SirVer** [comment]
@joaoandreporto It is called `g:UltiSnipsSnippetStorageDirectoryForUltiSnipsEdit`. Rolls of the tongue.

**Comment by joaoandreporto** [comment]
Mmmm… maki sushi rolls
