### ISSUE TITLE
Suggestion list pops up when pressing tab to expand trigger

### ISSUE THREAD

**Issue by RiccardoBarbieri** [SirVer/ultisnips#1499]
**Expected behavior:**
No popup list appears

**Actual behavior:**
Popup list appears

**Steps to reproduce**
1. Type a character and press <tab>, or the key set to expand a trigger
2. List appears
-----
- **Operating System**: Ubuntu 22.04
- **Vim Version**: NVIM v0.6.1
![temp_screenshot](https://user-images.githubusercontent.com/43068188/196957704-dcf6cbf7-a87d-425a-a895-e253fa7e7f5a.png)

I don't understand if it's an UltiSnips feature or it's some remnant of a past installation of YouCompleteMe (which I deleted thoroughly). If it is UltiSnips, how can I disable that feature?

**Comment by SirVer** [comment]
I do not know what it is, but it is not UltiSnips. It does not contain a completion feature and creates no popups.
