### ISSUE TITLE
vim_interface's has_version() doesn't handle non-contiguous patch ranges properly

### ISSUE THREAD

**Issue by jamessan** [SirVer/ultisnips#1514]
https://github.com/SirVer/ultisnips/blob/e99fdf15cd55a4a8e0cb0a80a6810c1867a5c401/test/vim_interface.py#L92-L97

This errors out with a version like:

```
$ vim --version | grep Included
Included patches: 1-1000, 1087, 1117-1118, 1129
```

```
     _patch = int(line.split(":")[-1].strip().split("-")[-1])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '1118, 1129'
```

The simplistic version checking here also implies the wrong semantics.  A patch is only included if `(_major, _minor) > (major, minor)` or if `patch` is one of the listed patch levels.
Also, checking if the highest patch number is greater than the given patch isn't a valid way to see if a patch is included.  In this example, `has_version(9, 0, 1088)` should return False.

**Comment by SirVer** [comment]
@jamessan Thanks for reporting this. Are you interested in crafting a patch?

**Comment by jamessan** [comment]
I'm not familiar with the code, so no.  I was just forwarding the issue from Debian.
