### ISSUE TITLE
i_ctrl-i

### ISSUE THREAD

**Issue by aloispichler** [SirVer/ultisnips#1515]
What is ultisnips doing with `i_Ctrl-i`???
With ultisnups plugged in, I cannot
`inoremap <C-i> <nop>`.
The docs don't say a word about `i_Ctrl-i`.
Thanks!

**Comment by SirVer** [comment]
Duplicate of #1212. tl;dr: Terminal emulators make no difference between `<tab>` and `<ctrl-i>`, it is the same to them. This has nothing to do with UltiSnips.
