### ISSUE TITLE
Clarification on `!b` and `b!`

### ISSUE THREAD

**Issue by frankjonen** [SirVer/ultisnips#1525]
What exactly are these?

They show up in the YouTube tutorial in two places.

https://youtu.be/hKrrOevbrxY?t=181 and https://youtu.be/JJQYwt6Diro?t=138

The help file has nothing on these. Any ideas?

**Comment by SirVer** [comment]
They are outdated and have been replaced with the priority statement. They used to overwrite existing snippets with the same trigger. Am 02.03.2023 um 03:21 schrieb Frank Jonen ***@***.***>:﻿
What exactly are these?
They show up in the YouTube tutorial in two places.
https://youtu.be/hKrrOevbrxY?t=181 and https://youtu.be/JJQYwt6Diro?t=138
The help file has nothing on these. Any ideas?

**Comment by frankjonen** [comment]
Thanks for the clarification.
