### ISSUE TITLE
multi-word triggers

### ISSUE THREAD

**Issue by aloispichler** [SirVer/ultisnips#1530]
This is rather a question, which I could not figure out based on the docs.
Suppose the snippet (in an example from LaTeX) is `\includegraphics`.
I'd like to expand the snipped upon typing `\includeg',` or `'includegraphics` or any word in between.
How can that be accomplished with Ultisnips?

**Comment by SirVer** [comment]
You need to use a regular expression trigger that matches the partial trigger word for the moment. There was a feature request for this, but I could not find it right now.

**Comment by aloispichler** [comment]
Would you mind sharing the regular expression which does the job?

**Comment by SirVer** [comment]
This one maybe:

```
snippet "\\includegr.*" "Description" r
\includegraphics{
endsnippet
```
