### ISSUE TITLE
just installed Ultisnips and got this error

### ISSUE THREAD

**Issue by santiago-aghemo** [SirVer/ultisnips#1544]
After i installed the pluggin, i entered a file, then enter insert mode and tryed to type something, but i got this error 
![image](https://github.com/SirVer/ultisnips/assets/106884348/57391e40-a119-4430-b317-0b0c04b6fcb3)

when i run :py import sys; print(sys.version) i get "python library could not be loaded"

pls help

-----

- **Operating System**: Windows 10
- **Vim Version**: gVim 9.0 
- **UltiSnips Version**: 3.1
- **Python inside Vim**: 
- **Docker repo/vimrc**:

**Comment by SirVer** [comment]
This is a problem in how your Vim is compiled/trying to find Python. This might help:

https://github.com/SirVer/ultisnips/issues/1522
