### ISSUE TITLE
[Feature Request] Subfolder in `filetype` snippets folder & Specific `extends` and `excludes`

### ISSUE THREAD

**Issue by pilgrimlyieu** [SirVer/ultisnips#1547]
**Expected behavior:**

I would like to classify for my snippets. For example, I will have some snippets in `basic.snippets` for basic `markdown`syntax, some snippets with different types for math syntax, and some snippets for specific cases. And my expected structure is like below.

```
markdown
  ├─math
  │  ├─layout
  │  │  ├─annotation.snippets
  │  │  └─spacing.snippets
  │  ├─operators
  │  │  ├─big-operators.snippets
  │  │  └─binary-operators.snippets
  │  └─katex
  │     ├─a.snippets
  │     └─b.snippets
  ├─cases
  │  ├─changelog.snippets
  │  └─blog.snippets
  └─basic.snippets
```

And I would like to use math snippets in `tex` filetype, and I hope we could have a way likes below to achieve this.

```snippets
extends markdown/math
```

Furthermore, the sub folder `katex` may not work in `tex` and I prefer to exclude them from `markdown/math`, so I have a preference to use

```snippets
extends markdown/math
excludes markdown/math/katex
```

For specific snippets file

```snippets
extends markdown/basic.snippets
```

I've read the documentation and searched the Internet, finding this seems haven't been achieved. As a result, I open this issue to make a feature request. Thanks anyway in advance!

**Actual behavior:**

**Steps to reproduce**

1.
2.
3.

-----

- **Operating System**: 
- **Vim Version**: 
- **UltiSnips Version**: 
- **Python inside Vim**: 
- **Docker repo/vimrc**:

**Comment by SirVer** [comment]
Excludes is really, really hard to get right I think. Extends is already supported, however it works on filetype basis and not on snippet files basis. Are you [familiar with dotted filetypes](https://vi.stackexchange.com/questions/4940/where-are-vim-compound-dotted-filetypes-documented)? I use them all the time to extend the scope of my snippets and pull others in. So for example, you could have a filetype `markdown_katex` with corresponding snippets and if you want to use it in a markdown file, you simply define the filetype to be `markdown.markdown_katex`. Would that help you some?

**Comment by pilgrimlyieu** [comment]
> Excludes is really, really hard to get right I think. Extends is already supported, however it works on filetype basis and not on snippet files basis. Are you [familiar with dotted filetypes](https://vi.stackexchange.com/questions/4940/where-are-vim-compound-dotted-filetypes-documented)? I use them all the time to extend the scope of my snippets and pull others in. So for example, you could have a filetype `markdown_katex` with corresponding snippets and if you want to use it in a markdown file, you simply define the filetype to be `markdown.markdown_katex`. Would that help you some?

Thanks. I have a basic understanding of dotted filetypes. I've tried to avoid using it before since I thought it seemed to mess up the filetype, and was inconvenient to change(That means, I have to change original filetype `markdown` to something likes `markdown.math`). However, I'll look into this feature and have a try. Thanks!
