### ISSUE TITLE
Vim LaTeX Suite interferes with UltiSnips <C-j> <C-k> bindings

### ISSUE THREAD

**Issue by SirVer** [SirVer/ultisnips#170]
Vim LaTeX suite (vim-latex) (http://vim-latex.sourceforge.net/) provides handy utilities for working with LaTeX documents. Unfortunately when it is installed as a plugin along with UltiSnips, it completely ruins the mappings of <C-j> (Control + J) and <C-k> (Control + K) such that the user can no longer jump forward and backward in a snippet. Curiously, this happens for all file types, not just .tex files. I have no idea why this happens but I'm hoping someone familiar with UltiSnips internals would be able to test this and have some idea.

Steps to reproduce:
1) Install UltiSnips and vim-latex plugins using a plugin manager, such as vim-addon-manager or Vundle
2) Open a file of prefered type in Vim (e.g., "vim foo.py")
3) Start using a snippet with placeholders (e.g., type "def<Tab>")
4) Try to jump to the next placeholder with <C-j>; observe the cursor does not advance

Launchpad Details: [#LP944215](https://bugs.launchpad.net/bugs/944215) Chris Lasher - 2012-03-01 19:24:21 +0100

**Comment by bongbang** [comment]
I'm having the same problem (in .tex files only) but I don't understand your last proposed solution ("brand new feature").  The new default you mentioned apparently didn't quite do it because the problem persists despite the latest version of UltiSnip I installed.
