### ISSUE TITLE
list_snippets does not show potential regex defined snippet

### ISSUE THREAD

**Issue by SirVer** [SirVer/ultisnips#177]
## For example, if I have the following snippet. type `u` and hit  `<C-tab>` will not show the following snippet as possible match.

global !p
def upper_right(inp):
    return (75 - 2 \* len(inp))*' ' + inp.upper()
endglobal

snippet /upper_right|ur/ "text ... TEXT" r
${1:Text}`!p snip.rv = upper_right(t[1])`
$0
endsnippet

Launchpad Details: [#LP1171276](https://bugs.launchpad.net/bugs/1171276) Zhao Cai - 2013-04-22 03:33:23 +0200

**Comment by SirVer** [comment]
https://github.com/SirVer/ultisnips/issues/479 reported this for inword snippets. This might be fixable rigt now - only regular expression snippets are hard to fix without partial regexp support in python.

**Comment by uberbrodt** [comment]
What's the status on this one? Just ran into it while defining a new snippet with `br`.

**Comment by SirVer** [comment]
As long as python's standard library regex support does not add support for partial matches this one cannot be implemented. Closing as non-actionable.
