### ISSUE TITLE
Variables in the status bar

### ISSUE THREAD

**Issue by SirVer** [SirVer/ultisnips#182]
Hi Holger,

I'd like to have the option to insert one or more variables into the status bar to let the user know at which position (jump mark) he currently is. Eventually with the current snippet name inside.

E.g.: <snippetName> Field: <curPosition> of: <maxPositions>

It would be nice to clear the whole string when the last jump mark is reached so we only have this visual "guide" when we are inside a current snippet.

All variables should be optional, e.g. if somebody doesn't want to see the name of the snippet he just omits that variable.

Regards,
Ulf

Launchpad Details: [#LP931366](https://bugs.launchpad.net/bugs/931366) Ulf Kohlmorgen - 2012-02-13 12:06:00 +0100

**Comment by m-kru** [comment]
@SirVer what is the best way to have some kind of status for UltiSnips?
