### ISSUE TITLE
UltiSnips Supertab integration mysteriously stopped working

### ISSUE THREAD

**Issue by vaibhavsagar** [SirVer/ultisnips#212]
Hi,

UltiSnips has mysteriously stopped working for me. Opening a new file and typing "box<Tab>" gives me the message "Pattern not found". My vimrc is [here](https://github.com/vaibhavsagar/dotfiles/blob/master/vimrc) and I haven't been able to pinpoint the issue. I've tried commenting out my UltiSnips config options to no avail. I use Python 3 on Windows and I would really appreciate some guidance. Thanks!

**Comment by mooreniemi** [comment]
for future googlers, I encountered this issue and fixed it by updating my plugins too.
