### ISSUE TITLE
Several errors after update

### ISSUE THREAD

**Issue by lervag** [SirVer/ultisnips#214]
After an update to most recent version of Ultisnips today, I get several errors when I start vim and ultisnips is loaded. This is a critical issue, and I have to deactivate Ultisnips until this is fixed.

```
Error detected while processing /home/lervag/.vim/bundle/ultisnips/plugin/UltiSnip
s.vim:
line   53:
E117: Unknown function: UltiSnips#map_keys#MapKeys
Error detected while processing /home/lervag/.vim/bundle/ultisnips/after/plugin/Ul
tiSnips_after.vim:
line   11:
E117: Unknown function: UltiSnips#map_keys#MapKeys
Error detected while processing /home/lervag/.vim/bundle/ultisnips/autoload/UltiSn
ips.vim:
line  179:
Traceback (most recent call last):
Error detected while processing /home/lervag/.vim/bundle/ultisnips/autoload/UltiSn
ips.vim:
line  179:
  File "<string>", line 1, in <module>
Error detected while processing /home/lervag/.vim/bundle/ultisnips/autoload/UltiSn
ips.vim:
line  179:
  File "/home/lervag/.vim/bundle/ultisnips/pythonx/UltiSnips/__init__.py", line 13
, in <module>
Error detected while processing /home/lervag/.vim/bundle/ultisnips/autoload/UltiSn
ips.vim:
line  179:
    vim.eval('g:UltiSnipsExpandTrigger'),
Error detected while processing /home/lervag/.vim/bundle/ultisnips/autoload/UltiSn
ips.vim:
line  179:
vim.error: Vim:E121: Undefined variable: g:UltiSnipsExpandTrigger
Error detected while processing function UltiSnips#CursorMoved:
line    1:
Traceback (most recent call last):
Error detected while processing function UltiSnips#CursorMoved:
line    1:
  File "<string>", line 1, in <module>
Error detected while processing function UltiSnips#CursorMoved:
line    1:
NameError: name 'UltiSnips_Manager' is not defined
```

**Comment by lacombar** [comment]
This seems to be broken for me as well with the latest git... :-(

**Comment by SirVer** [comment]
@lacombar if your problem persists, please consider opening a new bug report - this one is ancient, it is unlikely that you have the same issues.

**Comment by sebastianvera** [comment]
I'm getting a similar error when opening any file with `--noplugin` flag:

```
Error detected while processing FileType Auto commands for "*":
E117: Unknown function: UltiSnips#FileTypeChanged
```

**Comment by SirVer** [comment]
@sebastianvera I cannot reproduce that. The latest version should also not set any autocommands when `--noplugin` is used. Which SHA are you on?

**Comment by sebastianvera** [comment]
@SirVer I'm using this SHA `67fbdb2`. I'm not sure what do you refer with the commandline that I'm using, but I realized that when I run `vim --noplugin foo.rb` I get the error, but if the file has no extension `vim --noplugin foo` I get no errors.

**Comment by SirVer** [comment]
@sebastianvera The secret sauce was the `foo.rb` - I only tried without a filename and could not reproduce. Should be fixed.

**Comment by vonpupp** [comment]
Hello,

I am having the same problem:

    Error detected while processing FileType Auto commands for "*":
    E117: Unknown function: UltiSnips#FileTypeChanged

I installed using vundle with the following config:

    Bundle 'SirVer/ultisnips'
    
    " Trigger configuration. Do not use <tab> if you use https://github.com/Valloric/YouCompleteMe.
    let g:UltiSnipsExpandTrigger="<tab>"
    let g:UltiSnipsJumpForwardTrigger="<c-b>"
    let g:UltiSnipsJumpBackwardTrigger="<c-z>"
    
    " If you want :UltiSnipsEdit to split your window.
    let g:UltiSnipsEditSplit="vertical"

I am using Arch Linux. Any idea?

Thank you.

**Comment by jerome-diver** [comment]
@vonpupp it is late (one year and more after) but, i had the same problem as long as i not understand (by myself, because nothing is indicate on the document... or i not see that) i have to:
`set filetype=on`
inside ~/.vimrc file
and also, after installed vim-snippets (i use vim-Plug manager), indicate option
`let g:UltiSnipsSnippetDirectories=["~/.vim/plugins/vim-snippets/snippets","~/.vim/plugins/vim-snippets/UltiSnips"]
`
where actually is my .snippets files from vim-snippets installed from.
