### ISSUE TITLE
Commit fe7cb4cf breaks on linux Vim/gVim

### ISSUE THREAD

**Issue by mMontu** [SirVer/ultisnips#239]
The latest version doesn't work under linux Vim/gVim:

![error](https://f.cloud.github.com/assets/1397534/2386018/30251798-a926-11e3-8d49-96d7bcf31e40.png)

Testing the previous commits shows that this error was introduced by fe7cb4cf, as it works fine with 6b8bb1b64.

Additional information:
- Vim 7.4
- Python:
  
  :py import sys; print(sys.version)
  2.7.5+ (default, Sep 19 2013, 13:52:09) 
  [GCC 4.8.1]
- OS - Linux Mint 16 Petra:
  
  $ uname -a
  Linux mmontu 3.11.0-12-generic #19-Ubuntu SMP Wed Oct 9 16:20:46 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

Any ideas?

**Comment by luozhaoyu** [comment]
I met the same error with version **3001566**, I am using RHEL 6.4 workstation. Pre-installed python2.6 and compiled python3.4 in `/usr/local/`

I solved the problem by compiling vim 7.4 with
`./configure --enable-pythoninterp --enable-python3interp` missing enable-pythoninterp would not allow it to work.
