### ISSUE TITLE
Feature request: Highlight unvisited tabstops

### ISSUE THREAD

**Issue by noahfrederick** [SirVer/ultisnips#242]
I've been using UltiSnips for about a year now (coming from [XPTemplate](https://github.com/drmingdrmer/xptemplate)), and I still find the process of using snippets to be disorienting, specifically judging my progress filling out the tabstops. Others have suggested making a status line function available for displaying your position in the snippet, but I don't think that's a very elegant solution.

Better would be to highlight each unvisited placeholder, as XPTemplate does. That gives you a very clear idea of which tabstops still need to be visited and keeps your eyes on the snippet rather than the bottom of the screen.

I'm not familiar at all with UltiSnips's codebase. Is this feasible?

**Comment by SirVer** [comment]
I am not interested in working on that and it seems other are also not. setting to wontfix for now.

**Comment by noahfrederick** [comment]
Okay. I have no immediate plans to pick this up again.
