### ISSUE TITLE
ImportError: No module named UltiSnips

### ISSUE THREAD

**Issue by msloan** [SirVer/ultisnips#244]
I get the following error whenever I try to start vim after installing UltiSnips via vundle:

Error detected while processing function UltiSnips#bootstrap#Bootstrap:
line 35:
Traceback (most recent call last):
 File "<string>", line 1, in <module>
ImportError: No module named Ultisnips

UltiSnips at one point in the past worked fine for me. Not sure what changed that is causing this error.

It seems that UltiSnips is the only plugin I have that uses the {rtp}/pythonx import mechanism. Any ideas on why this would fail?

I've tried re-installing python (2.7.5, only version on machine) and vim 7.4 with only vundle and UltiSnips plugins - same issue.

Help! I miss my snippets :(

**Comment by SirVer** [comment]
Could you post the backtrace of the error? I am super confused by this bug.

**Comment by smancill** [comment]
I am sorry, I found that my problem was the same as @SergioBenitez, I had a symlinked `.vim` directory to a mounted shared folder. Moving `.vim` to the VM local filesystem solved the issue.

But, fe7cb4cf8d6fd2a66058f001b14fe737a0fb6560 introduced the problem. I can have the Vim directory symlinked to a shared folder if I checkout its parent (6b8bb1b642a9941f75e71c78c58fa3c7c73595a6).

Anyway, it's solved if I keep everything in the local file system, without needing to checkout an old commit.

**Comment by hushicai** [comment]
The same problem to me. python 2.7.11 not wok, but when i downgrade to 2.7.6, everything is ok now.
