### ISSUE TITLE
JS snippets in HTML file

### ISSUE THREAD

**Issue by nobleach** [SirVer/ultisnips#247]
If a file is designated an HTML file, my JS snippets are not available. Is this the default behavior?

**Comment by dominikduda** [comment]
This is not working for me anymore, did the implementation change since OP asked the question?

**Comment by xavierartot** [comment]
@SirVer As React developer we're using JSX, Javascript and CSS in the same file.
How can I import my CSS file snippet in my React Snippet?

**Comment by SirVer** [comment]
@xavierartot Same as before. Either use [UltiSnipsAddFiletype](https://github.com/SirVer/ultisnips/blob/6fdc3647f72e0a1f321ea6bd092ecd01f7c187ba/doc/UltiSnips.txt#L252), i.e. `UltiSnipsAddFiletype css` or use [`extends`](https://github.com/SirVer/ultisnips/blob/6fdc3647f72e0a1f321ea6bd092ecd01f7c187ba/doc/UltiSnips.txt#L593) in your snippets.
