### ISSUE TITLE
Indentation with some snippets

### ISSUE THREAD

**Issue by whatyouhide** [SirVer/ultisnips#258]
I have `set tabstop=2` in my `vimrc`. Using some snippets from `vim-snippets` (for example the `if` snippet), the lines in the `if` block are indented at column 8.

Is it normal? Should I look for a solution on the `vim-snippets` side or the UltiSnips one?

**Comment by subhojit777** [comment]
I had block indentation mapping enabled

```
vmap <tab> :><CR>gv
vmap <S-tab> :<<CR>gv
```

And this was conflicting with `<tab>` trigger of Ultisnips. Commenting out `shiftwidth` fixed the issue. Thanks.
