### ISSUE TITLE
Feature request: add support for redo/repeat of snippet actions

### ISSUE THREAD

**Issue by stephentalley** [SirVer/ultisnips#259]
UltiSnips is an absolutely great plugin, but lacks one feature I'd love to see.

If I enter insert mode, type a snippet trigger, expand it, then exit insert mode, I would expect "." (redo) to add the same text.  Currently hitting "." just outputs the trigger text.

The vim-repeat plugin (https://github.com/tpope/vim-repeat) might facilitate the implementation of this feature significantly.  Several other plugins currently employ vim-repeat for that purpose.

Thanks for all the work on this fantastic plugin!

**Comment by leandrochiarini** [comment]
Would it be possible to make an option of whether one terminates the snippet if that meant snippets become repeatable?

My use case comes from latex for articles in mathematics, much like G. Castel's blog post. Specially on early stages of writing an article, I find it useful to write as many steps of the equations as possible. I usually copy the last line of equations (via a custom text object) and apply one change in the line. Often, this one step is in fact the same operation applied on multiple parcels of the last line (for instance a change of variable). 

Even though I have been using Ultisnips for almost over a year,  I often change one such parcel, then move to the next and try to use the dot command. I would find the repeatability a major improvement.

I fully understand that the use case might be rather specific, but I think it is useful to share.
