### ISSUE TITLE
Breaks vim-7.4.237 after installiations (older Linux machine)

### ISSUE THREAD

**Issue by insidewhy** [SirVer/ultisnips#260]
This is using vim-7.4.237:

```
Error detected while processing function UltiSnips#bootstrap#Bootstrap:
line   35:
Traceback (most recent call last):
  File "<string>", line 1, in ?
ImportError: No module named UltiSnips
```

On other machines using the same vim version it works fine, but not on Centos5.

All copies of vim were compiled the exact same way to use the python 2.7 interpreter.

**Comment by sbromberger** [comment]
FWIW, I'm having a similar problem on OSX with homebrew versions of python and vim installed. I'm not quite sure how to fix it.
