### ISSUE TITLE
UltiSnips not working 'by default'

### ISSUE THREAD

**Issue by jillesme** [SirVer/ultisnips#264]
I'll try to describe the problem as good as possible. First of all, my ultisnips settings in my .vimrc. I am also using YCM.

```
let g:UltiSnipsExpandTrigger="<c-tab>"
let g:UltiSnipsListSnippets="<c-l>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"
```

When I open macvim from terminal, ie: example.php my custom php snippets won't get loaded.

When I type ph [for php] I DO get an Apache snippet pop up, but none of my php snippets.

Now, I do 

```
:UltiSnipsAddFiletypes php  
```

Still, nothing.. Now I do

```
:UltiSnipsEdit     
```

There we go, my custom php.snippets file opens in a new buffer. Now when I :w and :bd and go back to my example.php, all php snippets work! 

I have to do this every single time to get my snippets working, am I missing something? I've read the docs but I can't find a solution to my problem

( Here, a video to illustrate my problem https://www.youtube.com/watch?v=sXFIeERydTQ )

**Comment by matsko** [comment]
I was having the same issue, but it turned out that neovim was loading the snippets from `~/.nvim/UltiSnips` instead of from the `.vim` directory (where I had them saved). Placing a symlink for `.vim` to `.nvim` fixed the issue.

**Comment by mjacobus** [comment]
Thanks @matsko ! That solved my problem =)

**Comment by hatelove85911** [comment]
Ok, I finally find out the root cause of my problem: ftdetect issue.
In my case it's due to I'm using Vundle as Plugin manager.

If anybody using Vundle installed Ultisnips and having the same problem here. Please refer to the solution link below.
After apply gmarik's configuration to vimrc. Everything works fine!

https://github.com/VundleVim/Vundle.vim/issues/16

**Comment by WscriChy** [comment]
I still have the same problem (that type detection do not work)I do not use any packet managers.

The loaded scripts are

     81: ~/Vim/Plugins/UltiSnips/Plugin/plugin/UltiSnips.vim
     82: ~/Vim/Plugins/UltiSnips/Plugin/autoload/UltiSnips/map_keys.vim
     95: ~/Vim/Plugins/UltiSnips/Plugin/after/plugin/UltiSnips_after.vim

**Comment by WscriChy** [comment]
When the type detection do not work use this

    filetype off
    filetype on

In the case of UltiSnips this brings in addition to the scripts above

     13: ~/Vim/Plugins/UltiSnips/Plugin/ftdetect/UltiSnips.vim
     14: ~/Vim/Plugins/UltiSnips/Plugin/ftdetect/snippets.vim

I do not why is that, but really curious, can somebody explain. Why do I need explicitly off, then on to make vim to load scripts from ftdetect directory?

**Comment by SirVer** [comment]
Because Vim's defaults of when/what is loaded is really not intuitive. Do yourself a favor and get a packet manager - then stick to it's minimal vimrc and go from there.

**Comment by craftgear** [comment]
Mind you, I found another reason to prevent Ultisnips from working.
If you use vim-autosession plugin, try to remove .vim_auto_ses file from your project directories.

I switched vim-autosession to xolox/vim-session after I found this.

**Comment by ponelat** [comment]
I had a similar problem, where I could load the snippets file with `:UltiSnipsEdit`, but my snippets weren't working ( only the ones provided by vim-snippets).
My particular problem, was  _not_ adding my snippets dir to the runtime. After that, all worked well.

```vimscript 
set rtp+=~/my/other/.vim

"...
let g:UltiSnipsSnippetsDir = "~/project/dotfiles/.vim/snips"
let g:UltiSnipsSnippetDirectories=["UltiSnips", "snips"]
let g:UltiSnipsEditSplit= "context"
```

Hope it helps

**Comment by rcdosado** [comment]
correct me if i'm wrong is it correct to assume that `g:UltiSnipsSnippetsDir` equals to the parent directory of your "snippet folders"? and `g:UltiSnipsSnippetDirectories` contains other directories relative to the former variable that contains snippets files?cause setting them accordingly solves this problem for me. thanks

**Comment by sureshsaragadam** [comment]
" YouCompleteMe and UltiSnips compatibility, with the helper of supertab
" (via http://stackoverflow.com/a/22253548/1626737)
let g:SuperTabDefaultCompletionType    = '<C-n>'
let g:SuperTabCrMapping                = 0
let g:UltiSnipsExpandTrigger           = '<tab>'
let g:UltiSnipsJumpForwardTrigger      = '<tab>'
let g:UltiSnipsJumpBackwardTrigger     = '<s-tab>'
let g:ycm_key_list_select_completion   = ['<C-j>', '<C-n>', '<Down>']
let g:ycm_key_list_previous_completion = ['<C-k>', '<C-p>', '<Up>']
