### ISSUE TITLE
Expand snippet if currently typed prefix uniquely identifies it

### ISSUE THREAD

**Issue by majutsushi** [SirVer/ultisnips#268]
It would be handy if a snippet would be expanded if the text before the cursor uniquely identifies one. For example, say I have a snippet named `function` that expands to a Vim function I would only have to type `fun<Tab>` (or even just `f<Tab>`) to expand it, provided there are no other snippets that have the same prefix. Of course I could just name the snippet `f` (like several of the provided snippets do), but that has some drawbacks:

- It is rather cryptic, which makes it harder to remember
- You probably won't see it in the YCM autocompletion list due to only being one character long
- It won't work if you type for example `fun<Tab>`, which would be a natural thing to try when writing a Vim function and remembering midway through typing `function` that there was a snippet for that.

**Comment by SirVer** [comment]
closed for inactivity. Now there are also completers that are better suited for this kind of option.
