### ISSUE TITLE
Jump to next tabstop when deleting current one

### ISSUE THREAD

**Issue by janlarres** [SirVer/ultisnips#269]
When deleting the current tabstop with `<BS>` it would be useful if the cursor then jumped to the next one, since removing the tabstop usually means that there's nothing to do at this position any more. I tried accomplishing that with this mapping:

```
snoremap <BS> <C-g>c<C-R>=UltiSnips#JumpForwards()<cr>
```

But this doesn't quite work and seems to confuse UltiSnips.

**Comment by majutsushi** [comment]
Bram just added a new patch to Vim that may finally make this possible:
https://groups.google.com/forum/?fromgroups#!topic/vim_dev/qxf0yYZu52Y
