### ISSUE TITLE
UltiSnips doesn't load ~/.vim/bundle/vim-snippets/UltiSnips

### ISSUE THREAD

**Issue by johntyree** [SirVer/ultisnips#277]
I have `honza/vim-snippets`, `valloric/youcompleteme`, and `sirver/ultisnips` installed, all via `Vundle`. I have confirmed that `~/.vim/bundle/vim-snippets/UltiSnips` exists and is populated with snippets. I know YCM is working because semantic completion in Python and C are both fine. YCM's option `g:ycm_use_ultisnips_completer = 1` is set.

If I open a blank file and type `lorem<c-j>`, it expands the Lorem Ipsum snippet. In fact, all of the snippets from `all.snippets` seem to work, although they never show in the completion list. No other snippets work or show up in the completion list.

What can I do to start troubleshooting this?

```
    Bundle "honza/vim-snippets"
    Bundle 'SirVer/ultisnips'
    let g:UltiSnipsExpandTrigger = '<C-j>'
    let g:UltiSnipsJumpForwardTrigger = '<C-j>'
    let g:UltiSnipsJumpBackwardTrigger = '<C-k>'
    let g:UltiSnipsEditSplit="vertical"
```

**Comment by ikhos** [comment]
Hi, sorry to dig a a thread but I'm having this trouble too, I don't seem to find any symlink, could you tell me what files were supposed to be symlinked please?

**Comment by ikhos** [comment]
Nevermind, I found that I had some leftover files from snipMate, I deleted everything and now UltiSnips works.

**Comment by sfinktah** [comment]
Hmmm, looking at the OP's question, I am struck by the invalidity of the first line, `"` is not a quote, it's a comment indicator, and ergo that line wouldn't load, and no snippets would be loaded.

    Bundle "honza/vim-snippets"

**Comment by johntyree** [comment]
That's not actually true, unfortunately. Vim tries to be smart about it and
will treat "this" like a string in some cases.

**Comment by sfinktah** [comment]
It was certainly true when I pasted it in 3 hours ago.

    Error detected while processing /root/.vimrc:
    line   71:
    E471: Argument required: Plugin
    Press ENTER or type command to continue

    VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 31 2015 23:35:48)
    Included patches: 1-488, 576

**Comment by SirVer** [comment]
> don't work that well together, or even apart.

that was kinda unasked for.

Do you know this [SO post](http://stackoverflow.com/a/18685821/200945). Most people are happy with that configuration. I for myself just use a different trigger for ycm and ultisnips and I use it daily, for all my coding.

**Comment by sfinktah** [comment]
Oh dude, I've watched your videos, you are a master of productivity with Ultisnips. In fact, it was watching those, that convinced me YCM could never integrate without slowing down (both in time and number of keystrokes) the ultisnips process.

And yes, I've tried every known method of combining then, including trying to keep them as separate as possible.  Best results (which are not that great) were achieved with <c-y> mapped purely to expand (but still takes far too long to select the ultisnip from the YCM list,   which doesn't prioritise ultisnips to the top of the list).

I also have F6 mapped to list all ultisnips, from which I pick by number.  That can often be quicker.

An annoyance that I hope I can fix is this:
  
    snippet .attr "setAttribute(k,v)"
    .setAttribute('$1', $2)
    endsnippet

The problem being that the '.' doesn't qualify as a word separator, and thus won't trigger when used like so:   element*.attr*

Hoping there is an easy fix.

**Comment by SirVer** [comment]
yes, you can use a regular expression trigger: `snippet /\.attr/ "..." r` should work, but I have not tested it right now.

**Comment by sfinktah** [comment]
that would be awesome....  

this worked:

    snippet /\.e/ ".forEach(v,k..)" r
    .forEach (value, index, array) ->
    endsnippet


this didn't:
    snippet /\(\w\+\)\.ea/ "_.each(..)" r
    _.each(\1, function(value, key) {
    $1
    }

it didn't even get recognised as a snippet - what form of regex is it expect?   i wasn't expecting the sub-pattern replacement to work, although that would obviously be awesome.

**Comment by SirVer** [comment]
All your questions are answered in the docs. This works:

```
snippet /(\w+)\.ea/ "_.each(..)" r
_.each(`!p snip.rv = match.group(1)`, function(value, key) {
	$1
}
endsnippet
```

If you still have issues, please open a new issue. We already derailed this discussion rather far.

**Comment by wanchaol** [comment]
I have the problem that UltiSnips doesn't load ~/.vim/bundle/vim-snippets/UltiSnips, instead it only load the  ~/.vim/bundle/vim-snippets/snippets, could anyone tell me how to fix it?

**Comment by seletskiy** [comment]
@wanchaol: Can you open separate issue and describe your issue profoundly?

Also, try the workaround proposed in https://github.com/SirVer/ultisnips/issues/711

**Comment by wanchaol** [comment]
@seletskiy Thanks I found the problem, it's about the snippets, not about the engine.
