### ISSUE TITLE
Lazy loading Ultisnips and custom snippets

### ISSUE THREAD

**Issue by pgilad** [SirVer/ultisnips#280]
Hi, I'm using NeoBundle to lazy load Ultisnips and Vim-Snippets in the following way:

``` vim
NeoBundle 'honza/vim-snippets', {
            \ 'lazy': 1,
            \ 'autoload' : {
            \    'on_source': ['ultisnips']
            \  }
            \ }
NeoBundle 'SirVer/ultisnips', {
            \ 'depends': ['vim-snippets'],
            \ 'lazy': 1,
            \ 'autoload' : {
            \    'insert': 1
            \  }
            \ }
```

My intention is obviously to load Ultisnips only when going into insert mode, and then loading vim-snippets.

This works great the for supplied snippets in `honza/vim-snippets` but only after I re-open the current buffer, or edit a different buffer I can use my custom snippets.

My custom snippets work great alongside the factory snippets if I don't lazy load Ultisnips. They are defined like so:

``` vim
set runtimepath+=~/.dotfiles
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<s-tab>"
let g:UltiSnipsSnippetsDir='~/.dotfiles/mysnippets'
let g:UltiSnipsSnippetDirectories=['UltiSnips', 'mysnippets']
```

Any help on how to successfully lazy load both plugins and have them work the second I enter insert mode in the same buffer?

**Comment by kshenoy** [comment]
@pgilad Thanks! I was looking for something similar. Do you know if it's possible to enhance this by loading only when UltiSnips is triggered and not just enter insert mode?

**Comment by pgilad** [comment]
Depends on what you mean by **UltiSnips is triggered**

**Comment by kshenoy** [comment]
I mean, when you press `<Tab>` in insert mode i.e. when the `UltiSnips#ExpandSnippetOrJump()` is called.

**Comment by pgilad** [comment]
Yeah it's definitely possible. I would look into NeoBundle `functions` or `function_prefix` for autoload. (https://github.com/Shougo/neobundle.vim/blob/0b44247d063838e7709aeb225727020080cdc454/doc/neobundle.txt#L1051)
