### ISSUE TITLE
Identify snippets by UUID for other plugins instead of by trigger

### ISSUE THREAD

**Issue by hushicai** [SirVer/ultisnips#285]
I use ultisnips with YCM. 

I get a completion menu when i type something:

![image](https://cloud.githubusercontent.com/assets/1249423/2754708/d7bbed70-c95a-11e3-9e92-cf121380a86d.png)

And hit `<tab>` to select a snip, then i want to expand the selected snips with `<c-j>`, it behaves like this:

![image](https://cloud.githubusercontent.com/assets/1249423/2754723/1284d746-c95b-11e3-83cd-caff62c698f0.png)

I have to type a number again to expand the snips, i feel a little troublesome!

I wonder why it can't expand immediately when i type `<c-j>`？Does it mean that using `<tab>` to select a snippet is useless when a trigger matches multiple snippets?

**Comment by SirVer** [comment]
Closing this for more discussion in #521.
