### ISSUE TITLE
UltisnipsEdit doesn't go to the defined directory

### ISSUE THREAD

**Issue by Thanatermesis** [SirVer/ultisnips#298]
I have defined a directory for my own snippets:

>  let g:UltiSnipsSnippetDirectories=["thanasnippets", "UltiSnips"]

Which correctly works, but now (it worked before) when I run ":UltisnipsEdit" it doesn't go to edit the snippets on my directory

**Comment by rubencabrera** [comment]
Hello, I had the same problem trying to follow this line of the documentation:
https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L400

Just created the pull request  #775 to update it, hope it helps someone having the same issue.
