### ISSUE TITLE
Pythonless vim gives lots of errors (even with UltiSnipsNoPythonWarning=1)

### ISSUE THREAD

**Issue by m-ou-se** [SirVer/ultisnips#301]
To reproduce:

 - Get a vim without Python support.
 - Install UltiSnips through Vundle or something.
 - (Add `let g:UltiSnipsNoPythonWarning=1` to your `.vimrc`, if you want.)
 - Launch vim and get a bunch of errors, try to do anything and get more errors, etc.

The problem seems to be that when `!has('python')`, the `Bootstrap` function tries to do `:finish` when from inside the function, which is apparently not possible (vim says: `:finish used outside a sourced file`), and then vim just continues with the function trying to do Python stuff.

**Comment by SirVer** [comment]
Fixed in master in becab789a844631c49d776eccec753e7e3220e5a.
