### ISSUE TITLE
Documentation does not mention, what happens if there is no $0 in snippet.

### ISSUE THREAD

**Issue by cwahbong** [SirVer/ultisnips#354]
For example, python.snippet in honza/vim-snippets has the following snippet without ending placeholder $0.

    snippet if "If" b                                                   
    if ${1:condition}:                                              
        ${2:pass}
    endsnippet

Then I need to press the expand trigger key twice when I want to expand next snippet under this block since UltiSnips thinks that the first snippet is not finished.  Just want to ask if it is expected behavior, or a bug in snippet or ultisnips.

**Comment by SirVer** [comment]
Fixed by #483
