### ISSUE TITLE
CSS snippets won't trigger in SCSS files

### ISSUE THREAD

**Issue by felixjung** [SirVer/ultisnips#372]
Hi,

I'm trying to get the CSS snippets to trigger in SCSS files. Since CSS is perfectly valid SCSS and putting standard CSS properties in SCSS, I'd expect the CSS snippets to work just fine with SCSS.

Did I miss some config setting? CSS and SCSS by themselves work as expected.

Thanks!

**Comment by chaucerbao** [comment]
I'm trying to achieve the same thing, loading CSS snippets inside SCSS files. However, using `extends css` only seems to include `UltiSnips/css.snippets`, and not `snippets/css.snippets`.

For example, using [Honza's](https://github.com/honza/vim-snippets) snippets, the `rgb` snippet is defined only in UltiSnips, and `d:b` only in regular snippets. When editing `test.css` I can use both snippets. But when editing `test.scss`, only `rgb` works.

**Comment by SirVer** [comment]
As mentioned, extends is per soruce, so you need an `extends css` in `snippets/scss.snippets` too.

**Comment by eduardoarandah** [comment]
> As mentioned, extends is per source, so you need an `extends css` in `snippets/scss.snippets` too.

Hey! 
Are there any best-practices to handle custom snippets? 
I spent hours figuring out why my custom blade.php snippets didn't extend html anymore
