### ISSUE TITLE
Why when I set UltiSnipsExpandTrigger to '<cr>', I loose '<cr>' in normal Vim editing.

### ISSUE THREAD

**Issue by ghost** [SirVer/ultisnips#376]
I use YCM/Ultisnips/Supertab and hope to use carriage return to activate snippets, as I tend to think of tab as an 'enter the PUM/go to next candidate key, and it is disconcerting to have a tab key trigger a snippet.
I got it working how I would like it but soon noticed that setting UltiSnipsExpandTrigger to carriage return seems to disable carriage returns in insert mode for Vim, and of course that isn't acceptable.....
So, am I doing something wrong, or is there a way around this?  It seems to me that UltiSnips should only be redefining the UltiSnipsExpandTrigger key when the PUM is visible and the selection candidate is a snippet???  Or am I missing something.

Thanks,
Dave Day

And sorry if this is not the right place for this question.  I wasn't sure where to put it.

**Comment by tsaleh** [comment]
Hrm...  that `ExpandSnippetOrCarriageReturn` solution isn't working for me.  When I complete a snippet from the YCM popup menu (menu triggered with `<tab>`, snippet triggered with `<enter>`), the following is inserted into the buffer instead of the snippet:

```
pumvisible() ? "
" : "\
"
```

I've never seen a mapping that used vim code before, so I can't tell if there's a typo in your example using `pumvisible()`.  Or maybe this doesn't work with newer versions of Ultisnips or YCM?

**Comment by kbenzie** [comment]
I may have made a mistake, or there could be some behaviour that relevant settings were not included in the snippet, here is a copy paste from my `.vimrc` which is slightly updated.

```
let g:ycm_key_list_select_completion=["<tab>"]
let g:ycm_key_list_previous_completion=["<S-tab>"]

let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<S-tab>"
let g:UltiSnipsExpandTrigger="<nop>"
let g:ulti_expand_or_jump_res = 0
function! <SID>ExpandSnippetOrReturn()
  let snippet = UltiSnips#ExpandSnippetOrJump()
  if g:ulti_expand_or_jump_res > 0
    return snippet
  else
    return "\<CR>"
  endif
endfunction
inoremap <expr> <CR> pumvisible() ? "<C-R>=<SID>ExpandSnippetOrReturn()<CR>" : "\<CR>"
```

Hope that works for you as it does for me.

**Comment by tsaleh** [comment]
Strange - still doesn't work.  Must be something in my config, but thanks
for sending over the updated snippet!

Cheers,
Tammer Saleh
+44 7463 939332

**Comment by tsaleh** [comment]
Finally had time to debug this.  Removed all of my plugins and re-enabled them one-by-one, and the end culprit was https://github.com/tpope/vim-endwise

**Comment by DAddYE** [comment]
@tsaleh I use delimitMate and I modified @kbenzie's script to work with it:

```viml
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<S-tab>"
let g:UltiSnipsExpandTrigger="<nop>"
let g:ulti_expand_or_jump_res = 0
function! <SID>ExpandSnippetOrReturn()
  let snippet = UltiSnips#ExpandSnippetOrJump()
  if g:ulti_expand_or_jump_res > 0
    return snippet
  else
    return "\<C-Y>"
  endif
endfunction
imap <expr> <CR> pumvisible() ? "<C-R>=<SID>ExpandSnippetOrReturn()<CR>" : "<Plug>delimitMateCR"
```

**Comment by fourcolors** [comment]
Is there any way to get it to work with vim-endwise?

**Comment by timtyrrell** [comment]
I found this somewhere and it worked with my endwise, delimitmate, ultisnips, youcompleteme, etc. Replace the last line in the previous solution with this:

`let g:endwise_no_mappings = 1`
`inoremap <expr> <CR> pumvisible() ? "\<C-R>=ExpandSnippetOrCarriageReturn()\<CR>" : "\<CR>\<C-R>=EndwiseDiscretionary()\<CR>"`

**Comment by systemmonkey42** [comment]
The following command doesn't strictly work:

let g:UltiSnipsExpandTrigger="<nop>"

It results in the text string '<nop>' being mapped to the expand trigger.  This resulting in typing '<' in insert mode to misbehave, and typing '<nop>' will actually trigger completion..

Checking the source, there doesn't seem to be a reasonable way to completely prevent ultisnips mapping "SOMETHING" to the expand trigger, but ensuring 'g:UltiSnipsExpandTrigger' is set to the same value as 'g:UltiSnipsJumpForwardTrigger' has the most reasonable outcome.

let g:UltiSnipsExpandTrigger= "<c-f>"
let g:UltiSnipsJumpForwardTrigger = "<c-f>"

**Comment by duckworthd** [comment]
While `<nop>` is not a valid special token, `<NUL>` is. The following will do what you want,

```
    let g:UltiSnipsExpandTrigger = "<NUL>"
```

**Comment by weilbith** [comment]
An alternative solution which worked better for me, since I use to auto-complete snippet triggers with _Deoplete_. Therefore the here presented solutions are a nightmare, cause as soon as trigger is typed, but a different completion item is selected (not a rare case), this would always end up expanding the snippet. So I want to expand the snippet only when I selected this entry. (Just to mention, I use to add `menuone` to the `completeopt` option.) Therefore I leave my completion mapping as it is:

`inoremap <expr> <Tab> pumvisible() ? "\<C-y>" : "\<Tab>"`

And I hook into the `CompleteDone` event. Break it down it looks something like this (please make this more pretty, since this is only a shorten example within one file):

```vim
autocmd! CompleteDone * call <SID>try_expand()

function! s:try_expand() abort
  " Ignore events without completion item.
  " Furthermore ignore completions with items having a 'kind' property, since
  " UltiSnips does not define such. This is useful to avoid snippet completion
  " in case no snippet trigger has been completed, but a equal named candidate
  " like a variable or function.
  " Check if a at least one completion candidate exists (only one available
  " after completion).
  if !empty(v:completed_item) ||
        \ strlen(v:completed_item.kind) == 0 ||
        \ len(UltiSnips#SnippetsInCurrentScope()) > 0

    call UltiSnips#ExpandSnippet()
  endif
endfunction
``
Except the remaining issue mentioned at the in-line comments, this works pretty well. I opened a issue ( #1042 ) to improve the `kind` handling to make this solution absolutely accurate.
