### ISSUE TITLE
Effectively finding a snippet in a long snippet list

### ISSUE THREAD

**Issue by robrechtdr** [SirVer/ultisnips#398]
I've got a bunch of snippets. If I want to find a particular snippet I don't exactly remember the name of I can summon the snippet list with the UltiSnipsListSnippets command to look for it. 

However, the list of snippets is so long that it is very inconvenient to scroll down the whole list searching for the snippet description. 

How would you handle this problem? Is it possible to have a search functionality inside the search list?

I suppose ideally there would be a command that opened the snippet list in a split screen, on the one side you'd have something like a ncurses selection bar, the other side would display the raw snippet code of the currently hovered over ncurses selection bar as a preview of the snippet. That in combination with a search functionality.

**Comment by juanibiapina** [comment]
+1
