### ISSUE TITLE
Wishlist: Trigger snippets without a <TAB> key press

### ISSUE THREAD

**Issue by curioustolearn** [SirVer/ultisnips#401]
I love the functionality provided by UltiSnips#Anon. Essentially, I want to be able to expand snippets without pressing any trigger key. UltiSnips#Anon makes this possible. There are two problems with this: 
(i) I now have some snippets in the snippets file and some in my .vimrc. It would be better if they are in one file for a certain fileType. 
(ii) The UltiSnips#Anon triggers in all kinds of files. Hence, with that approach we lose the nice separation of snippets that one gets by putting snippets in <fileType>.snippets file. 

Hence, it would be great to have a setting/option that allows one to expand snippets defined in say, tex.snippets file without a trigger key.

**Comment by eshel9** [comment]
New version has the 'A' flag, which allows autotrigger.
:h UltiSnips-autotrigger
