### ISSUE TITLE
Add more features to integrate with Unite

### ISSUE THREAD

**Issue by kevin4fly** [SirVer/ultisnips#405]
I see that `ultisnips` has integration with `unite`, so I hope that `ultisnips` is able to provide more features as what [neosnippet] (https://github.com/Shougo/neosnippet.vim/blob/master/doc/neosnippet.txt#L673) did.

For example: 
1. add action for editing snippet
2. add ultisnips/user source for showing candidates of user snippet files. As I know, `ultisnips` will search the [directory](https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L313) including snippet definition files

**Comment by SirVer** [comment]
Closing for lack of interest.
