### ISSUE TITLE
Mess in the snippet 

### ISSUE THREAD

**Issue by bestxolodec** [SirVer/ultisnips#418]
When i hit a snippet  i get automatically pasted some mess in the places where i inteded to write. 
The mess i am writing about constantly appears  as  `;<Esc>v12G13|o12G7|o;<c-g>`
Here is an example:

    class ;<Esc>v12G13|o12G7|o;<c-g>MyClass(object):

        """Docstring for ;<Esc>v12G13|o12G7|o;<c-g>MyClass. """

        def __init__(self):
            """TODO: to be defined1. """

What am i doing wrong ? 
Here is my [.vimrc](https://github.com/bestxolodec/dotfiles/blob/master/.vimrc) file which contains nothing that might seem criminal to me.

**Comment by SirVer** [comment]
ping?

**Comment by bestxolodec** [comment]
I am sorry for being so slow. I will try to do it during next two weeks.

**Comment by SirVer** [comment]
ping?

**Comment by bestxolodec** [comment]
I am so sorry for being late. So JFYI:
I figured out what trigger such a behavior. The cause is line in the vimrc file:

    set langmap+=\\;*

Which maps `;` to `*` when using another language. 
None of any other [langmaps i use](https://github.com/bestxolodec/dotfiles/blob/master/vimrc#L256) dont mess snippets when triggered.

**Comment by SirVer** [comment]
If you have a very recent vim version and use `set langnoremap`, your woes should be gone.

See this commit: https://github.com/SirVer/ultisnips/commit/e041187669b25ce131055eac4a603ecffc8e360d#diff-3f3e133c49f174c1c2c9a7580ecf1f22R295

**Comment by bestxolodec** [comment]
Thank you very much!
