### ISSUE TITLE
Indentation spacing incorrect for Ruby

### ISSUE THREAD

**Issue by ianks** [SirVer/ultisnips#420]
It seems that the indentation for Ruby is incorrect when using UltiSnips. This issue does not exist for Python. Could there be some other setting that is causing this? Possibly from another plugin? Am I doing it wrong?

Here is the example:

![indent](https://dl.dropboxusercontent.com/u/5967734/ultisnips.gif)

I have confirmed that both `shiftwidth=2` and `expandtab` is set.

**Comment by SirVer** [comment]
The snippet definition is correct and the behavior with it is also correct on my machine in MacVim. possibilities:

1) this is something in your configuration that is triggering an Ultisnips bug that I do not have in my options, i.e. a rogue plugin or setting.
2) you are using a different snippet than you think. 

You can rule out 2 by editing the snippet and seeing if this changes anything. I'd also try putting something into `${0:txt}` - maybe that fixes the problem already.

**Comment by SirVer** [comment]
Why did you close this? Did you figure out what was wrong?

**Comment by ianks** [comment]
I mainly closed this because I could not find the issue and and ended up
moving to Neosnippet for now (it was easier to integrate with Neocomplete).
Therefore I won't have any further time to debug it. If you guys want to
look into it more than feel free to open it but I cannot contribute much
more to the issue.
