### ISSUE TITLE
Matching multiple orderless patterns at the same time

### ISSUE THREAD

**Issue by dclong** [SirVer/ultisnips#422]
I want to be able to use nature language as triggers. I want a line to trigger an snippet if it contains certain keywords. For example, I have the following snippet define, but it doesn't work. Could you please point out any mistake that I've made or clarify about whether this can be done in UltiSnips?

snippet "(?=.*one)(?=.*line)(?=.*comment)" "One Line Comment" r
/*${1:comment}*/
endsnippet

**Comment by SirVer** [comment]
I do not follow what you want to do. Could you provide a sample input and a desired output?

**Comment by dclong** [comment]
For example, if I type on a new line: 
one line comment
and press tab, I want it to expand to 
/*comment*/
The regular expression I defined uses "lookahead" and works in Python but it doesn't work as my snippet.

**Comment by SirVer** [comment]
What is wrong with the simple snippet?

~~~
snippet "one line comment" "One Line Comment" r
/*${1:comment}*/
endsnippet
~~~

**Comment by dclong** [comment]
The example I give is a simple one. What if I also want the following line to be expanded to 1 line of comment? 

comment one line

**Comment by SirVer** [comment]
You would probably need another snippet. Matching all possible combinations out of order is also possible with a very complex regular expression, but that does not scale.

**Comment by dclong** [comment]
I want to get it done in one snippet and the following is an example

snippet "(?=.one)(?=.line)(?=.comment)" "One Line Comment" r
/${1:comment}*/
endsnippet

The regular expression "(?=.one)(?=.line)(?=.comment)" successfully matches "one line comment", "comment one line", etc. in Python. However, it fails to work in UltiSnips.

**Comment by SirVer** [comment]
It does not match in python for me either. The regular expression is all asserts.. it has no length, I have a hard time thinking about how a state machine would match that.

~~~python
print(None is re.match(r"(?=.one)(?=.line)(?=.comment)", "comment one line"))
True
~~~

**Comment by dclong** [comment]
There's a star after each "?=.". GitHub eats all the starts. Please try the following regular expression in Python.

re.match(r"(?=.\*one)(?=.\*line)(?=.\*comment)", "comment one line")

**Comment by SirVer** [comment]
That matches, but of course the match has zero length. So there is nothing to replace in the line:

~~~
re.match(r"(?=.*one)(?=.*line)(?=.*comment)", "comment one line").group(0)
Out[12]: ''
~~~

So it is ill defined what ultisnips should do here - should it replace "one line comment" - no, it is not part of the match. But where should it insert the output then? Look aheads just do not work for your case.

**Comment by dclong** [comment]
Then do you have some suggestions about how we can achieve this in UltiSnips? We can certainly use regular expressions like 

.\*(one|line|comment).\*(one|line|comment).\*(one|line|comment).\*

but I'm looking for a simpler and scalable way of writing the regular expression.

**Comment by SirVer** [comment]
You cannot solve this with regular expressions since this is not inherently regular. UltiSnips trigger matching is only regular. So you need a programmatic solution. You could write a simple VimL function that checks if the current line contains trigger words you want, then clear out the line and use anonymous snippet expansion to trigger a snippet.

**Comment by dclong** [comment]
I understand your basic idea here, but I do I trigger an anonymous snippet in a Vim Script function? Can you shed some light on me?

**Comment by SirVer** [comment]
See https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L415

**Comment by dclong** [comment]
Thank you for the tutorial! As a Vim user, I really love UltiSnips. As you have seen, I'm pushing the limit of UltiSnips and trying to use to do fancy stuff. I'll blog about cool ways of using UltiSnips later.

**Comment by SirVer** [comment]
Cool, let me know when it is done. And spread the word about UltiSnips :)
