### ISSUE TITLE
Completion not triggering

### ISSUE THREAD

**Issue by kurkale6ka** [SirVer/ultisnips#423]
Hi,
UltiSnips works for me while on f6ce0f92d078d90d0e987aa59d51a61539d81d96 but if I update my submodule to d240aa24df36f08fb7ee48097ce502a83fd9e4aa it doesn't work anymore. The completion is not triggered.
My vimrc for info: https://github.com/kurkale6ka/vim/blob/master/.vimrc#L482-L487

**Comment by SirVer** [comment]
The tests still pass and I have no reports that something broke from somebody else. Also I see nothing wrong in your vimrc.

Could you bisect which commit actually did break you? Also, is `ctrl + tab` still working? Are the `all.snippets` still working or is everything broken?

**Comment by kurkale6ka** [comment]
Hi, thanks for looking into this! I could pin it down a bit more precisely.
The exact commit where it breaks is: `5c87806d7b2b32837f5ea11a9952343d8b27868b`
Still works with the previous (

**Comment by SirVer** [comment]
Mmhh. Did you try to nuke and recheckout the python directory? I saw Python getting confused about stale .pyc files.

**Comment by kurkale6ka** [comment]
Hmm,
I tried two things:
* I removed the `pythonx` directory and the ran `git reset --hard`
* I deleted all .pyc files (`find . -iname '*.pyc' -delete`)

Neither helped. I will keep digging...

**Comment by SirVer** [comment]
Can you check what `:imap <tab>` returns?

**Comment by kurkale6ka** [comment]
It looks correct: `i  <Tab>       * <C-R>=UltiSnips#ExpandSnippetOrJump()<CR>`

**Comment by SirVer** [comment]
what about pressing `<ctrl-tab>` in gvim (won't work in vim console).

**Comment by kurkale6ka** [comment]
Ok, so after doing a bit of python debbuging, turns out it's a problem with finding the snippet but I can't figure out where it is failing. A message would be helpful here. Ex: `No snippets were found in ~/vim/ulti_snippets/`.

**Comment by Morantron** [comment]
I have the same issue, my snippets are not expanding since I recently updated. I use terminal vim on linux.

**Comment by SirVer** [comment]
@Morantron please provide more information: your config, mappings and so on.

@kurkale6ka I just saw this line:

`let g:UltiSnipsSnippetsDir         = '~/vim/ulti_snippets/'`

But ~/vim is not on your `rtp` is it? UltiSnips will not find your snippets then. That should probably be `~/.vim/ulti_snippets`.

**Comment by kurkale6ka** [comment]
In fact `~/vim` is in my `&rtp` (otherwise it wouldn't have worked with previous versions either).
These lines are at the very top of my vimrc:
```
let &runtimepath = substitute(&runtimepath, '\.\zevim', '', 'g')

execute pathogen#infect('.bundle/{}', 'bundle/{}')
```

**Comment by SirVer** [comment]
Does `!UltiSnipsEdit!` allow you to choose from any of the path? Also,could you bisect the breaking commit for you?

**Comment by kurkale6ka** [comment]
Hey,
I made some progress with this!

So, after using `clear_snippets` as defined in
https://raw.githubusercontent.com/SirVer/ultisnips/fe7cb4cf8d6fd2a66058f001b14fe737a0fb6560/pythonx/UltiSnips/snippet/source/_snippet_dictionary.py (no priority)
and calling it as `self._snippets[ft].clear_snippets(triggers)` in `.../pythonx/UltiSnips/snippet/source/file/_base.py`, my snippets trigger again.

**Comment by SirVer** [comment]
I am confused at what you changed. Could you point me to a commit?

**Comment by kurkale6ka** [comment]
Basically I used an earlier (`fe7cb4cf8d6fd2a66058f001b14fe737a0fb6560`) version of the `clear_snippets` function.
(I manually changed `_snippet_dictionary.py`)

I used
https://github.com/SirVer/ultisnips/blob/fe7cb4cf8d6fd2a66058f001b14fe737a0fb6560/pythonx/UltiSnips/snippet/source/_snippet_dictionary.py#L27-L36
instead of
https://github.com/SirVer/ultisnips/blob/5c87806d7b2b32837f5ea11a9952343d8b27868b/pythonx/UltiSnips/snippet/source/_snippet_dictionary.py#L29-L39

And I called it like this
https://github.com/SirVer/ultisnips/blob/fe7cb4cf8d6fd2a66058f001b14fe737a0fb6560/pythonx/UltiSnips/snippet/source/file/_base.py#L100
Instead of
https://github.com/SirVer/ultisnips/blob/5c87806d7b2b32837f5ea11a9952343d8b27868b/pythonx/UltiSnips/snippet/source/file/_base.py#L97

I kept all other python code unchanged from HEAD of master

**Comment by cwahbong** [comment]
I think that it is cause by the behavior change of priority-based snippets. If clearsnippets and other snippets are in the same priority level then those snippets will be treated as cleared.

**Comment by cwahbong** [comment]
However, as mentioned in the documentation *UltiSnips-clearing-snippets*, it should only remove all snippets with a priority LOWER than the current one. So this should be fixed.

And note that after the fix, the behavior of `clearsnippets` is still different from before.

**Comment by kurkale6ka** [comment]
The only times I use `clearsnippets` is when I don't want default snippets mixed with my own ones but I get it this is the default behaviour now. Right?
Removing all my `clearsnippets` directives fixes the issue I have

**Comment by SirVer** [comment]
oh, so that is the issue. Raise the priority of your snippets then.

~~~
clearsnippets

priority 10 
~~~~

**Comment by Morantron** [comment]
@SirVer this is my configuration https://github.com/Morantron/dotfiles/blob/master/vimrc#L233

Tried both shas mentioned by @kurkale6ka but they do not work for me

* `:imap <tab>` returns `i <Tab> * <C-R>=UltiSnips#ExpandSnippetOrJump()<CR>`
* `:UltiSnipsEdit` opens up `~/.vim/UltiSnips/all.snippets` which is an empty file in an empty folder.

More stuff I've tried without success:

* Tried removing my custom snippets and use only honza's ones.
* Tried removing all other plugins.
* Tried open vim outside tmux.

Any other ideas that I might try?

**Comment by SirVer** [comment]
What happens if you add a snippet in all.snippets. Does that expand?

**Comment by Morantron** [comment]
Yep, snippets do expand in `~/.vim/UltiSnips/all.snippets`, thanks :tada: 

I can as a workaround place my snippets there, but I guess there is some other problem that causes that file and folder to be empty?

**Comment by SirVer** [comment]
Let's go from there: put something in `~/.vim/UltiSnips/cpp.snippets` and try editing `/tmp/blub.cc`. Does the snippet expand?

**Comment by SirVer** [comment]
ping?

**Comment by Morantron** [comment]
Sorry I went on vacation and forgot about this! :pray: 

Just tried adding `~/.vim/UltiSnips/cpp.snippet` and snippets in `*.cc` files do expand correctly.

If you need more stuff to troubleshoot just let me know ( not on vacations anymore :trollface: :sob: )

**Comment by SirVer** [comment]
It seems that UltiSnips is correctly installed and finding your snippets. 

Which snippets do not expand for you that you think should expand?

**Comment by SirVer** [comment]
ping?

**Comment by SirVer** [comment]
closing for no reply.

**Comment by noscripter** [comment]
Running into the same issue here. My situation is that ultisnips expand trigger custom key works in gvim(mac osx) but simply failed silently in my iterm vim. Read all your conversations and find no clue about it. Maybe you could give some clue about troubleshooting this? @SirVer @kurkale6ka

**Comment by kurkale6ka** [comment]
@noscripter I'd wrongly used 'priority' IIRC: https://github.com/kurkale6ka/vim/commit/e81196cd7da953618dc1428026585324e2c465a3#diff-a7212cfa2c81f893f8897f8f9c788fad

**Comment by sprnza** [comment]
I've also faced the same issue. Doesn't work in vim but does work in gvim. I've removed all `priority` to no avail. @noscripter How did you solve your issue?

**Comment by noscripter** [comment]
@sprnza I'm stilling having this issue, what's your specific solution? can you give me more details?
