### ISSUE TITLE
Put snippet below the line instead of replacing it

### ISSUE THREAD

**Issue by fatih** [SirVer/ultisnips#432]
Hi @SirVer 

I'm using a simple snippet in the form of

```viml
snippet ff "fmt.Printf(...)"
fmt.Printf("${1:${VISUAL}} = %+v\n", $1)
endsnippet
```

This is very handy to print out variables in their default formats in Go. Now if I select a word in visual, say with `viw` it'll be replaced with the snipept above which is very cool. But I don't want to replace that word, my intention is to create the snippet but **paste it below the current line**. Example, suppose we have this one liner below:

```go
foo := []string{"ultisnips", "vim"}
```

The **current** way is, when I select the word `foo` with `viw` and execute the snippet above results in:

```go
fmt.Printf("foo = %+v\n", foo) := []string{"ultisnips", "vim"}
```

but instead what It **should** be is:

```go
foo := []string{"ultisnips", "vim"}
fmt.Printf("foo = %+v\n", foo)
```

Is this possible? I'll try to avoid any Python based interpolation because I'm trying to make https://github.com/fatih/vim-go pure VimL so it can be also used with NeoVim. Maybe this can be solved somehow differently, I'm open to any suggestion.

Thanks for the plugin again, it's really awesome :+1:  :)

**Comment by SirVer** [comment]
What you want is not currently supported, but how about yanking the variable you are interested in and then use 

~~~
snippet ff "fmt.Printf(...)"
fmt.Printf("${1:`!v @"`} = %+v\n", $1)
endsnippet
~~~

> I'm trying to make https://github.com/fatih/vim-go pure VimL so it can be also used with NeoVim

NewVim works great with UltiSnips and Python - I use it every day. No need to avoid python interpolation. You are probably just need to run `pip install neovim` on your machine.

**Comment by fatih** [comment]
Thanks for the trick. I think I can try to wrap it into custom function. Awesome :+1:
