### ISSUE TITLE
How to stop execution of snippet in python block ?

### ISSUE THREAD

**Issue by pelonpelon** [SirVer/ultisnips#437]
I need to short circuit a snippet under certain conditions.
```python
if snip.ft != 'a.b':
  snip.stop()
```
Is that possible ?
...or maybe through vim ?

**Comment by SirVer** [comment]
Your question is too abstract for me to understand. Could you ask more specifically what you want to achieve?

**Comment by pelonpelon** [comment]
I am working with a new javascript framework called mithril.js. I’m trying to create a single snippet file to accommodate 2 filetypes: mithril.javascript and mithril.html

The snippet file has 2 functions. First, to save keystrokes, to help someone proficient in mithril be efficient and fast. Secondly, as mithril is very new, I want some snippets in the file to have a wizard quality. Essentially I want someone new to mithril to be able to type a succession of triggers and TABS and end up with a working application (including both javascript and HTML). I am almost there, but I need a snippet that will function only when editing an .html file.

EXPECTATION:
The snippet mhtml is full of HTML and a few tabstops, inappropriate for a .js file.
The user types mhtml<TAB>
when editing an .html file the snippet works as expected.
when editing a .js file the trigger disappears from the screen but the snippet does not execute.
Something like `!p snip.stop()` at which point the snippet is abandoned and control returns to vim.

I've tried versions of
```
`!p vim.command('exec "normal! \<ESC>"')`

AND

.vimrc
function! UltisnipsStop()
  if &ft=="mithril\.javascript"
    exec "normal! \<ESC>"
  endif
endfunc

mithril.snippets
`!v UltisnipsStop()`
``` 

My goal is to create a low adoption barrier for newbies. Through a vimscript variable those same triggers become more or less verbose at different levels: let mithril_ultisnips_level = 1,2,3

I have other options:
- I could create 2 separate snippet files: mithril_javascript.snippet and mithril_html.snippet and use each appropriately through auto commands. But I’m trying very hard to simplify adoption.
- I could expect the user to only use the snippet in the appropriate filetype

But I'm a little obsessed with user friendliness. I like the user's first interaction to require no familiarity with the documents.
 
I can imagine other situations where, depending upon user input ( snip.rv=? ), I would want a snippet to stop, or skip over remaining tabstops and jump to $0.

Is there a way? Maybe a technique I’m not seeing?

And thanks very much.
I would have to switch to Sublime if it were not for Ultisnips and YouCompleteMe.

**Comment by SirVer** [comment]
What you want is currently not supported. It could be added but it feels awkward because snippets are not run linearly, but very often - on each key stroke. My suggestion:

> I could create 2 separate snippet files: mithril_javascript.snippet and mithril_html.snippet and use each appropriately through auto commands. But I’m trying very hard to simplify adoption.

I think this is the way to go, frankly. I am not sure how that should be bad for adoption? You probably already have a `ftdetect/` and `ftplugin/` folder in your plugin. Just add in correct calls to `:UltiSnipsAddFiletypes` in these and you are done.
