### ISSUE TITLE
Triggering eruby snippets within html

### ISSUE THREAD

**Issue by jasonlong** [SirVer/ultisnips#440]
I'm hoping this is just a configuration problem on my end, but I'm wondering if it's possible to trigger eruby snippets while your cursor is inside an html tag.

For example, I have the following inside `eruby.snippets`

```
extends html, rails

snippet et
<% ${1} %>
endsnippet
```

Let's say my cursor is where the █ character is below and I type `et<tab>`:

```
<span class="█">Hello</span>
```

In this case, the snippet doesn't trigger. Similarly, if my cursor is "touching" an html tag, like:

```
<span class="foo">Hello</span>█
```

... the snippet won't trigger, but if there's a space after the closing tag:

```
<span class="foo">Hello</span> █
```

... then it **does** work. 

Is there something I can do to fix this?

**Comment by kovetskiy** [comment]
I think you should use option 'word boundary'. 

https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L624

**Comment by jasonlong** [comment]
@kovetskiy Thx, that seemed to do the trick!
