### ISSUE TITLE
Bug: Path With Spaces Causes Issues

### ISSUE THREAD

**Issue by starcraftman** [SirVer/ultisnips#445]
Hello,

I was testing vim-plug with spaces in the bundle location path in response to a bug against us (junegunn/vim-plug#154) and it seems ultisnips does not handle spaces well. It occurs on Linux and Windows. To replicate with vim-plug:

```vim
call plug#begin('/tmp/j jjj/bundle')
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets' " Default snippets for ultisnips
call plug#end()
```
Then run `PlugInstall`. Bugs are apparent immediately.

--------
Messages I get after installing:
```vim 
Error detected while processing function UltiSnips#bootstrap#Bootstrap:
line   35:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named UltiSnips
```
Then on any cursor movement, it reports `Error detected while processing function UltiSnips#CursorMoved:  line 1`. I imagine this is secondary to crashing in the bootstrap function.

**Comment by SirVer** [comment]
I think this is either a vim or a python issue: the Python import mechanism is not finding pythonx/Ultisnips. But vim 7.4 guarantees that it is in the python Path. Two Options: either vim does not add it correctly or Python cannot import it from paths with spaces. I bet it is 1.

**Comment by starcraftman** [comment]
@SirVer Interesting. If you can confirm 1 maybe it should be filed against vim_dev? 

I don't put spaces in my plugin path so this doesn't affect me. I'll leave it to you from here.

**Comment by SirVer** [comment]
Manually setting the `rtp` to `/tmp/import path/` let me import `/tmp/import path/blub.py`, so my hunch seems wrong. 

@starcraftman could you provide the full output of `set rtp` and also try to `py import UltiSnips` yourself?

**Comment by starcraftman** [comment]
Original RTP I get with vim-plug.
```vim
runtimepath=~/.vim,/tmp/jj\ jj/bundle/ultisnips/,/tmp/jj\ jj/bundle/vim-snippets/,~/.opt1/share/vim/vimfiles,~/.
opt1/share/vim/vim74,~/.opt1/share/vim/vimfiles/after,/tmp/jj\ jj/bundle/ultisnips/after,~/.vim/after```
Import fails with this one.

I took initiative of trying without the `\ ` in the names, so rtp was.
```vim 
rtp=/home/starcraftman/.vim,/tmp/jj jj/bundle/ultisnips/,/tmp/jj jj/bundle/vim-snippets/,/home/starcraftman/.opt1/shar
e/vim/vimfiles,/home/starcraftman/.opt1/share/vim/vim74,/home/starcraftman/.opt1/share/vim/vimfiles/after,/tmp/jj
jj/bundle/ultisnips/after,/home/starcraftman/.vim/after
```
This case seems to work. I can only confirm that the import works after manually changing the rtp. 
Guess I will open a ticket against vim-plug, or append to the existing one this info. Thanks for helping to debug @SirVer. Will close this one for now.

**Comment by SirVer** [comment]
Agreed, this looks like a vim-plug issue now.
