### ISSUE TITLE
Wrong folding?

### ISSUE THREAD

**Issue by dmitriy-korotayev** [SirVer/ultisnips#447]
Pretty simply, *.snippet files used to fold from `snippet` to (including) `endsnippet`.
Some time ago, it went to folding to one line before `endsnippet`

Is it a defined behavior or something is wrong?

Here's a visual example:
![example, yo](http://imgur.com/M0xwaP9l.png)

**Comment by SirVer** [comment]
That does not seem intended. I wouldn't know when that has changed though. But then again, I do not use folding in Vim anymore. Feel free to send a PR fixing it.

**Comment by cwahbong** [comment]
I think that I've fixed it.  However, I don't know if I break anything.  I think that it is better to have a test for folding (by checking the content of buffer?) and syntax (no idea now). What do you think?

**Comment by SirVer** [comment]
Thanks for the fix. A test would be nice, but I do not know how such a test could look like. The buffer's content does not change through the folding. You could hack something together that evals vim's foldlevel variable, but that seems fragile. If you have a better idea, I'd like to hear it, a test would be superb.
