### ISSUE TITLE
Completion won't trigger after HTML Tag

### ISSUE THREAD

**Issue by Pertubation** [SirVer/ultisnips#448]
Directly after an HTML Tag it seems to me that the completion can't be triggered.

For example if I type the following:
```html
<li>b<TAB></li>
```

It won't expand to:
```html
<li><b></b></li>
```

It only works if I add a space after `<li>`.
I'm using the HTML snippets from [honza/vim-snippets](https://github.com/honza/vim-snippets).
Is this a bug or am I holding it wrong?

**Comment by SirVer** [comment]
That snippet probably misses the `i` or `w` option. I suggest sending a PR to vim-snippets to fix it.

https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L618

**Comment by Pertubation** [comment]
Thanks I will do that.
