### ISSUE TITLE
help with supertab configuring

### ISSUE THREAD

**Issue by bounceme** [SirVer/ultisnips#451]
I am trying to figure out how I could have both supertab and ultisnips together with ultisnips using only tab and shift-tab as it's mappings. Mostly it works but if I am in the middle of a line like in this example
    $(document).ready(f[cursor here])
I would like to expand the function snippet though it instead triggers supertab.

However inside of a snippet I would like to first try supertab and then if there isn't any completions expand a nested snippet or go to the next stop.

**Comment by SirVer** [comment]
UltiSnips integrates with supertab in the following way: it tries to do it's own action first and falls back to supertab if that does not work out.

You want to switch this in some contexts which will require programming and special casing - there is no way to configure it more granularly right now.

The suggestion I always give is to use different keys for different tasks - there are always context where you want something else than what will happen if you put anything on tab. Expanding, completion and jump forward are really three different things and at any one point you might want to do any one of them - so bind them to different keys.

**Comment by bounceme** [comment]
thank you,I can deal with a few more binds then
