### ISSUE TITLE
UltiSnips simply won't work

### ISSUE THREAD

**Issue by jnardiello** [SirVer/ultisnips#452]
Hi,
for some reason - which I haven't yet understood - UltiSnips isn't working at all for me.

my .vimrc:
```
" Snippets
Plugin 'SirVer/ultisnips'
Plugin 'honza/vim-snippets'
let g:UltiSnipsExpandTrigger="<c-k>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"

" PHP
Plugin 'StanAngeloff/php.vim'
Plugin 'tpope/vim-commentary'
" PHP Autocomplete
autocmd FileType php setlocal omnifunc=phpcomplete#CompletePHP
set completeopt=longest,menuone
let g:SuperTabDefaultCompletionType = "<c-x><c-o>"
Bundle 'shawncplus/phpcomplete.vim'
let g:phpcomplete_parse_docblock_comments = 1
let g:phpcomplete_complete_for_unknown_classes = 1
```

Vim version `7.4.52`, python `2.7`

Whenever I trigger `<c-k>` simply nothing happens.
The only similar issue I found is this:
https://github.com/SirVer/ultisnips/issues/264

But in my case it seems that the filetype is working correctly. Any idea? I'm really running out of options. I've used UltiSnips in the past without issues.

Thanks

**Comment by jnardiello** [comment]
Actually, I just tried to:
1. Move the php.snippet from `bundle\vim-snippet\UltiSnips\php.snippet` to `UltiSnips\php.snippet` - still nothing
2. Rename `UltiSnips\php.snippets` to `all.snippets` AND it's now working. So, seems like a filetype issue. PHP Completion and linting is working thou so seems like something affecting only UltiSnips

**Comment by jnardiello** [comment]
So, for the records... This fixed it:
https://bugs.launchpad.net/ultisnips/+bug/1067416

Looks like the plugin is broken without issuing those commands.

**Comment by SirVer** [comment]
How did you install the plugin?

**Comment by jnardiello** [comment]
I use `Vundle` to handle all my plugins. I issued the `:BundleInstall` command.

**Comment by SirVer** [comment]
I used Vundle for years and never had any issues with filetype detection. I believe your problem is that your vimrc is not correct. Vundle (or rather vim) is very finicky about the order of statements. See for example https://github.com/gmarik/Vundle.vim/issues/16.

I doubt that this is an UltiSnips issue. Closing until new evidence surfaces.
