### ISSUE TITLE
`extends html` doesn't seem to work

### ISSUE THREAD

**Issue by lpil** [SirVer/ultisnips#453]
Hello!

Probably a config problem on my end, but the `extends html` I've just created for the `.eex` snippets doesn't seem to be working.

https://github.com/honza/vim-snippets/blob/master/UltiSnips/eelixir.exs

Any ideas? :)

Cheers,
Louis

**Comment by SirVer** [comment]
Filetype need to be *.snippets

**Comment by lpil** [comment]
Doh! How embarrassing. Thanks :)
