### ISSUE TITLE
Tab from python interpolation are not expanded

### ISSUE THREAD

**Issue by vheon** [SirVer/ultisnips#454]
Hi have the the following in the snippet definition:
```python
global !p
def junit(snip):
	if snip.opt("g:ultisnips_java_junit", "") == "3":
		snip += ""
	else:
		snip.rv += "@Test\n\t"
```
and
```
snippet test "test" b
`!p junit(snip)`public void $1() {
	$0
}
```

Where before the `$0` there's a `tab`. When I expand this in a java file with `set expandtab` `set shiftwidth = 2` and `set tabstop = 2` I get the following:

```java
  @Test
	public void () {
    
  }
```

Where before the `public` I got a hard tab and inside the method I got spaces. Is there something wrong in the snippet definition?

**Comment by SirVer** [comment]
snip gives you tools to increase or decrease the indent, tabs are not automagically replaced. See https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L873. This works for me:

~~~python
global !p
def junit(snip):
    if snip.opt("g:ultisnips_java_junit", "") == "3":
        snip += ""
    else:
        snip += "@Test"
        snip >> 1
        snip += ""
endglobal
~~~

**Comment by vheon** [comment]
Thanks I couldn't know how to search for this. I copied the snippet from [honza/vim-snippets](/honza/vim-snippets) so I thought that it was correct.
