### ISSUE TITLE
Edit snippet after leaving insert mode

### ISSUE THREAD

**Issue by fran-penedo** [SirVer/ultisnips#455]
I'm trying to reproduce the behavior of the gif in the readme and I can't add the additional arguments to \__init\__ so that the self.\_e = e sentence is automatically added. I'm not sure if I'm not understanding how to use the plugin, I have a configuration problem or this is something that's not possible anymore.

I'm trying to reproduce the actions seen in the gif, but I'll write them here in case there's something I'm missing:

- Expand the "class with docstrings" snippet with the expand trigger bind (in my case, "\<c-j\>").
- Jump forward using the JumpForwardTrigger bind (in my case also <c-j>) until the cursor is after the self argument of the \__init\__ method.
- Type ", a". A self.\_a = a sentence is added automatically at the end of the \__init\__ method, as well as a line to the docstring of the method for the "a" argument.
- Leave normal mode. This places the cursor over the parameter a.
- Move to closing bracket of the argument list of \__init\__ and enter insert mode with "i". Type ", b".

Expected result: a self.\_b = b sentence as well as a corresponding line in the docstring is added to the \__init\__ method as it would have been had I not left insert mode between typing ", a" and ", b".

Actual result: the aforementioned lines are not added.

If this behavior is likely due to a missconfiguration, let me know and I'll add the relevant information.

**Comment by SirVer** [comment]
Works for me and there are also (passing) tests for this behavior. Are you using the latest version of everything? Maybe another plugin or setting interferes in a bad way with US here - can you try with minimal settings?

**Comment by fran-penedo** [comment]
I don't understand what happened. Today I tried to disable every plugin by removing them from the runtimepath. After that, US worked as intended for the use case. However, as I started enabling each plugin again I couldn't reproduce the bug anymore, even with everything enabled and configured as it was yesterday. I'm sorry to have bothered you, I'll let you know if I manage to break it again.
