### ISSUE TITLE
Dot repeat entire expansion

### ISSUE THREAD

**Issue by ironhouzi** [SirVer/ultisnips#458]
When using a snippet with multiple tab stops (`$1`, `$2`, etc.. ), is it possible to have the entire snippet be dot repeatable instead of repeating the action of the last tab position?

The other benefit would be to undo the entire snippet expansion in a single hit of the `u` key. If one argues that it's nice to have a granular undo, I would say that this is better done in normal mode anyways. Perhaps each tab stop could be recorded in the jump list, so `<C-o>` would take you directly to the tab stops while a single undo command would undo the entire snippet expansion.

**Comment by SirVer** [comment]
Dot repeat is discussed here:
https://github.com/SirVer/ultisnips/issues/259

Undo is probablematic, but report is here:
https://github.com/SirVer/ultisnips/issues/154

**Comment by SirVer** [comment]
Sorry, undo problem is actually this one:
https://github.com/SirVer/ultisnips/issues/438
