### ISSUE TITLE
Is it possible?

### ISSUE THREAD

**Issue by neotohin** [SirVer/ultisnips#459]
In drupal we define a menu definition inside a function where we declare the function name in an array. Like: 

```php
function mytest_menu() {
  
  $items['path'] = array(
    'title' => '',
    'page callback' => 'my_custom_function',
  );
  $items['another'] = array(
    'title' => '',
    'page callback' => 'another_custom_function',
  );
  return $items;
}

function my_custom_function(){
  // code
}

function another_custom_function(){
   // Code  
}
```

So i want to write a snippet like : 

```php
  $items['another'] = array(
    'title' => '',
    'page callback' => '$1',
  );

  function $1(){
  }
```
Where **function $1** should be added at the bottom of file. Can this be done using python interpreter?

**Comment by SirVer** [comment]
No, for technical reasons (limitation in the way, Vim reports buffer changes) all changes to a buffer most be in one self contained block per snippet - so it is not possible to append something to the end of the buffer or, for example, include a C header when you expand a snippet at the top of the file. This might be possible in neovim in the future though.
