### ISSUE TITLE
Snippets won't expand until moving out of buffer and back in

### ISSUE THREAD

**Issue by stuartmemo** [SirVer/ultisnips#461]
Hi! I'm having an issue where when I start vim (using NERDTree), snippets won't expand until I move into  the NERDTree window and back again into the main buffer.

I have this line in my `.vimrc`
`autocmd VimEnter * wincmd p     " Move cursor to file being edited`

...which I don't believe is triggering my autocmd to expand the snippet. Any ideas?

My vimrc is [here](https://github.com/stuartmemo/vimmy-jones/blob/master/vimrc) if that helps, and gif of the issue is below.

Thanks!

![ultinerd](https://cloud.githubusercontent.com/assets/59205/6582100/e503a008-c752-11e4-8a5d-39ddb9024a56.gif)

**Comment by SirVer** [comment]
That sounds like a funky issue. It seems to be something in your setup - I suggest disabling as much of it as you can bare (i.e. plugins) and see if snippets are working as expected. Then enable one by one your remaining setups and see when the problem starts surfacing again. 

Also, try moving your vundle block to the top of your vimrc - exactly as described in the vundle readme, point 3. The `syntax on` for example might be problematic

**Comment by stuartmemo** [comment]
Yeah, can't figure it out. Moving the vundle block didn't help. Seems to be a loading order issue. Will close this and reopen if it's still an issue after some investigation. Thanks!
