### ISSUE TITLE
Snippet not executing shell command

### ISSUE THREAD

**Issue by pdoak** [SirVer/ultisnips#463]
I have just started using UltiSnips and am trying to write a snippet which moves a file and then inserts the path into a markdown link like this:
```
snippet mvimg "Move image from desktop" b
![](`mv ~/Desktop/*(om[1]) $PWD/images/ && print $PWD/images/*(om[1]) | urlencode`)
endsnippet
```
where urlencode is a function in my .zshrc.

The snippet fails though. Even if I just try and use this snippet:
```
snippet tester "test snippet" b
`echo ls ~/Desktop/*(om[1])`
endsnippet
```
The snippet does not like the (om[1]) because if I remove that it will list the contents of the Desktop directory. Do I need to do something else to make this work.

Thanks 
Paul

**Comment by pdoak** [comment]
I got it working - I needed put a shebang at the head of the file and also escape the individual commands like this:
```
snippet mvimg "Move image from desktop" b
![](`#!/usr/local/bin/zsh 
mv ~/Desktop/*(om[1]) $PWD/images/
path=\`print $PWD/images/*(om[1]:t) \`
echo ./images/${path// /%20}`)
endsnippet
```

**Comment by SirVer** [comment]
Great. Yes, the escaping has a bit too much of onions - too many layers :).
