### ISSUE TITLE
my tab completition wont load the snippet

### ISSUE THREAD

**Issue by tiagonbotelho** [SirVer/ultisnips#464]
https://github.com/tiagonbotelho/_vimrc <. my .vimrc

i have the filetype off at the begging, after that a block for Vundle only and only after that do filetype plugin indent on

im spending hours trying to fix this bug and i do not understand what is happening all my plugins work except this one :/

**Comment by SirVer** [comment]
The vimrc looks good. Maybe try commenting 

    let g:UltiSnipsSnippetsDir = '~/.vim/bundle/vim-snippets/UltiSnips/'

Maybe that is a problem, but I do not know.

Otherwise, see if the mappings are correct: try `:verbose imap <tab>`. Also try 'lorem<tab>` to see if that is expanded (it is from all.snippets in vim-snippets).

**Comment by SirVer** [comment]
Snippet descriptions can go after the snippet line instead of as comments - which will make them pop up in some plugins.

**Comment by tiagonbotelho** [comment]
Nvm fixed this after i referenced the right version of my vim that i installed with brew. i was using a previous version. It is working now thank you for your time
