### ISSUE TITLE
Regexp Snippet Incorrectly Re-Matched.

### ISSUE THREAD

**Issue by bmustiata** [SirVer/ultisnips#466]
This is supposed to allow creating tags when the user types `<` followed by anything else.

```
snippet /<([^>]*)$/ "Create a tag" r
<`!p snip.rv += match.group(1) `${1:}>
	${VISUAL}${0:}
</`!p snip.rv += match.group(1) `${1/(.*?)\s.*/$1/}>
endsnippet
```

The regexp matches only if there is no closing `>` for the given `<` until the end of line.

**Steps to reproduce:**

So:
`<di` then
* press `tab` (expand)
* type `v id="asd"`
* press `tab`

**Expected result:**
```
<div id="asd">
|
</div>
```

**Actual result:**
```
<div id="asd"|>
    
</div id="asd">>
    
</di>
```

*Thank you for the amazing plugin*.

**Comment by SirVer** [comment]
That is working as intended. The second time you press Tab, UltiSnips prefers to expand (which it is allowed to, since this snippets trigger matches), but you are expecting it to jump. This is a common problem with overloading your tab key for two semantic meanings. If you think about it, there are reasons to prefer jump over expand (like here) and sometimes expand over jump (for example when another short snippet matches) and the plugin cannot know which one you want in which case. 

Correct solution: do not overload the tab key, make expand and jump forward two separate key bindings. 

Quick solution: fix your regular expression trigger to not match in the place where you press tab the second time.

**Comment by bmustiata** [comment]
Thank you for the response. Please take note that the regexp does not match
the second time tab is pressed.

I think the problem is that ultisnips doesn't parse correctly the $ suffix.

**Comment by SirVer** [comment]
I wonder what makes you think it does not match? Because it very clearly does: 

~~~python
> ipython                                                          

In [1]: import re

In [2]: re.match(r'<([^>]*)$', '<div id="asd"')
Out[2]: <_sre.SRE_Match at 0x10ef9e918>

In [3]: _.group(0), _.group(1)
Out[3]: ('<div id="asd"', 'div id="asd"')
~~~

**Comment by bmustiata** [comment]
Well 'duh' it matches the expression you wrote :).

Maybe I don't understand something obvious, but after the first expand, the code is then:
```
<di|>
</di>
```

Typing `v id="asd"` should fill the group 1, 'v' is the matcher in the replacement, and now we have:
```
<div id="asd"|>
</div>
```

Note that on my line I have a > after my cursor. The question is what text gets feeded into ultisnips? I would have expected the full line, but I tend to believe now it's up the the cursor position.

**Comment by SirVer** [comment]
Yes, it is everything before the cursor.

**Comment by bmustiata** [comment]
Well that sucks. Thank you man anyway. Awesome plugin!

**Comment by SirVer** [comment]
Sorry and thanks.

**Comment by bmustiata** [comment]
SirVer, I noticed that when I expand snippets I generally don't expand snippets while I am already expanding snippets. If a snippet would accidentally match while I am expanding some parameter, I am finding it inconvenient, since I don't know how to undo this easily.

I doubt I am the only person who runs into that, so the question is, would it be ok if there would be a config option to disable expansion, if already completing parameters inside an expanded snippet?

**Comment by bmustiata** [comment]
(I comment here since this would also solve this issue, I don't know if I should have created a new issue instead).

**Comment by SirVer** [comment]
> I doubt I am the only person who runs into that, so the question is, would it be ok if there would be a config option to disable expansion, if already completing parameters inside an expanded snippet?

Easy solution is to use different triggers to jump and expand - and if you never want to expand a snippet while already in one, you are not using enough snippets :).

No, I do not think another option is a good idea - maybe it might help to surface the current state that UltiSnips is in (inside a snippet or not) to vim script similar to the return values of the functions (https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L285). You could then programmatically overload your expansion key to jump if you prefer.
