### ISSUE TITLE
minor issue: texmath vs tex

### ISSUE THREAD

**Issue by vsilv** [SirVer/ultisnips#467]
Let us assume I am editing a formula in .tex, for instance in a equation environment. If I now use :UltiSnipsEdit, I am opening the tex.snippets file, not the textmath.snippets file. I know, this is not a big issue, but wouldnt it be great if the textmath.snippets file would be opened?

**Comment by SirVer** [comment]
Not in the scope for UltiSnips.

Vim decided to only support filetypes (think: languages) on a per-file basis. That is the `filetype` option which can only be set per buffer. Other Editors (e.g. TextMate) are more flexible and support embedding other languages, but this is not Vim's model. UltiSnips automatically inherits this limitation.
