### ISSUE TITLE
Error in 'as_vimencoding'

### ISSUE THREAD

**Issue by trevor-ratliff** [SirVer/ultisnips#468]
I'm running a 64-bit vim on Windows 7 with 64-bit python installed (2.7 and 3.4) and I recently installed Ultisnips as a pathogen bundle.  I've also installed the snippets from Honza.  I've mapped <tab> to start the completion.  When I enter a valid snippet code then press tab the snippet is expanded, but then I get an error.  If I start a snippet code and use <ctl+tab> I get the possible match menu, then when selecting a number and hitting <enter> I get the same result.  The snippet is expanded, but then throws a python error and I'm not able to do anything else with the snippet.

This is the error I get:

```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

Following is the full stack trace:
Traceback (most recent call last):
  File "$HOME\vimfiles\bundle\ultisnips\pythonx\UltiSnips\snippet_manager.py", line 56, in wrapper
    return func(self, *args, **kwds)
  File "$HOME\vimfiles\bundle\ultisnips\pythonx\UltiSnips\snippet_manager.py", line 200, in list_snippets
    self._do_snippet(snippet, before)
  File "$HOME\vimfiles\bundle\ultisnips\pythonx\UltiSnips\snippet_manager.py", line 567, in _do_snippet
    self._jump()
  File "$HOME\vimfiles\bundle\ultisnips\pythonx\UltiSnips\snippet_manager.py", line 417, in _jump
    _vim.select(ntab.start, ntab.end)
  File "$HOME\vimfiles\bundle\ultisnips\pythonx\UltiSnips\_vim.py", line 133, in select
    _unmap_select_mode_mapping()
  File "$HOME\vimfiles\bundle\ultisnips\pythonx\UltiSnips\_vim.py", line 184, in _unmap_select_mode_mapping
    all_maps = list(filter(len, eval(r"_tmp_smaps").splitlines()))
  File "$HOME\vimfiles\bundle\ultisnips\pythonx\UltiSnips\_vim.py", line 99, in eval
    rv = vim.eval(as_vimencoding(text))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 1023: invalid start byte
```

It doesn't matter the snippet I try, so I'm guessing it's a problem with Ultisnips :-(

**Comment by SirVer** [comment]
The error happens in the part of UltiSnips, that unmaps select-mode mappings. See the documentation why we do this: https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L370

One of your select mode mappings is not valid utf-8 - no idea how that happened. You can either disable Vim's select mode unmapping using `let g:UltiSnipsRemoveSelectModeMappings = 0` or figure out which mapping is troubling UltiSnips and unmap it manually in your vimrc before using UltiSnips.

**Comment by trevor-ratliff** [comment]
Thanks for the quick response, I'll see if I can figure out which mapping
is not right.

**Comment by trevor-ratliff** [comment]
There were mappings in the mswin.vim I am using that maps '<M-Space>' to some ':simalt' keys that caused the issue.  Commenting those out allowed UltiSnips to work correctly.
