### ISSUE TITLE
Expand snippets not preceded by whitespace

### ISSUE THREAD

**Issue by mattbreeden** [SirVer/ultisnips#471]
Is there a way to set snippets up so that they don't have to have whitespace? For example: often I want to use a snippet after an html tag in erb- `<h1>%(tab)` does nothing  

I was hoping the 'w' option could be used for this because that it was what many of the html snippets use and I do not have that issue with them. However adding the w to my eruby snippets does not make a difference.

**Comment by SirVer** [comment]
The `w` option triggers at word boundaries, i.e. parenthesis, hyphens or other depending on your vim configuration. What you probably want is [the `i` option](https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L618) which triggers everywhere.
