### ISSUE TITLE
Does not work with vim-slimv/Lisp filetype

### ISSUE THREAD

**Issue by axionix** [SirVer/ultisnips#472]
This snippet is never inserted in a Lisp file buffer. Not sure if this is due to the slimv plugin or not, but the same snippet works fine in other filetypes (python tested).

snippet t "Test"
"test"
endsnippet

**Comment by axionix** [comment]
On closer inspection, it seems to work if i disable the slimv plugin. I'm not sure what is conflicting here. Any workarounds? This seems like a nice plugin I'd like to use.

**Comment by SirVer** [comment]
> Any workarounds?

probably not. the plugins need to do too similar things (keeping track of the cursor and move it around) to not step on each others toes all the time. Vim was not really designed with extensibility in mind and therefore the models are rather poor - and therefore plugins interfere very quickly with each other. Sorry.
