### ISSUE TITLE
Is there an option for empty forward stack when switch to normal mode

### ISSUE THREAD

**Issue by kelly-apollo** [SirVer/ultisnips#474]
Example:

<pre>
snippet cl
    console.log(${0});
</pre>

With `cl` snippet expands to `console.log(hit_escape_to_normal_mode);`  and hit `o` for a new line editing. The next time I type `<TAB>` for indent (as `let g:UltiSnipsJumpForwardTrigger="<tab>"`), it jumped back to the old trailing placeholder which I want to abandon.

**Comment by SirVer** [comment]
confirmed. It only happens with vim-snippets snippet files though. The snippet should be terminated as soon as $0 is reached, but that does not seem to happen.

**Comment by SirVer** [comment]
No longer reproduces with c309637e0243b71f7e3265ebe3cffdfe9674cfbc.
