### ISSUE TITLE
[wishlist] move initialization to vimenter autocmd.

### ISSUE THREAD

**Issue by introom** [SirVer/ultisnips#475]
Hi.

Ultisnips is a huge, if_py based plugin. When startup, it takes lots of time, in the scale of hunders of milliseconds.

It will be cool if the intialization part is moved into a VimEnter autocmd, kinda like: 
https://github.com/Valloric/YouCompleteMe/blob/master/plugin/youcompleteme.vim#L175-L178

**Comment by SirVer** [comment]
Sounds good. Patch is welcome.

**Comment by SirVer** [comment]
I cannot reproduce this on master:

~~~
vim --startuptime vim.log -c 'quit'; cat vim.log | grep -i ultisnips
053.312  000.049  000.049: sourcing /Users/sirver/.vim/bundle/ultisnips/ftdetect/snippets.vim
053.402  000.061  000.061: sourcing /Users/sirver/.vim/bundle/ultisnips/ftdetect/UltiSnips.vim
152.872  000.102  000.102: sourcing /Users/sirver/.vim/bundle/ultisnips/autoload/UltiSnips/map_keys.vim
152.974  000.602  000.500: sourcing /Users/sirver/.vim/bundle/ultisnips/plugin/UltiSnips.vim
156.179  000.129  000.129: sourcing /Users/sirver/.vim/bundle/ultisnips/after/plugin/UltiSnips_after.vim
~~~

The python code is only loaded after this through autocommands - therefore it will not slow down the start of vim.
