### ISSUE TITLE
Tabstops mirroring

### ISSUE THREAD

**Issue by jrean** [SirVer/ultisnips#477]
Hi,

To practice with your nice plugin I would like to understand how I could manage multi parameters mirroring in the following exemple:

```
snippet m "New method" !b
/**
 * ${8:Method description}
 * @param ${6:type} $3 ${7:Description}
 *
 * @return ${5:type}
 */
${1:protected} function $2($3)
{
	return ${4};
}
${0}
endsnippet
```

By default $3 will be mirrored within `* @param ${6:type} $3 ${7:Description}`
- How can I manage "Multi parameters"? `function foo($param1, $param2, $paramN)` and so get the following mirrored:
```
 * @param xx $param1 Description
 * @param xx $param2 Description
 * @param xx $paramN Description
```

At the opposite how could I manage if I don't insert anything within `$3`? (`function foo()`)
I would like `* @param ${6:type} $3 ${7:Description}` to be conditionally printed only if $3 (and other parameters) are not empty.

I'm sure it's possible.

Thanks for your help and your hard work.

**Comment by SirVer** [comment]
It is possible, but needs python coding. see the python class snippet for an example: https://github.com/honza/vim-snippets/blob/master/UltiSnips/python.snippets#L212

**Comment by jrean** [comment]
Thank you @SirVer.

**Comment by jrean** [comment]
@SirVer can you please help me to write the needed code? Unfortunately it's out of my competences :(

**Comment by jrean** [comment]
@SirVer,
I think I found something I can work with by I still need some extra help to finish it

```
snippet construct "__construct()" b
/**
 * @param $2mixed ${1/, /\n     * \@param mixed /g}
 */
public function __construct(${1:$dependencies})
{${1/\$(\w+)(, )*/\n        $this->$1 = $$1;/g}
}
$0
endsnippet
```

`@param $2mixed ${1/, /\n     * \@param mixed /g}` will expands based on the number of parameters. Cool :)

My last issue is if I delete the first (and unique) parameter, it won't delete the first (and unique) DocBlock `@param $2mixed`

Can someone help to fix this little detail?

Thank you

**Comment by jrean** [comment]
I spent a couple of hours discovering what you can do with Ultisnips and Python. It's so powerful, magic but hard for a non Python programmer.

I came with this solution which I'm sure is ugly.
Can you help me now @SirVer?

```
snippet m "New Method" !b
/**
 *
`!p 
if t[3]: snip.rv = ' * @param mixed'
else: snip.rv = ' *'` ${3/,/\n     * \@param mixed/g}
 *
 */
${1:protected} function ${2}(${3})
{
	return${4};
}
${0}
endsnippet
```

Thank you

**Comment by SirVer** [comment]
Sorry, I just came from work. How about this?

~~~~
snippet m "New Method" !b
/**
 *
`!p snip.rv = "\n".join(" * @param mixed %s" % a.strip() for a in t[3].split(','))`
 *
 */
${1:protected} function ${2}(${3})
{
    return${4};
}
${0}
endsnippet
~~~

The list comprehension is broken down here:

~~~python
Python 2.7.2 (default, Jul 20 2011, 02:32:18)
[GCC 4.2.1 (LLVM, Emscripten 1.5, Empythoned)] on linux2
   t = "int a, int b, char c"
   t.split(',')
=> ['int a', ' int b', ' char c']
   [ a.strip() for a in t.split(',') ]
=> ['int a', 'int b', 'char c']
   "\n".join("%s" % a.strip() for a in t.split(','))
=> 'int a\nint b\nchar c'
~~~

hope that helps.

**Comment by jrean** [comment]
Thank you very much @SirVer for your time.
``!p snip.rv = "\n".join(" * @param mixed %s" % a.strip() for a in t[3].split(','))`` should be a little  more specific because ` * @param mixed ` should be only displayed when `${3}` is not empty AND should be deleted (delete the line) when the first `${3}` is also deleted.

I watch your video casts! Amazing to see play with Python! I hope I could find the time to learn it.

**Comment by SirVer** [comment]
I think the remaining requests you already figured out in your post, right? Or do you still need help from me?

**Comment by jrean** [comment]
Hi,
You mean using the `if else` statement? Is it a good way of handling the behaviour?
There is still an issue with:
``!p if t[3]: snip.rv = "\n".join(" * @param mixed %s" % a.strip() for a in t[3].split(','))``
If `t[3]` is empty I have and empty line. How can we manage that?

So yes if you still want to help me it's welcome :)

**Comment by jrean** [comment]
Can you please help @SirVer (see my previous message)?
Thank you :)

**Comment by SirVer** [comment]
sorry, I am super busy these days. Here you go:

~~~~
snippet m "New Method" !b
/**
 * Method desription goes here
 *
`!p
if t[3]:
	for param in t[3].split(','):
		snip.rv += snip.mkline(" * @param mixed %s\n" % param.strip())
else:
	snip.rv = ""
` * @return type description
 */
${1:protected} function ${2}(${3})
{
    return${4};
}
${0}
endsnippet
~~~

**Comment by jrean** [comment]
Thank you so much!!
Perfect!

Regards.
