### ISSUE TITLE
How can I open the files from which snippets are being read?

### ISSUE THREAD

**Issue by icymist** [SirVer/ultisnips#481]
Is there a way to list the files from which the current snippets are being read, select one of them, and come back to the initial place of editing?

I don't seem to remember all the shortcuts that have been defined. And doing <C-l> list a ton of snippets, and I can search for any text inside the snippets. So, I was thinking I could visit the file from where the snippets are being listed and do a normal search with Vim. I know this is not very clever, but at least ill I remember the names of the snippets that I want to use, it will be a work around.

Any ideas?

**Comment by SirVer** [comment]
Have you tried the bang version of the edit command? `:UltiSnipsEdit!`

**Comment by icymist** [comment]
Great thanks!
