### ISSUE TITLE
Neovim: Gives me a prompt (there is only one possible expansion)

### ISSUE THREAD

**Issue by unphased** [SirVer/ultisnips#485]
I couldn't find another issue that seemed related. 

Basically I am a lightweight snippet user, but I have come to depend on the few snippets that I have trained myself to use so far. 

Neovim does work with ultisnips. It does not crash. However, when I trigger the hotkey, I get this prompt: 

```
1: (l) "console.log()" (/home/steven/.vim/UltiSnips/javascript.snippets:60)
Type number and <Enter> or click with mouse (empty cancels):             
```

This obviously puts a huge damper on the speed advantage of snippets.

I wonder what's causing this and if there is some way to force it not to ask me. Regular vim doesn't do this.

**Comment by SirVer** [comment]
that seems weird. Could you check out your mappings, i.e. `:verbose <imap>` for your trigger?

**Comment by unphased** [comment]
i  <C-Tab>     * <C-R>=UltiSnips#ListSnippets()<CR>                             
        Last set from ~/.vim/bundle/ultisnips/autoload/UltiSnips/map_keys.vim   
Press ENTER or type command to continue

**Comment by unphased** [comment]
I think this is related to the default binding and possibly some behaviors related to the YouCompleteMe plugin. Basically what I tested just now was this: If I set this binding for neovim: `let g:UltiSnipsExpandTrigger="<m-c>"` then I can use Alt+C and it does give me useful correct behavior for performing the snippet completion. I just don't know why the `ListSnippets()` binding is misbehaving in neovim. It also appears that `<c-tab>` is just being bound automatically because I can still trigger `ListSnippets()` after changing my binds.

**Comment by unphased** [comment]
Update: Okay I fixed my problem, it's mostly to do with the the combination of the following reasons:

- `<c-tab>` binding being bound to presenting the prompting list by default
- vanilla vim in terminal failing to respond to  `<c-tab>`
- `<c-tab>` binding working out of box in neovim
