### ISSUE TITLE
How to use predefined functions for my own snippets

### ISSUE THREAD

**Issue by josefson** [SirVer/ultisnips#487]
So, I can use UltiSnipsEdit in order to create my own snippets which i believe have priority over the shipped ones. That said, i wish i could use functions and snippets located on:
```
~/.vim/bundle/vim-snippets/snippets/python.snippets
~/.vim/bundle/vim-snippets/UltiSnips/python.snippets 
```
inside the file UltiSnipsEdit is linked to.
Like source those files or something like that.

**Comment by SirVer** [comment]
It is actually pretty easy to do so:

1) make a pull request that pulls out the methods you want to use into a file in `pythonx`, like for example this: https://github.com/honza/vim-snippets/blob/master/pythonx/vimsnippets.py

2) import this in your snippet file and the one you pulled it out from:

```
global p!
from vimsnippets import myfunc
endglobal
```

So this is not about UltiSnips, but about the layout of vim-snippets. I am closing this - feel free to follow up with any questions.
