### ISSUE TITLE
Feature request: allow vimL to manipulate inputs

### ISSUE THREAD

**Issue by roylez** [SirVer/ultisnips#488]
I am not sure if this feature is already there.

Basically what I want to do is to type a word, select it, and use ultisnips to expand it into a vim folding marker group. The problem here is the comment char, because apparently ruby and javascript has different comment definition.

For example, `foo` in ruby should expand to 

```
# {{{ foo
# }}} 
```
but in javascript should be 

```
// {{{ foo
// }}}
```
and the same snippet should work for all file types supported by a commenter plugin like TComment.

**Comment by SirVer** [comment]
You can already do that - look at the box snippet here: https://github.com/honza/vim-snippets/blob/master/UltiSnips/all.snippets#L19

You can reuse the same code to make it work for folds.

Closing as this just requires work in vim-snippets, not in UltiSnips.

**Comment by roylez** [comment]
Awesome. I did not know there is a "foldp" already.
