### ISSUE TITLE
UltiSnips not displayed in YCM popup menu, but inserted after pressing expand trigger

### ISSUE THREAD

**Issue by sandric** [SirVer/ultisnips#490]
After some .vimrc refactoring, I noticed strange behaviour of UltiSnips - it works just fine, just not displaying in YouCompleteMe completion popup. 

Here's my .vimrc file (all except mappings):
```
set rtp+=~/.vim/bundle/Vundle.vim

highlight LineNr ctermfg=grey
hi visual ctermbg=81

let mapleader=","

set nocompatible
set shell=/bin/bash
set expandtab
set shiftwidth=2
set softtabstop=2
set ignorecase
set incsearch
set hlsearch
set hidden
set clipboard=unnamedplus
set background=light
set tabstop=2
set backspace=2
set number



call vundle#begin()

Plugin 'gmarik/Vundle.vim'

Plugin 'tpope/vim-fugitive'

Plugin 'git://git.wincent.com/command-t.git'

Plugin 'vim-ruby/vim-ruby'

Plugin 'vim-scripts/Conque-GDB'

Plugin 'airblade/vim-gitgutter'

Plugin 'moll/vim-node'

Plugin 'scrooloose/nerdtree'

Plugin 'Valloric/YouCompleteMe'

Plugin 'marijnh/tern_for_vim'

Plugin 'jelera/vim-javascript-syntax'

Plugin 'nathanaelkane/vim-indent-guides'

Plugin 'therubymug/vim-pyte'

Plugin 'scrooloose/syntastic'

Plugin 'walm/jshint.vim'

Plugin 'scrooloose/nerdcommenter'

Plugin 'SirVer/ultisnips'

Plugin 'honza/vim-snippets'

Plugin 'yegappan/greplace'

Plugin 'nsf/gocode', {'rtp': 'vim/'}

Plugin 'ekalinin/Dockerfile.vim'

Plugin 'raimondi/delimitmate'

"Plugin 'Lokaltog/vim-easymotion'

let g:UltiSnipsExpandTrigger="<c-a>"
let g:UltiSnipsJumpForwardTrigger="<c-t>"
let g:UltiSnipsJumpBackwardTrigger="<c-r>"

let delimitMate_expand_cr = 2
let delimitMate_expand_space = 1 

autocmd FileType ruby,eruby let g:rubycomplete_buffer_loading = 1 
autocmd FileType ruby,eruby let g:rubycomplete_classes_in_global = 1
autocmd FileType ruby,eruby let g:rubycomplete_rails = 1

autocmd FileType javascript setlocal omnifunc=tern#Complete

let g:ycm_key_invoke_completion = '<c-t>' 

call vundle#end()

start

syntax enable

filetype on
filetype plugin on
filetype plugin indent on
```

Can someone see where is the configuartion error? thx.

**Comment by SirVer** [comment]
The last 6 lines seem weird - what is start, and filetype should probably only be one line. 

What happens if you hit the list-snippets trigger, does it display all the snippets that you expect in YCM?

**Comment by sandric** [comment]
@SirVer start makes start vim in insert mode - this is my workflow for now. Anyway, I tried to comment out start and nothing changed. Also I tried to left filetype on the only line, removing last two, and still the same.

No, the thing is that it does not display them in YCM popup menu. For example, if I have snippet for `fu` for go function, and already created function before in code, typing `fu` brings YCM popup menu where `func` displayed, as memorized word, entered before in text, but no `fu` snippet, although I can type <C-t> to bring UltiSnips trigger function and it paste `fu` snipped code just as it supposed to do, its just not displayed in YCM popup. All working great, different snippets for different languages, and mine, and default from vim-snippets plugin, its just not displayed in popup.

**Comment by mmwtsn** [comment]
Not sure if this is the issue but your Vundle configuration does not match the [suggested setup](https://github.com/gmarik/Vundle.vim#quick-start).

Try starting your `.vimrc` with the following _then_ adding the rest of your configuration:
```vim
" Setup Vundle
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim

" Load plugins
Plugin 'gmarik/Vundle.vim'

" Finish Vundle setup
call vundle#end()
filetype plugin indent on
call vundle#begin()
```

As SirVer pointed out the last three lines are redundant. Setting `filetype plugin indent on` includes `plugin`, `indent`, and `on`. No need to call them separately on the previous two lines. Check the documentation in Vim for more (`:help filetype-overview`).

**Comment by SirVer** [comment]
@mellery451 You can check UltiSnips with the `g:UltiSnipsListSnippets` trigger - if it shows the snippets, the problem is with YCM.

**Comment by sandric** [comment]
@SirVer well, I tried to enter the snippet keyword and insert to command mode `call g:UltiSnipsListSnippets()` and it showed me enormous amount of file listing, don't know if it was what you asking for). calling expand snippet from command mode working though.

**Comment by SirVer** [comment]
@sandric: that was not quite what I meant - I meant to trigger the key bindings that you used for  listing snippets - https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L247. I guess though from you explanations that UltiSnips finds everything and it is YCM not listing th - could you doublecheck with the trigger?

**Comment by sandric** [comment]
@SirVer oh, I didn't use any binding for that - it just popped up automaticly. I tried c-tab default anyway and it didn't do nothing.

**Comment by SirVer** [comment]
the `c-tab` is likely eaten by your terminal emulator. Could you give it a try in gvim or bind it to another key for testing real quick?

**Comment by mellery451** [comment]
well, my "me too" report above seems to have resolved itself, although I'm not sure how (no plugins updated or configs changed). I think it's possible I had an ephemeral syntax error in a snippet file, leading to omission. Sorry for any confusion.

**Comment by sandric** [comment]
hm, this one actually gets interesting one - if I set `g:UltiSnipsListSnippets` to some key in my .vimrc, its actually pops up, but not in ycm pop up, but in window below, which contains a list of snippets starting with this keyword for this language (which is right behaviour), and then there's a lite with 
`Type number and <Enter> or click with mouse (empty cancels):`

**Comment by SirVer** [comment]
sandric, that is the expected behavior. that is ultisnips built in selection screen - which is what all the people have to use that do not use a completer plugin. If the snippets you expect show up there, everything is fine and UltiSnips is working - so the problem is with the YCM integration.

**Comment by sandric** [comment]
looks like it smth similar to this one https://github.com/Valloric/YouCompleteMe/issues/1214

**Comment by sandric** [comment]
hm, oh well, think I should start over on ycm issue tracker then)
Thanks anyway though.

**Comment by Aster89** [comment]
I came to this page since my problem is the same, i.e. UltiSnips snippet are not displayed in YCM popup menu, but they are inserted after pressing expand trigger.
I can give you just one more information, which is maybe a big help in understanding what the problem and the solution are: It's enough that I open Vim's help (`:h<CR>`) to get everything work again.
