### ISSUE TITLE
UltiSnip not working when vim launched - issue 426 update

### ISSUE THREAD

**Issue by pdoak** [SirVer/ultisnips#491]
I am still having problems with this but have done some further work to narrow down the problem.

I am using the [YADR](https://github.com/skwp/dotfiles) set up so my vimrc looks like this:
```
filetype off

set rtp+=~/.vim/bundle/vundle/
set rtp+=~/.vim/vundles/ "Submodules
call vundle#rc()

" let Vundle manage Vundle (required)
Bundle "gmarik/vundle"

" YADR's vundles are split up by category into smaller files
" This reduces churn and makes it easier to fork. See
" ~/.vim/vundles/ to edit them:
runtime ruby.vundle
runtime languages.vundle
runtime git.vundle
runtime appearance.vundle
runtime textobjects.vundle
runtime search.vundle
runtime project.vundle
runtime vim-improvements.vundle

" The plugins listed in ~/.vim/.vundles.local will be added here to
" allow the user to add vim plugins to yadr without the need for a fork.
if filereadable(expand("~/.yadr/vim/.vundles.local"))
  source ~/.yadr/vim/.vundles.local
endif


"Filetype plugin indent on is required by vundle
filetype plugin indent on
```

It was suggested that because the vimrc does not have the `call vundle#begin()` and `call vundle#end() `, that the vimrc is broken. I don't think this is the case as I have changed the vimrc to include the `call vundle#begin()` and `call vundle#end()` and the problem still persists.

`verbose imap` on initial launch of vim shows these settings: 
```
i  <C-Tab>     * <C-R>=UltiSnips#ListSnippets()<CR>
	Last set from ~/.yadr/vim/bundle/ultisnips/autoload/UltiSnips/map_keys.vim
i  <C-E>       * <C-R>=UltiSnips#ListSnippets()<CR>
	Last set from ~/.yadr/vim/bundle/ultisnips/autoload/UltiSnips/map_keys.vim
```
After issuing a `:UltiSnipEdit` command, `verbose imap` shows this:
```

i  <S-Tab>     * <C-R>=g:UltiSnips_Reverse()<CR>
	Last set from ~/.vimrc.after
i  <C-Tab>     * <C-R>=UltiSnips#ListSnippets()<CR>
	Last set from ~/.yadr/vim/bundle/ultisnips/autoload/UltiSnips/map_keys.vim
i  <C-E>       * <C-R>=UltiSnips#ListSnippets()<CR>
	Last set from ~/.yadr/vim/bundle/ultisnips/autoload/UltiSnips/map_keys.vim
i  <Tab>       * <C-R>=g:UltiSnips_Complete()<CR>
	Last set from ~/.vimrc.after
```

It looks as though the reason why UltiSnips is not working on initial launch of vim is that the mapping for the <Tab> key is not being set. In my vimrc, I have the following code for UltiSnip:
``` 
let g:UltiSnipsEditSplit="vertical"
function! g:UltiSnips_Complete()
    call UltiSnips#ExpandSnippetOrJump()
    if g:ulti_expand_or_jump_res == 0
        if pumvisible()
            return "\<C-N>"
        else
            return "\<TAB>"
        endif
    endif

    return ""
endfunction

function! g:UltiSnips_Reverse()
    call UltiSnips#JumpBackwards()
    if g:ulti_jump_backwards_res == 0
        return "\<C-P>"
    endif

    return ""
endfunction

au BufEnter * exec "inoremap <silent> " . g:UltiSnipsJumpBackwardTrigger . " <C-R>=g:UltiSnips_Reverse()<cr>"
au BufEnter * exec "inoremap <silent> " . g:UltiSnipsExpandTrigger . " <C-R>=g:UltiSnips_Complete()<cr>"
let g:UltiSnipsJumpBackwardTrigger="<s-tab>"

let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsListSnippets="<c-e>"
" this mapping Enter key to <C-y> to chose the current highlight item
" and close the selection list, same as other IDEs.
" CONFLICT with some plugins like tpope/Endwise
inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
``` 
My understanding of vim is that these two lines from my vimrc should be executed on entering a buffer:
```
au BufEnter * exec "inoremap <silent> " . g:UltiSnipsJumpBackwardTrigger . " <C-R>=g:UltiSnips_Reverse()<cr>"
au BufEnter * exec "inoremap <silent> " . g:UltiSnipsExpandTrigger . " <C-R>=g:UltiSnips_Complete()<cr>"
```
Therefore, the <Tab> mapping should get triggered but clearly that is not happening. Does anyone have any idea how to get this to work.

Many thanks

**Comment by SirVer** [comment]
This is hard to debug without your specific setup, but it is very, very likely not a UltiSnips bug, but a bug in your setup. Likely the `ftdetect/UltiSnips.vim` file is not sourced - this is an indication of a wrong vimrc. You need more than just `vundle#start` and `vundle#end`, you also need `nocompatible` at the right place and

~~~
call vundle#end()            " required
filetype plugin indent on    " required
~~~

My suggestion is to start from the minimal vundle config that is listed in the vundle README.md and move from there. Your setup seems very complicated - it is likely that it violates some of the many weird assumption Vim has. 

Closing as this is not an UltiSnips issue until proven. I will continue to provide assistant as much as I can though.

**Comment by pdoak** [comment]
Thanks for the quick reply. I will try your suggestion. 

You kindly said that you would provide assistance - should I continue to post to this thread or should I communicate in another method as you feel that it is not a UltiSnip issue.

Many Thanks

Paul

**Comment by SirVer** [comment]
feel free to use this issue. If we figure out what the problem was it can help other people with the same problem in the future.
