### ISSUE TITLE
[FEATURE REQUEST] adding personal snippet-directory to the search path automatically

### ISSUE THREAD

**Issue by ikcalB** [SirVer/ultisnips#494]
What about *automatically* adding the **personal** snippets directory (if specified)
``` vim
let g:UltiSnipsSnippetsDir = '~/.templates/vim/UltiSnips/'
```
to the snippet search path:
``` vim
let g:UltiSnipsSnippetDirectories = [$HOME.'/.templates/vim/UltiSnips/']
```

Both options, as above, are necessary to use the snippets from my `~/.templates/vim/UltiSnips/` directory. (If deploying to multi-user systems, I'd rather like to specifiy a system-wide absolute search-path, and have the personal folder in the search-path automatically)

*marginalia*
as shown above, one cannot use `'~'` in the search path (it does not expand)

**Comment by SirVer** [comment]
Those two variables are already terribly complicated and loaded with a ton of historic ballast - I'd rather not add any more features to them, not even for ergonomic's sake.

**Comment by ikcalB** [comment]
Then, that is fine for me!
