### ISSUE TITLE
[FEATURE REQUEST] default value for '${VISUAL}' placeholder

### ISSUE THREAD

**Issue by ikcalB** [SirVer/ultisnips#496]
this is a low priority|niceto have feature:
when inserting a snipped 
``` snip
snippet if "if .. else"
if (${1:/* condition */}) {
	${VISUAL}${2:/* statements */}
}${0}
endsnippet
```
obviously, the default value of ${2} will only be overridden, when not inserting from visual mode.

Still, some parameter description might come in handy, when inserting this snip empty (maybe this is not the most obvious case, though)

**Comment by SirVer** [comment]
Did you [see this](https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L714)? I am confused what the request is here.

~~~
snippet if "if .. else"
${VISUAL:this is a default text}
endsnippet
~~~

Closing for now, will reopen as soon as I understand the problem.

**Comment by ikcalB** [comment]
Sorry, I was really unclear. Let me further explain this:
"/* default */" in `${VISUAL:/* default */}` does work for providing a value, when not snipping from visual mode.

BUT when not snipping from visual mode, <kbd>TAB</kbd> DOES NOT STOP at "/* default */".  
This is the intended behavior imho. Because when not snipping from visual mode, I still want to change the provided default, as with every other snippet!

Hope this is more clear now

**Comment by SirVer** [comment]
I still don't get it.... It sounds to me you want this: `${1:${VISUAL:default}}` or 
~~~
${1:`!p snip.rv = snip.v.text or "default"`}
~~~

If that is not what you want, could you make a short snippet and a couple of usage examples to point out what you cannot achieve?

**Comment by ikcalB** [comment]
@SirVer this seems to work as intended! Idk, but at that time I didn't come up with that myself.
(please excuse my late reply)

**Comment by ikcalB** [comment]
@SirVer your proposed solution has one minor flaw (as I encountered while testing).
What already works:
- enter some default value, which is to be a tab stop (starting to type, after changing to that tabstop, replaces the default value entirely)
- when inserting the same snippet in visual mode, I want the selection to replace the default value

What I want:
- when inserting that snippet in visual mode, I WOULD NOT WANT a tab stop on the selection.  
Because starting to type, after changing to that tabstop, would replace the entire visual selection
- place the cursor AFTER the content from the visual selection, without selecting that content (or as an [configurable] alternative, just skip that tabstop

consider the following snippet (c preprocessor directive):
```
snippet #if "#if .. #endif"                                                                                        
#if ${1:0}
${2:${VISUAL:\/\/ default value}}
#endif${0}
endsnippet
```
Can you get, what I'm trying to explain?

**Comment by SirVer** [comment]
You can not have conditionally more or less tabstops in the snippet right now - there is already a feature request open for that. That means what you want is not currently possible.

**Comment by ikcalB** [comment]
So that is, what my feature request was about, finally.

Tnx for clarifying
