### ISSUE TITLE
[BUG] Regex matching

### ISSUE THREAD

**Issue by ikcalB** [SirVer/ultisnips#497]
I'm trying to check for valid naming for:  
 (just for fun; i know, the compiler would complain anyways)
- MACRO names
- names of variables
- names of types in definitions (for loop, typedef,...)

## BEHAVIOR
If the regex *group* DOES NOT match, I always get the complete string, what is obviously wrong.
Even the ternary operator does not work as expected; see the following snippet:
(checking for [_a-zA-Z0-9] with *no leading* digit)
``` snip
snippet #ifndef "#ifndef ... #define ... #endif"
#ifndef ${1/^([_a-zA-Z]+[_a-zA-Z0-9]*).*/(?1:VALID:INVALID)/}
#define ${1:SYMBOL} ${2:/* value */}
#endif${0}
endsnippet
```
with this snippet, I can only get "VALID" or exactely the string i typed (i.e. "0MAX_ANYTHING")

ofc, this does not work as expected either:
``` snip
#ifndef ${1/^([_a-zA-Z]+[_a-zA-Z0-9]*).*/$1/}
```
what incorrectly too, gives the full string always.
## EXPECTED BAHAVIOR
return nothing, or an OBVIOUS error string

**Comment by SirVer** [comment]
Your regular expression is flawed - it does not match the tabstop 1 for an INVALID identifier, so there will no replacement triggered. You can fix that by inserting a catch all clause like so:

~~~
snippet #ifndef "#ifndef ... #define ... #endif"
#ifndef ${1/^([_a-zA-Z]+[_a-zA-Z0-9]*)|.*/(?1:VALID:INVALID)/}
#define ${1:SYMBOL} ${2:/* value */}
#endif${0}
endsnippet
~~~

**Comment by ikcalB** [comment]
Thank You Sir!

This does work PARTIALLY:

As the standard dictates, no special characters are allowed for MACRO names.
I'm using the updated snippet, as below:
```
snippet #ifn "#ifndef #define #endif"
#ifndef ${1/^([_a-zA-Z]+[_a-zA-Z0-9]*).*|.*/(?1:$1:\/* INVALID SYMBOL NAME *\/)/}
#define ${1:SYMBOL} ${2:/* value */}
#endif${0}
endsnippet
```

When I begin to type some invalid string like `-INVAL...` (starting with a `-`), the above snipped does work - the value is replaced with "/* INVALID SYMBOL NAME */".

When I begin to type something valid and insert a bad character, for example: `VALID_UNTIL-now` - the value is updated until the `-` is encountered. Nothing seems to happen, until I delete back until everything matches the regex again?

**Comment by ikcalB** [comment]
NEVERMIND - ofc, still wrong regex. (Did not watch out when adding the catchall clause)

This works as intended:
```
snippet #ifn "#ifndef #define #endif"
#ifndef ${1/^([_a-zA-Z]+[_a-zA-Z0-9]*)$|.*/(?1:$1:\/* INVALID SYMBOL NAME *\/)/}
#define ${1:SYMBOL} ${2:/* value */}
#endif${0}
endsnippet
```
