### ISSUE TITLE
vim-snippets required to load personal snippets?

### ISSUE THREAD

**Issue by alexlafroscia** [SirVer/ultisnips#499]
I've trying to get away from the "default" `vim-snippets` package to just define ones that I really use/want.  I went and uninstalled the `vim-snippets` package, but ultisnips seemed unable to find my snippets after that.  It was able to locate the file correctly when I used `:UltiSnipsEdit`, but none of the completions actually worked.  If I re-install `vim-snippets`, it all works again.

Is it intentional that there is this dependency on the other package?  Or maybe just something weird with my configuration?

**Comment by SirVer** [comment]
No, there is no dependency. Can you post your `.vimrc` and detail your directory layout under `~/.vim/.

**Comment by alexlafroscia** [comment]
My `.vimrc` is broken into multiple files and might be a pain to browse through, but you can find it [here](https://github.com/alexlafroscia/dotfiles/tree/master/vim).

While working today, I realized that even with `vim-snippets` installed, custom-defined snippets aren't recognized.  Under `~/.vim` I have an `UltiSnips` directory.

`g:UltiSnipsSnippetsDir` is set to `~/.dotfiles/vim/UltiSnips`, and I have my custom files in there, although they are never used.

**Comment by SirVer** [comment]
Is that path on your `rtp`? Otherwise it will not be searched for snippets.

**Comment by alexlafroscia** [comment]
Yes, it is.  I'm a little new to writing Vim config aside from copy/pasting from pros -- is there anything wrong with this?

```
let &runtimepath = "$HOME/.dotfiles/vim, " . &runtimepath

**Comment by SirVer** [comment]
No that should be `:set rtp+=...` and I am not sure if `$HOME` is expanded. See `:help runtimepath`

**Comment by alexlafroscia** [comment]
Would I use `:set` in the `.vimrc` file? Or should I use `let`?

**Comment by SirVer** [comment]
You would use `set`. Please see the vim docs. 

I suspect that this is a configuration issue on your part, please see the Vim docs how to configure it. In the meantime I suggest using the UltiSnips default settings and symlink ~/.vim/UltiSnips to ~/.dotfiles/vim/UltiSnips or wherever you have your snippets - than everything should just work. 

Closing this as it does not seem to be a bug for now. Feel free to speak up if you disagree.

**Comment by alexlafroscia** [comment]
No, I'm sure you're right. Thanks for the help, I really appreciate it!
