### ISSUE TITLE
& does not work as tab_trigger with word boundary option inside parentheses

### ISSUE THREAD

**Issue by raine** [SirVer/ultisnips#500]
Is this a property of special characters or a bug?

### `&` as tab trigger

```
snippet & "arguments" w
arguments
endsnippet
```

```
foo(&<TAB>) # does not work
&<TAB> # works
```

--

### single character

```
snippet a "arguments" w
arguments
endsnippet
```

```
foo(a<TAB>) # works
a<TAB> # works
```

**Comment by SirVer** [comment]
See https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L617. This depends on the vim setting of `iskeyword`. Try using option `i` or use a regular expression trigger.
