### ISSUE TITLE
Installation instructions using pathogen are not updated and not working

### ISSUE THREAD

**Issue by gabri470** [SirVer/ultisnips#501]
Following instructions in Readme file to install ultinsnips using pathogen are not working properly.

$ git submodule add git://github.com/SirVer/ultisnips.git bundle/ultisnips 

$ fatal: Not a git repository (or any parent up to mount point /home)
   Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

**Comment by edi9999** [comment]
I think it should be 

`cd ~/.vim && git clone git://github.com/SirVer/ultisnips.git`

**Comment by gabri470** [comment]
which means that the installation instructions are not updated.

**Comment by SirVer** [comment]
Would you mind sending a pull request?

**Comment by SirVer** [comment]
I am asking because I see it correctly in the docs: https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L135

Or is that incorrect?

**Comment by gabri470** [comment]
Hi,

if I run the commands exactly as stated in https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L135, I end up with the error reported in the message. I was able to install pathogen with the clone command instead of the submodule add

**Comment by SirVer** [comment]
Could you give me the exact commands? I am not using pathogen and have not for years, so things might have changed. I'd gladly post working commands in the docs.

**Comment by gabri470** [comment]
cd ~/.vim && git clone git://github.com/SirVer/ultisnips.git

**Comment by SirVer** [comment]
Fixed now. sorry for taking so long.
