### ISSUE TITLE
Language specific snippets are never loaded

### ISSUE THREAD

**Issue by edi9999** [SirVer/ultisnips#502]
I'm running neovim and it seems like I can't have language specific snippets:

Here is my the relevant part of my .vimrc

```
" Track the engine.
Plugin 'SirVer/ultisnips'

" Snippets are separated from the engine. Add this if you want them:
Plugin 'honza/vim-snippets'

" Trigger configuration. Do not use <tab> if you use https://github.com/Valloric/YouCompleteMe.
let g:UltiSnipsExpandTrigger="<c-l>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"
```

If I type `c` than `<c-l>`, I get 

```
1: (c)) (/home/edi/.vim/bundle/vim-snippets/snippets/_.snippets:4)
Type number and <Enter> or click with mouse (empty cancels):
```

If I type `class` than `<c-l>`, nothing seems to happen.

I'm in a file called Payment.php and when I run `:set filetype` , I get ` filetype=php` as expected.

What could be the error ?

**Comment by edi9999** [comment]
After investigating, it seems to be because of the line :+1: 

`filetype plugin indent on`

that apperas before all the other code.

However, I still don't understand exactly how this interferes with the plugin

**Comment by SirVer** [comment]
Where did you find the installation instructions? Vundle/Vim is very peculiar about ordering of configuration in the .vimrc.

Closing, as this is not an UltiSnips issue. If you disagree, please feel free to speak up.

**Comment by edi9999** [comment]
Do you have an idea of why that line  interferes ? It is quite unexpected  .

**Comment by edi9999** [comment]
I found the installation instructions from the readme

**Comment by SirVer** [comment]
Which readme? UltiSnips or Vundles? 

> Do you have an idea of why that line interferes ? It is quite unexpected .

Please post your full vimrc - otherwise I cannot answer that question.
