### ISSUE TITLE
Python, 'snip += line' does not include a new line

### ISSUE THREAD

**Issue by dadaphl** [SirVer/ultisnips#504]
Hello
according to the documentation the += operator is suppose to add a new line (\n). in the end everything is in the same line though 

    snip += line:
            Equivalent to "snip.rv += '\n' + snip.mkline(line)"

snippet:

    snippet test
    ${1:`!p
    snip.rv += "Line1"
    snip.rv += "Line2"
    `}
    endsnippet

result

    Line1Line2

expected result    
    
    Line1
    Line2

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled May  7 2015 19:39:25)
MacOS X (unix) version
Python 2.7.8_2

**Comment by dadaphl** [comment]
never mind, now i got it!, snip += is not the same as snip.rv +=, didnt see that for one hour!

**Comment by SirVer** [comment]
:) happens.
