### ISSUE TITLE
Issue with g:UltiSnipsSnippetDirectories

### ISSUE THREAD

**Issue by raine** [SirVer/ultisnips#505]
As per documentation

> If only one directory is specified in this variable and this directory is
> specified by absolute path, UltiSnips will not look for snippets in
> &runtimepath, which can lead to significant speedup. So, the common case is:
> 
>    `let g:UltiSnipsSnippetDirectories=[$HOME.'/.vim/UltiSnips']`

I'm using 

```viml
let g:UltiSnipsSnippetDirectories=[$HOME.'/.vim/UltiSnips']
let g:UltiSnipsEnableSnipMate = 0
```

Yet, UltiSnips is using snippets from `~/.vim/bundle/vim-snippets/UltiSnips/`

Any idea what might be wrong? Thanks.

**Comment by SirVer** [comment]
qq: Why do you even track vim-snippets if you do not want the snippets from it?

The `g:UltiSnipsEnableSnipMate` has nothing to do with this - but the second setting is definitvely behaving has described in the docs, [here is the link](https://github.com/SirVer/ultisnips/blob/master/pythonx/UltiSnips/snippet/source/file/ultisnips.py#L35) to the implementation.

There are a couple of things I can think of: do you change the variable in another place? Doublecheck by running `:verbose let g:UltiSnipsSnippetDirectories` in the file that shows wrong behavior. Or could it be that you have a rogue symlink somewhere that conects ~/.vim and ~/.vim/bundle somehow?

**Comment by SirVer** [comment]
ping?
