### ISSUE TITLE
expanding Ultisnips

### ISSUE THREAD

**Issue by rudrab** [SirVer/ultisnips#516]
Hi,
I have a map, which is working as:
`:execute 'imap `prg prg' . g:UltiSnipsExpandTrigger . '<Esc>gg=G<C-j>'`

from inside ftplugin. So, in vim's insert mode, I press `prg, it expands Snippet prg

But, when I call it from vim's status line as it is, or as:
`:execute prg . g:UltiSnipsExpandTrigger . '<Esc>gg=G<C-j>'`

it gives error:
```E115: Missing quote: '```
```E15: Invalid Expression: 'imap `prg prg' . g:UltiSnipsExpandTrigger . '```

This is definitely not an issue, but I failed to solve it in irc and stackexchange.
It will be very helpful if I get it to work here.
Kindly help.

**Comment by SirVer** [comment]
It will not work in the status line - it requires vim insert mode and even sends keystrokes. So there is currently no way of expanding it in the status line.
