### ISSUE TITLE
[Feature Request] Integration with deoplete

### ISSUE THREAD

**Issue by HerringtonDarkholme** [SirVer/ultisnips#517]
I'm just suggesting the possibility of integration with [deoplete](https://github.com/Shougo/deoplete.nvim).  

Deoplete is the next generation completion plugin for neovim. While still in alpha stage, both neovim and deoplete are quite stable.

Integration with deoplete is not hard, given UltiSnip's python implementation.(e.g https://github.com/Shougo/neosnippet.vim/blob/master/rplugin/python3/deoplete/sources/neosnippet.py)

I can put similar file in my own `.nvim`, but I'm more glad that UltiSnip will play well with deoplete out of box.

**Comment by Shougo** [comment]
Well, the deoplete sources API is not stable.
it may be changed.

**Comment by HerringtonDarkholme** [comment]
oh.. I can put it in my own .nvim for now

**Comment by SirVer** [comment]
A pull request is welcome once shougos new plugin is stabilized. I'd rather not have it right now if there are chances that it breaks soonish down the line.

**Comment by simonweil** [comment]
Any chance this can be revisited?
AFAIK, deoplete is now stable.

**Comment by Shougo** [comment]
deoplete will be version 1.0 in 11/22.

**Comment by SirVer** [comment]
@simonweil I will not work on this, but I gladly merge a contribution.

**Comment by domi91c** [comment]
I'd just like to be able to use tab for both UltiSnips and Deoplete. Is that possible? I've had no luck.

**Comment by Shougo** [comment]
deoplete UltiSnips support is already merged.
If it is not work, you should create new issue with minimal configuration and the reproduce ways.

**Comment by simonweil** [comment]
The deoplate support for the source is merged but tabing and enter do not work nicely out of the box.

I made it work with a few custom functions and mappings:
https://github.com/simonweil/dotfiles/blob/master/nvimrc#L29-L85

I use supertab though I'm not sure it's needed.
Any comments and suggestions are welcome.

**Comment by chrisnicola** [comment]
@simonweil (or anyone) do you know if it is possible to get autocompletion to work with mirrored tab stops. Such as:

```
snippet mySnippet
    ${1:Something}
    $1
```

I find that if I allow the first tab to be completed by deoplete the mirror will stop being updated and stop at whatever I started typing before it was completed.

**Comment by Shougo** [comment]
The text cannot be updated when the popup exists...

**Comment by chrisnicola** [comment]
@Shougo yeah I was getting that impression. That's too bad. Oh well.

**Comment by Shougo** [comment]
It is Vim/neovim's feature.

**Comment by app** [comment]
Did not find right place to leave this usefull (thanks to Shougo) notice about Configuring Deoplete to work with snippets.
add to init.vim
```
call deoplete#custom#set('ultisnips', 'matchers', ['matcher_fuzzy'])
```
or you'll miss snippets with short (single or double char) names from Deoplete completion list :(

For example many php.snippets snippets will be hidden from your eyes without this command in config.
