### ISSUE TITLE
CursorMoved(I) autocmds better be temporary

### ISSUE THREAD

**Issue by BohrShaw** [SirVer/ultisnips#518]
These auto-commands are so expensive(even :python is invoked) that I believe they should be temporary. Actually the one from `$VIMRUNTIME/plugin/matchparen` is the only global CursorMoved(I) autocmd in my setup.

Sample codes in  [SnipMate](https://github.com/garbas/vim-snipmate/blob/master/autoload/snipMate.vim#L67):
```viml
aug snipmate_changes
	au CursorMoved,CursorMovedI <buffer> if exists('b:snip_state') |
				\     call b:snip_state.update_changes() |
				\ else |
				\     silent! au! snipmate_changes * <buffer> |
				\ endif
aug END
```

I've been tolerating the delay(especially when in an underpowered VM) caused by these auto-commands for very long and really hope this situation can be improved.

**Comment by SirVer** [comment]
> I've been tolerating the delay(especially when in an underpowered VM) caused by these auto-commands for very long and really hope this situation can be improved.

I hope you also tolerate the features that UltiSnips provides you :) 

How about you conjecture a patch and a pull request?

**Comment by bohrshaw** [comment]
@SirVer :) I feel I don't have enough time these days and haven't look into the project in details. So I just *fired* the issue, for now! (Forgive me if I've used some inaccurate words. I still need to refer the English Dict for proper language usage as during this writing.)

**Comment by ajzafar** [comment]
@bohrshaw I'm a little confused as to whether this issue is meant for UltiSnips or SnipMate, but in SnipMate those autocommands should only exist while you have a snippet expanded. They're created at the location you linked and [should be destroyed when the snippet is removed](https://github.com/garbas/vim-snipmate/blob/master/autoload/snipmate/jumping.vim#L15-L20). The conditional is only there as a work around for garbas/vim-snipmate#128, a rare bug where the state variable is destroyed before the snippet is finished.

**Comment by bohrshaw** [comment]
@ajzafar I referred SnipMate for a possible similar solution to this issue. 

But UltiSnips allows in-snippet jumping even after returning from normal-mode, in which case I think a different key can be used to escape from insert-mode and meanwhile to cancel the auto-commands, in another way to say, quit UltiSnips.

**Comment by SirVer** [comment]
Mhh - the autocommand does only necessary state keeping when there is no snippet in place - and that is not very much work. Can you back up your claim that it is slow with timing measurements?

**Comment by bohrshaw** [comment]
I just did a simple profiling on the latest neovim with python3 on a Arch Linux VM under Windows and got:

    FUNCTION  UltiSnips#CursorMoved()
    Called 40 times
    Total time:   0.569387
     Self time:   0.569387
    
    count  total (s)   self (s)
       40              0.568927     exec g:_uspy "UltiSnips_Manager._cursor_moved()"
    
    FUNCTIONS SORTED ON TOTAL TIME
    count  total (s)   self (s)  function
       40   0.569387             UltiSnips#CursorMoved()
    
    FUNCTIONS SORTED ON SELF TIME
    count  total (s)   self (s)  function
       40              0.569387  UltiSnips#CursorMoved()

It's 0.014235s per move, which is noticeable, especially when in a macro.
And for fun and comparison(Linux is a VM, time in ms):

nvim on Arch|vim on Arch|nvim on Ubuntu|vim on Ubuntu|gvim on Windows
------------|-----------|--------------|-------------|---------------
14.235(8.046 in a second test)|0.7147538(0.5078079)|11.829|0.4865462|0.31076

It's obvious that invoking python on every cursor move could better be avoided if we can, especially when considering the new architecture of neovim.

**Comment by SirVer** [comment]
Amazing! thanks for getting the run down here. nvim really looks horrible ....

Could you detail how you did the profiling? Your approach seems more professional than the one I usually use for inside vim profiling. Maybe we can turn that into a benchmark of sorts.

**Comment by bohrshaw** [comment]
I used this command after several manual testing: (may replace vim with nvim)

`vim +"sleep 2|execute 'normal 22ifoo'|profile start t|profile func UltiSnips#CursorMoved|execute repeat('doautocmd UltiSnips CursorMoved,CursorMovedI|', 222)|profdel *|q\!"`

The profiling result is in the file `t`. (I put some extras in the command to mimic the real editing scenario, though not identical to a manual testing. But the result is close.)

I *tolerate* nvim being *horrible* in this case. :)

**Comment by BohrShaw** [comment]
A little bit excited, Thanks! @SirVer
