### ISSUE TITLE
execute normal mode commands on snippet insertion

### ISSUE THREAD

**Issue by atomfried** [SirVer/ultisnips#520]
Hi there,
first of all thanks for your work -- great plugin.
Is there a way to make something like this happen:

    snippet foo
    This goes to the trigger position.
    `!v execute "normal :1OThis goes to the top of the file.\<ESC>"\`
    endsnippet

The above doesn't work as v! seems to be expecting a variable. 

Update: Instead of using execute I can call a function, however I still can't use the normal command:
> error: Vim(normal):E523: Not allowed here

Take care
M

**Comment by SirVer** [comment]
Nochanging the buffer will screw up UltiSnips. However https://github.com/SirVer/ultisnips/pull/507 will give you hooks into this with python scripting - you can then change the buffer with python and UltiSnips will know about it.

**Comment by seletskiy** [comment]
@atomfried: It's already possible with (yet) unmerged branch `snippet-actions`. Consider using my fork till it will be incorporated into upstream.

You can fix your issue by following syntax:
```
pre_expand "snip.buffer[0:0] = ["This goes to the top of the file"]
snippet foo
This goes to the trigger position.
endsnippet
```
