### ISSUE TITLE
How use the version 7.2

### ISSUE THREAD

**Issue by xavierartot** [SirVer/ultisnips#524]
Hi,
I have some trouble to update Vim in Mac and Yosemite and Ultisnips works only with Vim 7.4.
How can I have the version 7.2  and use Bundle.
Thanks

**Comment by SirVer** [comment]
Older released versions of UltiSnips work with older vim versions. So do older commits in this repo - you have to dig through for them

As for how to install them using vundle - I do not know. That is also out of scope for UltiSnips - please see the vundle docs or ask the vundle community about that.

**Comment by ingkebil** [comment]
Just my two cents:
You can install Ultisnips like normal with vundle. Then cd into the bundle location, usually something like: `cd ~/.vim/bundle/ultisnips`. You can then checkout commit `de70b1e` which is the commit before ultisnips required 7.4.

**Comment by ingkebil** [comment]
Also: https://github.com/VundleVim/Vundle.vim/issues/35
