### ISSUE TITLE
Match after underscore and dot

### ISSUE THREAD

**Issue by dani-h** [SirVer/ultisnips#525]
Is it possible to perform snippet matches only after underscore and dot? So for the following example if I pressed "_." these results would pop up 
_.capitalize
_.endsWith
```
snippet _.capitalize "_.capitalize(str)"
_.capitalize.(${1:str})
endsnippet

snippet _.endswith "_.endsWith(str, str)"
_.endsWith(${1:str}, ${2:str})
endsnippet
```

I have tried doing this with regular expression matching, but the snippets don't seem to show up in the list.

**Comment by SirVer** [comment]
Regular expression snippets do not show up in the list, this is https://github.com/SirVer/ultisnips/issues/177. But they will still work.
