### ISSUE TITLE
Cannot jump to tabstops after returning to normal mode

### ISSUE THREAD

**Issue by davidlowryduda** [SirVer/ultisnips#526]
Let's say I have a generic snippet in tex.snippets

```vimL
snippet testing "generic test" b
This ${1:is} a completely
generic ${2:test} of UltiSnips
largely amazing ${3:functionality}.
```

I can expand the snippet (currently mapped to <leader>E for me) after typing testing. And I can immediately jump (currently mapped to c-j for me) to $2 and $3. But if I return to normal mode immediately after expanding the snippet, then hitting c-j does not bring me to $2 or $3.

My investigations have led me to some strange behavior. I have a large snippet (a TeX document template) with 4 tabstops, and I *can* jump to $2, $3, $4 after escaping to normal mode if I re-enter insert mode and hit c-j from there. If I try `:verb imap <c-j>` or `:verb smap <c-j>` right then, it says my .vim/bundle/Ultisnips/autoload/UltiSnips.vim as expected. It does not recognize `:verb nmap <c-j>` at all. I do not know (nor do I see it in the documentation) if it is by design, but I also believe that navigating outside of the snippet completely clears <c-j> UltiSnips maps. I do not yet understand what it is that is resetting this mapping, but soon it acts like the standard CTRL-J: just like j in normal mode, and adding a line in insert mode.

If I expand another snippet, imap and smap temporarily gets remapped to UltiSnips#JumpForwards() as expected.

To answer some of the standard questions: I've updated everything (or rather had Vundle update everything). I've tried with only Vundle and UltiSnips installed on a variety of different filetypes. If I explicitly type `:call UltiSnips#JumpForwards()` before navigating outside the body of the snippet, it correctly takes me to the next tabstop and highlights it in select mode.

I'm attaching my minimal testing vimrc here.

```vimL
set nocompatible
filetype off                    " required for vundle!

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle
" required!
Plugin 'gmarik/Vundle.vim'

Plugin 'SirVer/UltiSnips'
Plugin 'honza/vim-snippets'

call vundle#end()               " required
filetype plugin indent on       " required too!


let mapleader = ','
let g:UltiSnipsExpandTrigger='<leader>E'
let g:UltiSnipsJumpForwardTrigger='<C-j>'
```

**Comment by SirVer** [comment]
UltiSnips does not set any normal mode mappings. So jumping only ever works in insert mode. 

What would be your expected behavior when jumping in normal mode? To enter select mode/insert mode over the next trigger?

**Comment by davidlowryduda** [comment]
Yes, my expected behavior when jumping in normal mode would be to select mode/insert mode over the next trigger. That seems deeply intuitive to me, I suppose.

I'm also interested in when exactly  I cannot continue to jump (even in insert mode). For instance, if I navigate outside of the inserted snippet, are the tabstops lost? (Presumably they're in some stack or queue --- is this cleared once I navigate outside the snippet?)

**Comment by SirVer** [comment]
How about you add a `:nmap <ultisnips jump trigger> i<ultisnips jump trigger>` to your vimrc?

Yes, once you leave the snippets bounds, the snippet is exited, i.e. dropped. The reason is that while a snippet is active, each cursor movement triggers an expensive diff of the current buffer state to the last which we do not want to keep up if you are not actively using the snippet anymore. The same happens wen you reach the last tabstop ($0) in a snippet.

**Comment by SirVer** [comment]
I do not think UltiSnips should set any normal mode mappings. Does my suggestion work for you?

**Comment by davidlowryduda** [comment]
Thank you for letting me know. Thd constant diff'ing makes sense to me.

I actually do have an `:nnoremap` set (to manually call `UltiSnips#JumpForwards()` which works for me. Thank you again.
