### ISSUE TITLE
Imap expansion breaks nested snippets

### ISSUE THREAD

**Issue by yubo56** [SirVer/ultisnips#528]
Dear all,

I'm trying to use imap to insert a snippet and it's messing up the nesting of snippets. If anybody has a better idea of how to insert a snippet without having to press <tab>, appreciated!

I have a snippet, say, something like
```
snippet test "Test" i
Test ($1) worked! $0
endsnippet
```
and an imap such as
```
imap abc test<tab>
```
or even
```
inoremap <silent> abc test<C-R>=UltiSnips#ExpandSnippetOrJump()<cr>
```
as it is done in `ultisnips/autoload/UltiSnips/map_keys.vim`. This works marvelously the first time I type `abc`, expanding the snippet, but if I try to type `abc` again while still within the `$1` of the first snippet, the tags on the outer snippet become mispositioned. e.g., when I'm at
`Test (Test (text) worked! <cursor>) worked!`
having just forward-jumped my way out of the inner snippet, if I forward-jump again (expecting to go after the last exclamation point) I instead find myself somewhere like
`Test (Test (text) worked!) work<cursor>ed!`

This isn't an issue when I manually type `test<tab>`, only with the imap. I'm suspecting that the imap somehow screws up the position of the outer $0 marker. Is there any reason for this, and of course can it be fixed?

Alternatively, if anybody has any good ideas to trigger snippets without <tab> press, that would be appreciated. I checked the issue https://github.com/SirVer/ultisnips/issues/401 but both the `feedkeys` based and `anon` solution produce the same behavior; I include what I have tried below.
```
inoremap <silent> abc test<C-R>=UltiSnips#Anon('Test ($1) worked!$0', 'test', 'Test', 'i')<cr>
```
and
```
imap abc <C-R>=ExpandSnippet("abc","test")<cr>

fun! ExpandSnippet(typed, snippet)
    cal feedkeys("\<tab>")  " for me, g:UltisnipsExpandTrigger = '<C-C>'
    return a:snippet
endf
```

**Comment by SirVer** [comment]
I can reproduce this - however I think it is hard to fix. UltiSnips is best tested for interactive use with expanding the snippets using a trigger key. Not using a trigger key like you try to do here will change the timing of the key presses that reach vims key buffer - and that changes Vim's internal behavior on how it processes these.

These issues are super hard to debug and the best solution you can find is a workaround inside UltiSnips. I will gladly review code that introduces workarounds for this case, but I will likely not spend the time to find them myself. Maybe neovim will rid us of this nonsense with a more solid implementation.

**Comment by yubo56** [comment]
Thank you for your speedy response!

Do you have any suggestions for where I would start looking for a workaround? I haven't looked at the python codebase yet so perhaps just a pointer to the file/function where the jumps are calculated or where the nested snippets are implemented would be super helpful.

**Comment by SirVer** [comment]
Nested snippets are kinda all over the place. I would start [here](https://github.com/SirVer/ultisnips/blob/master/pythonx/UltiSnips/_vim.py#L131) - that is the function that is selecting the next snippet - also zero length ones. Either the jump bug is in there (i.e. the location is correctly send to this function, but it fails to navigate there) or in the code that call this method (i.e. the location is already wrongly tracked).

**Comment by dNItro** [comment]
I think the point is what SirVir cite: *'timing of the key presses that reach vims key buffer'*. Anyway it seems changing the code like following regulate timing; if makes any help!
```
imap abc <C-R>=ExpandSnippet("abc","test")<cr>

fun! ExpandSnippet(typed, snippet)
    cal feedkeys("\<Esc>a\<tab>")  " for me, g:UltisnipsExpandTrigger = '<C-C>'
    return a:snippet
endf
```

**Comment by seletskiy** [comment]
@yubo56, @dNItro: please, use autotrigger feature for this.
