### ISSUE TITLE
Not listing snippets while in placeholder mode

### ISSUE THREAD

**Issue by moll** [SirVer/ultisnips#529]
Hey,

Listing snippets works okay in insert mode, but once you're expanding a snippet and inside a placeholder, the snippet listing key just inserts tabs (in my case, having left it to `<c-tab>`). Are you seeing this too?

**Comment by SirVer** [comment]
Nope, works for me. Maybe your snippets are not actually matching because of snippet options?

**Comment by moll** [comment]
You know, I'm unable to consistently reproduce this now too. I can get UltiSnips into a state where it first inserts a tab and does not list snippets, but I'm also using a custom jump-then-expand function. I don't have the time to debug this further right now, but should I find some, I'll readdress this. Thanks for the reply.
