### ISSUE TITLE
Can't make it work with Vundle and honza/web-snippets

### ISSUE THREAD

**Issue by bigbn** [SirVer/ultisnips#530]
set nocompatible
    filetype off

    " set the runtime path to include Vundle and initialize
    set rtp+=~/.vim/bundle/Vundle.vim
    call vundle#begin()
    " alternatively, pass a path where Vundle should install plugins
    "call vundle#begin('~/some/path/here')

    " let Vundle manage Vundle, required
    Plugin 'gmarik/Vundle.vim'

    " The following are examples of different formats supported.
    " Keep Plugin commands between vundle#begin/end.
    " plugin on GitHub repo
    Plugin 'tpope/vim-fugitive'
    " plugin from http://vim-scripts.org/vim/scripts.html

    " Track the engine.
    Plugin 'SirVer/ultisnips'

    " Snippets are separated from the engine. Add this if you want them:
    Plugin 'honza/vim-snippets'

    " Trigger configuration. Do not use <tab> if you use https://github.com/Valloric/YouCompleteMe.
    let g:UltiSnipsExpandTrigger="<tab>"
    let g:UltiSnipsJumpForwardTrigger="<c-b>"
    let g:UltiSnipsJumpBackwardTrigger="<c-z>"

    " If you want :UltiSnipsEdit to split your window.
    let g:UltiSnipsEditSplit="vertical"

    " All of your Plugins must be added before the following line
    call vundle#end()
    filetype plugin indent on
    " To ignore plugin indent changes, instead use:
    "filetype plugin on
    "
    " Brief help
    " :PluginList       - lists configured plugins
    " :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
    " :PluginSearch foo - searches for foo; append `!` to refresh local cache
    " :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
    "
    " see :h vundle for more details or wiki for FAQ
    " Put your non-Plugin stuff after this line

    syntax on
    set paste

All packages are installed and exist. Snippets folder is also right.

Can't make it work (tried on ubuntu, and on Arch with same null result)
Nothing happens when tab pressed. Maybe i miss something? How to debug it?

**Comment by bigbn** [comment]
[bigbn@bigbn ~]$ vim --version
    VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 29 2015 10:11:22)
    Заплатки: 1-764
    Скомпилирован  Arch Linux
    Огромная версия без графического интерфейса.  Включённые (+) и отключённые (-) особенности:
    +acl             +farsi           +mouse_netterm   +syntax
    +arabic          +file_in_path    +mouse_sgr       +tag_binary
    +autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
    -balloon_eval    +float           +mouse_urxvt     -tag_any_white
    -browse          +folding         +mouse_xterm     -tcl
    ++builtin_terms  -footer          +multi_byte      +terminfo
    +byte_offset     +fork()          +multi_lang      +termresponse
    +cindent         +gettext         -mzscheme        +textobjects
    -clientserver    -hangul_input    +netbeans_intg   +title
    -clipboard       +iconv           +path_extra      -toolbar
    +cmdline_compl   +insert_expand   +perl            +user_commands
    +cmdline_hist    +jumplist        +persistent_undo +vertsplit
    +cmdline_info    +keymap          +postscript      +virtualedit
    +comments        +langmap         +printer         +visual
    +conceal         +libcall         +profile         +visualextra
    +cryptv          +linebreak       +python          +viminfo
    +cscope          +lispindent      -python3         +vreplace
    +cursorbind      +listcmds        +quickfix        +wildignore
    +cursorshape     +localmap        +reltime         +wildmenu
    +dialog_con      +lua             +rightleft       +windows
    +diff            +menu            +ruby            +writebackup
    +digraphs        +mksession       +scrollbind      -X11
    -dnd             +modify_fname    +signs           -xfontset
    -ebcdic          +mouse           +smartindent     -xim
    +emacs_tags      -mouseshape      -sniff           -xsmp
    +eval            +mouse_dec       +startuptime     -xterm_clipboard
    +ex_extra        +mouse_gpm       +statusline      -xterm_save
    +extra_search    -mouse_jsbterm   -sun_workshop    -xpm
                общесистемный файл vimrc: "/etc/vimrc"
             пользовательский файл vimrc: "$HOME/.vimrc"
      второй пользовательский файл vimrc: "~/.vim/vimrc"
              пользовательский файл exrc: "$HOME/.exrc"
              значение $VIM по умолчанию: "/usr/share/vim"
    Параметры компиляции: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
    Сборка: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro -L/usr/local/lib -Wl,--as-needed -o vim        -lm -lncurses -lelf -lnsl   -lacl -lattr -lgpm -ldl  -L/usr/lib -llua -Wl,-E -Wl,-rpath,/usr/lib/perl5/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/core_perl/CORE -lperl -lpthread -lnsl -ldl -lm -lcrypt -lutil -lc -L/usr/lib/python2.7/config -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic   -lruby -lpthread -lgmp -ldl -lcrypt -lm  -L/usr/lib

**Comment by bigbn** [comment]
[bigbn@bigbn ~]$ tree ~/.vim -d
    /home/bigbn/.vim
    ├── bundle
    │   ├── ultisnips
    │   │   ├── after
    │   │   │   └── plugin
    │   │   ├── autoload
    │   │   │   ├── neocomplete
    │   │   │   │   └── sources
    │   │   │   ├── UltiSnips
    │   │   │   └── unite
    │   │   │       └── sources
    │   │   ├── ctags
    │   │   ├── doc
    │   │   ├── ftdetect
    │   │   ├── ftplugin
    │   │   ├── plugin
    │   │   ├── pythonx
    │   │   │   └── UltiSnips
    │   │   │       ├── snippet
    │   │   │       │   ├── definition
    │   │   │       │   ├── parsing
    │   │   │       │   └── source
    │   │   │       │       └── file
    │   │   │       └── text_objects
    │   │   ├── syntax
    │   │   ├── test
    │   │   └── utils
    │   ├── vim-fugitive
    │   │   ├── doc
    │   │   └── plugin
    │   ├── vim-snippets
    │   │   ├── autoload
    │   │   ├── plugin
    │   │   ├── pythonx
    │   │   ├── snippets
    │   │   │   ├── coffee
    │   │   │   └── javascript
    │   │   └── UltiSnips
    │   └── Vundle.vim
    │       ├── autoload
    │       │   └── vundle
    │       ├── doc
    │       └── test
    │           └── files
    └── UltiSnips

    44 directories

**Comment by SirVer** [comment]
you have `set paste` set in your vimrc. That means that vim will not intepret any mappings. read up on it.

**Comment by bigbn** [comment]
Thank you, now it works perfectly. Awesome plugin!

**Comment by SirVer** [comment]
thanks. spread the word!
