### ISSUE TITLE
Ultisnip parse error with select Snipmate snippets?

### ISSUE THREAD

**Issue by nemild** [SirVer/ultisnips#533]
Hi,

I'm using the latest ultisnips with vim-snippets - and am getting the following stack trace when using a Snipmate snippet (e.g., 'ifee', 'unlesee', 'unlesse')  from the snippets/ruby.snippets file:

```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

Following is the full stack trace:
Traceback (most recent call last):
  File "/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 56, in wrapper
    return func(self, *args, **kwds)
  File "/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 146, in expand_or_jump
    rv = self._try_expand()
  File "/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 616, in _try_expand
    self._do_snippet(snippet, before)
  File "/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 586, in _do_snippet
    None, start, end)
  File "/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet/definition/_base.py", line 278, in launch
    self.instantiate(snippet_instance, initial_text, indent)
  File "/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet/definition/snipmate.py", line 22, in instantiate
    parse_and_instantiate(snippet_instance, initial_text, indent)
  File "/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet/parsing/snipmate.py", line 44, in parse_and_instantiate
    _create_mirrors(all_tokens, seen_ts)
  File "/.vim/plugged/ultisnips/pythonx/UltiSnips/snippet/parsing/snipmate.py", line 30, in _create_mirrors
    Mirror(parent, seen_ts[token.number], token)
KeyError: 2
```

I switched the format of the snippet from the original:
```
snippet ifee
	if ${1:condition}
		$2
	elsif ${3:condition}
		$4
	else
		$0
	end
```

To this ($2, $4, and $0 now have braces around it):
```
snippet ifee
	if ${1:condition}
		${2}
	elsif ${3:condition}
		${4}
	else
		${0}
	end
```

And now it works.

I was going to send a pull request to fix a few areas where this happens, but I thought I'd check here first. Is the original format ok for Snipmate, but not for the Ultisnips parser for Snipmate? Or should I just go ahead and submit a pull request to fix this in the ruby.snippets file and let them know not to use the "\$\d" format going forward?

**Comment by SirVer** [comment]
Back when I implemented the support for snipMate it was a bug-for-bug/feature-for-feature implementation. `$1` was interpreted as a mirror, if there was no `${1}` it was an error.

They apparently changed this behavior. [This commit](https://github.com/garbas/vim-snipmate/commit/a59a3aea3574a5d4e3169d7d52e4839eec25029f#diff-d59870c017863be84045aee0ef4ed8a4R280) updates the documentation to reflect that. I am not sure if that is a backwards compatible change on their part, but it should be simple to support it in UltiSnips, since UltiSnips already did support this syntax that from the start.

**Comment by nemild** [comment]
Thanks for such a quick response and update!

**Comment by ajzafar** [comment]
This only works for version 1 of the SnipMate snippet parser, if you want to only target version 0. I [updated the docs](https://github.com/garbas/vim-snipmate/commit/9577da4a30fbabd37edddb186825718aefe6e93f) to clarify this.
