### ISSUE TITLE
Reloading global Python imports

### ISSUE THREAD

**Issue by moll** [SirVer/ultisnips#536]
Hey,

I've got a few Python files I load at the top of the snippets file to make their functions available. I've noticed when I change those Python files, their changes aren't reflected in the running instance. How would I ensure the files get reloaded?

Thanks a bunch!

**Comment by SirVer** [comment]
Unfortunately, that is not possible. You have to restart Vim. 

Python does not support reloading modules cleanly and Vim does not support to reload python modules at all.
