### ISSUE TITLE
UltiSnips leave trigger text when expanding snippets when filetype is set in modeline

### ISSUE THREAD

**Issue by seletskiy** [SirVer/ultisnips#542]
I've found bug which was introduced in commit c4ee3ec. Steps to reproduce:

* create file `/tmp/testfile`;
* write following to `/tmp/testfile`:
  ```
  # vim: ft=sh

  ```

* create snippet for `sh` filetype, e.g. (doesn't matter, actually):
  ```
  snippet a "alias" b
  alias
  endsnippet
  ```

* try to expand `a` in the `/tmp/testfile`:
  ```
  # vim: ft=sh
  a<TAB>
  ```

* see:
  ```
  # vim: ft=sh
  aalias
  ```

Commenting out following line (in the `pythonx/UltiSnips/snippet_manager.py`) will resolve issue:
```py
_vim.command('doautocmd User UltiSnipsEnterFirstSnippet')
```

I tried to define noop autocommand in my `.vimrc` for the `UltiSnipsEnterFristSnippet`, but it didn't help.

Also, this issue somehow linked with YouCompleteMe. Disabling YouCompleteMe resolves issue as well.

@wincent, you are probably interested in this issue.

**Comment by wincent** [comment]
I can repro this (thanks for all the detail). I think we want `<nomodeline>`; that resolves the issue:

```
_vim.command('doautocmd <nomodeline> User UltiSnipsEnterFirstSnippet')
```

From `:h :doautocmd`:

```
							*<nomodeline>*
			After applying the autocommands the modelines are
			processed, so that their settings overrule the
			settings from autocommands, like what happens when
			editing a file. This is skipped when the <nomodeline>
			argument is present. You probably want to use
			<nomodeline> for events that are not used when loading
			a buffer, such as |User|.
```

I'll whip up a patch.
