### ISSUE TITLE
Snippet with folder

### ISSUE THREAD

**Issue by xavierartot** [SirVer/ultisnips#547]
I have honza/vim-snippets and sirver/ultisnips installed, all with Vundle. 
I have confirmed that ~/.vim/bundle/vim-snippets/UltiSnips exists and is populated with snippets. 
But why I have two snippets folders?
vim-snippets/ snippets/
vim-snippets/UltiSnips/  
I want to print but which one I'll use?
Thanks

**Comment by SirVer** [comment]
Please post your full vimrc and check https://github.com/SirVer/ultisnips/issues/531 and https://github.com/SirVer/ultisnips/issues/530. It is likely that you have your vundle installation wrong or `set paste` in your configuration.

**Comment by SirVer** [comment]
Closing for now. If it is not a configuration error, I will reopen.
