### ISSUE TITLE
Snippet Does Not Expand, Trigger Function Not Working

### ISSUE THREAD

**Issue by nicodecker** [SirVer/ultisnips#554]
After using UltiSnips on Windows for some time now I desired to start using it under Linux now. However, I can't get expansion to work.

After pulling the trigger gvim/vim seems to shortly wait until the cursor starts to blink again.

UltiSnipsEdit brings me right to the snippet file I am also using under Windows successfully.
Python installation is ok. Expansion also does not work when typing the trigger function directly (\<c-r\>=UltiSnips#...). Thus, it cannot be a problem of mapping.

YCM does not complete the snippets either (as I am used to under Windows). Possibly this is a hint.

I tried the most recent commit (490430f), tag 3.0 and some others. There does not seem to be a difference.

**Comment by SirVer** [comment]
How is UltiSnips holding up on Windows? We didn't have a test suite for Windows in ~2 years so I feel least confident in it's performance there. 

Please post your .vimrc - it is likely related to your setup. Can you try with a snippets from all.snippets, i.e. not bound to a particular lifetime? If that works your ftdetect/UltiSnips.vim file is not properly sourced - that points to a wrong installation of your package manager.

**Comment by nicodecker** [comment]
Actually it does very well. I am using it for development in VIM quiete heavily and in Thunderbird ("external editor" plugin), too. Helps a lot. Thus, great job, by the way... ;-)

.vimrc is almost identical on both system. I'll post it later today. I tested with all.snippets anway (did not work, neither did c.snippets nor cpp.snippets). I didn't use a package manager (hands only...).

Installation went differently under Linux, however. Under Windows I extracted UltiSnips directly in ~/vimfiles. This time I worked with &rtp and UltiSnips' directory variables. Possibly this was the root of all evil...

**Comment by nicodecker** [comment]
Ok, I found the problem. Strangely :UltiSnipsEdit found the snippet files, but they were obviously not loaded unless I renamed directory ~/.vim/usnips to ~/.vim/UltiSnips and removed my .vimrc-setting g:UltiSnipsSnippetsDir="~/.vim/usnips".

It feels like a bug. However, it works now. So thanks anyway for your support.

**Comment by SirVer** [comment]
Not a bug, but really confusing interaction between the options. It is all documented, but you have to read carefully :/. We are stuck with these options for backwards compatibility reasons now too ....
