### ISSUE TITLE
ultisnips and neosnips in the same time

### ISSUE THREAD

**Issue by 7belrhalmia** [SirVer/ultisnips#555]
now neosnioppet help neocomplete to complete function prototype  and it's cool ,i wont to use it but ultisnips has the python interpolation that i love ,  they don't work together  , can you add a support for it

**Comment by SirVer** [comment]
I cannot parse your suggestion at all - the only thing I can grasp is that neosnippet is doing something that you wish ultisnips would do - but I do not understand what. I am closing this issue as it is non-actionable for me. 

If you feel strongly about this feature, please open a new issue. Try to use full sentences, proper punctuation, provide an example of what you would like to see and ideally a screencapture of what neosnippets does.
