### ISSUE TITLE
Breakline with ultisnips

### ISSUE THREAD

**Issue by chiru-L** [SirVer/ultisnips#558]
Hi, i dont know if here is the right place to answer this, but is possible to put line breaks in ultisnips ? example

jump = "\n"
if() {jump}{     
}
output
if()
{
}

I read the docs but cannt see anything like that, what i want is to changes styles without have to change snippets definitions one by one. Having jump in a var i could set jump = "" if i just want KR style or jump = "\n" if i want Allman.
Thanks

**Comment by chiru-L** [comment]
nvm, just set let g:ultisnips_java_brace_style="nl" and copy and paste the java snippets. Sorry

**Comment by Raymond0715** [comment]
Not sure if I have understand correctly. vim report bug after I add your function to my snip file.
`  7 Following is the full stack trace:
  8 Traceback (most recent call last):
  9   File "/home/raymond/.vim/bundle/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 18, in wrapper
 10     return func(self, *args, **kwds)
 11   File "/home/raymond/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 131, in expand
 12     if not self._try_expand():
 13   File "/home/raymond/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 770, in _try_expand
 14     self._do_snippet(snippet, before)
 15   File "/home/raymond/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 723, in _do_snippet
 16     text_before, self._visual_content, parent, start, end
 17   File "/home/raymond/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/definition/base.py", line 488, in launch
 18     snippet_instance.update_textobjects(vim_helper.buf)
 19   File "/home/raymond/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/snippet_instance.py", line 93, in update_textobjects
 20     if obj._update(done, buf):
 21   File "/home/raymond/.vim/bundle/ultisnips/pythonx/UltiSnips/text_objects/python_code.py", line 270, in _update
 22     exec(code, self._locals)  # pylint:disable=exec-used
 23   File "<string>", line 3
 24     snip += ""
 25              ^
 26 IndentationError: unindent does not match any outer indentation level`
