### ISSUE TITLE
Completion window does not appear with YouCompleteMe and Neovim

### ISSUE THREAD

**Issue by euclio** [SirVer/ultisnips#560]
Sorry if this is the incorrect place to open this issue -- I'm not sure if this is a problem with Ultisnips, YCM, or Neovim.

Using the following nvimrc:

```viml
call plug#begin('~/.local/share/vim/bundle')

Plug 'Valloric/YouCompleteMe', { 'do': './install.sh' }
Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets'
let g:UltiSnipsExpandTrigger='<c-j>'
let g:UltiSnipsJumpForwardTrigger='<c-j>'
let g:UltiSnipsJumpBackwardTrigger='<c-k>'

call plug#end()
```

The plugin works correctly in vim, as I type a completion trigger (i.e., def in Python), I get a completion window that appears with each letter I type. Pressing `<c-j>` triggers snippet expansion as desired.

In neovim, there is no completion window. However, pressing `<c-j>` still triggers snippet expansion.

Edit:
NVIM 0.0.0-alpha+201508240435 (compiled Aug 25 2015 13:53:50)

**Comment by osleg** [comment]
I had this too, a little research leaded me to this: https://github.com/Valloric/YouCompleteMe/issues/1214
In short: YCM uses python2; UltiSnips uses python3. If n/vim compiled with support for both pythons it breaks the cooperation. As a fix you can set US to force use python2. 
https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L107

**Comment by euclio** [comment]
Thanks for the workaround. I'm guessing this is a bug in how Neovim handles Python plugins then.

**Comment by osleg** [comment]
same behavious happen in vim (without neo).

**Comment by euclio** [comment]
I see. In that case, closing.
