### ISSUE TITLE
Parametric snippets

### ISSUE THREAD

**Issue by CrisTsan** [SirVer/ultisnips#563]
Hello! I'm interested in parametric snippets. For instance, with the following syntax:
snippet mysnip{myparam} ...
    Hello {myparam}
endsnippet

you would achieve these:
mysnipA -> Hello A
mysnipWorld -> Hello World

Sure you can use the $# to do the same thing, but it would be much faster
and more elegant to do the same thing in a parametric way, when you want to alter a small part fast.

**Comment by SirVer** [comment]
Already possible using regular expression triggering: https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L937
