### ISSUE TITLE
What's the special meaning of a single quote in snippet definitions?

### ISSUE THREAD

**Issue by BohrShaw** [SirVer/ultisnips#565]
The [doc](https://github.com/SirVer/ultisnips/blob/e48d8a28e55e931a3340dae937aa7f66954815ad/doc/UltiSnips.txt#L703) says:

> In snippet definitions, the characters '`', '{', '$', '\' and "'" (single
quote) have special meaning.

I read through the whole docs and search through this repository but still failed to find any info.

It could be helpful to add some notes to the docs.

**Comment by SirVer** [comment]
I cannot think of any special meaning of a single quote picking my brain... I think the docs are just wrong.
