### ISSUE TITLE
UltiSnips shows me snippets list, but I can't choose one

### ISSUE THREAD

**Issue by apast** [SirVer/ultisnips#567]
Hello,

I believe this question is really naive, but I didn't find a response for my problem.

I only installed python-mode, vundle and pathogen on my vim environment.

And, after enable UltiSnips, it works normally, showing up right snippet entries on suggestion list, but I can't use this. I tried <Enter>, <Tab>, <Left>, Ctrl+<a lot of keys>, and nothing.

There is something I am doing wrong?

Atteched to this message, I am sending my current .vimrc.

May you help me?

Best Regards,

And Past

~~~

=== .vimrc =================================================
execute pathogen#infect()
syntax on
filetype plugin indent on

set nocompatible              " be iMproved, required
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'

" Track the engine.
Plugin 'SirVer/ultisnips'

" Snippets are separated from the engine. Add this if you want them:
Plugin 'honza/vim-snippets'


call vundle#end()            " required
filetype plugin indent on    " required


" enable syntax highlighting
syntax enable

" show line numbers
set number

" set tabs to have 4 spaces
set ts=4

" indent when moving to the next line while writing code
set autoindent

" expand tabs into spaces
set expandtab

" when using the >> or << commands, shift lines by 4 spaces
set shiftwidth=4

" show a visual line under the cursor's current line 
set cursorline

" show the matching part of the pair for [] {} and ()
set showmatch

" enable all Python syntax highlighting features
let python_highlight_all = 1


"" UltiSnippets
" Trigger configuration. Do not use <tab> if you use https://github.com/Valloric/YouCompleteMe.
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"

" If you want :UltiSnipsEdit to split your window.
"" let g:UltiSnipsEditSplit="vertical"
==========================================================
~~~

**Comment by SirVer** [comment]
UltiSnips does not show a suggestion list. Are you using YCM or some other completer? What does `:verbose imap <tab>` give you?

**Comment by Shougo** [comment]
@apast Your description is unclear.
You should upload reproduce ways from Vim starting.
It is better to upload screenshot.

**Comment by apast** [comment]
Hello Holger and Shougo,

thanks for your reply.

Considering Holger suggestion to print my ":verbose imap <tab>", I had the
following output:

i  <Tab>       * pumvisible() ? "\<C-N>" : "\<Tab>"
        Last set from /usr/share/vim/vimfiles/autoload/youcompleteme.vim

Considering this result, I read something more about YCM, and mappings on
Vi.

I reset my .vimrc to understand how it was being built.

Then, I understood that I if ultisnips map <tab> as default for expand
triggers, as documented on Installantion process.

I replaced the mapped key to <CR>, resulting in:

" Trigger configuration. Do not use <tab> if you use
https://github.com/Valloric/YouCompleteMe.
let g:UltiSnipsExpandTrigger=*"<CR>"*
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"

" If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit="vertical"

Now, it is working perfectly.

Thanks for your reply.

If I get confused on my response, I can put my prints here.

Thanks and Best Regards,

And Past

**Comment by Shougo** [comment]
@apast The problem is resolved.  This issue should be closed.

**Comment by apast** [comment]
One more consideration.

<CR> was not a good solution because it conflicts with common <CR> usage.

For my own daily usage, I am trying to adequate my mapping. Now, I am
trying use with <tab><tab> (double tab)
Thanks for helping on guide me for a solution.
