### ISSUE TITLE
Handling multiple snippets for the same file type

### ISSUE THREAD

**Issue by paulhybryant** [SirVer/ultisnips#569]
For example, I have some snippets define for python, which is put in python.snippet.
However, I also have honza/vim-snippets installed.
UltiSnips seems to only provide snippets for those defined in vim-snippets, but not the ones I have (depending on the search order, it might be the other way around).

**Comment by SirVer** [comment]
UltiSnips searches in all your runtimepath if you did not configure it to do something different. Also, it is search order invariant - it uses priorities to figure out which snippets to use when. 

Which variables of UltiSnips did you change in your vimrc?

**Comment by paulhybryant** [comment]
Thanks for the reply. I think the issue is caused by my configuration for changing g:UltiSnipsSnippetDirectories.

I have got another question though. I put some of my snippets in UltiSnips in the root direcotry of a plugin (which is included in &rtp), but those snippets are not available after I restart vim (g:UltiSnipsSnippetDirectories is not set so it should have default value).

What is the best way to identify the issue that cause the snippet to be not available?

Thank you!

**Comment by paulhybryant** [comment]
My bad, NVM.

**Comment by nnop** [comment]
Sorry for responding to a closed issue. But, how do you define the priorities of choosing snippets? @SirVer
