### ISSUE TITLE
Enter is disabled to insert a new line after installing

### ISSUE THREAD

**Issue by rundisR** [SirVer/ultisnips#572]
enter is disabled after install ultisnips and i cannot insert a new line now
seems that no one had this problem before except me...
can anyone help? many thx!

my .vimrc (YCM installed):
```
let g:UltiSnipsUsePythonVersion = 2
let g:UltiSnipsSnippetDirectories=["mysnippets"]
let g:UltiSnipsExpandTrigger="<leader><tab>"
let g:UltiSnipsJumpForwardTrigger="<leader><tab>"
let g:UltiSnipsJumpBackwardTrigger="<leader><s-tab>"
```

**Comment by SirVer** [comment]
1. Please check `:verbose imap <cr>`.

2. Please try using non-arpeggios, i.e. only one key for your triggers. I am not sure if arpeggios work.

**Comment by rundisR** [comment]
it show's
<C-R>=UltiSnips#ExpandSnippetOrJump()<CR>
modified in ~/.vim/bundle/ultisnips/autoload/UltiSnips/map_keys.vim

sorry for bad format since im using phone;(

how to use non-appreggios?simply comment the statement and only use my own keybinding for expanding?

**Comment by SirVer** [comment]
```
let g:UltiSnipsUsePythonVersion = 2
let g:UltiSnipsSnippetDirectories=["mysnippets"] <- you will have less trouble if you just use UltiSnips and remove this line.
let g:UltiSnipsExpandTrigger="<c-l>"
let g:UltiSnipsJumpForwardTrigger="<c-m>"
let g:UltiSnipsJumpBackwardTrigger="<c-n>"
```

like so. just use a single key as trigger

**Comment by rundisR** [comment]
i make my .vimrc exactly as yours, and comment the directory settings, then:

now i can use snippets normally, however,
enter still don't work
still shows same msg for :verbose imap <cr>


sorry for bothering TAT

**Comment by rundisR** [comment]
Problem solved...
simply because ive modify it vimrc and forgot it...

really appreciate for helping!!!!
