### ISSUE TITLE
Using "call feedkeys()" to expand snippets feeds an extra TAB!

### ISSUE THREAD

**Issue by dNitro** [SirVer/ultisnips#574]
When in insert mode i use

```
call UltiSnips#ExpandSnippetOrJump()
```

using vim script to expand snippets or jump through placeholders, everything is fine; e. g. expansions occurs and if there isn't any defined snippet nothing happens and the cursor is right after the typed charachters.
BUT when i use 

```
call feedkeys("\<C-r>=UltiSnips#ExpandSnippetOrJump()\<CR>")
```

expansions occurs but if there isn't any defined snippet an extra `<Tab>` key is feeded and so the cursor is one tab besides the typed charachters!
I changed `if trigger.lower() == '<tab>':` on line _511_ of file 'ultisnips\pythonx\UltiSnips\snippet_manager.py' to `if trigger.lower() == '':` and the second approach is now working fine and it doesn't feed any extra `<Tab>`. i dont have **Super TAB** plugin installed and think implementing an if statement on aforesaid line of code to check whether this plugin is installed or not should eliminates the problem.

**Comment by SirVer** [comment]
I agree, that is a prudent approach. Though there is no surefire way of detecting supertab - but I think we already have one heuristic in the codebase for that.

**Comment by SirVer** [comment]
Cannot repro this with c309637e0243b71f7e3265ebe3cffdfe9674cfbc
