### ISSUE TITLE
How to name snippets for sub filetype?

### ISSUE THREAD

**Issue by carlitux** [SirVer/ultisnips#577]
Hi,

I want to add reactjs snippets the filetype is javascript.jsx but I can't get automatically the snippets loaded.

**Comment by SirVer** [comment]
Try putting it in jsx.snippets. Should work. As of why, read up on dotted filetypes in the vim doc.

**Comment by carlitux** [comment]
@SirVer thank you very much! I thought should be javascript.jsx.snippets... now working.

**Comment by bapjiws** [comment]
Very late to the discussion, but running `:UltiSnipsEdit` from within a `.jsx` file should open the right file for snippets -- in this case `javascriptreact.snippets` 🙂
