### ISSUE TITLE
How to transform an input of a variable, not using mirror?

### ISSUE THREAD

**Issue by lvarayut** [SirVer/ultisnips#581]
I'm trying to uppercase an input of a variable, so, the input will automatically be uppercase. What I have tried so far is using the transformation.

```cson
snippet csec "Section comment" b
/* ==========================================================================
   ${1/\w+/\U/}
   ========================================================================== */
endsnippet
```

However, I got the syntax error. If I defined the variable before as shown below, it worked perfectly fine.

```cson
snippet com_sec "Section comment" b
/* ==========================================================================
   $1
   ${1/\w+/\U/}
   ========================================================================== */
endsnippet
```

My question is how to transform on the variable itself to be uppercase without using mirror? Any help would be appreciated.

**Comment by SirVer** [comment]
you cannot do that. the input is as entered by the user, UltiSnips cannot transform user input.

**Comment by raine** [comment]
Transforming would be useful.

In my use case I'd like the argument to require to be transformed to kebab case.

```
snippet cr "const require()"
const ${1} = require('./${2:$1}')${0};
endsnippet
```

So as I type on the left side, it would transform the right side as such:

`const whateverNameHere = require('./whatever-name-here')`

**Comment by SirVer** [comment]
You can do that with Python interpolation. No access to a computer right now, but if you cannot figure it poke me next week again and I can provide an example.

**Comment by SirVer** [comment]
@raine This does exactly what you want:

~~~
global !p
def convert(name):
    s1 = re.sub('(.)([A-Z][a-z]+)', r'\1-\2', name)
    return re.sub('([a-z0-9])([A-Z])', r'\1-\2', s1).lower()
endglobal

snippet cr "const require()"
const ${1} = require('./`!p snip.rv = convert(t[1])`)${0};
endsnippet
~~~

**Comment by raine** [comment]
@SirVer Fantastic. Thank you so much!
