### ISSUE TITLE
vim can't recognize { when using ultisnips

### ISSUE THREAD

**Issue by Inori** [SirVer/ultisnips#583]
When the curser is at the next line of a ```if()```,  like:
![rtx](https://cloud.githubusercontent.com/assets/6732524/10409939/9eb1bf26-6f64-11e5-8910-f6f072e6941a.png)

When I input a ```{```, vim can indent correctly:
![rtx 1](https://cloud.githubusercontent.com/assets/6732524/10409940/9fe66540-6f64-11e5-91a5-e6c12061b866.png)

Then I define a snippet like:
```
snippet br "brace" i 
{ 
    ${1}
}${2}
endsnippet 
```
And input ```br<Tab>``` at the same place, vim can't recognize ```{``` as it is, and can't indent correctly:
![rtx 2](https://cloud.githubusercontent.com/assets/6732524/10409941/a15ee23a-6f64-11e5-8489-696967d6665f.png)

What can I do to fix this?

**Comment by SirVer** [comment]
nothing. The snippet expands at the place you expand it. Vim is not clever enough to autoformat the indent.

You could use '{' as your trigger of course, then it would get indented when you type it.

**Comment by Inori** [comment]
But even if I change the snippet to:
```
snippet br "brace" i 
{
endsnippet 
```
Vim can not get correct indent when the snippet expand as before.
On the other hand, if I type ```br``` and the delete it, replace with ```{```, Vim can get indent correctly.
So how ultisnips replace ```br``` with ```{```?

**Comment by Inori** [comment]
I know it.
When I complete a function line and the cursor is at the end of line, then type ```enter```,
it seems that Vim can record the current context, so when I type  ```{``` it can get indent correctly:
![gif1](http://i1353.photobucket.com/albums/q668/bingkan/1_zpscqgekvx5.gif)
But if I move the cursor to the start of the new line, type ```tab``` to get indent manually, 
then type ```{```, this time Vim can not get indented as the snippet does:
![gif2](http://i1353.photobucket.com/albums/q668/bingkan/2_zpsfyh3d3ix.gif)
![gif2](http://i1353.photobucket.com/albums/q668/bingkan/3_zpsh51tnq9z.gif)
I read some source code of UltiSnips, it seems that UltiSnips parse the indent of current context
and behaves like the secend way.
Is there any way to make it work like the first?

**Comment by SirVer** [comment]
I do not follow what you mean with your last post. This snippet works as expected for me:

~~~
snippet { "Description" b
{
	$0
}
endsnippet
~~~

Example:

![example](http://g48i.imgup.net/ScreenRecoa7c9.gif)
