### ISSUE TITLE
Any way to cycle the last jump?

### ISSUE THREAD

**Issue by krzkrzkrz** [SirVer/ultisnips#584]
Current have `let g:UltiSnipsJumpForwardTrigger="<c-j>"` which jumps forward fine. Ideally, when I jump to the last tabstop and I hit `<c-j>`, again, I would like it to jump back to the first tabstop.

Is this possible?

**Comment by SirVer** [comment]
no, for efficiency reasons, the snippet is exited as soon as you reach the last tabstop. If that were not the case, UltiSnips would run a full diff over your buffer whenever you move the cursor.

**Comment by seletskiy** [comment]
@krzkrzkrz: Maybe not exactly what are you looking for, but cursor jump can be done with `post_jump` action, like this:

```
post_jump "if snip.tabstop == 0: snip.cursor.set(*snip.tabstops[1].start)"
snippet aaa "x" b
first: $1 second: $2$0
endsnippet
```

Typing `aaa<Tab>1<C-J>2<C-J>` will render in following:

![gif](https://cloud.githubusercontent.com/assets/674812/10416788/369cf404-7014-11e5-9933-4df3299bd029.gif)

**Comment by krzkrzkrz** [comment]
@seletskiy It does, but pressing `ctrl+j` again wont bring you to the second tab stop

**Comment by seletskiy** [comment]
Yes, it will not, because, actually, snippet expansion is over. I'm
wondering, why do you need such behaviour? Maybe, there can be different
solution for what you are trying to achieve.

**Comment by krzkrzkrz** [comment]
Just thought it might be handy. I'm actually fine with the default behaviour

**Comment by sblask** [comment]
Should it not be possible to keep an internal dummy placeholder after the last one and instead of jumping to that one, you'd jump to the first? That should not hurt efficiency.

**Comment by SirVer** [comment]
efficiency is hurt by not exiting the snippet. it is a design decision to exit the snippet at the last placeholder, because otherwise you'd never exit the snippet in most cases. this would mean that UltiSnips keeps running a diff over your buffer for each keystroke - which gets very slow on long snippets/buffers.
