### ISSUE TITLE
Placeholders removed when semantic competition is triggered in YouCompleteMe

### ISSUE THREAD

**Issue by cHoco** [SirVer/ultisnips#586]
Hello, when I have an expanded snippet and trigger semantic completion with YouCompleteMe inside one of the placeholders I can't jump to the other placeholders in the snippets, they seem to get removed. 
Not sure if it's a known limitation, a bug or a configuration problem on the Ultisnips or Ycm side, so I'm sorry if this is the wrong place to post about it.
To reproduce:
1- expand a snippet with two or more placeholders
2- trigger semantic completion when editing one of the placeholders
3- try jumping to next (or previous) placeholder

**Comment by cHoco** [comment]
Today I started investigating I bit and found out that this happens because if I enable preview windows with Ycm the cursor leaves the buffer, BufLeave autocmd set up by UltiSnips is triggered, and the snippet is considered done. And after all this debugging I found the exact same issue documented here https://github.com/Valloric/YouCompleteMe/issues/323 XD
Silly me for not finding it before. Since its been such a long time, is there any workaround available?
Anyway, thanks for you work on this amazing plugin!

**Comment by cHoco** [comment]
My current "patch" around this issue just checks if the popup completion menu is visible when the autocmd is triggered. Since I don't think there's any other event that can trigger a BufLeave event aside the preview option in the completeopt when the pum is visible, I think that this is a safe approach
https://gist.github.com/cHoco/27549c8bc5119eda7d3b

**Comment by SirVer** [comment]
This patch is dangerous. If one of your buffers is big, you might trigger https://github.com/SirVer/ultisnips/issues/155 with that. This issue is also the reason why we have this exiting of snippets in the first place. 

I am sorry, I do not think there can be anything done with the current design of Vim.
