### ISSUE TITLE
Ultisnips with Vundle doesn't work for custom snippets

### ISSUE THREAD

**Issue by manishrjain** [SirVer/ultisnips#587]
I've installed UltiSnips with Vundle, as described here. I'm also using fatih's vim-go. Here's my ~/.vimrc:

```
  1 "Enable Vundle for plugin management.
  2 set nocompatible
  3 filetype off
  4 set rtp+=~/.vim/bundle/Vundle.vim
  5 call vundle#begin()
  6 Plugin 'gmarik/Vundle.vim'
  7 Plugin 'fatih/vim-go'
  8 Plugin 'majutsushi/tagbar'
  9 Plugin 'fatih/molokai'
 10 Plugin 'Valloric/YouCompleteMe'
 11 " IMPORTANT NOTE: nsf/gocode is what does the autocompletion.
 12 Plugin 'nsf/gocode', {'rtp': 'vim/'}
 13 
 14 " For Git
 15 Plugin 'tpope/vim-fugitive'
 16 
 17 " Track the engine.
 18 Plugin 'SirVer/ultisnips'
 19 " Snippets are separated from the engine. Add this if you want them:
 20 Plugin 'honza/vim-snippets'
 21 
 22 Plugin 'Yggdroot/indentLine'
 23 " For Ledger
 24 Plugin 'ledger/vim-ledger'
 25 call vundle#end()
 26 filetype plugin indent on
 27 "Ok. Done.
... <snip>
```

This is the directory structure for ~/.vim:
```
:~/.vim$ l
total 44
drwxr-xr-x  6 mrjn mrjn  4096 Oct 13 15:36 .
drwx------ 47 mrjn mrjn 12288 Oct 13 16:02 ..
drwxr-xr-x 13 mrjn mrjn  4096 Oct  8 17:51 bundle
drwxr-xr-x  2 mrjn mrjn  4096 Oct 13 15:52 ftplugin
-rw-r--r--  1 mrjn mrjn   103 Oct  9 11:33 .netrwhist
drwxrwxr-x  2 mrjn mrjn  4096 Oct 13 15:56 UltiSnips
drwxr-xr-x  2 mrjn mrjn  4096 Oct 13 15:33 view
```

Note that the UltiSnips directory got created after I ran `:UltiSnipsEdit` from my go code. **However, whatever snippet I add there doesn't work**. `:set filetype` shows me `filetype=go`. So, all that works. I suspect the lack of ftdetect is the culprit. Having said that, I did follow the standard instructions to load UltiSnips, so I do expect it to work.

Suggestions on what needs to be done here to get this working? I don't want to modify the snippets from vim-go or vim-snippets.

**Comment by SirVer** [comment]
Sorry for getting back so late, I have been traveling this week.

Your `vimrc` looks fine so far, but maybe there is something fishy further down. Can I see it in full somewhere? 

- Does triggering snippets from `all.snippets` work? For example, `lorem<your trigger key>` does that expand in your go code?
- What does `:verbose imap <your trigger key>` yield?
- Maybe some other plugin steals your keymaps? Can you disable all other plugins but UltiSnips and try then?
- Does it work for other filetypes? For example, edit `/tmp/blub.py` and try expanding `class`.

**Comment by SirVer** [comment]
@manishrjain friendly ping? Could you provide more information?

**Comment by manishrjain** [comment]
Hey @SirVer,

I'm sorry, it turned out to be an issue at my end. My snippet was flawed (unescaped backticks), and that caused it to not show up.

Thanks for following up and the good work! I'm going to close the issue.
