### ISSUE TITLE
Installation with Pathogen fails

### ISSUE THREAD

**Issue by themightyoarfish** [SirVer/ultisnips#591]
Following the documentation, I ran
`cd ~/.vim/bundle && git clone git://github.com/SirVer/ultisnips.git`
and
`cd ~/.vim/bundle && git clone git://github.com/honza/vim-snippets.git`

In vim `:help UltiSnips` is unacessible and the plugin not installed, obviously.
Also, when trying to set variables like `let g:UltiSnipsExpandTrigger <c-j>` in `.vimrc`, starting vim prints the error
`E121: Undefined variable: g:UltiSnipsExpandTrigger
E488: Trailing characters`

**Comment by SirVer** [comment]
> In vim :help UltiSnips is unacessible and the plugin not installed, obviously.

`:help UltiSnips` needs the helptags to be updated, according to the pathogen docs you need to run `:Helptags` once to do that. 

> Also, when trying to set variables like let g:UltiSnipsExpandTrigger <c-j> in .vimrc, starting vim prints the error. 

Not a ultisnips error, your code has a syntax error. As shown in the UltiSnips readme it has to read:
`let g:UltiSnipsExpandTrigger="<c-j>"`.

Closing for now. If the problem persists after fixing these two issues, please provide your full vimrc and Vim version and we can continue investigation.

**Comment by themightyoarfish** [comment]
What silliness, I should have seen this … I find it strange though that `:help UtilSnips` is not available although the `:Helptags` command is before the trigger redefinitions in my `.vimrc`. Not a vim-Guru though, so unsure what's going on.

**Comment by SirVer** [comment]
The `:Helptags` command is defined by pathogen, not by UltiSnips.

Also, the trigger redefinition is just setting a variable, it is not containing any logic. You could have that without having UltiSnips installed at all and it would not hurt one bit.
