### ISSUE TITLE
UltiSnips uses the wrong folder for neovim

### ISSUE THREAD

**Issue by Eisfreak7** [SirVer/ultisnips#596]
Hi
as already mentioned in #414, neovim planned switching to the xdg-directory structure.
Now the switch has happened. Therefore, the ```~/.nvim``` directory is incorrect.
I know it is easily configurable, I just wanted to give you a heads up, since the default is now wrong.
The directory should be ```$XDG_CONFIG_HOME/nvim``` (with a fallback to ```$HOME/.config/nvim```).

Thanks for creating this awesome plugin.

**Comment by SirVer** [comment]
Is there a compatible way of getting the current `.vim` directory path from NeoVim directly? Otherwise, if we keep hardcoding the path it will break all users who have not the latest NeoVim. Right now, the users who already have the newest are broken.

**Comment by Eisfreak7** [comment]
Not that I know of (and a quick search through the issues on neovim didn't show anything either).
However I don't really think that distinction would be necessary. Since neovim didn't have its first public release yet, changes that break backwards compability are to be expected and every user that experiences bugs should first upgrade to the newest version on upstream (at least thats how I see it).

**Comment by SirVer** [comment]
One more question: What do you mean with this?

> The directory should be $XDG_CONFIG_HOME/nvim (with a fallback to $HOME/.config/nvim).

does this mean that if `$XDG_CONFIG_HOME` is not set, we should use `$HOME/.config/nvim` or that if ` $XDG_CONFIG_HOME/nvim` does not exist we should use `$HOME/.config/nvim`?

**Comment by Eisfreak7** [comment]
The former. When ```$XDG_CONFIG_HOME``` does not exists, the standard location (```$HOME/.config```) is used. Sorry if I expressed myself badly.

**Comment by SirVer** [comment]
@Eisfreak7 could you have a look at  https://github.com/SirVer/ultisnips/commit/0480b2243cf7141bcbe554cd7f800532c6431e3e and see if that looks correct to you? Maybe even test it real quick?

**Comment by Eisfreak7** [comment]
Looks correct to me. 
A quick test with neovim and vim seems to be working. I updated vim-plug to download the neovim_path branch and delted my ```g:UltiSnipsSnippetsDir``` configuration. After that, opening a .tex file and calling ```:UltiSnipsEdit``` opens the correct file (```~/.vim/UltiSnips/tex.snippets``` or ```~/.config/nvim/UltiSnips/tex.snippets``` respectively).
However, ```:echo g:UltiSnipsSnippetsDir``` says that the variable isn't defined. I don't know, if that is intended behavior (maybe its just defined when it's user set), but it works anyway.
I couldn't test the windows bit, since I currently don't have windows running on any machine.

Thank you for your effort

**Comment by Dieterbe** [comment]
this makes it work for me too with neovim.
i was wondering why it didn't work, thinking i had an issue with the keybind configuration :)

i think it's arguable whether the snippets should be classified as configuration vs as data though (XDG_DATA_HOME in the xdg basedir spec), i'm more inclined to say it's data and belongs in the data folder, but if most similar neovim data goes into config then let's go with that.

**Comment by Eisfreak7** [comment]
I'd argue against this.
Personally, my criteria for "config vs data" is "what would I want to share between machines". I upload my configs on github, not my data.
Since I "configure" ycm with my preferred snippets and I want that on multiple machines, thats configuration (in my opinion). I would consider data to be something like a database or state information.

**Comment by SirVer** [comment]
@Dieterbe I refuse to be dragged in that sort of bikeshedding :). Config is data too. dotfiles worked fine for me for nearly 30 years, do not understand the idea behind .config/ anyways.

Besides, UltiSnips has hooks to configure where it searches for snippets, so everybody can put them where they like.
