### ISSUE TITLE
Add a comment about python mismatch with YCM in the readme

### ISSUE THREAD

**Issue by yograf** [SirVer/ultisnips#597]
Thanks @SirVer for ultisnips, It's great.
Could you add a note about this issue in the readme
https://github.com/Valloric/YouCompleteMe/issues/1214

**Comment by SirVer** [comment]
@yograf I suggest sending a pull request. You are in a better position to know what information you searched and where you expected to find it.

**Comment by seletskiy** [comment]
@yograf: Ping?

**Comment by yograf** [comment]
Sorry @seletskiy I don't remember what was needed here. I started using neosnippet with deoplete.
although I do miss ultisnips.
