### ISSUE TITLE
Extending UltiSnips snippet ignores snipmate

### ISSUE THREAD

**Issue by benebun** [SirVer/ultisnips#598]
I'm not sure if I'm expecting the wrong thing here and if there is a better approach:
* I'm using honza/vim-snippets which has UltiSnips/htmldjango.snippets which extends html.
* UltiSnips/html.snippets is unfortunately less complete (e.g. html5 tags) than snippets/html.snippets.
* Now in an htmldjango template file only the UltiSnips/html.snippets can be used, not the more complete snippets/html.snippets.

Is there a solution other than converting the snipmate html.snippets to UltiSnips?

**Comment by SirVer** [comment]
the extends framework works per source. I.e. the snipmate snippets need to have their separate extends definition.

Fixed in https://github.com/honza/vim-snippets/commit/cfb046a734c3e0e8573185955405db77f7ac5d7f.
