### ISSUE TITLE
Minimum vim version required ?

### ISSUE THREAD

**Issue by dhrubajyoti-das** [SirVer/ultisnips#607]
I have vim 7.3 installed ulitsnips through Vundle. 
Got a error ultisnips requires vim >=7.4 
Is there a way ?

**Comment by SirVer** [comment]
No, you'll need to update, sorry.

Vim 7.4 is now 2 years old, and supporting older Vim versions was too much work in maintenance.

**Comment by dhrubajyoti-das** [comment]
Oh No! 
Anyway thanks for your response.
