### ISSUE TITLE
snippet inserted but tabstops are ignored

### ISSUE THREAD

**Issue by john-gramophon** [SirVer/ultisnips#610]
hello,
I would like to have the following snippet, but it is not working. Snippet is inserted but tabstops are ignored ($n are displayed) and cursor jumps at the end of the text. Removing terminal $0 does not help.
Pls help.  thanks
(I have a suspicion that it is not a bug but lack of understanding escaping rules on my side....)

snippet smifig "smifigure" b
\begin{figure}[H]
  \centering
  \begingroup
        \catcode`\~=0
        \catcode`\%=11
        \catcode`\\=11
        ~smilesobabel[scale=0.6]{$1}{}
        ~endgroup
  \caption{$2}
\end{figure}
$0
endsnippet

thanks

**Comment by SirVer** [comment]
the snippet you have there is incomplete, it has no endsnippet.

**Comment by john-gramophon** [comment]
sorry for pasting not complete code, I updated it. It is not working, but other snippets are working form me.

**Comment by SirVer** [comment]
You did not escape the backticks, "`". They start shell interpolation. This makes the snippet work for me.

Also, you should use tabs for indentation in snippet files, ultisnips will convert them to spaces if you require that.

~~~
snippet smifig "smifigure" b
\begin{figure}[H]
  \centering
  \begingroup
        \catcode\`\~=0
        \catcode\`\%=11
        \catcode\`\\=11
        ~smilesobabel[scale=0.6]{$1}{}
        ~endgroup
  \caption{$2}
\end{figure}
$0
endsnippet
~~~
