### ISSUE TITLE
Do not prevent starting vim when vim's version < 7.4

### ISSUE THREAD

**Issue by charlax** [SirVer/ultisnips#612]
I get this message when I start vim:

```
% vim a
UltiSnips requires Vim >= 7.4
Press ENTER or type command to continue
```

I use my vim config on multiple machines, and some of them have an old vim. I usually only pretty basic changes and don't need utilsnips on those machines. Instead of waiting for enter, can utilsnips just display a warning but still allow vim to load?

**Comment by SirVer** [comment]
Why don't you wrap loading of UltiSnips in your vimrc in an if block?

~~~
if v:version >= 704
    Plugin "sirver/UltiSnips"
endif
~~~

UltiSnips does not work in Vim with lower versions. Why should it silently pretend to?

**Comment by charlax** [comment]
That's a very good idea. Here's the code for pathogen:

```
" To disable a plugin, add its bundle name to the following list
let g:pathogen_disabled = []

if v:version <= '704'
    call add(g:pathogen_disabled, 'ultisnips')
endif
```

I did not mean that it should silently fail. There could have been a message. Anyway, disabling it is much cleaner. Thanks!

**Comment by SirVer** [comment]
Thanks for the example!

**Comment by benjaminfjones** [comment]
Ran across this issue and wanted to add (in case anyone else is confused when copying it) that the code snippet in https://github.com/SirVer/ultisnips/issues/612#issuecomment-159359718 uses double quotes for the plugin name, which is a syntax error. The name should be surrounded by single quotes.
