### ISSUE TITLE
Go back to first placeholder after jumping to last placeholder

### ISSUE THREAD

**Issue by sblask** [SirVer/ultisnips#613]
I would like to go back to the first placeholder of a snippet after jumping to the last placeholder using `g:UltiSnipsJumpForwardTrigger` instead of being send into normal mode. This is where I am: https://github.com/honza/vim-snippets/blob/master/snippets/python.snippets#L43 and I would like to go back to https://github.com/honza/vim-snippets/blob/master/snippets/python.snippets#L38 when doing a jump forward. Ideally also the other way around when jumping backwards, so I'd have proper cycling. Is there a way to do that or would it be possible to add it? The biggest problem with the way it is now is, that I can't go back to change stuff once I reached the last placeholder as I am dropped into normal mode. So if I see a mistake to late or accidentally press the jump forward key too often, I can not go back.

**Comment by seletskiy** [comment]
@sblask: It's impossible, see #584.
