### ISSUE TITLE
Weird selection behaviour when modifying a first argument and erasing a second

### ISSUE THREAD

**Issue by Alex-Canales** [SirVer/ultisnips#616]
I found a weird behaviour for the following snippets:

    snippet two "Bug for two"
    ${1:one}(${2:xx})${3:three}
    endsnippet

    snippet three "Bug for three"
    ${1:one}(${2:xxx})${3:three}
    endsnippet

    snippet four "Bug for four"
    ${1:one}(${2:xxxx})${3:three}
    endsnippet

    snippet with_space "Bug for four (with spaces instead of parenthesis)"
    ${1:one} ${2:xxxx} ${3:three}
    endsnippet

    snippet with_d "Bug for four (with the letter d instead of parenthesis)"
    ${1:one}d${2:xxxx}d${3:three}
    endsnippet

    snippet no_space "No bug (apparently)"
    ${1:one}${2:xxxx}${3:three}
    endsnippet

Let say ``${1:one}`` is the first argument, ``${2:xx}`` the second and ``${3:three}`` the third. Supposedly, in any case, after modifying the second argument, the program is supposed to select only the third argument.

Here if the first argument is modified and second argument is **just erased with a backspace**, the selection is hazardous. Else the selection seems OK (no problem if second argument is erased, modified then erased then jump to the third argument).

Following are examples:

Normal comportment (did not modified the first argument and just erased the second):
![Normal](https://cloud.githubusercontent.com/assets/12187544/11611749/b3c2c23e-9bab-11e5-9502-eabca4d2851c.gif)

Bug (modified first, delete the second):
![Bug](https://cloud.githubusercontent.com/assets/12187544/11611752/c3d730b0-9bab-11e5-8450-524a56bf810c.gif)

Here are the selection when bug with the snippet ``two`` (selected from the beginning to the r of three):
![two](https://cloud.githubusercontent.com/assets/12187544/11611755/ecf15d54-9bab-11e5-81f6-d18624462170.png)

The snippet ``three`` (selection from the beginning to the first e of three when jumping to the third argument):
![three](https://cloud.githubusercontent.com/assets/12187544/11611756/f6388e78-9bab-11e5-91f8-dcb6a74b8bf1.png)

The snippet ``four`` (selection from the beginning to the second e of three when jumping to the third argument):
![four](https://cloud.githubusercontent.com/assets/12187544/11611757/fc4268de-9bab-11e5-8f3f-199d3a0fc9b5.png)

Also when using this snippet (for creating a private function in Haxe):

    snippet prf "private function (fun)" b
    private function ${1:functionName}(${2:arguments}):${3:Void}
    {
        ${VISUAL}$0
    }
    endsnippet

If modifying the first argument and erasing the second then jump to the third argument, the cursor goes to the beginning of the line instead of the third argument. If I type something, the first character of the line is replaced then it goes in insert mode.
Jumping to the third argument (the cursor is in the wrong place, in the beginning of the line):
![Jumped to third argument](https://cloud.githubusercontent.com/assets/12187544/11611776/1a9bc39c-9bad-11e5-8b28-78eaaff883ea.png)

After jumping back to the second argument (selection the begining of the line to the ``:`` before Void):
![Jumped back to the second argument](https://cloud.githubusercontent.com/assets/12187544/11611811/52b54108-9bae-11e5-860a-e48f6ef19362.png)

After modifying the "third argument" (typed ``modiying the "third argument"``) and jumping to the final argument (``$0``):
![Modified the third argument](https://cloud.githubusercontent.com/assets/12187544/11611777/2740f126-9bad-11e5-9c0d-4ffda6ff6dd2.png)

I tried to be the more detailled possible. I though at first the problem could be because of the parenthesis but if you try with the snippet ``with_space`` or ``with_d``, the bug appears. No bug with ``no_space``.

The only modifications I have made for Ultisnips are the following (in my ``.vimrc``):

    let g:UltiSnipsExpandTrigger="<tab>"
    let g:UltiSnipsJumpForwardTrigger="<c-j>"
    let g:UltiSnipsJumpBackwardTrigger="<c-z>"
    let g:UltiSnipsEditSplit="vertical" " :UltiSnipsEdit split window.

Tested with Vim version 7.4 (last version of Vim on ArchLinux) with the latest version of Ultisnips (I did a ``PluginUpload`` with Vundle). Not tested with NeoVim.

**Comment by seletskiy** [comment]
@Alex-Canales: Thanks for the great bug report! Yep, it's a bug. Needs further investigation.

**Comment by seletskiy** [comment]
@Alex-Canales: can you try branch fix-text-objects-update? Issue should be solved.

**Comment by Alex-Canales** [comment]
I have just tried quickly by redoing what caused the bugs. It seemed to be solved.

Impressive reactivity, thanks for the quick fix!

**Comment by seletskiy** [comment]
@Alex-Canales: Actually, you did half of the work by providing awesome bug report. Thanks!
