### ISSUE TITLE
UltiSnips#SnippetsInCurrentScope() slowdown in UltiSnips, Deoplete, MultipleCursors combo.

### ISSUE THREAD

**Issue by martin-svk** [SirVer/ultisnips#618]
Hi, I just noticed a big lag when edited multiple words using https://github.com/terryma/vim-multiple-cursors and after I hit `ESC` a got a 3sec lag. I profiled it and it looks like US is the problem.

Here is the profile output:

```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
  201   3.547166             provider#python3#Call()
  147   3.525468             UltiSnips#SnippetsInCurrentScope()   <----
   16   0.242989   0.238028  <SNR>198_wait_for_user_input()
  191   0.145978   0.017007  <SNR>154_completion_begin()
  105   0.141763   0.001184  neomake#CursorMoved()
  106   0.135951             neomake#signs#PlaceVisibleSigns()
    5   0.127674   0.001309  multiple_cursors#new()                  <----
```

Seems like `UltiSnips#SnippetsInCurrentScope()` is the root of problems.
I am using Neovim with Python3 support and Ubuntu 14.04.

EDIT:

**I just noticed it only happens when `ultisnips` autocomplete source for https://github.com/Shougo/deoplete.nvim is enabled. Otherwise it's ok.**

Thanks for Your time.

**Comment by seletskiy** [comment]
@HerringtonDarkholme: you're probably interested in this.

**Comment by HerringtonDarkholme** [comment]
I have reproduced that. It seems like deoplete will call `UltiSnips#SnippetsInCurrentScope` multiple times. Multiple cursors' home page has stated problems about plugin confliction. https://github.com/terryma/vim-multiple-cursors#interactions-with-other-plugins

But deoplete does not have disable function now.

**Comment by martin-svk** [comment]
Thanks, that is  a solution. For some reason `deoplete` does not enables the autocomplete again. But that's `deoplete`s issue. But the lag is gone. So I think this can be closed. Thanks for Your time.

For future reference, I did this:

```viml
" Called once right before you start selecting multiple cursors
function! Multiple_cursors_before()
  echo "Before"
  let b:deoplete_disable_auto_complete=1
endfunction

" Called once only when the multiple selection is canceled (default <Esc>)
function! Multiple_cursors_after()
  echo "After"
  let b:deoplete_disable_auto_complete=0
endfunction
```
