### ISSUE TITLE
When editing markdown file and using a snippet, some script executes

### ISSUE THREAD

**Issue by sittim** [SirVer/ultisnips#620]
Using NeoVim, and editing markdown file, at the beginning of a line I type

`sec<c-e>`

something blinks, the snippet editing ends and the following shows up

`# ge #`

when I hit undo once the following shows up

`# Section Name #`

When working in `C++`, and entering `if<c-e>` the snippet acts as expected, so this is particular to the MD file, what can I do?

My configs can be found here:

https://github.com/sittim/configs

**Comment by seletskiy** [comment]
@sittim: Please, post snippet definition here.

**Comment by sittim** [comment]
The `sec` snippet:

```
snippet sec "Section" b
# ${1:Section Name} #
$0
endsnippet
```

This snippet is part of the `vim-snippets` plugin, located at:  `~/.config/nvim/plugged/vim-snippets/UltiSnips/markdown.snippets`.  By the way the same thing happens for all of the snippets in that file.

Actually, I could not find the `if` snippet in the UltiSnips directory, but trying the `eli` snippet located in file `~/.config/nvim/plugged/vim-snippets/UltiSnips/c.snippets` which is listed as:

```
snippet eli "else if .. (eli)"
else if (${1:/* condition */}) {
        ${VISUAL}${0}
}
endsnippet
```

Works fine.

**Comment by sittim** [comment]
Wow, this is a surprise to me, when I comment out the `Plug 'ntpeters/vim-airline-colornum'` line, it all works fine.  Wonder what the vim-airline-colornum, markdown and the UltiSnips  have to do with each other.  I also started an issue here:

https://github.com/ntpeters/vim-airline-colornum/issues/14

**Comment by seletskiy** [comment]
@sittim: I confirm that issue reproduces with vim-airline-colornum.

**Comment by seletskiy** [comment]
Actually, it's reproduceable without `vim-airline-colornum` by using `sec` snippet and hitting <kbd>Left</kbd> just after expansion.

**Comment by seletskiy** [comment]
@sittim: Looks like issue in the `vim-airline` itself. Try to disable `ultisnips` and `vim-airline-colornum`, then open some markdown file, type `aaaaaaaaaaaaa`, select some block, press `<C-G>` to enter select mode and then hit `<Left>`. See what happens.
