### ISSUE TITLE
have to hit undo twice to undo snippet

### ISSUE THREAD

**Issue by mohitleo9** [SirVer/ultisnips#621]
Hey,
I have a simple snippet 

```
snippet ff "Description" b
asdf
endsnippet
```

so when I hit `ff<c-j>` it expands to asdf, but I have to hit undo twice to get back to the trigger words.
I was wondering is there a way to undo things in just one hit.

**Comment by seletskiy** [comment]
@mohitleo9: I can not reproduce:

![a](https://cloud.githubusercontent.com/assets/674812/11952743/aa06a5e4-a8bc-11e5-9fc6-48ed307a53b3.gif)

**Comment by seletskiy** [comment]
However, it's reproduceable with <kbd>&lt;C-O>u</kbd>.

**Comment by andreyorst** [comment]
Can't reproduce it now. Even with <kbd><C-)>u</kbd>. I'm closing it as old issue, that cn't be reproduced. If problem still exists, please create new issue, following [CONTRIBUTING.md#reproducing-bugs](https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs)
