### ISSUE TITLE
Anyway I can list all snips of current filetype?

### ISSUE THREAD

**Issue by chemzqm** [SirVer/ultisnips#623]
`UltiSnips#SnippetsInCurrentScope` is only useful for expand, but I want to list all of them in my unite list.
I got this function:
``` VimL
function! UltiSnips#ListSnippets()
    exec g:_uspy "UltiSnips_Manager.list_snippets()"
    return ""
endfunction
```
But It only return empty string  😕

I just want a command like:
```
nnoremap <silent> [unite]u  :<C-u>Unite -buffer-name=ultisnips ultisnips:all<cr>
```
could list all snips of current file,  thanks for help!

**Comment by seletskiy** [comment]
Fixed in #625, isn't it?
