### ISSUE TITLE
Conflict with Python 2.7.11 on Windows?

### ISSUE THREAD

**Issue by josephpei** [SirVer/ultisnips#626]
sys: Win10, Python 2.7.11 amd64, 64bit vim 

when start vim, get this error

E887: Sorry, this command is disabled, the Python's site module could not be loaded.

When I uninstall python 2.7.11, install old version 2.7.9, the error misses, everything is OK.

**Comment by seletskiy** [comment]
@josephpei: error `E887` means, that vim binary that you use was built with different python library version and `:python` command is unavailable. So it's not UltiSnips issue.

**Comment by josephpei** [comment]
vim has bug under Python 2.7.11 on windows, need modify the windows registery

HKLM_LOCAL_MACHINE\SOFTWARE\Python\PythonCore\2.7

**Comment by seletskiy** [comment]
@josephpei: :+1:
