### ISSUE TITLE
[python required] Can ultisnips be used on Windows 7 + Vim 7.4?

### ISSUE THREAD

**Issue by jwndev** [SirVer/ultisnips#632]
I installed this plugin but when I started Vim I got 

'Ultisnips requires py >=2.7 or py3. 

I have installed py3.4.3 on my system. 

This is on Windows 7 and vim 7.4 downloaded from vim.org. Please advise. 

Thanks,

**Comment by seletskiy** [comment]
@jwndev: I guess vanilla vim from vim.org do not have python support enabled for windows by default, so you need to get binary from somewhere else or build it by yourself. Try buillds from https://tuxproject.de/projects/vim/.

**Comment by jwndev** [comment]
Thank you @seletskiy !

I updated my gVim74 by downloading a version from vim.org and it looks it has a built-in support to python now. (echo has('python') =1 now) 

But for some reason, when I open vim, it gives a flash and closes right away. It is ok if I comment this plugin. 

I will do an installation from scratch. 

Thanks again!
