### ISSUE TITLE
Anonymous Snippet works only after whitespace

### ISSUE THREAD

**Issue by Hotschke** [SirVer/ultisnips#636]
I have tried UltiSnips#Anon for latex editing:

`inoremap <silent> __ __<C-R>=UltiSnips#Anon('_{$1}$0', '__')<cr>`
`inoremap <silent> ^^ ^^<C-R>=UltiSnips#Anon('^{$1}$0', '^^')<cr>`

It does only work after whitespace. $e__ $ does not work. Does anyone has encountered this as well?

**Comment by seletskiy** [comment]
@Hotschke: please, use autotrigger feature for that: `:h UltiSnips-autotrigger`.

**Comment by Hotschke** [comment]
Comment in the help:

*Warning:* using of this feature can lead to significant vim slowdown. If you
discovered that, report an issue to the github.com/SirVer/UltiSnips.

This is something I am not looking for. I guess I will give it a try, but if this is true it is a no-go for me. Drew Neil has a nice saying: do not blunt your vim.

**Comment by Hotschke** [comment]
Thanks to @lervag, it is possible to use `UltiSnips#Anon`, the option `i` has to be added to the function call:

    inoremap <silent> __ __<C-R>=UltiSnips#Anon('_{$1}$0', '__', '', 'i')<cr>
    inoremap <silent> ^^ ^^<C-R>=UltiSnips#Anon('^{$1}$0', '^^', '', 'i')<cr>

Maybe the helpfile of `:h Ultisnips#Anon` could be extended to get more easily to the list of valid options.

**Comment by seletskiy** [comment]
@Hotschke: That note about possible slowdown was added when autotrigger had had a bug, which affects vim performance. The number of issues was reported then, and now they are fixed, so that message was left just as a banner.

**Comment by Hotschke** [comment]
@seletskiy: I see. I didn't want to sound too harsh. I try to minimize any performance penalty by plugins. Vim can quickly become slow if certain plugins are installed. That's not what I and probably many vim users want. I would now rephrase it accordingly.

**Comment by seletskiy** [comment]
@Hotschke: I do not find your proposals harsh in any way, they sounds perfectly valid for me. I just described situation applicable for current state of autotrigger feature.

BTW, thanks for the remark about lack of documentation about options. I've fixed it in 0058e8664f5e331969d78855764cde190b751239.
