### ISSUE TITLE
Cycle through limited options

### ISSUE THREAD

**Issue by Sathors** [SirVer/ultisnips#637]
Hi,

I think it would be really useful if we could define for example a
```
${1:[value1,value2,value3]}
```
which would be a tabstop with a limited set of values.

With a defined keymapping I could cycle trough the possible values.

I have looked everywhere to find a way to do this, trying nesting tabstops, but could not achieve this behavior.

Thanks

**Comment by seletskiy** [comment]
Can you give concrete example when this feature will be useful?

**Comment by Sathors** [comment]
Thanks for the prompt answer.

In my case, when programming at work with Odoo (in Python), we have a decorator which can only take the value [@api.one, @api.multi, @api.model]. Every single method has to have one of the three.
The class we have to inherit from can only be within [Model, TransientModel, AbstractModel].

When programming using a framework, I would guess the options may be often limited among a few.

In the case of the first example, I guess autocompletion may be used, even though it will prompt me many options I rarely (never) use, and that I don't really know how well it will play with Ultisnips.
In the case of the second example, because I import directly the classes without their module, autocompletion wouldn't even be useful.

**Comment by seletskiy** [comment]
@Sathors: sorry for the long delay, tight schedule.

I asked your for the real case, because US engine already possess very powerful features which can be used to solving your problems by looking at them at slightly different way. Combining that features can lead to magically appearing code in right places. Some of them (you can see docs or ask): autotrigger, pre-expand actions, post-expand actions, post-jump actions, conditional replacements in transformations).

To convince you, I created some pretty dumb snippets which fits your case:
![a](https://cloud.githubusercontent.com/assets/674812/12481920/37800b22-c06e-11e5-933b-72fa7b92ee12.gif)

**Comment by seletskiy** [comment]
@Sathors: Note, that are really dumb snippets, which I made in several minutes without actual knowledge of the projects you're writing and framework you're using. Spice it with context, smart transformations and they will be really mind-blowing.

**Comment by Sathors** [comment]
@seletskiy: thanks for the answer, and don't worry for the response time.

Actually it seemed really strange to me that it may not be possible.
I already had a look at the \:help page, but still did not find a way to implement what I needed.

I will have a look at the options you gave to find out how to do it, else I will ask in a fitter place than here.

Thanks for your help and for the hard work!

**Comment by seletskiy** [comment]
@Sathors: Feel free to ask for it there, I do understand your case. My point was, that it's possible in slightly different way (not via common-sense autocompletion).

If you're wondering, I used following snippets in the recorder gif:

```


snippet "^c" "class" Arb
class $1($2${2/^((T)|(A)|(M))$|.*/(?2:ransientModel)(?3:bstractModel)(?4:odel)/}):
        $3
endsnippet

snippet "@" "method def decorated" Arb
@api.$2${2/^(()|(o)|(m)|(mo))$|.*/(?2:one)(?3:ne)(?4:ulti)(?5:del)/}
endsnippet
```
