### ISSUE TITLE
Python3 is the default on my system with both python2 and python3 installed.

### ISSUE THREAD

**Issue by Industrial** [SirVer/ultisnips#638]
Hi.

I like to think I have a modern Linux system; archlinux.

https://github.com/SirVer/ultisnips/blob/69b7c501a0ca3bb177472ca4aed8e6848e2143f4/plugin/UltiSnips.vim#L31 indicates my default python version should be python2 and not python3, but it is the other way around.

I'm configuring this package to use python2 instead of python3 because I need it to work with YouCompleteMe which uses python2 (for gods sake why cling on to dying software??? why split the community???)

Would it be possible to try the `python2` binary from the path FIRST before resorting to the `python` program?

**Comment by Industrial** [comment]
Apparently I need to install all of this:

`sudo pacman -Syu neovim python2-neovim python-neovim python-pip python2-pip` in order for things to even work.

Why not have neovim look for binaries of programming languages that neovim supports when you start neovim? If I have ruby installed then enable ruby .. if I have python then enable python support ........

**Comment by seletskiy** [comment]
@Industrial: what exactly is your problem? I'm using archlinux as well and experience no problems with YCM+US.

**Comment by Industrial** [comment]
That I had to find out I required all this software extra on top of the neovim package for neovim to work with plugins. I don't think you should package the software that enables your plugin architecture in different packages. It should live in the main package and 'just work'.
