### ISSUE TITLE
Snippet not executing shell command

### ISSUE THREAD

**Issue by pdoak** [SirVer/ultisnips#639]
I am trying to write a snippet which retrieves information from the front Safari page. The snippet uses some shell code with embedded applescript but it does not work. The snippet code is:

```
snippet surl "Grab highlighted text" b

`#!/usr/local/bin/zsh
mytext=$(/usr/bin/osascript << END 
tell application "Safari"
 selecTxt to (do JavaScript "(getSelection().toString())" in document 1)
set pgTitl to (do JavaScript "document.title" in document 1)
set pgDate to (do JavaScript "document.lastModified" in document 1)
set myURL to URL of front document
set copyText to selecTxt & return & return & "[" & pgTitl & "]" & return & "(" & myURL & ")" & return & "Page Last Modified:" & pgDate & return & "Clipped On:" & (current date)
return copyText
end
END)
echo $mytext`

endsnippet
```

I know that the shell code works as if I run this script, it returns the information and copies it to the clipboard:

```
#!/usr/local/bin/zsh

mytext=$(/usr/bin/osascript << END
tell application "Safari"
set selecTxt to (do JavaScript "(getSelection().toString())" in document 1)
set pgTitl to (do JavaScript "document.title" in document 1)
set pgDate to (do JavaScript "document.lastModified" in document 1)
set myURL to URL of front document
# set copyText to selecTxt & return & return & pgTitl & return & myURL & return & "Page Last Modified:" & pgDate & return & "Clipped On:" & (current date)
set copyText to selecTxt & return & return & "[" & pgTitl & "]" & return & "(" & myURL & ")" & return & "Page Last Modified:" & pgDate & return & "Clipped On:" & (current date)
return copyText 
end
END)

echo $mytext
echo "$mytext" |  pbcopy
```

It looks as though the applescript inside the shell code is not being interpreted. Is there a way I can fix this?

**Comment by seletskiy** [comment]
Can you, please, narrow down issue to the minimum reproduceable case? I do
not have OSX and cannot execute applescript code to test it.

On Thu, Jan 14, 2016 at 11:53 PM, pdoak <notifications@github.com> wrote:

> I am trying to write a snippet which retrieves information from the front
> Safari page The snippet uses some shell code with embedded applescript but
> it does not work The snippet code is:
>
> snippet surl "Grab highlighted text" b
>
> `#!/usr/local/bin/zsh
> mytext=$(/usr/bin/osascript << END
> tell application "Safari"
>  selecTxt to (do JavaScript "(getSelection()toString())" in document 1)
> set pgTitl to (do JavaScript "documenttitle" in document 1)
> set pgDate to (do JavaScript "documentlastModified" in document 1)
> set myURL to URL of front document
> set copyText to selecTxt & return & return & "[" & pgTitl & "]" & return & "(" & myURL & ")" & return & "Page Last Modified:" & pgDate & return & "Clipped On:" & (current date)
> return copyText
> end
> END)
> echo $mytext`
>
> endsnippet
>
> I know that the shell code works as if I run this script, it returns the
> information and copies it to the clipboard:
>
> #!/usr/local/bin/zsh
>
> mytext=$(/usr/bin/osascript << END
> tell application "Safari"
> set selecTxt to (do JavaScript "(getSelection()toString())" in document 1)
> set pgTitl to (do JavaScript "documenttitle" in document 1)
> set pgDate to (do JavaScript "documentlastModified" in document 1)
> set myURL to URL of front document
> # set copyText to selecTxt & return & return & pgTitl & return & myURL & return & "Page Last Modified:" & pgDate & return & "Clipped On:" & (current date)
> set copyText to selecTxt & return & return & "[" & pgTitl & "]" & return & "(" & myURL & ")" & return & "Page Last Modified:" & pgDate & return & "Clipped On:" & (current date)
> return copyText
> end
> END)
>
> echo $mytext
> echo "$mytext" |  pbcopy
>
> It looks as though the applescript inside the shell code is not being
> interpreted Is there a way I can fix this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SirVer/ultisnips/issues/639>.
>



-- 
Stanislav Seletskiy

**Comment by pdoak** [comment]
This snippet works:
```
snippet stest3

`#!/usr/local/bin/zsh
myvar=$(osascript -e "tell application \"Safari\"" -e "activate" -e "set myvar to URL of current tab of front window" -e "return myvar" -e "end tell")
echo $myvar`
endsnippet
```
But this doesn't:
```
snippet stet4

`#!/usr/local/bin/zsh
myvar=$(osascript -e "tell application \"Safari\"" -e "activate" -e "set myvar to URL of current tab of front window" -e "set myvar to (do JavaScript \"document.title\" in document 1)" -e "return myvar" -e "end tell")
echo $myvar`
endsnippet
```
UltiSnips gives the following error:
`UltiSnips.snippet.source.file._base.SnippetSyntaxError: Invalid line '-e "set myvar to (do JavaScript \\"document.title\\" in document 1)"' in ~/.config/nvim/UltiSnips/markdown.snippets:101`

Thanks for looking into this. Please let me know if you need any further information.

**Comment by seletskiy** [comment]
@pdoak: hmm, I can't even take a wild guess why it does not work. Can you try to return something very simple, like string "abc" from the JavaScript?

Also, try to add `exec &>>/tmp/lala` at the beginning of the script and then invoking snippet (at that point nothing will be inserted), and then look at output of `/tmp/lala`.

**Comment by pdoak** [comment]
Thanks for the reply. I am not particularly good with JavaScript. Please could you be more explicit with what you want me to try.

Many thanks

**Comment by seletskiy** [comment]
Something like this:
```
myvar=$(osascript -e "tell application \"Safari\"" -e "activate" -e "set myvar to (do JavaScript \"123\" in document 1)" -e "return myvar" -e "end tell")
```

**Comment by pdoak** [comment]
This snippet:
```
snippet stest6 "test" 

`#!/usr/local/bin/zsh
exec &>>/tmp/lala
myvar=$(osascript -e "tell application \"Safari\"" -e "activate" -e "set myvar to (do JavaScript \"123\" in document 1)" -e "return myvar" -e "end tell")
echo $myURL`

endsnippet
```
produces no output when invoked.

Also, /tmp/lala is created but empty.

Once again, thank you for looking into this and let me know if I can test anything further as I would like to get this working.

Many thanks

**Comment by seletskiy** [comment]
@pdoak: Sorry, I can not imagine what's causing the problem. I guess the difference somehow in the environment variables or so. Try to save shell code to the separate file and then invoke from the vim (e.g. via `:!my-shell-file.sh`) and see, is there difference or not. I think it's not US problem.

**Comment by pdoak** [comment]
@seletskiy: It works if I invoke from vim command line. That would suggest that it is not a problem with vim!
Please let me know if I can provide any further information to get to the bottom of the problem.

Many Thanks

Paul

**Comment by seletskiy** [comment]
@pdoak: Did you fix your issue?

**Comment by pdoak** [comment]
No. I attached the applescript to a Keyboard Maestro trigger which copied the data to the clipboard so that it could then be pasted into the document - not ideal but it worked.

If you have any further ideas, I would like to try and make a better workflow.

Regards

Paul

**Comment by SirVer** [comment]
I successfully ran your initial example by saving it into `/tmp/script.sh` and using the snippet:

~~~
snippet surl "Grab highlighted text" b
`sh /tmp/test.sh`
endsnippet
~~~
