### ISSUE TITLE
Snippets doesn't expand inside parenthesis

### ISSUE THREAD

**Issue by stevensgarcia** [SirVer/ultisnips#640]
Let's say ``cl`` to expand ``console.log()`` and ``hop`` to expand ``instance.hasOwnProperty('name')``. 
`|` ... represents cursor.

Now `cl` -> **console.log(|)**, and then type "hop" inside `console.log(hop)`, pop up shows the snip, but it doesn't expand it. After hit tab to expand it, cursor goes to the end of **console.log(hop);|**

So, How can I expand inside parenthesis? I have arleady tryed in various ways without success.

Thanks

![screen shot 2016-01-15 at 10 17 10 am](https://cloud.githubusercontent.com/assets/8174929/12356702/f7370ea4-bb71-11e5-8c04-23408b864486.png)

**Comment by dNItro** [comment]
you should add **i** option to your `hop` snippet definition like so:
```vim
snippet hop "Is this an own propert? -> bool" i
${1:instance}.hasOwnProperty("${2:key}")
endsnippet
```

**Comment by MatthewMDavis** [comment]
I haven't been able to get in-word ('i' option) or word-boundary ('w' option) flags to be recognized when they are preceded by ">" when I am editing html.erb files. I asked the following on the launchpad site:

I have some snippets that insert simple erb (embedded Ruby) tags into HTML files. If I try to insert one of these tags immediately following another HTML tag, I'd like it to expand the snippet even without any whitespace.

My understanding is that a snippet like the following should expand no matter what's in front of it:

  snippet erb i
       <% ${1:code} %>

And that a snippet like the following should expand if there is a ">" in front of it, but not a word character:

  snippet erb w
       <% ${1:code} %>

But that's not happening.

If I type " er" with preceding whitespace, and hit the key for UltiSnipsListSnippets, I get four candidates listed in a window at the bottom of my vim buffer. (I have snippets labeled erbe, erbl, erbb, and erb)

If I type ">er" with a preceding ">" character, from the HTML tag directly ahead of it, and hit the key for UltiSnipsListSnippets, it appears to be inserting a literal tab character, and the window at the bottom of the buffer does not appear. Changing the keystroke that invokes UltiSnipsListSnippets from <c-tab> (the default) to <c-l> made no difference in this behavior.

Three of the snippets have the 'i' option turned on, and one has the 'w' option, but none are recognized for expansion if "er" is preceded by a greater-than sign. Whether this carries over into the original problem with parentheses, I could not say. But it doesn't look like the 'i' option always does what it should.

**Comment by seletskiy** [comment]
@MatthewMDavis: so, do you have an issue right now or not? It's not clear from your last comment.

**Comment by MatthewMDavis** [comment]
Oh, sorry. No, I got it figured out now: snipmate formatted snippets don't
do in-word expansion.

**Comment by seletskiy** [comment]
@MatthewMDavis: Thanks. Closing issue, then.

**Comment by stevensgarcia** [comment]
Thank you very much @dNItro . It works like a charm!
