### ISSUE TITLE
add re.MULTILINE flag to transformation's regular expressions part

### ISSUE THREAD

**Issue by dNitro** [SirVer/ultisnips#641]
visual selecting multiple lines and doing a transformation on them treat them as whole a string. for example if i want to replace all the beginning of lines (i mean `^`) with a charachter for example `*`, it only replaces beginning of the first line and the other lines remain untouched. it means regular expression part in transformations uses defalut python behaviour and only applys to the start of the entire selected string.  as re.MULTILINE flag tells python to make the ‘^’ and ‘$’ special characters match the start or end of **any** line within a string, would you add this functionality to transformations pls.

**Comment by seletskiy** [comment]
@dNItro: That feature should be trivial to implement, can you provide a pull request? Check `TextObjectTransformation` class in the `pythonx/UltiSnips/text_objects/_transformation.py`.

**Comment by dNItro** [comment]
so have an eye on this: #643

**Comment by SirVer** [comment]
Fixed in pull request.
