### ISSUE TITLE
GetAllSnippets() not working as expected

### ISSUE THREAD

**Issue by pdoak** [SirVer/ultisnips#644]
I am trying to use the following function with [Unite](https://github.com/Shougo/unite.vim). I have inserted the function into my init.vim.
```
function! GetAllSnippets()
  call UltiSnips#SnippetsInCurrentScope(1)
  let list = []
  for [key, info] in items(g:current_ulti_dict_info)
    let parts = split(info.location, ':')
    call add(list, {
      \"key": key,
      \"description": info.description,
      \"path": parts[0],
      \"linenr": parts[1],
      \})
  endfor
  return list
end function
```
When I call Unite with `:Unite output:echo\ join(GetAllSnippets(),"\\n")`, the order is not `key, description ,path,linear,` but `linear,description,key,path`.

If I source a file with:
```
let a= GetAllSnippets()
echo a 
```
the order is still `linear,description,key,path`. Why is the function not returning the elements in the specified order?

**Comment by seletskiy** [comment]
@pdoak: As far as I know, order of keys in dictionary is not defined. And it's not UltiSnips issue, it's vim language limitation. So, closing issue.

**Comment by pdoak** [comment]
@seletskiy Thank you for letting me know.
