### ISSUE TITLE
Problem with numbers after placeholders

### ISSUE THREAD

**Issue by maxless** [SirVer/ultisnips#645]
Looks like I can't insert a placeholder if there is a number immediately after it.
For example, let's suppose I want this piece of code:

```
method();
method2();
method3();
```

If I write a snippet like this

```
snippet x
$1();
$12();
$13();
snippet endsnippet
```

That won't work since the numbers will be added to the placeholder.
And I can't do it like this apparently:

```
snippet x
${1:method}();
${1:method}2();
${1:method}3();
snippet endsnippet
```

Since it looks like only the first placeholder is allowed to have an extended syntax

```
${1}
```

is also not doing anything.

**Comment by seletskiy** [comment]
@maxless: yep, it can'be done in beautiful way, however, at least two workrounds exists:

Using transformations:
```
snippet x "Description" b
${1:method}()
${1///}2()
${1///}3()
endsnippet
```

Using extrapolation:
```
snippet x "Description" b
${1:method}()
`!p snip.rv = t[1]`2()
`!p snip.rv = t[1]`3()
endsnippet
```

**Comment by maxless** [comment]
I've tested the first method and it's working fine, thanks! The second one looks a bit too convoluted :)

Maybe you should mention this in the vimdoc in placeholders section?
