### ISSUE TITLE
honza/vim-snippets plugin directory ultisnips snippets not work

### ISSUE THREAD

**Issue by alanerzhao** [SirVer/ultisnips#649]
`bundle` installed

```
Plugin 'Valloric/YouCompleteMe'             "自动补全
Plugin 'SirVer/ultisnips'                   " Track the engine.snips引擎
Plugin 'honza/vim-snippets'                 "snippets列表
```

`vimrc` setting

```
.....
call vundle#end()            " required
filetype plugin indent on    " required

let g:ycm_key_list_select_completion = ['<C-n>', '<Down>']
let g:ycm_key_list_previous_completion = ['<C-p>', '<Up>']

let g:SuperTabDefaultCompletionType = '<C-n>'

"SirVer/ultisnips and vim-snippets
" Trigger configuration. Do not use <tab> if you use https://github.com/Valloric/YouCompleteMe.
let g:UltiSnipsSnippetDirectories=["UltiSnips"]
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"           "跳到下一个光标点
let g:UltiSnipsJumpBackwardTrigger="<c-z>"
""let g:UltiSnipsExpandTrigger="k"                    "supperTab继承
"" If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit="vertical"
```

I found there are so many good under the directory Ultisnips snippets but ycm seems to be able to selected

**Comment by alanerzhao** [comment]
![image](https://cloud.githubusercontent.com/assets/1327263/12531486/07c12234-c237-11e5-85e5-941f8c747a62.png)

**Comment by seletskiy** [comment]
@alanerzhao: I do not understand your problem. Can you reword?

**Comment by zirho** [comment]
could you try something like this?

```
let g:UltiSnipsSnippetDirectories = ['~/.vim/bundle/vim-snippets/Ultisnips', '~/.vim/bundle/jasmine.vim/snippets']
let g:UltiSnipsSnippetsDir = '~/.vim/after/snippets'
let g:UltiSnipsEditSplit = 'horizontal'
```

**Comment by zirho** [comment]
also YCM needs to be installed by running 
```
./install.sh --all 
```
something like this in ymc installed folder.

refer to YCM readme.

**Comment by wanchaol** [comment]
This issue is annoying me. I want to let the ultisnips only read the vim-snippets/UltiSnips folder, but it always read the default vim-snippets/snippets folder, no matter how I configured! Please fix it soon.

**Comment by seletskiy** [comment]
@wanchaol: Did you tried to disable snipmate? Via `let g:UltiSnipsEnableSnipMate = 0`?

**Comment by wanchaol** [comment]
@seletskiy Thanks dude, I tried it and it works! But I found my real problem is about the snipmate snippets and I have already fixed it :-)

**Comment by SirVer** [comment]
Closing as partially answered and partially stale.
