### ISSUE TITLE
Unicode warning on first snippet expansion

### ISSUE THREAD

**Issue by benyakov** [SirVer/ultisnips#650]
When first inserting a snippet after opening a file, Vim shows the following error messages:

> Error detected while processing function UltiSnips#ExpandSnippetOrJump:
> line    2:
> /home/jesse/.vim/vim-addons/UltiSnips/pythonx/UltiSnips/text_objects/_transformation.py:13
> 9: RuntimeWarning: Argument <type 'str'> is not an unicode object. Passing an encoded stri
> ng will likely have unexpected results.
> Press ENTER or type command to continue
> Error detected while processing function UltiSnips#ExpandSnippetOrJump:
> line    2:
>   text = unidecode.unidecode(text)
> Press ENTER or type command to continue

After pressing enter, the snippet is inserted as expected, and the error message is not repeated for subsequent snippet insertions.

The snippet being inserted is defined as follows:

> snippet sec "Section" b
> \section{${VISUAL}${1:section name}}
> \label{sec:${2:${VISUAL/\\\w+\{(.*?)\}|\\(.)|(\w+)|([^\w\\]+)/(?4:_:\L$1$2$3\E)/ga}${1/\\\w+\{(.*?)\}|\\(.)|(\w+)|([^\w\\]+)/(?4:_:\L$1$2$3\E)/ga}}}
>
> ${0}
> endsnippet

**Comment by seletskiy** [comment]
@benyakov: I can not reproduce. Snippet text provided by you has disbalanced parenthesis, the valid one is:
```
snippet sec "Section" b
\section{${VISUAL}${1:section name}}
\label{sec:${2:${VISUAL/\\w+{(.?)}|(.)|(\w+)|([^\w]+)/(?4:_:\L$1$2$3\E)/ga}${1/\\w+{(.?)}|(.)|(\w+)|([^\w]+)/(?4:_:\L$1$2$3\E)/ga}}}

${0}
endsnippet
```

Otherwise, look good for me:

![a](https://cloud.githubusercontent.com/assets/674812/12643933/2220b9d4-c5e1-11e5-9721-41436e2b43eb.gif)

As you can see, transliteration works well.

**Comment by benyakov** [comment]
A little more experimentation shows that if I remove the ${VISUAL ...} parts from the snippet, Vim no longer shows the error messages.

If I insert any snippet before trying one that produces the error messages, then the error messages are not produced. 

Lastly, if I insert the snippet that includes ${VISUAL ...} parts by first visually selecting a word to be included in the snippet, then the error message is not produced.

The error messages appear
* only with a snippet using ${VISUAL}, and
* only in the very first snippet insertion after opening the file, and
* only when inserting the snippet *without* using visual mode to select something to include

**Comment by seletskiy** [comment]
@benyakov: Please, try to debug it adding `print("text", text)` befure _transformation:139.

**Comment by benyakov** [comment]
When showing the error messages, it prints ('text', '') before the error messages and then ('text', u'section name') twice after the error messages. The empty string in the first is not a unicode string.

When inserting the same snippet a second time, nothing is printed and there are no error messages.

**Comment by seletskiy** [comment]
@benyakov: Please, provide vim and python version you are using.

**Comment by benyakov** [comment]
Vim: 7.4 (7.4.712 in Ubuntu)
Python: 2.7.10

**Comment by seletskiy** [comment]
@benyakov: Sorry, I have no time to track down that specific problem. However, I will gladly merge PR if you will fix that issue.

**Comment by benyakov** [comment]
I think I found the problem. The substitution specification for the \label
command in the example snippet used two flags/options: g and a. I didn't
recognize the a flag from Vim, and didn't find it documented anywhere, so I
removed it. The problem disappeared.

I still haven't found any documentation on the a flag in Vim, but Python 3
allows an A option, which changes certain elements to match only ASCII
characters. That may have been the cause.

Jesse

**Comment by benyakov** [comment]
The issue is resolved, but a mystery remains: what was the a flag doing in the substitution regexp? That is, why was it accepted, and what effect is it supposed to have?
