### ISSUE TITLE
completion snippets

### ISSUE THREAD

**Issue by nhooyr** [SirVer/ultisnips#652]
It'd be really nice to have neosnippets `g:neosnippet#enable_completed_snippet` in ultisnips. Essentially it lets you take completions of functions and cycle through parameters.

**Comment by seletskiy** [comment]
@nhooyr: Please, provide more info about what you want.

**Comment by nhooyr** [comment]
ah forget it, bad idea imo now.

**Comment by nhooyr** [comment]
Actually well maybe it could use some discussion.

Its essentially Valloric/YouCompleteMe#234 but implemented in neosnippet.

**Comment by seletskiy** [comment]
@nhooyr: It's already possible in UltiSnips, no modification required (I did it as part of pre-/post-expand actions).

I'm using it for a while:

https://cloud.githubusercontent.com/assets/8445924/8632759/338fe40c-2798-11e5-8dbf-4062e88ba08c.gif

Snippet that is shown in gif:

https://github.com/reconquest/snippets/blob/master/go.snippets#L657

**Comment by seletskiy** [comment]
@nhooyr: Actually, that feature is so versatile, that you can create anonymous snippet, that will expand to different anonymous snippet if some condition is present. See, how `if err != nil {` snippet added after `toml.Decode`. Actually, there is a check, that if `err :=` presents in previous expansion, then `if err != nil {` should be added.

**Comment by nhooyr** [comment]
interesting thanks!

**Comment by nhooyr** [comment]
@seletskiy could you link the snippet again? it's gone now :(
