### ISSUE TITLE
[Feature-Request]: ${variable}-mirroring 

### ISSUE THREAD

**Issue by shibumi** [SirVer/ultisnips#654]
Hello,
I would wish to have a mirror for `${variables}` in snippets.. I want to use regex for `$variables` and mirroring of them at the same time. But I just know that I can only use the regex in `${variables}`. (Maybe I am wrong).

An example:
I have at different positions in the snippet an `$7` for mirroring a version number for example 0.1.2-7 ..  but at a few positions I want only 0.1.2 and not 0.1.2-7. So I would be happy if I would have something like a mask so that I can mask some of the variables and all other will be mirrored normally.

**Comment by seletskiy** [comment]
@shibumi: I don't quite understand the exact behaviour you want to achieve. For version case you can use transformation, like that: `${7/-\d+$//}`, so release number will be treamed out of version.

**Comment by shibumi** [comment]
@seletskiy sorry my fault. I had the problem that the variable is not getting mirrored when I try this.. but with the current version it seems to work.

**Comment by shibumi** [comment]
@seletskiy Do you know how I can do the following:

I want to input a number and at some other position all number of the digits shall be replaced to "=".

I have tried the following:
```
${1}
${1/.*/=/}
```
this doesn't seem to work.. it will be just nothing replaced.. I tried also to escape the *-operator..  If I do `1/./=/` it's working correctly for one digit.

**Comment by shibumi** [comment]
sorry the spam.. I solved it by myself.. I just have to use the `g`-flag.. I didn't know that ultisnips supports that. awesome!
