### ISSUE TITLE
Ending a conditional tabstop transformation with backslash

### ISSUE THREAD

**Issue by kmarius** [SirVer/ultisnips#656]
It is not possible to end a conditional in the replacement with a backslash, because
`_find_closing_brace` and `_split_conditional` in `pythonx/UltiSnips/text_objects/_transformation.py` only check if the char before `:` or `)` is a backslash and not if the backslash is escaped.
Example:

    snippet test "Description" b
    $1
    ${1/(a).*|.*/(?1:\\\\:nope)/}
    endsnippet

I'm not sure how many backslashes are actually needed, but no amount works.

**Comment by seletskiy** [comment]
@kmarius: Thanks for bug report. If you can, please, do pull request, I will gladly merge it.
