### ISSUE TITLE
Neovim: Ultisnip messes with phpdoc indentation when hitting newline

### ISSUE THREAD

**Issue by thornycrackers** [SirVer/ultisnips#658]
**Gif of Issue:**
[link](http://giphy.com/gifs/l4KhSOtsW8N9SJYkw)
* I have an alias of vim -> nvim so please ignore that.

**My init.vim file:**
```
call plug#begin('~/.config/nvim/plugged')
Plug 'SirVer/ultisnips'
call plug#end()

let g:UltiSnipsExpandTrigger="<c-k>"
````

**Neovim version:**
NVIM v0.1.1-81-g1946f96

I have singled the issue down to just the ultisnips plugin. I stripped out of the other modules and made a simple snippet for phpdoc. Whenever I call the snippet, '/*', it will  complete the snippet but when I hit a newline it messes with the indenting. If someone knows why this is happening I would be forever grateful, it's driving me crazy.

**Comment by seletskiy** [comment]
Please, paste snippet's code that you are using.

**Comment by thornycrackers** [comment]
```
snippet /*
/**
 * ${0}
 */
```

This isn't a snippet I made, it was in the default set that comes with the php snippets.

**Comment by seletskiy** [comment]
@thornycrackers: Sorry, but I cannot reproduce your issue. See linked testcase.

Try to reproduce it with minimal configuration (only ultisnips enabled and `formatoptions` set to `r`).

**Comment by thornycrackers** [comment]
I should also mention that this happens on OSX. I listed my configuration on the first post, it only contains   plugged which loads the ultisnips module. I can replicate this replicate this problem on multiple mac machines.

**Comment by seletskiy** [comment]
@thornycrackers: Try to use newer version of nvim, I tried `NVIM v0.1.3-97-g7609a96` and `NVIM 0.1.2`, it works just fine.

**Comment by seletskiy** [comment]
@thornycrackers: Sorry, I actually now can confirm it, bug became reproduceable when I added `<?php` in the beginning of the file.

**Comment by seletskiy** [comment]
@thornycrackers: I'm afraid it's somehow linked with `indentexpr` option. Try to `set indentexpr=` and try again.

**Comment by thornycrackers** [comment]
@seletskiy What value should I set indentexpr to? I've never used that option and I am confused on how it works.

**Comment by seletskiy** [comment]
@thornycrackers: It is bug in the indent expression code that are you using and I highly recommend to ask author about it. As a quickest fix you can use UltiSnips snippets syntax (not snipMate) and define snippet like this:

```
post_expand "vim.command('let b:PHP_InsideMultilineComment = 1')"
snippet /*
/**
 * ${0}
 */
endsnippet
```

**Comment by thornycrackers** [comment]
This came from the 'honza/vim-snippets' repo so should I submit this code to fix the issue?

**Comment by seletskiy** [comment]
@thornycrackers: You can try. Or, you can try to communicate developer of PHP indenting function in vim.
