### ISSUE TITLE
I can't open any man page

### ISSUE THREAD

**Issue by oren** [SirVer/ultisnips#660]
if i add  `Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets'` to my init.vim i can't open any man page. For example - `man ls`. The console just freezes until i hit ctrl+c. any ideas?

btw, I have this line in my .bashrc: 
```
export MANPAGER="sh -c \"col -b | nvim -c 'set ft=man ts=8 nomod nolist nonu noma' -\""
```

**Comment by oren** [comment]
here is my init.vim: https://github.com/oren/dotfiles/blob/master/x1/init.vim

**Comment by seletskiy** [comment]
@oren: Try to narrow down issue by you own, e.g. reproduce it with minimal vimrc.

**Comment by oren** [comment]
yup. i'll do that and update the issue. thanks.

**Comment by oren** [comment]
Here is a minimal init.vim
```
call plug#begin()
Plug 'SirVer/ultisnips'
call plug#end()
```

More info about my system: ubuntu 15.10, nvim 0.1.3-dev

**Comment by seletskiy** [comment]
@oren: Please, paste your `vimrc` file, not some custom init file.

**Comment by oren** [comment]
I apologize but I should have mentioned it earlier. I am using neovim, not vim.  I don't have .vimrc file. init.vim is the name of the neovim config file.

**Comment by seletskiy** [comment]
@oren: I can not reproduce on clean setup with NVIM v0.1.3-97-g7609a96 and following `init.vim`:

```
if empty(glob('~/.config/nvim/autoload/plug.vim'))
    silent !mkdir -p ~/.config/nvim/autoload
    silent !curl -fLo ~/.config/nvim/autoload/plug.vim
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall
endif

call plug#begin()
Plug 'SirVer/ultisnips'
call plug#end()
```

MANPAGER:
```
export MANPAGER="sh -c \"col -b | nvim -c 'set ft=man ts=8 nomod nolist nonu noma' -\""
```

So I suggest you try clean setup and/or run man with strace. It's probably not UltiSnips issue. Closing for now, if you will have new thoughts, please, feel free to reopen.

**Comment by seletskiy** [comment]
@oren:
![a](https://cloud.githubusercontent.com/assets/674812/13045386/cdfa730a-d3f4-11e5-8676-504ec7ee98aa.gif)
