### ISSUE TITLE
ImportError with vim7.4 1317

### ISSUE THREAD

**Issue by chemzqm** [SirVer/ultisnips#661]
Just trying the latest vim 1317, and I got:
```
Error detected while processing /Users/chemzqm/.vim/bundle/ultisnips/autoload/Ul
tiSnips.vim:
line   15:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named UltiSnips
Error detected while processing function UltiSnips#FileTypeChanged:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'UltiSnips_Manager' is not defined
```
I've check the path by
```
:py print sys.path
```
and
```
:py import vim
:py print vim._get_paths()
```
The result looks exactly the same as the output from my macvim, which using vim 7.4 1147.
It's looks like a issue of vim, but I have no clue of digging deeper.

**Comment by seletskiy** [comment]
@chemzqm: unfortunately, latest version in the distro I'm using is 7.4.1294, so I'll wait until new version will arrive to test this issue. I do not want to rebuild vim by myself, sorry.

**Comment by chemzqm** [comment]
Looks like the problem is I've build vim with MacOX python 2.7.10. After I download vim source again and configure vim with
```
./configure --disable-gui \
                     --enable-fail-if-missing \
                     --enable-pythoninterp \
                     --enable-rubyinterp \
                     --with-features=huge \
                     -with-compiledby=chemzqm \
                     --with-local-dir=/Users/chemzqm/Library   \
                     --enable-luainterp \
                     --enable-multibyte \
                     --prefix=/usr/local \
                     --enable-cscope \
                     --with-lua-prefix=/usr/local \
                     --enable-pythoninterp \
                     --with-python-config-dir=/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7
```
after `make & sudo make install` I can build vim with brew installed python 2.7.11 (checked with `:py import sys;print sys.version`)
, the issue no longer exists.

**Comment by apburton84** [comment]
Same issue, but brew compiled vim with Python 2.7.11, however the issue still occurs
  
    Error detected while processing /Users/ant/.vim/bundle/ultisnips/autoload/UltiSnips.vim:
    line   15:
    Traceback (most recent call last):
    Press ENTER or type command to continue
    Error detected while processing /Users/ant/.vim/bundle/ultisnips/autoload/UltiSnips.vim:
    line   15:
    File "<string>", line 1, in <module>
    Press ENTER or type command to continue
    Error detected while processing /Users/ant/.vim/bundle/ultisnips/autoload/UltiSnips.vim:
    line   15:
    ImportError: No module named UltiSnips

vim --version

    VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar  7 2016 21:05:18)
    MacOS X (unix) version
    Included patches: 1-1468
    Compiled by Homebrew

:py import sys; print sys.version;

    2.7.11 (default, Mar  7 2016, 21:03:41)
    [GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]

installed both Python & Vim with: 

    brew install python
    brew install vim

any help would be appreciated :-)

**Comment by esbenp** [comment]
Had the same error on OSX. I simply installed VIM using brew `brew install vim`. This installed 8.x instead of 7.4 and the error disappeared.
