### ISSUE TITLE
Deoplete integration: UltiSnips suggestions do not appear when line is not empty

### ISSUE THREAD

**Issue by pwntester** [SirVer/ultisnips#662]
Hi,

When integrating with deoplete, snippets are only triggered if there is no text in the current line (just whitespaces). If there is any previous text in the line, the UltiSnips suggestions do not appear.

Thanks,
A

**Comment by seletskiy** [comment]
@HerringtonDarkholme: Can you take a look, please?

**Comment by HerringtonDarkholme** [comment]
Can you give more specific example? It works for me.
Also , US priority is quite low in deoplete. @seletskiy do you think it need a boost?

![screenshot from 2016-04-01 22 24 18](https://cloud.githubusercontent.com/assets/2883231/14209832/ad4dea82-f858-11e5-8f4f-910d8d5ee079.png)

**Comment by seletskiy** [comment]
@HerringtonDarkholme: I do not think it need a boost. However, I do not use deoplete personally, so it's better if you do that choice by yourself. If you do not think it's critical, I add specific tag to the issue.

**Comment by andreyorst** [comment]
I use deoplete and don't expirience this issue at all. 

![image](https://user-images.githubusercontent.com/19470159/38454223-cba93c5a-3a6b-11e8-915a-cddf78f745cf.png)
As for priority - snippets are short key sequence, or same as language facility and you don't need to reach it in the list to expand even if it has lo priority. If I hit expand key (in my case it is <kbd>Enter</kbd>) it will expand `for` snippet as no problem.

I close this as nonteproducible, feel free to reopen if you still expiriencing the problem.
