### ISSUE TITLE
Ultisnips interferes with other InsertLeave autocmd

### ISSUE THREAD

**Issue by lekv** [SirVer/ultisnips#664]
I have the following setting in my .vimrc to prevent the cursor from jumping one character to the left when leaving insert mode:

```
augroup EscapeOnSameChar
    autocmd!
    autocmd InsertLeave * :normal `^
augroup END
```

However, this leads to the cursor in expanded snippets to end up one character to the right of where it should be after expansion. For example, when expanding `cout` I'd expect the cursor to be at position A, but it ends up at position B:

```
std::cout <<  << std::endl;
             AB
```

This might not be an issue with Ultisnips, but as I could not find a work-around I'd be glad for any helpful tip. Thanks a lot.

**Comment by SirVer** [comment]
This is an unfortunate issue with Vim's design - you cannot merge, prioritize or disable different autocommands. I am sorry, but there is really no good work around here that I know off.
