### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by fan-tom** [SirVer/ultisnips#668]
When path to snippet file contain non-ascii symbols (i.e. C:\Users\Алексей...) _UnicodeDecodeError: 'ascii' codec can't decode byte ... in position ...: ordinal not in range(128)_
thrown at line 51 of ultisnips/pythonx/UltiSnips/snippet_manager.py:
`...escape(s.location, '\\')) for i, s in enumerate(snippets)]`
After such quick fix: 
`escape(s.location.decode('cp1251'), '\\')) for i, s in enumerate(snippets)]`
all works fine(i'm from Russia that is why my system codepage on Windows is cp1251). As we can see, it is necessary to decode s.location before future use

**Comment by seletskiy** [comment]
@fan-tom: I guess, that your fix is not compatible with other OSes, because it assumes, that `s.location` is `cp1251`, which is not.

**Comment by seletskiy** [comment]
@fan-tom: If you want, you can prepare pull-request, which works at cp1251 as well as in utf-8 encodings.

**Comment by SirVer** [comment]
This seems fixed at c309637e0243b71f7e3265ebe3cffdfe9674cfbc, likely due to the move to py3.
