### ISSUE TITLE
[feature request] trigger for autogenerating content when vim is opened

### ISSUE THREAD

**Issue by shibumi** [SirVer/ultisnips#671]
Hello,
I am not sure if this is already implemented. I want a trigger like this:

`/home/chris/.vim/UltiSnips/sh.snippets`
```
snippet header "headerfile" new
#!/bin/bash
# `date -I`
# Author: `echo $USER`
```

the keyword `new` should autogenerate the content when I open a new file with the suffix `sh`.
So for example if I do `vim projects/newproject.sh` the file should autogenerate the content without explicitly typing in `header` and pressing tab. The content should be generated without user interaction just when I open vim with a new fresh file with this suffix.

**Comment by seletskiy** [comment]
@shibumi: No need to modify ultisnips, it's already possible.

See either my configuration files: https://github.com/seletskiy/dotfiles/blob/master/.vimrc#L424-L425

Also, there is a very simple plugin for using ultisnips as skeletons: https://github.com/kovetskiy/vim-ski [cc: @kovetskiy]

**Comment by shibumi** [comment]
@seletskiy nice work! thank you. I will close this issue.
