### ISSUE TITLE
Crash on Windows 10

### ISSUE THREAD

**Issue by dix75** [SirVer/ultisnips#673]
Hi all
Ultisnips crashes on Windows 10 (x64)[ Russian Edition] and gvim74-1024.exe and (python 2.7.11(x32)  or 3.5.1(x32)).
I tried to disable all in _vimrc file (I keep only the Vundle loader)

For example.
My _vimrc

```
set rtp+=~/.vim/bundle/Vundle.vim/
call vundle#begin()
    Plugin 'VundleVim/Vundle.vim'
    Plugin 'SirVer/ultisnips'
call vundle#end()
```

All x64 versions of python aren't  loaded by Ultisnips.

---

P.S.
On Windows 7(x64) and 8.1(x64) and XP,  it works perfectly.
On Ubuntu ok too.

**Comment by seletskiy** [comment]
@dix75: What do you mean by "crashes"?

**Comment by dix75** [comment]
Like that.
The vim is terminated with error message.

**Comment by seletskiy** [comment]
Sorry, I can't help you unless you provide detailed bug report, including error message.

**Comment by dix75** [comment]
How to create full bug report?

**Comment by jacquesh** [comment]
I get the same issue on my machine (Windows 10 x64), I open gvim, enter insert mode and it breaks as soon as I start typing:
![ultisnipserror](https://cloud.githubusercontent.com/assets/4639662/22539454/d44aa826-e922-11e6-8777-a2a647ee8a85.png)

This is using a version that I compiled myself (though I didn't modify any of the vim source):
![ultisnipsbrokenbuildver](https://cloud.githubusercontent.com/assets/4639662/22539485/fce65cd0-e922-11e6-9ed5-dcb1c4c03050.png)

Interestingly though, if I use the pre-compiled binaries downloaded from [here](https://tuxproject.de/projects/vim/), it works fine.
![ultisnipsworkingbuildver](https://cloud.githubusercontent.com/assets/4639662/22539521/389bd426-e923-11e6-8d0c-f5e10653faff.png)

I suppose its possible that one of the patches between my build and the pre-compiled version fixed an issue which causes this but I haven't had a chance to make a new build and check yet.

**Comment by SirVer** [comment]
Likely a problem of pulling in both Python2 and Python3 in a non-compatible way. Probably similar to #1032.
