### ISSUE TITLE
Rails.snippets not triggering

### ISSUE THREAD

**Issue by anhari** [SirVer/ultisnips#674]
Hey, after porting my dotfiles over to a new machine all of my snippets are triggering as expected except for those within in my [rails.snippets file](https://github.com/michaelanhari/dotfiles2/blob/master/vim/snippets/rails.snippets).

I think I've fixed this issue before, but I cannot recall what the culprit was. Any ideas?

**Comment by seletskiy** [comment]
@michaelanhari: Check, that you have filetype equal to `rails` in buffer you're editing.

**Comment by miaopeng** [comment]
@anhari: Same issue before, renamed rails.snippet to ruby_rails.snippet and worked.

**Comment by kapsy** [comment]
I'm having the same issue with swift.snippets - is there something I'm doing wrong? C snippets in a custom c.snippets file work fine, and when I run `UltiSnipsAddFiletypes swift` for the currently open `file.swift` file, it works fine, but it won't work by default. Any help appreciated!

**Comment by anhari** [comment]
@kapsy This is likely because vim isn't setting the filetype to `swift` for your `file.swift` file. Try https://github.com/keith/swift.vim maybe?

@seletskiy Sorry for waiting so long to get back to you on this, butI think we can close this issue.  I must have been using a plugin that set the filetype to `rails` in the past.  I've moved my snippets to the ruby `snippets` file and all is well.

**Comment by borenho** [comment]
For anyone else who faces this issue and comes here, you can add 
```
extends rails
```
to the top of your `ruby.snippets`. This way, all Rails snippets will be available in your `.rb` files
