### ISSUE TITLE
C++ snippets not being expanded in parenthesis, angle brackets etc.

### ISSUE THREAD

**Issue by pmalek** [SirVer/ultisnips#675]
Having C++ snippets like [these ones from honza/vim-snippets](https://github.com/honza/vim-snippets/blob/master/snippets/cpp.snippets) some of those snippets e.g.

```
## Lambdas
# lamda (one line)
snippet ld
	[${1}](${2}){${3}}
```

will not expand when e.g. in parenthesis. This is especially useful when we write something like:

    vector.push_back( /* lambda expression should go here */ );

or when someone defines snippet like so:

```
# templates
snippet tpn
	typename ${1:T}
```

then it wouldn't expand in:

    template<tpn /* wouldn't expand here */

**Comment by seletskiy** [comment]
@pmalek: Please, report directly to the honza/vim-snippets. It's not issue in ultisnips by itself.
