### ISSUE TITLE
Visual and non visual snippet

### ISSUE THREAD

**Issue by netei** [SirVer/ultisnips#680]
I'd like to be able to have two snippets with the same name, one for VISUAL, the other for INSERT mode

```
snippet cl
console.log(${1:$VISUAL});
endsnippet
```

INSERT MODE `cl<Tab>` would write console.log(<cursor>);
and with the text `user` 

NORMAL MODE `ve<Tab>cl<Tab>` would write  `console.log(user);`

Is this already possible somehow ?

It would maybe make sense to say that VISUAL=$1 when you trigger the snippet without visual mode for all snippets.

What do you think ?

**Comment by seletskiy** [comment]
@netei: I do not completely understand, what behavior you want to achieve? Can you, please, rephrase?

**Comment by netei** [comment]
After testing a little bit, I found out that what I want can be achieved like this : 

```
snippet cl
console.log(${1:${VISUAL}});
endsnippet
```

**Comment by netei** [comment]
I also think one of the following two behaviours would make sense : 

1. If `${VISUAL}` is not is a snippet, then, when triggered visually, replace ${1} by ${1:${VISUAL}}
2. If `${VISUAL}` is not in a snippet, then, it shouldn't be possible to trigger it visually.

**Comment by seletskiy** [comment]
@netei: That two methods are already possible and they are described in docs (see `:help UltiSnips-context-snippets` and `:help UltiSnips-visual-placeholder`).

First way (via context snippets, introduced in 3a3e56a987091ed9622eca810d8185875a44b12b):
```
# will be triggered only if visual selection is not empty
snippet cl "console log visual" "snip.visual_text" be
console.log(${1:${VISUAL}})
endsnippet

snippet cl "console log" b
console.log(${1:'not in visual'})
endsnippet
```

Second way (default value in visual placeholder):
```
snippet cl "console log visual default value" b
console.log(${1:${VISUAL:'default value'}})
endsnippet
```
