### ISSUE TITLE
ultisnips forgets tabstops when preview window opens

### ISSUE THREAD

**Issue by alok** [SirVer/ultisnips#681]
I'm using neovim with deoplete, deoplete-jedi, and ultisnips (all latest versions from git) to edit a python file. Jedi pops up the preview window to show a docstring for the function I'm editing, but then any snippet I was writing suddenly loses the ability to jump through tabstops after the preview window pops up.

**Comment by seletskiy** [comment]
@Alok: I do not have enough time to track down that issue by myself, personally I do not use neither neovim nor deoplete, so, if you can fix that issue by yourself, I will gladly merge PR.

@HerringtonDarkholme: Maybe, you have some opinion on that issue.

**Comment by SirVer** [comment]
This is intended behavior - when you switch the window, snippets exit. 

A workaround is prepared in https://github.com/SirVer/ultisnips/pull/845 that optionally disables the preview window when a snippet is in progress.
