### ISSUE TITLE
 Error detected while processing /Users/Mr.Wu/.vim/bundle/UltiSni ps/autoload/UltiSnips.vim: line   15:

### ISSUE THREAD

**Issue by wudapeng268** [SirVer/ultisnips#687]
When I goto vim ,switch insert mode ,whatever I input,this is always give me error

Error detected while processing /Users/Mr.Wu/.vim/bundle/UltiSni
ps/autoload/UltiSnips.vim:
line   15:
Traceback (most recent call last):
How can I solve this problem?I use Mac OS.X EI,look forward you reply,thanks

**Comment by samumist** [comment]
@wudapeng268 
have you updated your python recently? If so, you might need to rebuild your vim.
I had the same issue recently when switching from system python to homebrew python. After brew installing python, I had the same error message when opening vim.

I just `brew uninstall vim` and `brew install vim `, then everything worked fine.

**Comment by kenng** [comment]
ya, seem like new macvim is compiled with python 3. so uninstall and install macvim again fix the problem. To check, run `brew info macvim`.

**Comment by moseshu** [comment]
when is goto Vim .use insert mode.this is always error below:
my mac system is MacOS Mojave.
Error detected while processing /Users/moses/.vim/bundle/ultisnips/autoload/UltiSnips.vim:
how to fix this error 


I try to install macvim . 
but Macvim install fails on MacOS 10.14 https://github.com/Homebrew/homebrew-core/issues/32464Homebrew macvim will not run after Sierra Security Update https://github.com/Homebrew/homebrew-core/issues/33656
