### ISSUE TITLE
The unite's source does not list all the snippets

### ISSUE THREAD

**Issue by KabbAmine** [SirVer/ultisnips#689]
I'm using `honza/vim-snippets` and my own custom snippets, the edition/expansion of snippets is working as expected.

`UltiSnips#SnippetsInCurrentScope()` returns me all the snippets (default & custom ones), but when I'm using the unite's source (Which also use the same function) only the global snippets are listed.  
Note that `<c-tab>` also lists all my snippets so the problem is definitely with unite or my config.

My configuration

``` vim
nnoremap <C-F2> :UltiSnipsEdit<CR>
let g:UltiSnipsExpandTrigger = '<tab>'
let g:UltiSnipsJumpForwardTrigger = '<tab>'
let g:UltiSnipsJumpBackwardTrigger = '<S-tab>'
let g:UltiSnipsEditSplit = 'vertical'
" Personal snippets folder
let g:UltiSnipsSnippetsDir = g:vimDir . '/various/ultisnips'
let g:UltiSnipsSnippetDirectories = ['UltiSnips', g:vimDir . '/various/ultisnips']
```

**N.B:** `g:vimDir` is my vim's directory (`$HOME/.vim` in Unix & `$HOME/vimfiles` in windows).

My [custom snippet files](https://github.com/KabbAmine/myVimFiles/tree/master/various/ultisnips).

_Vim 7.4.882_

**Comment by SirVer** [comment]
Closing as stale. OP contains dead links.
