### ISSUE TITLE
Error expanding snippet with encoding=utf-8 on windows

### ISSUE THREAD

**Issue by theothermatt** [SirVer/ultisnips#690]
Vim version:  7.4.1023, Windows GUI

Expanding a snippet causes the following error, but **only** when `encoding=utf-8`.  It doesn't seem to matter what `fileencoding` is set to, only `encoding`.

To be clear, I don't think this is a problem with the snippet, since it works with `encoding=latin1` for example.  Additionally, the snippet still expands when `encoding=utf-8`, I just get the error message too.

This doesn't happen on the same machine when using Cygwin, vim version 7.4.663.

```
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

Following is the full stack trace:
Traceback (most recent call last):
  File "U:\vimfiles\plugged\ultisnips\pythonx\UltiSnips\snippet_manager.py", line 61, in wrapper
    return func(self, *args, **kwds)
  File "U:\vimfiles\plugged\ultisnips\pythonx\UltiSnips\snippet_manager.py", line 166, in expand
    if not self._try_expand():
  File "U:\vimfiles\plugged\ultisnips\pythonx\UltiSnips\snippet_manager.py", line 763, in _try_expand
    self._do_snippet(snippet, before)
  File "U:\vimfiles\plugged\ultisnips\pythonx\UltiSnips\snippet_manager.py", line 734, in _do_snippet
    self._jump()
  File "U:\vimfiles\plugged\ultisnips\pythonx\UltiSnips\snippet_manager.py", line 525, in _jump
    _vim.select(ntab.start, ntab.end)
  File "U:\vimfiles\plugged\ultisnips\pythonx\UltiSnips\_vim.py", line 162, in select
    _unmap_select_mode_mapping()
  File "U:\vimfiles\plugged\ultisnips\pythonx\UltiSnips\_vim.py", line 241, in _unmap_select_mode_mapping
    all_maps = list(filter(len, eval(r"_tmp_smaps").splitlines()))
  File "U:\vimfiles\plugged\ultisnips\pythonx\UltiSnips\_vim.py", line 117, in eval
    rv = vim.eval(as_vimencoding(text))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 1343: invalid start byte
```

**Comment by seletskiy** [comment]
@theothermatt: This issue isn't reproduceable under linux and I do not have Windows development machine neither want one. I will be very glad if you trace it down and fix by making PR.

**Comment by mgedmin** [comment]
I have this issue on Linux.  I suspect that's because my vim now uses Python 3 instead of Python 2, because I didn't have this issue yesterday.

**Comment by mgedmin** [comment]
Ok, it's a bug in vim itself.  When a vim variable contains invalid UTF-8, `vim.eval("that_variable")` raises UnicodeError.

I've the following mapping in my .vimrc:
```
map             <Esc>@          <A-@>
```
which makes `:smaps` produce this
```
   <Esc>@        <c0>
```
and when you redir that to a variable and attempt to `vim.eval(...)` it, you get that UnicodeError.

**Comment by mgedmin** [comment]
I've filed https://github.com/vim/vim/issues/1053

**Comment by mgedmin** [comment]
It looks like it might be possible to work around this by using `vim.bindeval()` instead of `vim.eval()`:

```
:map! <Esc>@ <A-@>               # to get a non-UTF-8 mapping
:redir => tmp | smap <Esc>@ | redir END
:py3 vim.eval('tmp')             # crashes with UnicodeError
:py3 vim.bindeval('tmp')         # doesn't crash
:py3 print(vim.bindeval('tmp'))  # prints 'b'\n   <Esc>@        \xc0'
```
