### ISSUE TITLE
Nested snippets not working when the ExpandTrigger and JumpForwardTrigger is assigned to the same key.

### ISSUE THREAD

**Issue by midchildan** [SirVer/ultisnips#692]
When I assign both `g:UltiSnipsExpandTrigger` and `g:UltiSnipsJumpForwardTrigger` to  `<C-j>` and try to use nested snippets, the cursor always jumps forward instead of expanding the snippet. For example, when I have this snippet `s` :

```
snippet s "snippet s" i
a $1 b
endsnippet
```

and when I enter `s<C-j>s<C-j>foo` , instead of `a a foo b b` , I get `a s b foo` instead. Is there any way to change this behavior?

**Comment by seletskiy** [comment]
@midchildan: Please, show your `imap <C-J>` output.

**Comment by midchildan** [comment]
I get `i  <NL>        * <C-R>=UltiSnips#ExpandSnippetOrJump()<CR>` .

**Comment by SirVer** [comment]
@midchildan My understanding is that you would prefer to always expand if that is possible and only jump forward when expanding is not possible. But how should UltiSnips know that? I argue that prefering jumping over expanding is just as valid a design choice.

The correct solution seems to use two different triggers for two different functionalities, i.e. do not use the same trigger for jumping and expanding. 

Closing as WAI.

**Comment by bookercodes** [comment]
@SirVer Hey man, great plugin! I think what @midchildan is describing is essentially what neosnippet does: https://github.com/Shougo/neosnippet.vim
