### ISSUE TITLE
Automatically jump to next placeholder after hitting BS/DEL/<C-h>

### ISSUE THREAD

**Issue by dNitro** [SirVer/ultisnips#694]
‌By now if we got a Default placeholder after snippet expansion we are entering select mode and the default placeholder is selected. If we want to replace it just keep typing; and if we want to keep it just hitting the mapped jumpforwards key and we are good to go! BUT what if we dont want to replace it nor to keep it. of course we hit `BACKSPACE` or `DEL` or `Ctrl-h`. but after hitting these keys cursor will remain in the same location needing to jump to next placeholder ( if available ), so we hit **TWO** keystrokes ( one for delete + one for jump ) whereas Our intention from deleting was lack of need for that placeholder and jump to next placeholder so if we map `BACKSPACE` / `DEL` / `Ctrl-h` to jump forwards after deleting we just hitted **ONE** keystroke.
changing the following will do the job.
(file: ultisnips/autoload/UltiSnips/map_keys.vim)
original:

```
    snoremap <silent> <BS> <c-g>c
    snoremap <silent> <DEL> <c-g>c
    snoremap <silent> <c-h> <c-g>c
```

changed:

```
    snoremap <silent> <BS> <c-g>c<Esc>:call UltiSnips#JumpForwards()<cr>
    snoremap <silent> <DEL> <c-g>c<Esc>:call UltiSnips#JumpForwards()<cr>
    snoremap <silent> <c-h> <c-g>c<Esc>:call UltiSnips#JumpForwards()<cr>
```

Of course in the new situation we need a new option to Remove any whitespace immediately before the cursor, before jumping to the next tabstop for anyone who dont want to keep spaces. something like `s` option we've already got.
Of course these are not issues, but as a request implementing them would be GREAT.

**Comment by seletskiy** [comment]
@dNItro: It's already possible. I will post an article about it little bit later.

**Comment by dNItro** [comment]
@seletskiy : So +1 for it. Eagerly waiting ... Thanks.

**Comment by seletskiy** [comment]
@dNItro: https://github.com/SirVer/ultisnips/tree/master/doc/examples/autojump-if-empty

**Comment by dNItro** [comment]
@seletskiy : thank you man. it works fine. but now if insert a default placeholder in $2 then after jumping, placeholder is resides in wrong position. just change your snippet definition in your article to following to see the issue:
```
context "px.snippets.make_context(snip)"
post_jump "clean_first_placeholder(snip)"
snippet x "Description" b
`!p jump_to_second_when_first_is_empty(snip)
`func (${1:blah}) ${2:blahblah}() {
    $3
}
endsnippet
```
and it is not move by changing snip.cursor.set() ! is it possible to move it to select the default placeholder in right position ?

**Comment by seletskiy** [comment]
@dNItro: looks like bug in the ultisnips in the first place, need further investigation.

**Comment by dNItro** [comment]
I am agree. Someday SirVir stated that its caused by vim design and you told me to use autotrigger option (does not worked!) (issue #528). I dont now how much these two issues are relate to each other. But tabstop selections always hurts. Though UltiSnips is so complete, its placeholder selection doesn't work well in many complex situations like nested snippets (issue #528) and times when you select candidates from popup menu list items and scriptically jump to next placeholder or this new one; In such situations it nearly always reside in wrong position in select mode. So i think of course its a bug and you may revision the way placeholders are selected.

**Comment by seletskiy** [comment]
@dNItro: usually, bugs in US can be worked around one way or another. vim API is very ugly indeed, and due it's ugliness there are number of bugs.

What kind of issue you experience with autotrigger? I use that option in my daily work and do not encounter any issue at all. Consider creating new issue.

Also, I do recommend not using selection unless it's making the difference in typing, and that kind of cases are rare. So, do not use selections like `${1:MethodName}`, where MethodName is just meaningless string. `$1` is enough in that case, and it's bug free.

**Comment by dNItro** [comment]
@seletskiy : Of course by defining placeholders like $1, I also do not encounters any problem even with autotrigger option. Thank you to take your time answer all my questions. I appreciate it.

**Comment by SirVer** [comment]
Closing as answered.
