### ISSUE TITLE
space at the end of tab_trigger string prevents expantion

### ISSUE THREAD

**Issue by dNItro** [SirVer/ultisnips#695]
why inserting space at the end of tab_trigger string prevents its expansion?
for example the following does not expand at all:
```
snippet "foo "
foobar
endsnippet
```
is it meant to be like this or is an issue?

**Comment by seletskiy** [comment]
@dNItro: if you want spaces in the tab trigger, make it regexp-triggered by adding flag `r`.

**Comment by seletskiy** [comment]
@dNItro: more over, it's even possible to create empty tab trigger using regexp `^`

**Comment by dNItro** [comment]
Genius. the only option that i did'nt try! but logical. where in src are these options defined so i can have a look at them?

**Comment by seletskiy** [comment]
@dNItro: `grep` source codes by `_opts`, and you will find the way  :+1:
