### ISSUE TITLE
nested tabstops broken

### ISSUE THREAD

**Issue by scrooloose** [SirVer/ultisnips#697]
Hi, nested tabstops seem to be broken. I have tried this (from the docs) and it doesn't work for me. The `${2:example.com}` tabstop is never highlighted. Just me?

```
snippet a
<a href="${1:http://www.${2:example.com}}"</a>
    $0
</a>
endsnippet
```

**Comment by seletskiy** [comment]
@scrooloose: Seems, that just you:
![nested-tabstops](https://cloud.githubusercontent.com/assets/674812/15217101/d65a0152-187b-11e6-8684-647cb572fc3f.gif)
Please, report your vim version (including patches).

**Comment by scrooloose** [comment]
Ah, yes. I am using neovim `0.1.5-dev`.

This issue is not present in standard vim.

**Comment by seletskiy** [comment]
@scrooloose: UltiSnips are utterly broken under nvim, I do not have time neither motivation to fix it.
