### ISSUE TITLE
Vim crash when opening a line within stdin buffer

### ISSUE THREAD

**Issue by rminster** [SirVer/ultisnips#699]
I often pipe command output to 'gvim -' in order to edit the stdout and save or copy/paste somewhere.  If ultisnips is enabled, vim crashes as soon as I try to edit the "-stdin-" buffer.  This problem is absent when I turn off ultisnips.

## Environment

OS is Windows 10 with relevant packages installed via Chocolatey:
```bash
> choco list --local-only vim python lua
chocolatey 0.9.9.12
lua53 5.3.2
python3 3.5.1
vim-tux 7.4.1824
vim-tux.install 7.4.1824
vim-x64 7.4.1824
6 packages installed.
```

## Vim configuration
_vimrc_minimal
```vimscript
set nocompatible
set runtimepath=$VIMRUNTIME,$HOME/.vim/bundle/SirVer_ultisnips
```

Ultisnips (version b5edea2 examples: add link to vim-pythonx lib)
cloned to ~/.vim/bundle/SirVer_ultisnips

## Workflow
`dir | gvim -u _vimrc_minimal -`
'o' to open a new line in vim
Vi Improved - A Text Editor has stopped working...

**Comment by seletskiy** [comment]
@rminster: The only thing I can propose for you is to use wrapper for vim, so when there are stdin not from terminal load vim with config without ultisnips.

I do not maintain US under windows, and it looks like issue inside vim itself, not US.

Can you show at least error you encounter with?

**Comment by rminster** [comment]
Thanks for the quick response.  I'm good with that workaround.  Using pathogen, I have this script to which I pipe my output....

gvimin.cmd
```
@echo off

start /b gvim --cmd ":let g:pathogen_disabled = ['SirVer_ultisnips']" -
```

To clarify, the only error I get is a generic Windows "A problem caused the program to stop working correctly.".  I tried running with

**Comment by seletskiy** [comment]
@rminster: Then, I guess, error should be reported to vim, not UltiSnips.
