### ISSUE TITLE
E71: Invalid character after \%

### ISSUE THREAD

**Issue by malkomalko** [SirVer/ultisnips#701]
Looks like https://github.com/SirVer/ultisnips/commit/47d343d5c49302b6b6c4749e3d3729acac4180f2 causes this syntax regex error when loading snippet files for snipContext and snipContextKeyword.

**Comment by malkomalko** [comment]
Tracked this down to a vim setting `set regexpengine=1`.  So if anybody has that set you'll run into some problems.

**Comment by seletskiy** [comment]
@malkomalko: fixed, I guess.
