### ISSUE TITLE
Define ultisnip snippets using Python

### ISSUE THREAD

**Issue by ColinKennedy** [SirVer/ultisnips#702]
First off, I love ultisnips and use it everywhere now. I just have a lot of basic snippets and I’m looking to find smarter ways of defining snippets automatically so I don't have to maintain them all individually. For clarification, I’m not talking about ultisnip’s Python interpolation, I mean that I’d like to use Python's classes/methods so that I don't need to manually write and maintain snippets by hand.

Why I would want this - take Python’s magic methods, for example. If I wanted to write ultisnip snippets for some of them, I might write one like this

```
snippet __init__ “My Python __init__”
def __init__(self,$1):
    super(MyKlass, self).__init__($2)
endsnippet
```

This snippet is very straightforward for __init__ but I can't really do the same thing for methods like __iadd__ or __mul__, which will always expect an input.

```
snippet __iadd__ “My Python __iadd__”
def __iadd__(self, ${1:other}):
    self.${2:var} += other.$2
    return self
endsnippet
```

```
snippet __mul__ “My Python __mul__”
def __mul__(self, ${1:other}):
    self.${2:data} = self.$2 * other.$2
    return self
endsnippet
```

So despite the fact that __init__ isn't that different from __mul__ and __iadd__, I have to write and maintain 3 snippets separately anyway. My current solution is to group methods and use __(.+)__ with the "r" flag enabled to grab and translate them with regex but that's a very rough solution because Python has [tons of these methods](http://www.rafekettler.com/magicmethods.html) and they vary their in syntax & inputs. I fully recognize that snippets like these and even more simpler ones could benefit from automation with class inheritance.

Originally, my thought was to define snippets using Python classes that could generate strings much like how, in the ultisnips/test folder, you can find dozens of test classes that do just that. If there's an even better way than that, I'm all-ears. My problem is that I'm not sure how to write my own and have it still load and execute in my environment. So just to reiterate, I want to use Python to automate the process of writing and maintaining my snippets in my environment. Can you please point me in the right direction?

**Comment by seletskiy** [comment]
@ColinKennedy: glad to see someone else who into automation as myself! Keep going!

There at least two ways of creating snippets on the fly. First, is by creating anonymous snippets using [expand_anon](https://github.com/SirVer/ultisnips/blob/master/pythonx/UltiSnips/snippet_manager.py#L222) function. It can be used to create snippets and expand them on the fly.

Second, is little bit more complicated, and is called snippet aliasing: https://github.com/SirVer/ultisnips/blob/master/doc/examples/snippets-aliasing/README.md

So, you can combine both ways and and define regexp triggered snippet `__(.+)__` that will expand anonymous snippets depends on what content is desired.

Like an example, there are partly automatically generated [snippet](https://github.com/reconquest/snippets/blob/master/go.snippets#L425) (little bit ugly :disappointed:), which will expand into method call with dynamic number of tabstops which will represent arguments and return values of the method. Also, depends on situation, that snippet can insert `if err != nil {` condition if `err` is one of the return arguments of the function:
![demo](https://cloud.githubusercontent.com/assets/8445924/8632759/338fe40c-2798-11e5-8dbf-4062e88ba08c.gif)

**Comment by SirVer** [comment]
Closing as answered.
