### ISSUE TITLE
indentation after snippet expansion

### ISSUE THREAD

**Issue by bounceme** [SirVer/ultisnips#704]
when I use the 'iife' snippet for js, in the honza repo, after selecting text and hitting tab so it will be inserted inside the expanded snippet. once the snippet is used and you are in normal mode using the '=' operator will crash vim (version 7.4.1830)

**Comment by seletskiy** [comment]
@bounceme: Please, paste snippet definition there.

**Comment by bounceme** [comment]
https://github.com/honza/vim-snippets/blob/master/UltiSnips/javascript.snippets#L67

**Comment by seletskiy** [comment]
@bounceme: can not reproduce using vim 7.4.1797, can you?

**Comment by bounceme** [comment]
try this:
select all text in a buffer, <tab>, iife, <tab>, gg=G

**Comment by SirVer** [comment]
Cannot reproduce on latest master and Vim 8.
