### ISSUE TITLE
Ultisnips requires py >= 2.7 or py3

### ISSUE THREAD

**Issue by Oliver8668** [SirVer/ultisnips#707]
Hi,everybody.

**Issus:**
Recently, I install the ultisnips for my vim7.4 which was compiled by myself, but ,after installing the plugin the vim reminds me that "Ultisnips requires py >= 2.7 or py3". 

**My checks:**
What confused me is that python is supported by my vim. For python3, it is just "-" in my vim version. So I guess that py suppoeted by my vim is lower version than py2.7.  There is a picture about the message in the end.

**My tries:**
In terminal, I type "python --version", and got the message that "Python 2.7.6". Obviously, my py version is higher. 

**Hlep me:**
Now, what should i do?

Thanks!

**Comment by seletskiy** [comment]
@Oliver8668: What is output of the `:py import sys; print(sys.version_info)` command?

**Comment by Oliver8668** [comment]
@seletskiy ：I type the ":py import sys; print(sys.version_info)" command in terminal, this is what you said, right?
I am a new guy for ubuntu system, so I can not get you, sorry

**Comment by seletskiy** [comment]
@Oliver8668: No, you should type it in your vim instance.

**Comment by Oliver8668** [comment]
@seletskiy : OK, I did it as what you said, and got two error as follow:

![screenshot from 2016-06-06 10 12 01](https://cloud.githubusercontent.com/assets/19757545/15810236/29610632-2bcf-11e6-8d09-bec428a0b532.png)

So why? what should I do to deal with it?

**Comment by seletskiy** [comment]
@Oliver8668: You should install vim with python support using your package manager (apt).

**Comment by Oliver8668** [comment]
@seletskiy ：So happy! I have solved it by reinstalling with new config parameters.
It is as follows: Firstly,  I uninstall the current vim. Secondly, I recompile vim7.4 with new config parameters as 
```
sudo ./configure –enable-multibyte \
            --enable-fontset \
            --enable-xim \
            --enable-gui=auto \
            --enable-luainterp=dynamic \
            --enable-pythoninterp=yes \
            --enable-rubyinterp=dynamic \
            --enable-perlinterp \
            --enable-cscope \
            --enable-sniff \
            --with-x \
            --with-compiledby=erocpil \
            --with-features=huge \
            --with-python-config-dir=/usr/lib/python2.7/config-x86_64-linux-gnu
```
Then, vim was installed successfully. And The issue that I asked disappeared.

Contrasted with old config parameters of vim, there is only a difference, that is the parameter ---- "--enable-pythoninterp" ---- is "yes" or "dynamic". The old one is "--enable-pythoninterp=dynamic", which leads to the “py library can't be loaded”. If this parameter is "yes", all the problems are solved.But the reason is still unclear for me.

Anyway, I appreciate you very much!

**Comment by seletskiy** [comment]
@Oliver8668: :+1:

**Comment by Wenchao21** [comment]
@MichaelDiao Here i hit the issue when i build VIM8.0 from the sources code.....

Issus:
Recently, I install the ultisnips for my **vim8.0** which was compiled by myself, but ,after installing the plugin the vim reminds me that "Ultisnips requires py >= 2.7 or py3".

My checks:
I checked my python installed is python2.7.11

My tries:
In terminal, I type "python --version", and got the message that "Python 2.7.11". Obviously, my py version is higher. 

please help.

**Comment by Wenchao21** [comment]
![vim](https://cloud.githubusercontent.com/assets/8581320/22411283/239ee31c-e6dd-11e6-83a2-086f4c48a3ad.JPG)

here is the screen shoot.

thanks.

**Comment by Vagrantin** [comment]
@Wenchao21 , once you have started up vim, if you type ":py import sys; print(sys.version_info)" what result do you have ?

**Comment by Konstantin8105** [comment]
![py](https://user-images.githubusercontent.com/16690032/27435316-7da8cd9e-5764-11e7-885e-0d5ed4227317.PNG)

**Comment by eromoe** [comment]
Happen on windows with python installed:
```
$ python
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
$ vim
UltiSnips requires py >= 2.7 or py3
Press ENTER or type command to continue
$ vim -version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan 25 2017 09:05:56)
Garbage after option argument: "-version"
More info with: "vim -h"
```

**Comment by LvChengbin** [comment]
I encountered the same problem after update my VIM to 8.1 from 8.0.
This is the result of `:py import sys; print(sys.version_info)`
![image](https://user-images.githubusercontent.com/963223/42619170-d81b6246-85e9-11e8-92ed-ad4edbd258e1.png)

I got `Python 2.7.10` by `python ---version`, and I tried adding `--enable-pythoninterp=yes` while compiling VIM8.1, but it doesn't work.

**Comment by jpoutrin** [comment]
I followed that:
https://github.com/zchee/deoplete-jedi/wiki/Setting-up-Python-for-Neovim

seems to have solved the issue.

**Comment by nickhq** [comment]
I had this issue after but solved it by  running `sudo apt install vim-gtk`

**Comment by CesarTavo** [comment]
> I had fixed it with this command:"apt install vim-gtk"
It works for me

**Comment by YanYankovskyiGL** [comment]
When configuring vim, make sure that you enabled either python2 or python3, not both.
https://vi.stackexchange.com/a/12925

**Comment by therealcode** [comment]
> I had fixed it with this command:"apt install vim-gtk"

This fixed it for me too. 

Running :
VIM 8.0 (2016 Sp 12, compiled Sep 30 2017 18:21:38)  
MX Linux 9 (Debian Stretch) Kernel: Linux 4.19.0-1-amd64

**Comment by yuceltoluyag** [comment]
```
004 ~ > python --version
Python 3.7.4
008 ~ > uname -r
5.2.6-arch1-1-ARCH
004 ~ > 
```
same error

**Comment by pierreN** [comment]
To anyone trying to run vim with `python3`: replace `--enable-pythoninterp` by `--enable-python3interp`

**Comment by Armstrong-Douglas** [comment]
> I had fixed it with this command:"apt install vim-gtk"

I did what you said and it fixed

**Comment by MichaelMW** [comment]
For someone with a macOS encountering the same issue, 
if you are looking for an easy solution without re-compiling vim from source, 
do this:

```
brew remove vim
brew cleanup
brew install vim    
```

Optionally use 
`brew install vim --with-python3` for older system where default is python2. 


This recompiles vim with python support by default.
