### ISSUE TITLE
Replacement string next to placeholder

### ISSUE THREAD

**Issue by Svalorzen** [SirVer/ultisnips#708]
Hello,
I had a snipped from some time ago like this:

    snippet ns "Namespace" b
    namespace $1${1/.+/ /}{
        $0
    }
    endsnippet

The idea is that if the user does not write anything, the result will be:

    namespace {
        ...
    }

Otherwise it will add a second space between the user's text and the curly brackets. Unfortunately it does not seem to work anymore as intended, as UltiSnips will insert the space just after the first letter, moving the writing cursor and thus breaking. Thus the cursor will end after the first letter typed and the space, and just next to the curly bracket, and any text added later will be separated from the first letter.

    namespace T est{
     
    }

Putting the replacement before works, but seems weird as the cursor is at first before the space and not after:

    snippet ns "Namespace" b
    namespace${1/.+/ /}$1 {
        $0
    }
    endsnippet

Is there a better way to do this? Is it possible to change the behavior so that the first solution works?
Thanks.

**Comment by seletskiy** [comment]
@Svalorzen: try
```
snippet ns "Namespace" b
namespace $1`!p snip.rv = ' {' if t[1] else '{'`
    $0
}
endsnippet
```

UltiSnips fails to precisely detect user edits (due vim API limitations) when using transformations, which can evaluate to empty output. So workaround there is to add prior/next character into output.
