### ISSUE TITLE
Same snipppet trigger but different context?

### ISSUE THREAD

**Issue by codeinabox** [SirVer/ultisnips#712]
Is it possible to define two snippets with the same trigger but with different context? I am thinking something like this:-

```viml
snippet gs "PHP getter and setter" "if not contains 'declare(strict_types=1)'" be
....
snippet gs "PHP strict getter and setter" "if contains 'declare(strict_types=1)'" be
....
```
Also how would I write an expression to check if `declare(strict_types=1)` is near the top of the file?

**Comment by seletskiy** [comment]
@codeinabox: see `:h UltiSnips-context-snippets`, it contains examples.

**Comment by codeinabox** [comment]
Thank you @seletskiy one question is how can I perform a regular expression on the whole buffer? Only figured out how to do it on the second line of the buffer

```python
global !p
import vim

def isPHPStrictMode(snip):
	return re.match('^\s*declare\(strict_types=1\);', snip.buffer[1])
endglobal
```

**Comment by seletskiy** [comment]
@codeinabox: Just join `snip.buffer` using `.join()` method: `re.search(r'declare', '\n'.join(snip.buffer))`
