### ISSUE TITLE
Don't map ultisnips in visual mode

### ISSUE THREAD

**Issue by danihodovic** [SirVer/ultisnips#713]
By default ultisnips will map \<Tab> in both insert and visual mode. Is there an option to turn this behavior off? I don't want to use Ultisnips in visual mode and I want to bind \<Tab> to something else.

It seems like disabling this mapping works:
https://github.com/SirVer/ultisnips/blob/master/autoload/UltiSnips/map_keys.vim#L64

**Comment by seletskiy** [comment]
@danihodovic: Try `vunmap <Tab>`.

**Comment by danihodovic** [comment]
@seletskiy It seems like this mapping is set _after_ my vimrc is loaded using autoload. So unmapping it after won't work.

**Comment by seletskiy** [comment]
@danihodovic: Then, try `au VimEnter * vunmap <Tab>`.

**Comment by danihodovic** [comment]
That seems to do the trink

`autocmd VimEnter * vmap <Tab> %`
