### ISSUE TITLE
AttributeError: 'SnippetUtilForAction' object has no attribute 'opt'

### ISSUE THREAD

**Issue by codeinabox** [SirVer/ultisnips#716]
Python is not my strong suite but I am having issues with the following snippet

```viml
global !p
import vim

def isPHPScalarTypesEnabled(snip):
	phpScalarTypes = snip.opt("g:ultisnips_php_scalar_types", False);
	return phpScalarTypes == True or re.match('<\?php\s+declare\(strict_types=[01]\);', '\n'.join(snip.buffer))
endglobal

snippet gm "Strict Type PHP Class Getter" "isPHPScalarTypesEnabled(snip)" be
/**
 * Getter for $1
 *
 * @return ${2:string}
 */
public function get${1/\w+\s*/\u$0/}(): $2
{
    return $this->$1;
}
endsnippet
```

This results in the following error

> AttributeError: 'SnippetUtilForAction' object has no attribute 'opt'
> 
> Snippet, caused error:
> 
>   Defined in: /Users/matt/Dropbox/workspace/vim-snippets/UltiSnips/php.snippets:28
>   Trigger: gm
>   Description: "Strict Type PHP Class Getter"
>   Context: isPHPScalarTypesEnabled(snip)
>   Pre-expand: <none>
>   Post-expand: <none>
> 
> Executed snippet code:
>   1   import re, os, vim, string, random
>   2   import vim
>   3
>   4   def isPHPScalarTypesEnabled(snip):
>   5 > 	phpScalarTypes = snip.opt("g:ultisnips_php_scalar_types", False);
>   6   	return phpScalarTypes == True or re.match('<\?php\s+declare\(strict_types=[01]\);', '\n'.join(snip.buffer))
>   7   snip.context = isPHPScalarTypesEnabled(snip)
>

**Comment by seletskiy** [comment]
@codeinabox: `snip.opt` is not defined in the context code. Use `vim.eval(...)`.
