### ISSUE TITLE
not working at all(using pathogen)

### ISSUE THREAD

**Issue by shammellee** [SirVer/ultisnips#718]
**Notes**
- [vimrc file](http://d.pr/f/1dMGD)
- vim 7.4.1988
- python 2.7.10
- using YouCompleteMe

Here's how I installed (using pathogen)…

```
$ cd ~/.vim/bundle
$ git clone git://github.com/SirVer/ultisnips.git
```

Added UltiSnips variables to `.vimrc`

Created a test file…

```
$ cd ~
$ mkdir test
$ vim foo.js
```

Created a test snippet…

```
:UltiSnipsEdit -> ~/resources/vim/UltiSnips/javascript.snippets

snippet cl
console.log($1)
$0
endsnippet
```

Tried to use snippet by typing…

```
i # insert mode
cl # snippet trigger
control + j # expand snippet
```

Nothing happens

**Comment by seletskiy** [comment]
@shammellee: See that topic: https://github.com/SirVer/ultisnips/issues/711

Workaround should help.

**Comment by shammellee** [comment]
@seletskiy works!!! Thanks

Can you please explain what the bug is and what the workaround is doing?

**Comment by AlexVentura** [comment]
I'm using **MacVim (mvim)** with the [Janus](https://github.com/carlhuda/janus) config and to have it working fine I just did this:

1. Install
    ```sh
    cd ~/.janus
    git clone git://github.com/SirVer/ultisnips.git
    ```
2. Add some config to janus
  Add this lines to `/Users/alex/.vimrc.before`:
    ```sh
    " Define a directory where my snippets were to be located:
    let g:UltiSnipsSnippetDirectories = ["/Users/alex/Dropbox/Code/dotfiles/vim/Ultisnips", "Ultisnips"]
    " Trigger configuration. Do not use <tab> if you use https://github.com/Valloric/YouCompleteMe.
    let g:UltiSnipsExpandTrigger="<tab>"
    " If you want :UltiSnipsEdit to split your window.
    let g:UltiSnipsEditSplit="vertical"
    ```
3. Create a snippet
    - Then for a _rails snippet_ I opened a file called `welcome_controller.rb` and then run `:UltiSnipsEdit`
    - In the new vertical window with a file called `rails.snippets` I add my sample snippet:
      ```rb
      snippet ppp "Just to print out any variable with emojis" b
      puts "💭 " * 50
      pp(${1:variable_to_print_out})
      endsnippet
      ```
  Save it, and them in my `welcome_controller.rb` file typing `ppp` and trigger with `<tab>` key.

I hope it could help somebody else! ✌🏻😉
