### ISSUE TITLE
Several Markdown snippets cause ultisnip to block vim

### ISSUE THREAD

**Issue by bogdan** [SirVer/ultisnips#719]
I have the following snippets file for markdown:

<pre>
snippet	cc "code"
``` ${1}
```
endsnippet
snippet rb "rb"
``` ruby
${1}
```
endsnippet

snippet sl "sl"
!SLIDE ${1}
endsnippet
</pre>

When I try to expand the `rb` snippet macvim starts to hang forever with no response.

**Comment by seletskiy** [comment]
@bogdan: Escape `\`` inside of the snippet:

```
snippet rb "rb"
\`\`\` ruby
${1}
\`\`\`
endsnippet
```

**Comment by bogdan** [comment]
I will, but why do I need to kill vim after I made an invalid snippet?

**Comment by seletskiy** [comment]
@bogdan: Because you running interactive ruby interpreter by writing "`ruby`" in the snippet which is waiting for user input. So, you can `pkill -f ruby` instead of killing vim in that case.
