### ISSUE TITLE
The content of snippets is interpreted as a modeline

### ISSUE THREAD

**Issue by statox** [SirVer/ultisnips#723]
I have a custom snippets file for text filetype. This file contains a snippets defining a modeline that I often use:

    1. # Snippets for text filetypes
    2. 
    3. # A snippets used for the modeline
    4. snippet modeline "Modeline for text files" b
    5. vim:tw=80:ft=text:spell:spelllang=en
    6. endsnippet

The snippet works fine but when I edit the file (either with `:UltiSnipsEdit` or `vim path/to/text.snippets`) the line 5 is interpreted as an actual modeline: this will set the `tw` option, the `spell` option, etc, and mess with the syntax highlighting for the snippet file which is not really convenient.

For a reason that I don't understand adding `vim: modelines=0` as the first or as the last line of  `text.snippets` doesn't disable this behavior.

So far the only workaround I have found (which is really not a good option) is to add enough lines before and after the snippet so that Vim doesn't interpret the modeline.

This is clearly not a major issue but this can be annoying, so is there a good way to deal with it?

**Comment by seletskiy** [comment]
@statox: Try this one:
```
snippet modeline "Modeline for text files" b
`!p snip.rv="vim:"`tw=80:ft=text:spell:spelllang=en
endsnippet
```

**Comment by statox** [comment]
@seletskiy: That's a good workaround, thank you!
