### ISSUE TITLE
w option ignored?

### ISSUE THREAD

**Issue by danielbmarques** [SirVer/ultisnips#726]
I'm probably doing something stupid, but I can't figure out what. I have these two snippets in my `tex.snippets` file:

```
snippet "\\?cite" "\cite" rw
\cite${1:[$2]}{$3}$0
endsnippet

snippet "\\?textc(ite)?" "\textcite" r
\textcite${1:[$2]}{$3}$0
endsnippet
```

When I try to expand `\textcite` I'm asked to chose between the two. But the `\\?cite` snippet has the `w` option set, so it shouldn't be triggered in the middle of `textcite`, right?

**Comment by seletskiy** [comment]
`w` flag does not count when specified with `r`. Use `priority` keyword to skip snippet selection dialog.

**Comment by danielbmarques** [comment]
Ah, that's perfect, thank you!
This should be better documented in the options section, I looked there for a long time and couldn't figure it out. It crossed my mind that this could be related to the `r` option, but since it works with others (e.g. `br`) I assumed it worked with `w` too.
