### ISSUE TITLE
Way to enable ultisnips in a gitcommit buffer

### ISSUE THREAD

**Issue by mrsipan** [SirVer/ultisnips#727]
Somehow I cannot enable ultisnips in gitcommit files, that is, COMMIT_EDITMSG. This may not be an issue with ultisnips.

**Comment by seletskiy** [comment]
@mrsipan: Did you tried to add snippets file named `gitcommit.snippets`?

**Comment by mrsipan** [comment]
@seletskiy thanks for responding!, yes, I tried using `gitcommit.snippets` but it doesn't work as one would expect, wonder if it has to do with the fact that I am using *fugitive*.

**Comment by mrsipan** [comment]
after rearranging my plugins, this is working, closing, thanks!
