### ISSUE TITLE
Snippet and YouCompleteMe not working with spaces

### ISSUE THREAD

**Issue by rwolst** [SirVer/ultisnips#729]
Consider the following snippet

```
snippet "con = lite.connect" "Select from a database"
con = lite.connect(${1:DataBase.db})
cur = con.cursor()
SQL = "SELECT ${2:Column} FROM ${3:TableName}" 
with con:
    cur.execute(SQL) 
    data = cur.fetchall() 
endsnippet
```

When I start typing `con` in Vim, YouCompleteMe shows the snippet. However as soon as I enter the first space the auto-complete disappears. Then once I begin typing `lite`, the auto-complete reappers, however if I select it I am left with

```
con = con = lite.connect........
```

How can I use spaces in my snippet trigger without this happening? Standard escaping doesn't seem to work.

**Comment by seletskiy** [comment]
@rwolst: As far as I know YCM can't complete items with spaces.
