### ISSUE TITLE
UltiSnips snippets don't show up in deoplete completion menu after delimiters

### ISSUE THREAD

**Issue by rusty1s** [SirVer/ultisnips#731]
It seems that for me, snippets from UltiSnips don't show up in the completion menu after a delimiter like `.` or `(` although the snippet has the `i` option for in-word expansion. I can still use the shortcut to expand the snippet, but it seems that the snippet list for autocompletion doesn't function correctly when using options like `i`.
## minimal init.vim

``` vim
call plug#begin('~/.config/nvim/cache')
Plug 'Shougo/deoplete.nvim'
Plug 'SirVer/ultisnips'
call plug#end()

set runtimepath+=~/.config/nvim/cache/deoplete.nvim/
call deoplete#enable()

let g:deoplete#sources={}
let g:deoplete#sources._=['buffer', 'file', 'ultisnips']
```

**Comment by seletskiy** [comment]
@HerringtonDarkholme: And here I call you again :cat:

**Comment by SirVer** [comment]
Since the snippet is expanded (and also reported through `UltiSnips#SnippetsInCurrentScope`) this seems to be a deoplete issue to me. Please speak up if you disagree and I can reopen.
