### ISSUE TITLE
UltiSnips tab triggering Not Working after installing the YouCompleteMe 

### ISSUE THREAD

**Issue by blackode** [SirVer/ultisnips#732]
I am new `vimmer` and `vundler`.
At first i installed the `UltiSnips` ,when i hit the trigger  it works. But problem is it is not showing the dropdown completions but if i hit the tab  it expands.One of my friends suggested to use the 

> YouCompleteMe

 for the feature of showing all the snippets while typing but after installing my tab trigger is remapped to some other functionality Now the list of snippets nor snippets expanding neither is working. `
<Tab>       * <C-R>=UltiSnips#ExpandSnippet()<CR>` This is my first mapping after installing the `YouCompleteMe` it changed like this `<Tab>       * pumvisible() ? "\<C-N>" : "\<Tab>"`

**Comment by blackode** [comment]
@seletskiy thanks for the quick response
hey I tried like this based on some suggestions 
 

> let g:UltiSnipsExpandTrigger="<tab>"

**Comment by seletskiy** [comment]
@blackode: Try to add following mapping into your 

```viml
inoremap <Tab> <c-r>=UltiSnips#ExpandSnippet()<cr>
```

**Comment by blackode** [comment]
@seletskiy Thanks a lot It worked sorry for late reply ........ just had sight of it .........

**Comment by tbruyelle** [comment]
> @blackode: Try to add following mapping into your
> 
> inoremap <Tab> <c-r>=UltiSnips#ExpandSnippet()<cr>

The problem with that setting is it disables the ability to validate a suggestion with `<Tab>` :disappointed:
