### ISSUE TITLE
Example in readme

### ISSUE THREAD

**Issue by olleharstedt** [SirVer/ultisnips#734]
Hi,

Thanks for an awesome plugin! Would you mind adding a complete example at the bottom of the readme file on github? That way, users won't need to click around to get a quick update on syntax etc.

Thanks

**Comment by seletskiy** [comment]
@olleharstedt: Can you provide more insight? What info do you want to see as an introduction?

**Comment by seletskiy** [comment]
@olleharstedt: ping?

**Comment by olleharstedt** [comment]
Hi!

I thought about it and couldn't come up with anything... Sorry. I'll close it and reactivate if I can come up with a good example. Cheers.
