### ISSUE TITLE
snippets definetion can not be trigged but all.snippets

### ISSUE THREAD

**Issue by jianglong1992** [SirVer/ultisnips#736]
I have a problem, I defined myself directory and add this "let g:UltiSnipsSnippetDirectories=[$HOME.'/UltiSnips']" in vimrc ,when I make a test, snippets can not works such as php.snippets, html.snippets .But all.snippets can work
I dont know why it happend!

**Comment by SirVer** [comment]
Probably related to #711. Otherwise I cannot reproduce with more detailed instructions.
