### ISSUE TITLE
Snippets can not be triggered without "UltiSnipsEdit"

### ISSUE THREAD

**Issue by lircn** [SirVer/ultisnips#737]
Problem: 
Snippets can not be loaded automatically. And the "UltiSnipsEdit" command will solve it.

Example:
1. I open a .c file, write "if" and type <tab>, nothing happened.
2. Then I open the snippet file with "UltiSnipsEdit", this file opened correctly. (so my search path was correct)
3. After step 2, snippets works fine.

Q:
1. How to make snippets loaded automatically? (vim 7.4, python 2.7.12)
2. May I load this manually? 
Thank you!

**Comment by SirVer** [comment]
Please post a minimal vimrc to go from, otherwise this cannot be reproduced (since it works for me and others).
