### ISSUE TITLE
ultinsips not working with jedi-vim

### ISSUE THREAD

**Issue by fugokidi** [SirVer/ultisnips#739]
I have jedi-vim before. I tried ultisnips today since it is so cool, thanks to you. After installing it, vim cannot load any file anymore, I tried to disable jedi-vim, it works again. I used vim-plug for plugin management.  The error is like this. It happens any file, not only cpp files, python files as well.
![screen shot 2016-08-21 at 9 32 44 pm](https://cloud.githubusercontent.com/assets/9945857/17837660/15c373e6-67eb-11e6-9fbe-067019df31dd.png)
Please guide me a bit, I can only use either jedi-vim or ultisnips for the time being, I want both.
The following is how i install the plugins, I manage plugin  and settings together so that I can debug or find related settings easily. Thank you.

```
silent! if plug#begin('~/.vim/plugged')

" Jedi-vim
Plug 'davidhalter/jedi-vim'
let g:jedi#goto_definitions_command = "<Leader>d"
let g:jedi#popup_on_dot = 0
let g:jedi#popup_select_first = 0
map <Leader>b Oimport ipdb; ipdb.set_trace() # BREAKPOINT<C-c>

" ultisnips
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
" let g:UltiSnipsExpandTrigger="<tab>"
" let g:UltiSnipsJumpForwardTrigger="<c-b>"
" let g:UltiSnipsJumpBackwardTrigger="<c-z>"

" If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit="vertical"
call plug#end()
```

**Comment by SirVer** [comment]
My guess is that `jedi-vim` uses python2 while UltiSnips will default to `python3`. Some platforms will crash if you load both. Try putting `let g:UltiSnipsUsePythonVersion = 2` in your vimrc. If that does not work, try `let g:UltiSnipsUsePythonVersion = 3`.
