### ISSUE TITLE
All snippets fail to function.

### ISSUE THREAD

**Issue by JSDurand** [SirVer/ultisnips#740]
### Explain the issue

I downloaded Ultisnips following the steps found in _Quick Start_ in https://github.com/SirVer/ultisnips
But no snippets function; and even the snippets that I wrote (such as tex.snippets and notes.snippets) have no effect at all.
At first I thought maybe I am not activating the plugin, but the command `:UltiSnipsEdit`just works fine, so I don't know where the problem is.
Also, I have looked into the `:help UltiSnips` but found no solution to the problem: 
I have changed some settings accordingly, as shown in _the .vimrc_ file below.
### Minimal working example

A minimal working UltiSnips example.

Just any snippet fails to function; even the simplest one fails.

``` snippets
snippet he "hello world" b
hello world!
endsnippet
```
### Minimal vimrc file

``` vim
set nocompatible

" Load UltiSnips
Plugin 'SirVer/ultisnips'
Plugin 'honza/vim-snippets'

" Load some other plugins.
Plugin 'Valloric/YouCompleteMe'

colorscheme vividchalk
filetype plugin indent on
syntax on

" Ultisnips settings {{{
let g:UltiSnipsJumpForwardTrigger  = "<c-b>"
let g:UltiSnipsJumpBackwardTrigger = "<c-z>"
let g:UltiSnipsUsePythonVersion = 2
let g:UltiSnipsSnippetsDir = "~/.vim/UltiSnips/"
" }}}

```

Here the ~/.vim/UltiSnips is symlinked to ~/.vim/bundle/vim-snippets/UltiSnips
### Complete .vimrc file

I don’t know if the above .vimrc is enough, and the complete .vimrc file is on github as well:
https://github.com/JSDurand/vimconfig/blob/githubShare/vimrc

**Comment by SirVer** [comment]
Cannot reproduce - the minimal `vimrc` is not complete (`Plugin` is not defined). My hunch is that this is related to #711, but I cannot know from the given context.
