### ISSUE TITLE
Ultisnips and Deoplete mapping works only after reloading init.vim 

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [SirVer/ultisnips#742]
After installing deoplete and mapping the tab key to code completion via adding the below code to my init.vim, the deoplete completion would only work after reloading init.vim. Someone posted this same dilemma : https://github.com/Shougo/deoplete.nvim/issues/164
According to Shougo though it is a problem with Ultisnips. 

in the init.vim...
`inoremap <silent><expr> <TAB>
			\ pumvisible() ? "\<C-n>" :
			\ <SID>check_back_space() ? "\<TAB>" :
			\ deoplete#mappings#manual_complete()
function! s:check_back_space() abort "{{{
	let col = col('.') - 1
	return !col || getline('.')[col - 1] =~ '\s'
endfunction"}}}
`

**Comment by Shougo** [comment]
I think `<TAB>` mapping is overwritten by UltiSnips to expand snippets.
You should check it by `verbose imap <TAB>`.

**Comment by Luis-Henriquez-Perez** [comment]
`verbose imap <TAB>` displays the tab mapping in my init.vim file I posted above. It doesn't seem like it's being overwritten. 
Right now my tab key scrolls through options in the snippet/completion popup window. I think that I would have to map Ultisnips completion to a key other than `<TAB>`. Otherwise I'm not sure how it differentiate between scrolling through options and choosing one of the snippets to complete. I resolved the problem by setting snippet completion to the `<space>` key. 

`let mapleader = "\<space>"`
`let g:UltiSnipsExpandTrigger = "<leader>j"`

On a side not I'm not sure yet why `<leader>j `translates to just having to press `<space>` (instead of `<space>j)` when I complete a snippet, but it works.

**Comment by Shougo** [comment]
Hm.   You can use the mappings.

https://github.com/SirVer/ultisnips/blob/master/autoload/UltiSnips/map_keys.vim#L56

**Comment by Luis-Henriquez-Perez** [comment]
Thanks! These mappings ended up working out. `<TAB>` seems to be working now for both scrolling through a set of potential autocompletions with deoplete and for expanding a snippet.

**Comment by partounian** [comment]
Sorry for my confusion, but can you specify how you got it working? map_keys link is throwing me off. @Luis-Henriquez-Perez

**Comment by Luis-Henriquez-Perez** [comment]
Sure I use this function for Ultisnips:
'
function! <SID>ExpandSnippetOrReturn()
    let snippet = UltiSnips#ExpandSnippetOrJump()
    if g:ulti_expand_or_jump_res > 0
        return snippet
    else
        return "\<CR>"
    endif
endfunction

inoremap <expr><CR> pumvisible() ? "<C-R>=<SID>ExpandSnippetOrReturn()<CR>" : "\<CR>"
'
And this function for Deoplete:
`
inoremap <silent><expr> <TAB>
\ pumvisible() ? "\<C-n>" :
\ <SID>check_back_space() ? "\<TAB>" :
\ deoplete#mappings#manual_complete()

function! s:check_back_space() abort
let col = col('.') - 1
return !col || getline('.')[col - 1]  =~ '\s'
endfunction
`
And with this configuration deoplete's suggestions and ultisnips snippets show up.

**Comment by partounian** [comment]
@Luis-Henriquez-Perez that seems to expand a snippet, but does not scroll through deoplete, and inside of a snippet will not go to the next mark. Maybe some configuration is missing? (I uncommented all other config I had and used only yours)

**Comment by Luis-Henriquez-Perez** [comment]
I think perhaps I did miss some more configurations. This is all my ultisnips config:
'
let g:UltiSnipsExpandTrigger = "<nop>"
let g:ulti_expand_or_jump_res = 0
let g:UltiSnipsEnableSnipMate = 1

let g:UltiSnipsSnippetsDir = "~/.config/nvim/UltiSnips"

function! <SID>ExpandSnippetOrReturn()
    let snippet = UltiSnips#ExpandSnippetOrJump()
    if g:ulti_expand_or_jump_res > 0
        return snippet
    else
        return "\<CR>"
    endif
endfunction

inoremap <expr><CR> pumvisible() ? "<C-R>=<SID>ExpandSnippetOrReturn()<CR>" : "\<CR>"
'
I think that the expandtrigger set to nothing is something important I left out before.

**Comment by partounian** [comment]
I got 
`No mapping found
No mapping found`
I think I should just stick with Tab and Shift Tab, then <C-e> for expanding. Thank you though.
