### ISSUE TITLE
using buffer name in snippets

### ISSUE THREAD

**Issue by seymen** [SirVer/ultisnips#744]
Hi all - trying to use the name of the buffer (started with :e) in my snippets. This is for XML documents of certain type where we have a convention to use the name of the file in one of the attributes.

I'd appreciate if anybody can provide any tips on how to do that if it is possible.

**Comment by seletskiy** [comment]
@seymen:

```
snippet x "buffer name" b
`!p snip.rv = snip.fn`
endsnippet
```

**Comment by seymen** [comment]
thanks a lot!
