### ISSUE TITLE
SnippetManager object has no attribute '_track_change'

### ISSUE THREAD

**Issue by opadron** [SirVer/ultisnips#746]
I haven't been able to get UltiSnips working for a while.  I've since abandoned the project, but would really like to start using it, again.

The problem is this exception gets thrown on every keystroke:

```
Error detected while processing function UltiSnips#TrackChange:
line    1:
Traceback (most recent call last):
Press ENTER or type command to continue
Error detected while processing function UltiSnips#TrackChange:
line    1:
  File "<string>", line 1, in <module>
Press ENTER or type command to continue
Error detected while processing function UltiSnips#TrackChange:
line    1:
AttributeError: 'SnippetManager' object has no attribute '_track_change'
```

I am on a Mac running latest OS X.

Things I've tried:

 - using vim from homebrew, using the system vim, and using macvim (`brew install --HEAD macvim`)
 - using the python from homebrew, and the system python
 - installing Ultisnips manually, using pathogen, and using vundle
 - every possible work around I could find from going through prior github issues.

All my attempts fail with the same issue, except when using the system vim, since UltiSnips rejects it for being too old.

Assistance greatly appreciated.

**Comment by seletskiy** [comment]
@opadron: Please, show output of the `:py print(dir(UltiSnips_Manager))` command.

**Comment by opadron** [comment]
@seletskiy thanks a lot for helping me with this.

I ran these commands

```
:py from pprint import pprint as pp
:py pp(dir(UltiSnips_Manager))
```

and got this output:

```
['__class__',
 '__delattr__',
 '__dict__',
 '__doc__',
 '__format__',
 '__getattribute__',
 '__hash__',
 '__init__',
 '__module__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_added_snippets_source',
 '_buffer_filetypes',
 '_check_if_still_inside_snippet',
 '_cs',
 '_csnippets',
 '_ctab',
 '_current_snippet_is_done',
 '_cursor_moved',
 '_do_snippet',
 '_file_to_edit',
 '_handle_failure',
 '_ignore_movements',
 '_inner_mappings_in_place',
 '_jump',
 '_leaving_buffer',
 '_leaving_insert_mode',
 '_map_inner_keys',
 '_reinit',
 '_save_last_visual_selection',
 '_snippet_sources',
 '_snips',
 '_supertab_keys',
 '_try_expand',
 '_unmap_inner_keys',
 '_visual_content',
 '_vstate',
 'add_buffer_filetypes',
 'add_snippet',
 'backward_trigger',
 'expand',
 'expand_anon',
 'expand_or_jump',
 'expand_trigger',
 'forward_trigger',
 'jump_backwards',
 'jump_forwards',
 'list_snippets',
 'register_snippet_source',
 'reset_buffer_filetypes',
 'snippets_in_current_scope',
 'unregister_snippet_source']
```

**Comment by seletskiy** [comment]
@opadron: What is output of `:py import inspect; print(inspect.getfile(UltiSnips_Manager.__class__))`?

**Comment by opadron** [comment]
`/Users/opadron/.vim/pythonx/UltiSnips/snippet_manager.pyc`

**Comment by seletskiy** [comment]
@opadron: Run `cd /Users/opandron/.vim/pythonx/UltiSnips/ && git rev-parse HEAD`.

**Comment by opadron** [comment]
Running the commands exactly as you've asked gives me this SHA1: `614b86e9564957a7c37096ac3de95d07bcdf041e`.  Although I suspect that's not what you're looking for, since there's no clone of UltiSnips under that directory; the hash is for my own dot-files repo.

At the moment, I'm using vundle with separate clones of my chosen plugins as the remotes.  I maintain these clones as submodules, to exercise finer control over the precise versions of each plugin.

This is the version of my clone.  This should be the latest master, if I'm not mistaken.
```
cd ~/.vim-modules/ultisnips/pythonx/UltiSnips
 $ git rev-parse HEAD
ff10513cddc36f316e5d848c9b54aa8dd9ba9cd5
 $ git describe --tags
3.0-362-gff10513
```

vundle uses this repo as the remote that it, in turn, clones again into its own staging area, where it does whatever process it does to plugins before updating what you see under `~/.vim`.

Checking vundle's copy shows the same version as the one I have cloned.

```
 $ cd ~/.vim/bundle/ultisnips/pythonx/UltiSnips
 $ git rev-parse HEAD
ff10513cddc36f316e5d848c9b54aa8dd9ba9cd5
 $ git describe --tags
3.0-362-gff10513
```

I've had the same issue, even when installing by hand, so I don't think vundle is to blame, although I could certainly try manual installation again to narrow down on the possibilities.

**Comment by seletskiy** [comment]
@opadron: As you can see from the `.pyc` file path you're probably have missetup of ultisnips, because it's located not in `~/.vim/bundle/` neither in `~/.vim-modules`.

**Comment by opadron** [comment]
After digging some more, I discovered the issue was that my `~/.vim/pythonx` directory with the byte-compiled `.pyc` files was somehow leftover from something I must have done before, and ultisnips was picking up those files instead of the ones in the vundle bundle.

After clearing all that up, my snippets work, again! :+1:

Thank you very much for your help, @seletskiy.  And please forgive me for the noise.

**Comment by seletskiy** [comment]
@opadron: No problem! I glad you've solved your issue and can use UltiSnips.
