### ISSUE TITLE
Can't work together with YouCompleteMe

### ISSUE THREAD

**Issue by xusiyuan841028** [SirVer/ultisnips#748]
@blueyed From commit: dfde9b0, the integration with YouCompleteMe is broken, and the complete menu doesn't contains any snips. Could you re-review the code of this PR to resolve the issue of working together with YCM?

commit: dfde9b0
![image](https://cloud.githubusercontent.com/assets/1681459/18408282/0c3abb7c-775e-11e6-9c7a-787d7a308fdf.png)

commit: 8d77e89d
![image](https://cloud.githubusercontent.com/assets/1681459/18408293/45ca4d62-775e-11e6-85bb-1e81db4d49c6.png)

**Comment by Kedra** [comment]
I have this same issue with the latest commit.

**Comment by blueyed** [comment]
This should be fixed with https://github.com/Valloric/YouCompleteMe/pull/2321 in YCM.

**Comment by xusiyuan841028** [comment]
@blueyed Cool! Thanks for you response.
