### ISSUE TITLE
python detect error

### ISSUE THREAD

**Issue by vanabel** [SirVer/ultisnips#749]
I use gvim on win7 and with `python/dyn` support, I can use `python --version` in windows 7's cmd to get `Python 2.7.11`. The problem is why I enconter error message `require py>2.7 or py3`? did it caused by `has('python')` function? since it returns `0`.

**Comment by nevesnunes** [comment]
I bumped into a similar issue: a plugin that required python2 would not run, because of `has('python')` returning 0. Forcing UltiSnips to use python2 worked for me, try adding this option to your `.vimrc`:
`let g:UltiSnipsUsePythonVersion = 2`

**Comment by SirVer** [comment]
Closing as answered.
