### ISSUE TITLE
Broken at commit 8d77e89d65d5678d3c9b15496e462ab5b8ebd8e9 under Windows 7

### ISSUE THREAD

**Issue by fsworld009** [SirVer/ultisnips#752]
Hi:

First, thanks for this awesome plugin.
Today after upgrading the plugin, I found that UltiSnips python script is throwing error whenever I enter insert mode and I cannot use any snip completion:

![error](https://cloud.githubusercontent.com/assets/7109839/18564832/5d1d55a8-7b5b-11e6-8d88-4de7cce906c5.png)

(Sorry I have to use a snapshot, I  couldn't find a way to copy message under neovim-qt)

I've tested different commits and found out that this issue is introduced in master branch commit [8d77e89d65d5678d3c9b15496e462ab5b8ebd8e9](https://github.com/SirVer/ultisnips/commit/8d77e89d65d5678d3c9b15496e462ab5b8ebd8e9), if I revert to the previous commit ([dfde9b00325caf478eaa49868f77fed7a88f5358](https://github.com/SirVer/ultisnips/commit/dfde9b00325caf478eaa49868f77fed7a88f5358)), then the plugin is working fine.

My environment:
Windows 7 x64
nvim 0.1.5-DEV + neovim-qt
python version: 3.5.2

I'll test Neovim.app under Mac OSX when I get a chance.

**Comment by fsworld009** [comment]
Tried the plugin under Mac OSX and Neovim.app
It is working properly with the latest version, so this issue is Windows only

**Comment by seletskiy** [comment]
@fsworld009: Thanks for the bug report!

@blueyed: Can you take a look on the issue, because it looks like problem regarding your changes? :cake:

**Comment by blueyed** [comment]
@fsworld009 
Do you use other plugins that use UltiSnips?

The traceback looks a bit weird.. can you try a minimal vimrc/init.vim, please?

**Comment by fsworld009** [comment]
@blueyed 
I use deoplete to autocomplete UltiSnips, but removing ultisnips from g:deoplete#sources does not fix the issue.

As of now Neovim does not work in Windows terminal environment, a GUI is required for Windows build so I cannot test it.

I'll try to create a minimal init.vim then do the test again when I have time.

**Comment by fsworld009** [comment]
I tried with only the following line in init.vim
```vim
set runtimepath+=(path to ultisnips)
```

and still get the same error when go to insert mode

**Comment by blueyed** [comment]
@fsworld009 
Same traceback?

Please use `:redir @+> | silent mess | redir END` to copy all of `:mess` into the clipboard, and paste it here.

**Comment by fsworld009** [comment]
@blueyed that command didn't work for me, I think neovim-qt has some issues on interacting with system clipboard, I am never able to copy anything from or to neovim-qt window.

**Comment by fsworld009** [comment]
@blueyed Ok being able to catch it
It's different compare to the original post but the last message is the same so I though they were the same message, sorry about that.

```
"C:\my\cpptest\main.cpp" 13L, 181C
Error detected while processing function provider#python3#Call:
line   18:
Traceback (most recent call last):

  File "<string>", line 1, in <module>

Error detected while processing function provider#python3#Call:
line   18:
ImportError: No module named 'UltiSnips'
Error detected while processing function UltiSnips#TrackChange[1]..provider#python3#Call:
line   18:
Traceback (most recent call last):

  File "<string>", line 1, in <module>

Error detected while processing function UltiSnips#TrackChange[1]..provider#python3#Call:
line   18:
NameError: name 'UltiSnips_Manager' is not defined

```

**Comment by sim590** [comment]
On my end, on commit 5352d98, I do experience a similar issue. The error seems to trigger only in a certain file type: pandoc. I do use the [pandoc plugin](https://github.com/vim-pandoc/vim-pandoc). The commit revision is [f01f297](https://github.com/vim-pandoc/vim-pandoc/commit/f01f29795d082afb664c5e47f6ccca67b7193121).
```
Error detected while processing function UltiSnips#TrackChange[1]..provider#python3#Call:
line   18:
Invalid channel "2"
Error detected while processing function UltiSnips#TrackChange[1]..provider#python3#Call:
line   18:
Invalid channel "2"
Error detected while processing function UltiSnips#TrackChange[1]..provider#python3#Call:
line   18:
Invalid channel "2"
Error detected while processing function UltiSnips#TrackChange[1]..provider#python3#Call:
line   18:
Invalid channel "2"
"notes.pandoc" 244L, 15299C written
Error detected while processing function UltiSnips#TrackChange[1]..provider#python3#Call:
line   18:
Invalid channel "2"
```
I have to use `au! UltiSnips_AutoTrigger` to stop this. However, when trying to use any snippets, the error appears also.

## My setup

**OS**
```
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.0 (stretch)
Release:	9.0
Codename:	stretch
```

**Neovim version**
```
NVIM 0.1.7
Build type: None
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-pN7CDA/neovim-0.1.7=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1  -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-pN7CDA/neovim-0.1.7/build/config -I/build/neovim-pN7CDA/neovim-0.1.7/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim-pN7CDA/neovim-0.1.7/build/src/nvim/auto -I/build/neovim-pN7CDA/neovim-0.1.7/build/include
Compiled by pkg-vim-maintainers@lists.alioth.debian.org

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

```

**Comment by SirVer** [comment]
This issue was closed due to it only affecting [Neovim](https://github.com/neovim/neovim) and not core [Vim](https://github.com/vim/vim).

## Why is Neovim only best-effort?

UltiSnips maintenance is a lot of work. Reproducing bug reports is tedious, slow and error prone. The current maintainers have to limit their scope to provide a reasonable level of service to the community. 

Neovim should work with any plugin that core vim works with. But in the past, Neovim support has been difficult for UltiSnips: It regularly had bugs that did not affect the core Vim distributions, i.e. Vim, gVim, MacVim, and Vim for Windows and its testing approach required a completely separate code path from core as well. Therefore, currently Neovim bugs are considered on a best effort basis. 

UltiSnips is looking for an additional maintainer that is interested in bringing the Neovim level of service on par with core Vim. If you are interested in helping out, please reach out to [SirVer](https://github.com/SirVer/).
