### ISSUE TITLE
Snippets with a multiplier

### ISSUE THREAD

**Issue by atsepkov** [SirVer/ultisnips#755]
Is it possible to create a snippet which allows the user to specify to perform some sub-snippet action N times? Here are a few examples/use cases:
- switch statement with N cases, it would be nice for the user to type something like `switch 10` to generate a switch with 10 cases and a default
- hashmap with N key-value pairs
- if/else with N "else if" cases
- class with N methods
- N assignments of type `self.arg = arg` in constructor

I was looking through some other snippets, and while I'm no expert in snipmate, had a couple ideas about the approach, and wanted to know whether either of them is feasible or would lead me to a dead end:
1. in JS, `cl` expands to `console.log(${1:"${2:value}"});`, this is a clever use of nesting to allow automatic quoting/quote-removal, perhaps a similar mechanism could be applied to allow excess element stripping/addition?
2. Seems like some snippets use python to do magic behind the scenes, perhaps it's possible for it to take the relevant number from nearby context when snippet gets activated. For example, if I was to type `5 hash`, and tab, `switch` keyword would trigger the switch-case snippet, and the relevant Python code may look for the N prefix to remove and use as a loop, generating a map like this:

```
{
    "${1}": ${2:"${3}"},
    "${4}": ${5:"${6}"},
    "${7}": ${8:"${9}"},
    "${10}": ${11:"${12}"},
    "${13}": ${14:"${0}"}
}
```

**Comment by seletskiy** [comment]
@atsepkov: Try to follow tutorial about [tabstop generation[(https://github.com/SirVer/ultisnips/blob/master/doc/examples/tabstop-generation/README.md).
