### ISSUE TITLE
Jumping to unused mark on snippet hook

### ISSUE THREAD

**Issue by jasonmay** [SirVer/ultisnips#756]
This was a fun one for me to track down.

I have been playing around with bindings that set a mark, jump to the top of a file, automatically trigger expansion on something, and have the binding jump back to the mark on the exit hook.

What happens is when I try this naively, the normal-mode `A` binding doesn't put the cursor on the end of the line, it puts it on the second-to-last column after I perform a successful ExpandTrigger action.

I honestly couldn't tell if this is a core vim issue or an UltiSnips issue.

Nevertheless, here's how to repro:

**Create a sample snippet (not necessary if you already have snippets)**

```
snippet l
dosomething($1)
endsnippet
```

**Create an exit-snippet hook to jump to a mark**

``` viml
autocmd User UltiSnipsExitLastSnippet normal `u
```

Now somewhere, try to expand the `l` snippet you made. Now go to the end of a line somewhere, and you'll see that the cursor doesn't go to the very end of the line on the press of `A` in normal mode.

I had to work around this (pretty hackily) by checking if the mark existed first.

``` viml
function! DoExitSnippetHook()
    let markpos = getpos("'u")
    echom join(markpos)
    echom markpos[1]
    if markpos[1] != "0"
        normal `u
        delmarks u
    endif
endfunction

autocmd User UltiSnipsExitLastSnippet call DoExitSnippetHook()
```

... but obviously just doing `normal `u` would be more ideal.

Thanks!

(Vim info: [vim-version.txt](https://github.com/SirVer/ultisnips/files/478487/vim-version.txt))

**Comment by andreyorst** [comment]
I can't reproduce it. However I may not understand your steps right. I created a line in empty file, then created a snippet, and run:
```vim
:autocmd User UltiSnipsExitLastSnippet normal `u
```
Then executed a snippet on the line above, and pressed <kbd>Esc</kbd><kbd>j</kbd><kbd>A</kbd>, and my cursor positioned at the end of the line.

![image](https://user-images.githubusercontent.com/19470159/38768287-092c8d6e-3ffa-11e8-8346-3cc1d46174a9.png)

**Comment by SirVer** [comment]
I cannot reproduce this either with Vim 8.1 and 3a8b0548b3efd01bff0393f8f32228786149806c.
