### ISSUE TITLE
Skip all triggers

### ISSUE THREAD

**Issue by lohfu** [SirVer/ultisnips#757]
If i am happy with all the pre-entered text in a snippet, is there anyway to skip all the tabstops without having to press <C-j> repeatedly?

**Comment by seletskiy** [comment]
@lohfu: Not so easily posssible. Try to investigate `_jump` method in the source code, maybe you will come up with some solution.

**Comment by SirVer** [comment]
Thinking about the design for this, the only thing that comes to mind for me is to add another trigger to immediately finish the snippet. Since this seems to be a rare feature request, it does not warrant the extra complexity this would add. hence I am closing this as wontfix.
