### ISSUE TITLE
Snippets with a number as the first character do not appear in deoplete

### ISSUE THREAD

**Issue by languitar** [SirVer/ultisnips#760]
Eg. in LaTeX mode, the snippet `2columns` is not visible in the deoplete completion menu despite completing correctly:
![completes](https://cloud.githubusercontent.com/assets/1336287/18704624/fe7ac44c-7fea-11e6-819f-b846a443e18c.png)
![doesnot](https://cloud.githubusercontent.com/assets/1336287/18704629/029f083a-7feb-11e6-8327-e0a19c0124c6.png)

**Comment by seletskiy** [comment]
@languita: I suggest you should contact @Shougo as he is developer of deoplete or @HerringtonDarkholme as he introduced deoplete support.

**Comment by HerringtonDarkholme** [comment]
It's a known issue due to ultisnip's low priority. 

https://github.com/SirVer/ultisnips/pull/611#issuecomment-170450786

**Comment by languitar** [comment]
But there is no other identifier in the document that is called `2columns` which could override mine. Also, in the completion popup you can see that the number is completely ignored and probably not parsed as being part of the word to complete for deoplete.

**Comment by SirVer** [comment]
Closing as answered by https://github.com/SirVer/ultisnips/issues/760#issuecomment-249104707.
