### ISSUE TITLE
How to add optional expanding?

### ISSUE THREAD

**Issue by vanabel** [SirVer/ultisnips#765]
I want to define a snippet as

``` snippet
snippet int "\int_{}^{}" iA
\int_{$1}^{$2}$0
endsnippet
```

which will expand `int<tab>` to `\int_{}^{}`, but sometimes, I want it to expand to `\int_{}`, i.e., the second placeholder is optional, can I get this in one snippet?

**Comment by seletskiy** [comment]
@vanabel: Check out that article: https://github.com/SirVer/ultisnips/blob/master/doc/examples/tabstop-generation/README.md

**Comment by andreyorst** [comment]
Closing this since it is answered, and provide solution works in this case.
