### ISSUE TITLE
Ctrl-j Ctrl-k not working in OSX

### ISSUE THREAD

**Issue by caoimhinp** [SirVer/ultisnips#772]
Snippets are recognized and tab completed but jumping to the next / previous tab stop isn't working.
Using vim 8.0 with nocompatible set.

At first it would just print a j or a k when pressing ctrl-j or k.
I commented out the original lines and substituted an unused letter in the following lines:

"inoremap <silent><C-j> <C-R>=OmniPopup('j')<CR>
inoremap <silent><C-e> <C-R>=OmniPopup('j')<CR>
"inoremap <silent><C-k> <C-R>=OmniPopup('k')<CR>
inoremap <silent><C-t> <C-R>=OmniPopup('k')<CR>

Now it does nothing when pressing ctrl-k and inputs a linefeed when pressing ctrl-j; but only the first time it is pressed.

Searching for other 'j>' entries in my .vimrc did not find any other uses of ctrl-j or k.

**Comment by advpetc** [comment]
A workaround for me is remapped those trigger key:
```vim
let g:UltiSnipsExpandTrigger="<c-e>"
let g:UltiSnipsJumpForwardTrigger="<c-f>"
let g:UltiSnipsJumpBackwardTrigger="<c-b>"
```

**Comment by SirVer** [comment]
https://superuser.com/questions/987547/how-to-remap-ctrl-j-to-enter-on-mac-os-x-yosemite says that `<ctrl-j>` is likely getting eaten by your terminal before even reaching vim. not sure what the issue is with `<ctrl-k>`, that works for me without issues.
