### ISSUE TITLE
Request: auto-skip placeholders

### ISSUE THREAD

**Issue by sfinktah** [SirVer/ultisnips#776]
This is an idea coming from any of the JetBrains series of IDE's (lets say PyCharms).

Although their snippets are inferior to Ultisnips, they do have one cool feature what Ultisnips does not.

![auto-skip placeholder](https://d3nmt5vlzunoa1.cloudfront.net/webide/files/2012/10/lt_step5.png)

You can set a placeholder to be automatically skipped (if it has a value, but that part isn't important).

Let me provide an example:

```
/**
 * $FNNAME$
 * @static
 */
$CLASS$.$FN$ = function($ARGS$) {
    $END$
};
```

And here's how placeholder is defined:
1. **FNNAME** [default value:_"function name"_]
2. **CLASS** [default value: _fileNameWithoutExtension()_, _skip if defined_]
3. **FN** [default value: _camelCase(FNNAME)_, _skip if defined_]
4. **ARGS** [empty]

To use, `static`**[Tab]**`my dogs breath smells like cat food`**[Tab]**`name`**[Tab]**

And the result is

```
/**
 * my dogs breath smells like cat food
 * @static
 */
snippets.myDogsBreathSmellsLikeCatFood = function(name) {
    |
}
```

Now, I can already here y'all saying, **pfft** UltiSnips can do that you dumb-ass.  And I know that, in fact, here is an UltiSnips version (a little more complex, it emulates the coffee-script transpiler)

```
snippet /@(\w+): (.*) ->/ "static" rb
/**
 * $2
 *
 * @returns {undefined}
 */
${1:`!p snip.rv = snip.basename`}.${2:`!p snip.rv = match.group(1)`} = function`!p snip.rv = match.group(2)` {
    $0
};
endsnippet
```

Now I guess **technically** I could get the same effect in UltiSnips as I do in a JetBrains product, since you can't shift-tab back to edit the placeholders marked for skip.   So I **could** write a whole bunch of python and get the same result, but I'd be doing it without the benefit of easily defined and repeated placeholders.

What would be **super-cool** would be placeholders that are automatically skipped (as in, _pretend tab was pressed_) when the snippet is expanded, but (because UltiSnips is cool) you could shift-tab (or whatever) back to edit them if you really really wanted to.

Since this sounds suspiciously like a "big ask", I offer the following minor token of appreciation.
### The universe's most essential snippet

`[~/.vim/bundle/vim-snippets/UltiSnips/snippets.snippets]`

```
snippet /\$\$(\d+)/ "match.group" r
\`!p snip.rv = match.group(`!p snip.rv = match.group(1)`)\`
endsnippet
```

And I'll even give you a hint.  That snippet was built using that snippet.

**Comment by sfinktah** [comment]
I tried inserting some VimL to fake the press of <Tab>, but it didn't quite work... 

    `!v feedkeys("\<Tab>", "t")`

Which I thought it should, since you can get the effect when using `feedkeys` from command mode, eg:

    :call feedkeys("ofor\<Tab>\<Tab>\<Tab>")

Although if you try and insert any text inbetween the Tab's it ends up failing, feels like it's jamming keystrokes in before UltiSnips is ready to handle them.

**Comment by seletskiy** [comment]
@sfinktah: this one should do the trick:

```
global !p
def get_some_value():
    return 'xxx'

def jump_if_value_equals(expected):
    if len(snip.tabstops) <= 1:
        return

    if snip.tabstops[1].current_text == expected:
        if snip.tabstop == 1:
            if snip.jump_direction == 1:
                vim.command('call feedkeys("\<C-J>")')

endglobal

post_jump "jump_if_value_equals('xxx')"
snippet i "if" b
if ${1:`!p snip.rv = get_some_value()`} {
    $2
}
endsnippet
```

**Comment by sfinktah** [comment]
@seletskiy thx! that did indeed work, with a change to `feedkeys` to match my preferences of `\<Tab>` (should probably find a way to generalize that).

I'm not yet sure how I'd use it implement multiple skips, but you have provided the missing piece in the puzzle, so I can continue my efforts.

**Comment by SirVer** [comment]
Closing as answered.
