### ISSUE TITLE
auto-trigger depends on old buffer content not only typed characters

### ISSUE THREAD

**Issue by nilsbecker** [SirVer/ultisnips#777]
i am using auto-trigger to autoexpand parentheses:

```
snippet (( "auto paren" iA
($1)$0
endsnippet
```

the reason to use this instead of anonymous snippets is to be able to exit nested snippets consistently. 

however, when i try to actually make nested parentheses, i type `((` which leaves me here: `(.)` where `.` is supposed to indicate the cursor. fine. now for the nested parenthesis i again want to type `((`. however already after typing the first paren, the snippet triggers again since then the buffer contains `((.)` and this is apparently detected as valid trigger and transformed to `(.))`. then i type the second paren and after another expansion end up with `(.)))` . 

what i wanted was `((.))` of course. 

is this intended? to me it seems that the autotrigger would be more useful if working like a vim shortcut, only on the immediately typed characters?

**Comment by seletskiy** [comment]
@nilsbecker: autotrigger flag `A` is only points, that snippet engine should try to match specified snippet definition on any change made in insert mode, so `((` in your definition is not matched against some kind of temporary type buffer, it's matching against previous line as all other non-autotrigger snippets.

If you want, you can organize that kind of type buffer by yourself using `context` feature.

**Comment by nilsbecker** [comment]
it makes sense that it works this way, since the regular snippets also work the same way. for my use case however the abbreviation-like behavior is more useful. i'll check out `context`. another option that just came to my mind would be to define an actual abbreviation the standard vim way, which expands `((` to another unused character (some weird unicode value or so) and then make an autotrigger for that. it's a bit of a hack but it would reuse the keyboard interaction of vim abbreviations...

**Comment by nilsbecker** [comment]
hmm, i read the docs on the context feature but i am not sure how one would solve my problem using it. sometimes when the buffer looks like `((.` i want to expand (the normal case) and sometimes when it looks the same, i do not want to expand (the case when `(` was there from before and `((.` occurs after typing only one parenthesis. so just by looking at the buffer contents, even the surrounding context, one cannot decide which one is meant?

**Comment by nilsbecker** [comment]
ok, so the vim abbreviation feature also is not a perfect match. they only get expanded after typing a non-keyword character afterwards and under some other conditions. any help doing it with ultisnips would be appreciated...

**Comment by nilsbecker** [comment]
i mixed things up: what i was looking for was not `:abbrev` but `:digraph` . i will investigate that route.

**Comment by seletskiy** [comment]
@nilsbecker: ugly but works:

```
global !p
def match_auto_paren(snip, match):
    vim.command('let b:auto_paren = exists("b:auto_paren") \
        ? b:auto_paren : {"line": -1, "text": ""}')

    state = vim.bindeval('b:auto_paren')
    line = snip.buffer[snip.line]

    if snip.line != state['line'] or not line.startswith(state['text']):
        state['line'] = snip.line
        state['text'] = line[:snip.column]
        return False

    if line[len(state['text']):][:2] == match:
        state['line'] = snip.line
        state['text'] = line[:snip.column]
        return True

endglobal

context "match_auto_paren(snip, '((')"
snippet ( "auto paren" Ai
$1)$0
endsnippet
```

**Comment by nilsbecker** [comment]
cool, i will give it a try later. thanks!

**Comment by nilsbecker** [comment]
hi, i must admit i don't really get what's going on in the snippet code; there is some checking if the content of a line matches some internal state. anyway when i tried, i got it working at the beginning of a line, with several nested parentheses immediately after one another, but nowhere else. what is the logic behind it? i would think some sort of timeout would be needed to distinguish new input from buffer contents?

**Comment by nilsbecker** [comment]
i am starting to understand it a bit. on the first `(` you store a state but don't trigger. on the next `(` you look if the line where the state was last saved and the new `(` together match `((`. hmm. is there maybe an update of the vim variable missing ? i noticed that the value of `b:auto_paren` is not always updated when a `(` is typed...

**Comment by seletskiy** [comment]
@nilsbecker: `vim.bindeval` links vim variable `b:auto_paren` with python `state` variable, so it updated accordingly. I tested it in several cases and it works, can you provide malfunctioning example?

**Comment by nilsbecker** [comment]
i copied the code above into a file all.snippets in a directory included in g:UltiSnipsSnippetDirectories. then i open a new buffer and type `a ((`. this does trigger the snippet. then `<c-j>` to move out of it and again `((`. here already it does not expand.

**Comment by SirVer** [comment]
Autotrigger has no specific semantics, but what you want here should be possible with an Anon expansion using inoremap: https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L444
