### ISSUE TITLE
No way of marking a block as 'do not execute continously'

### ISSUE THREAD

**Issue by sim590** [SirVer/ultisnips#779]
ORIGINALLY POSTED THIS [HERE](https://github.com/honza/vim-snippets/issues/806)

Consider the following snippet taken from vim-snippets plugin:

``` snippets
snippet deff
    def ${1:fname}(${2:`indent('.') ? 'self' : ''`}):
        ${0}
```

Let the following initial file where `^` indicates the cursor position:

``` python
deff
    ^
```

Pressing the expand shortcut, I get the first snippet like so:

``` python
def fname():
    ^
```

Pressing `<ctrl-j>`:

``` python
def fname():
          ^
```

Pressing `<ctrl-j>`:

``` python
def fname(self):

    ^
```

Even though the initial `deff` word was at position 0, the final snippet did insert a `self` word. I guess that this has to do with the instruction `indent('.')` being interpreted at the end of the `ctrl-j` sequence since at the end, it is true that the cursor position (column-wise) is not 0.

**Comment by sim590** [comment]
From the last cursor position illustrated in my last post, you can go up one line using `k` to see `self` disappear and go back down using `j` to see the word `self` reappear continuously.

**Comment by seletskiy** [comment]
@sim590: try to use following snippet (UltiSnips syntax):

```
snippet deff
def ${1:fname}(`!p snip.rv = vim.eval('indent(".") ? "self, " : ""')`$2):
    $0
endsnippet
```

**Comment by sim590** [comment]
It works well.

@seletskiy Seems like Ultisnips has a bug in interpreting legacy style snipMate snippets, because the snippet you suggest to use is quite the Ultisnips equivalent to the one I was using. What do you think?

**Comment by seletskiy** [comment]
@sim590: Yes, it probably is. But I do not feel I will ever fix it by myself, so if somebody wants, I will gladly accept PR.

**Comment by SirVer** [comment]
The UltiSnips snippet has the same behavior at c309637e0243b71f7e3265ebe3cffdfe9674cfbc and I'd argue this is actually working as intended: the vimscript block is evaluated for every key stroke and since `indent(".")` is continuously evaluated, the self keyword will be added or removed depending on where the cursor is.

However ther is no great solution to mark a block as excute only once.

**Comment by seletskiy** [comment]
@SirVer there's one method which works reasonably well:

```
`!p

try:
	once
except:
	once = True
	# code goes here
`
```
