### ISSUE TITLE
Expand trigger not working

### ISSUE THREAD

**Issue by thinksalot** [SirVer/ultisnips#780]
Hi, 

My expand trigger which was working before is not working anymore since i upgraded to ubuntu 16.04 and vim 7.4. My .vimrc is [here](https://github.com/thinksalot/dotfiles/blob/master/.vimrc)

**Comment by seletskiy** [comment]
@thinksalot: Sorry, but it's impossible to assist until you provide exhaustive bug report describing what you do, what you expect to see and minimal setup reproducing issue.
