### ISSUE TITLE
the ultisnips can't show available snips on window

### ISSUE THREAD

**Issue by clay-f** [SirVer/ultisnips#781]
i'm edit the .py file
 i'm typed class on vim
the autocomplete can't show options
 ultisnips config is:
          `let g:UltiSnipsExpandTrigger="<tab>"`
          `let g:UltiSnipsJumpForwardTrigger="<c-b>"`
          `let g:UltiSnipsJumpBackwardTrigger="<c-z>"`
         `let g:UltiSnipsEditSplit="vertical"`
the filetype is on in .vimrc
         `filetype detecton:ON plugin:ON indent:ON`
                `Plugin 'honza/vim-snippets'`
                `Plugin 'sirver/ultisnips'`
              is installed
the ultisnips could be using tag
it's just con't show available snips when i edit files 
e.g .java file counldn't show available snips options.

**Comment by seletskiy** [comment]
@lyf-t: I guess you should install one of the autocompletion plugins to make it work.

**Comment by SirVer** [comment]
Closing as stale.
