### ISSUE TITLE
extended standard snippets do not expand

### ISSUE THREAD

**Issue by Konfekt** [SirVer/ultisnips#785]
Install `honza/vim-snippets` and in `~/.vim/UltiSnips/pandoc.snippets`, put
```
    extends markdown, tex
```
Then in a buffer of file type `pandoc` among others the following snippets do not expand: in tex.snippets,
```
    snippet url
    \url{${1}} ${0}
```
 in markdown.snippets,
```vim
    snippet ```
	    \`\`\`
	    ${1:code}
	    \`\`\`
```
However, other snippets at the beginning of both snippet files expand and, they expand just fine after an explict
```vim
    :UltiSnipsAddFiletypes markdown.tex
```

**Comment by seletskiy** [comment]
@Konfekt: is it reproduceable using non-snipMate snippets (e.g. UltiSnips-syntax)?

**Comment by Konfekt** [comment]
I am not sure what a snippets makes incompatible to snip-Mate. Could you point out one in either markdown.snippets or tex.snippets?

Note that the first snippets in either file, tex.snippets or markdown.snippets, do work. For example in tex.snippets,
```
snippet nc \newcommand
	\newcommand{\\${1:cmd}}[${2:opt}]{${3:realcmd}} ${0}
```
Is this because it uses snipmate incompatible syntax?

**Comment by Konfekt** [comment]
Not sure: What makes a snippet incompatible to snip-Mate? Could you point out one in either markdown.snippets or tex.snippets?

Note that the first snippets in either file, tex.snippets or markdown.snippets, do work. For example in tex.snippets,
```
snippet nc \newcommand
	\newcommand{\\${1:cmd}}[${2:opt}]{${3:realcmd}} ${0}
```
Is this because it uses snipmate incompatible syntax?

**Comment by SirVer** [comment]
UltiSnips never mixes snipmate & UltiSnips snippets. So the extends in the UltiSnips file does not pull in the snipMate snippets. See https://github.com/SirVer/ultisnips/blob/8ff301c651d6df806c0f9305273a6c62a693bc48/doc/UltiSnips.txt#L1753 for details.

**Comment by Konfekt** [comment]
Thank you, that really cleared it up.
