### ISSUE TITLE
Add UltiSnips#isExpandable()

### ISSUE THREAD

**Issue by Konfekt** [SirVer/ultisnips#786]
Add a function UltiSnips#isExpandable() (as neosnippet offers in guise of neosnippet#expandable()), useful for example for autocompletion plug-ins like delimitmate:
```vim
 nnoremap <expr> <tab> delimitMate#isEmptyPair() && UltiSnips#isExpandable() ? <del>:UltiSnips#Expand() : '<tab>'
```
This way, a snippet with delimiters such as
```vim
  snippet [
	[${1:text}](http://${2:address})
```
in markdown.snippets of vim-snippets, is expanded with no trailing ] (auto-inserted by the autocompletion plugin).

**Comment by seletskiy** [comment]
@Konfekt: pull request is welcome.

**Comment by Konfekt** [comment]
Discovered `UltiSnips#SnippetsInCurrentScope()` which does something very similar: If non-empty, the snippet in front of the cursor expands. Therefore my `isExpandable()` function is superfluous? Perhaps @SirVer knows best.

**Comment by SirVer** [comment]
Closing, as the functionality is available in more general form in `UltiSnips#SnippetsInCurrentScope()`.

**Comment by thorlucas** [comment]
> Closing, as the functionality is available in more general form in `UltiSnips#SnippetsInCurrentScope()`.

This is not really the same functionality. `UltiSnips#SnippetsInCurrentScope()` returns a full dictionary even when `UltiSnips#ExpandSnippet()` would fail. For example, if you check `UltiSnips#SnippetsInCurrentScope()` when theres just white space at your cursor, it'll return the dictionary of *all* snippets. So this functionality is still needed

**Comment by SirVer** [comment]
@thorlucas True. Reopening and thanks for the pull request, I try to review during the week!

**Comment by thorlucas** [comment]
> @thorlucas True. Reopening and thanks for the pull request, I try to review during the week!

Thanks for the plugin! It's really quite fantastic.
