### ISSUE TITLE
Behavior of the path variable in python interpolation

### ISSUE THREAD

**Issue by kshenoy** [SirVer/ultisnips#788]
Hi, according to the doc, `path` in python interpolation is supposed to give the complete path to the current file.

However, I see that instead of giving the full path it gives the path relative to the working directory.
From `pythonx/UltiSnips/text_objects/_python_code.py`:

    path = _vim.eval('expand("%")') or ''

If this is intentional, is there a way to get the equivalent of `%:p` in python interpolation?

Also, is there a difference between `fn` and `snip.fn`?

**Comment by seletskiy** [comment]
@kshenoy: `fn` is `os.path.basename(path)`, and `snip.fn` is `_vim.eval('expand("%:t")')` (dunno why it's done that way).

One way to get absolute path in python interpolation is to use `vim.eval('expand("%:p")')` in it.

**Comment by SirVer** [comment]
Closing as answered.
