### ISSUE TITLE
Transform the only occurence of one placeholder

### ISSUE THREAD

**Issue by iago-lito** [SirVer/ultisnips#789]
This (imaginary) snippet does what I (imaginary) want:

	snippet t "test" b
	option: ${1/(.+)/(?1:first $1)/}
	$1
	endsnippet

.. well, almost. I (imaginary) do not need this optional `$1` to be written a second times on the second line. However, this snippet:

	snippet t "test" b
	option: ${1/(.+)/(?1:first $1)/}
	endsnippet

fails with `RuntimeError: Tabstop 1 is not known but is used by a Transformation`.

Is there a way we can "Transform" a placeholder even if it appears only once?

**Comment by seletskiy** [comment]
@iago-lito: So, you want to prepend `first ` before `$1` if it's not empty?

**Comment by iago-lito** [comment]
Precisely. Is this what [pending feedback](https://github.com/SirVer/ultisnips/labels/pending%20feedback) is about?

**Comment by seletskiy** [comment]
@iago-lito: It's just label to mark issues after first comment. Sometimes, people do not reply back and it's just for managing purposes.

**Comment by seletskiy** [comment]
@iago-lito: Your example can be implemented using python interpolation:
```
snippet x "test" b
option: `!p snip.rv = 'first: ' if t[1] else ''`$1
endsnippet
```
