### ISSUE TITLE
Can't get ultisnips to work with latest neovim on Mac Os

### ISSUE THREAD

**Issue by asishallab** [SirVer/ultisnips#793]
Dear SirVer,

thank you very much for providing the community with the most useful UltiSnips plugin. I have greatly depended on it with classic Vim and MacVim. Now, I switched to neovim and cannot get it to work any more. Please help.

My environment is: 
- Mac OS X Yosemite 10.10.5
- iTerm2 3.10.12 or default Terminal-App 2.5.3
- neovim v0.1.2 (full output of `nvim -v` below)
- `Python 2.7.12` installed and managed through `virtualenvwrapper`
- `pip 9.0.1` (Full list of packages installed in the Python environment 'neovim' below)
- For testing I used a [minimal vim config](https://github.com/asishallab/neovim_config/tree/test_UltiSnips) with `junegunn/vim-plug` and `UltiSnips` (Please, click the link to be redirected to my neovim environment setup.)

I tested different UltiSnip trigger keys, but cannot get it to expand any snippet. Not even the ones stored in `all.snippets`. My `runtimepath` appears to be setup correctly including UltiSnips.

Output of `nvim -v`:
<code>NVIM 0.1.2
Build type: Release
Compilation: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -pipe -Os -Wconversion -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/opt/local/var/macports/build/_opt_mports_dports_editors_neovim/neovim/work/neovim-0.1.2/config -I/opt/local/var/macports/build/_opt_mports_dports_editors_neovim/neovim/work/neovim-0.1.2/src -I/opt/local/include -I/opt/local/include -I/opt/local/include/luajit-2.0 -I/opt/local/include -I/opt/local/include -I/opt/local/include -I/opt/local/include -I/opt/local/include -I/opt/local/var/macports/build/_opt_mports_dports_editors_neovim/neovim/work/neovim-0.1.2/src/nvim/auto -I/opt/local/var/macports/build/_opt_mports_dports_editors_neovim/neovim/work/neovim-0.1.2/include
Compiled by macports@tenten-slave.macports.org

Optional features included (+) or not (-): +acl   +iconv    -jemalloc
For differences from Vim, see :help vim-differences

  system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/local/share/nvim"</code>

Output of `(neovim) > $ pip list`
<code>futures (3.0.5)
greenlet (0.4.10)
msgpack-python (0.4.8)
neovim (0.1.11)
pip (9.0.1)
setuptools (28.8.0)
six (1.10.0)
trollius (2.1)
wheel (0.30.0a0)</code>

Please help!
Thank you and Cheers!

**Comment by languitar** [comment]
I am experiencing a similar issue using ultisnips on neovim recently, running on archlinux 64.

**Comment by seletskiy** [comment]
@asishallab: neovim is not supported, sorry. If you want to make it work, you can dig into reasons why it's not working and prepare PR, I will gladly merge it.
