### ISSUE TITLE
What is the minimal install for Sierra?

### ISSUE THREAD

**Issue by jychri** [SirVer/ultisnips#794]
Hi. I think I'm slowly losing my mind. 

I just setup a fresh install of MacOS Sierra and I've been trying all day to get UltiSnips to expand even a basic snippet. The machine has the full version of Xcode (not just the command line tools), Homebrew, MacVim, iTerm2 and literally nothing else. MacVim is set to override system vim, (brew install macvim --with-override-system-vim) and the version is 8.0.94.

My vimrc only has the basics:

set nocompatible       
filetype off          

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'SirVer/ultisnips'
Plugin 'honza/vim-snippets'
call vundle#end()    
filetype plugin indent on    

let g:UltiSnipsExpandTrigger='<tab>'
let g:UltiSnipsJumpForwardTrigger='<c-j>'
let g:UltiSnipsJumpBackwardTrigger='<c-k>'

Everytime I create a new snippet with :UltiSnipsEdit it creates a new folder inside the current directory. If I'm working on ~/Desktop/tmp it creates ~/Desktop/UltiSnips/all.snippets. If I'm working at ~ it creates ~/UltiSnips/all.snippets (screenshot attached). 

What am I missing? I've scoured the manual and the kicker is that I have UltiSnips and YouCompleteMe working 100% perfectly on my main development machine with Supertab. When I ported over my full vimrc, I couldn't get UltiSnips to work, so I wiped that box and started fresh. I've restored the thin image at least 10 times now and no matter what I do, I still can't get UltiSnips to engage.

![screen shot 2016-11-29 at 1 43 43 pm](https://cloud.githubusercontent.com/assets/5490881/20726371/e0ee0ebc-b63a-11e6-964d-a25e209dcbca.png)

**Comment by seletskiy** [comment]
@JCodesMN: Try to set `g:UltiSnipsSnippetsDir` in your vimrc:

```
let g:UltiSnipsSnippetsDir = $HOME . '/.vim/UltiSnips/'
```

**Comment by JCodesMN** [comment]
I have fully reinstalled Sierra again. The machine has Xcode, Karabiner Elements and Atom on top of a fresh install of 10.12.1. I still can't get UltiSnips to engage. At this point, I haven't installed Homebrew, upgraded Python (/usr/bin/python 2.7.10) or Vim (version 7.4.898), everything is stock.

Vimrc:

set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'SirVer/ultisnips'
call vundle#end()
filetype plugin indent on

let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"
let g:UltiSnipsSnippetsDir = $HOME . '/.vim/UltiSnips/'

**Comment by JCodesMN** [comment]
Wiped my test box again and now UltiSnips is working on a base Sierra install. 

The box has:
- 'stock' Vim 7.4.898
- Atom
- full Xcode install
- Karabiner Elements

Vimrc:

set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'SirVer/ultisnips'
call vundle#end()            " required
filetype plugin indent on    " required

let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"
let g:UltiSnipsSnippetsDir = $HOME . '/.vim/UltiSnips/'

I can comment out the last line and everything still works. I'm going to install Homebrew now and pull in the rest of my .vimrc from my main laptop. If I discover a breaking change I'll post it.

**Comment by SirVer** [comment]
Closing as resolved.
