### ISSUE TITLE
Custom Snippet Not Expanding

### ISSUE THREAD

**Issue by 56phil** [SirVer/ultisnips#797]
I'm trying to get a python snippet to work. No problems using the provided snippets. I am fairly sure my snippet is the problem. Here is the snippet:
`
snippet nn "test" b
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# date: `date +%Y-%m-%d`
# copyright © $2 `date +%Y` all rights reserved.
"""
${1:Python source code - replace this with a description of your code}
"""
__author__ = "${2:Philip R. Huffman}"

#def main():
#    """
#    ${3:Used by terminal}
#    """

#if __name__ == "__main__":
#    main()
endsnippet

and my .vimrc:
`
let mapleader=','
set nocompatible              			" required
filetype off                  			" required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'			" requrired
" let Vundle manage Vundle, required

" Add all your plugins here

Plugin 'b4winckler/vim-objc' 			" vim for Objective-C
Plugin 'bling/vim-airline'			" pretty status lines
Plugin 'ctrlpvim/ctrlp.vim'			" a fuzzy file finder
Plugin 'honza/vim-snippets'			" adds snippets for ultisnips
Plugin 'jiangmiao/auto-pairs'			" adds the closer
Plugin 'jlanzarotta/bufexplorer'		" move from buffer to buffer
Plugin 'klen/python-mode'			" useful tools for Python
Plugin 'lervag/vimtex'				" for the LaTeX community
Plugin 'majutsushi/tagbar'			" keeps you honest w/tags
Plugin 'scrooloose/nerdcommenter'		" toggles comments etc.
Plugin 'sirver/ultisnips'			" a great snippet manager
Plugin 'terryma/vim-multiple-cursors'		" just like in sublime text
Plugin 'tommcdo/vim-exchange'			" moves ext easily
Plugin 'tpope/vim-dispatch'			" for async scripts
Plugin 'tpope/vim-fugitive'			" a fine git tool
Plugin 'tpope/vim-repeat'			" works with many plugins
Plugin 'tpope/vim-sensible'			" a set useful mappings
Plugin 'tpope/vim-speeddating'			" manipulates dates in buffers
Plugin 'tpope/vim-surround'			" every developer needs this
Plugin 'tpope/vim-unimpaired'			" handy
Plugin 'tpope/vim-vinegar'			" works with ctrlp
Plugin 'vim-airline/vim-airline-themes'		" multiple themes for airline
Plugin 'wincent/ferret'				" like an ack on steroids

" All of your Plugins must be added before the following line
call vundle#end()            			" required
filetype plugin indent on    			" required

set guifont=Droid\ Sans\ Mono\ for\ Powerline:h15
set clipboard=unnamed	     			" use system clipboard
set showmatch
set number
set undofile                 			" Save undo's after file closes
set undodir=$HOME/.vim/undo  			" where to save undo histories
set undolevels=1024          			" How many undos
set undoreload=16384         			" number of lines to save for undo
colorscheme desert				" much better for the eyes

" unfold everything
nnoremap <space> zR

" move curser from split to split
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" toggles comment on a line
nnoremap <D-/> :execute  "normal \<Plug>NERDCommenterInvert"<CR>

" the next few lines are used to work with the .vimrc file
nnoremap <silent> <leader>ev :e $MYVIMRC<CR>
nnoremap <silent> <leader>wv :w<CR> :so $MYVIMRC<CR>
nnoremap <silent> <leader>pv :w<CR> :so $MYVIMRC<CR> :PluginInstall<CR>

let g:UltiSnipsExpandTrigger="<tab>"		" use tab to trigger completions

let g:pymode_rope=0				" no rope! Takes over 1m to :w
"let g:pymode_rope_completion=0
"let g:pymode_rope_lookup_project=0
"let g:pymode_rope_autoimport_modules=['os', 'datetime']
"let g:pymode_rope_autoimport_import_after_complete=1

" this chunk moves a line up or down
function! s:swap_lines(n1, n2)
    let line1=getline(a:n1)
    let line2=getline(a:n2)
    call setline(a:n1, line2)
    call setline(a:n2, line1)
endfunction

function! s:swap_up()
    let n=line('.')
    if n == 1
        return
    endif

    call s:swap_lines(n, n - 1)
    exec n - 1
endfunction

function! s:swap_down()
    let n=line('.')
    if n == line('$')
        return
    endif

    call s:swap_lines(n, n + 1)
    exec n + 1
endfunction

noremap <silent> <a-d-down> :call <SID>swap_down()<CR>
noremap <silent> <a-d-up> :call <SID>swap_up()<CR>
" end of move line chunk

"controls airline
let g:airline#extensions#tabline#enabled=1
let g:airline_powerline_fonts=1
let g:Powerline_symbols='fancy'
let g:airline_skip_empty_sections=1
set t_Co=256
set encoding=utf-8
set fillchars+=stl:\ ,stlnc:\
set termencoding=utf-8
AirlineTheme ubaryd

autocmd BufWritePre * :%s/\s\+$//e				" loose the trailing spaces

let g:tagbar_ctags_bin='/usr/local/bin/ctags'  			" Proper Ctags location
let g:tagbar_width=32                          			" Default is 40, seems too wide
nnoremap <F8> :TagbarToggle<CR>

au FileType py set textwidth=79 				" PEP-8 Friendly

let mapleader=','
`
Thank you.

**Comment by vhoyer** [comment]
I'm with the same error, like, using snippets provided by honza/vim-snippets there s no problem, but using the command `:UltiSnipsEdit` and/or `:UltiSnipsAddFileTypes`  to edit my own snippets, it doesn't work... I want to use ultisnips without the honza's but I just can't figure it out. Also, I'm pretty sure I've the right sintax since I've tried to copy from honza's to mine and it didn't work

**Comment by fikovnik** [comment]
I have the same problem here. I also try to set the paths in:

```
let g:UltiSnipsSnippetsDir="~/.vim/my-snippets"
let g:UltiSnipsSnippetDirectories=[g:UltiSnipsSnippetsDir]
```

but that did not helped either (plus I guess it must work without this).

**Comment by fikovnik** [comment]
Somehow I get it working by setting:

```
let g:UltiSnipsSnippetsDir="~/.vim/UltiSnips"
```

**Comment by 56phil** [comment]
Thanks Filip, that worked.
