### ISSUE TITLE
Running `UltiSnipsEdit` won't open on the default directory

### ISSUE THREAD

**Issue by chris-fa** [SirVer/ultisnips#798]
### Context
I'm inside a PHP file and run `:UltiSnipsEdit` and then `:w`. 

### Expected behavior
It saves to `~/.vim/UltiSnips/php.snippets`

### Actual Behaviour
Saves to `UltiSnips/php.snippets` inside the project directory

### Miscellaneous
* My `~/.vim` folder is a soft symbolic link to the actual location. 
* The directory `~/.vim/UltiSnips` exists.

**Comment by dkrmr** [comment]
Same here.

**Comment by Sathors** [comment]
Seems to be a duplicate of #709.

**Comment by andreyorst** [comment]
related to #711
