### ISSUE TITLE
Neovim: Lagging when inserting text

### ISSUE THREAD

**Issue by cbaumhardt** [SirVer/ultisnips#801]
I have the following file `vimrc_ultisnips`:
```VimL
call plug#begin()
Plug 'SirVer/ultisnips'
call plug#end()

""" the following options I tried, they don't help
" let g:python_host_prog='/usr/bin/python'
" let g:python3_host_prog='/usr/bin/python3'
" augroup UltiSnips_AutoTrigger
"   au!
" augroup END
" autocmd! UltiSnips_AutoTrigger

""" activate later for profiling
" profile start output.log
" profile func *
```

Open a new file with neovim by typing `nvim -u vimrc_ultisnips`, then enter `1000isometext<Esc>`. It takes about 5 seconds till the text appears, during that time nvim is not responsive.

Note that when I comment out `Plug 'SirVer/ultisnips'` I do not have this issue. Also, this seems to be just an issue on neovim, as with `vim -u vimrc_ultisnips` I do not experience this issue.

The output from profiling gives:

```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
 8009   3.186269   3.055471  provider#python3#Call()
 8007   3.089445             UltiSnips#TrackChange()
    1   0.130798   0.000115  remote#host#Require()
    1   0.130682   0.130651  provider#pythonx#Require()
    1   0.022475   0.000049  provider#pythonx#Detect()
    1   0.022426             <SNR>12_check_interpreter()
   17   0.003623             <SNR>19_Highlight_Matching_Pair()
    2   0.000154             UltiSnips#map_keys#MapKeys()
    1   0.000098   0.000042  <SNR>20_VimEnter()
    1   0.000086   0.000069  remote#host#RegisterPlugin()
    2   0.000072             <SNR>20_LocalBrowse()
    2   0.000034             remote#host#PluginsForHost()
    3   0.000030             remote#host#Register()
    1   0.000024             remote#host#RegisterClone()
    1   0.000008             provider#python3#Prog()
    1   0.000007             remote#host#IsRunning()

```
It don't understand why an UltiSnips function is called 8000 times during the process describe above, when I am not even using a snippet. Removing the Autotrigger autocommand as @justinmk suggested [here](https://github.com/neovim/neovim/issues/5702#issuecomment-264457101) didn't help either.

I am using NVIM v0.2.0-457666b49 (RelWithDebInfo), and `:CheckHealth` gives no warnings or errors. I tried also to use `let g:python_host_prog='/usr/bin/python'` and `let g:python3_host_prog='/usr/bin/python3'` but that doesn't seems help with this issue.

**Comment by SirVer** [comment]
This issue was closed due to it only affecting [Neovim](https://github.com/neovim/neovim) and not core [Vim](https://github.com/vim/vim).

## Why is Neovim only best-effort?

UltiSnips maintenance is a lot of work. Reproducing bug reports is tedious, slow and error prone. The current maintainers have to limit their scope to provide a reasonable level of service to the community. 

Neovim should work with any plugin that core vim works with. But in the past, Neovim support has been difficult for UltiSnips: It regularly had bugs that did not affect the core Vim distributions, i.e. Vim, gVim, MacVim, and Vim for Windows and its testing approach required a completely separate code path from core as well. Therefore, currently Neovim bugs are considered on a best effort basis. 

UltiSnips is looking for an additional maintainer that is interested in bringing the Neovim level of service on par with core Vim. If you are interested in helping out, please reach out to [SirVer](https://github.com/SirVer/).

**Comment by justinmk** [comment]
>  It regularly had bugs that did not affect the core Vim distributions, 

@SirVer Aren't you only referring to one bug (actually a behavior change: https://github.com/neovim/neovim/issues/2454) , plus a performance issue? 

"Regularly had bugs" implies that there's an endless stream of Neovim-only bugs that aren't being addressed by Neovim. AFAIK we've monotonically decreased the number of regressions that we have compared to Vim, and there is not a "regular" stream of new bugs.

**Comment by SirVer** [comment]
@justinmk These are semantics to me and you are free to interpret the situation that way too. To me,  Neovim forking the functionality of Vim in a non-expected way is a bug for an editor that claims compatibility. And performance is a feature, the lag of it a bug. I understand that you see this differently as you care about Neovim. For me though, the project is a disappointment and a constant source of nuisance in the maintenance of UltiSnips: [roughly 80 reported issues](https://github.com/SirVer/ultisnips/issues?utf8=%E2%9C%93&q=neovim) to day, most closed as non-fixable).

As long as no hero steps forward and changes UltiSnips design to work with the out-of-core design of Neovim - which adds orders of magnitude to each `CursorMovedI` that UltiSnips depends on - I doubt these issues stop flooding in. This boilerplate closing message is at least a pointer to why we do not support Neovim.

**Comment by justinmk** [comment]
@SirVer no disagreement, just wanted to get an understanding. If there is some other bug causing these 80 reports (mostly duplicates? over 4 years?) that I'm not aware of, let me know.

**Comment by SirVer** [comment]
@justinmk Thanks for the offer!

**Comment by tan-wei** [comment]
Met the same issue in 2022. But still saidly, no heros appear. Still thanks to @SirVer for the great plugin.
