### ISSUE TITLE
Wishlist: support replace mode

### ISSUE THREAD

**Issue by mgedmin** [SirVer/ultisnips#803]
## Summary

It would be nice if expanding snippets would overwrite text instead of inserting it, when using Vim's replace mode.

## Details

I've a `date` snippet that expands to

```
snippet date "YYYY-MM-DD" w
`!v strftime('%Y-%m-%d')`
endsnippet
```

Often I'm editing a file that already has an (outdated) date, e.g.

```python
__date__ = '2015-07-24'
```

and I wish to replace the date.  So I position the cursor on the `2` and hit `R` and type `date` and then trigger snippet expansion, which expands

```python
__date__ = 'date-07-24'
```

to

```python
__date__ = '2016-12-14-07-24'
```

which makes me sad, since I was expecting

```python
__date__ = '2016-12-14'
```

**Comment by seletskiy** [comment]
@mgedmin: Just use regexp snippet:

```
snippet "\d{4}-\d{2}-\d{2}" "update date" br
`!v strftime('%Y-%m-%d')`
endsnippet
```

Hit `<Tab>` at the `|` cursor position.
```
__date__ = '1111-11-11|`
```

If you want it your way (e.g. with replacing year by `date`), then use `pre_expand` feature to remove all following text till next quote (will be more complex than regexp-based snippet).

**Comment by mgedmin** [comment]
For the record, here's what I ended up with:

```
global !p
def handle_replace_mode(trigger_length):
    if vim.eval('v:insertmode') == 'i':
        return
    start_line, start_col = snip.snippet_start
    end_line, end_col = snip.snippet_end
    if start_line != end_line:
        return
    replacement_length = end_col - start_col
    if replacement_length == trigger_length:
        return
    if replacement_length > trigger_length:
        delete = replacement_length - trigger_length
        line = snip.buffer[end_line]
        snip.buffer[end_line] = line[:end_col] + line[end_col + delete:]
        ## snip.cursor.set(end_line, start_col + replacement_length) # XXX does not work
        ## snip.snippet_end = end_line, start_col + replacement_length # XXX does not work
    elif replacement_length < trigger_length:
        # not implemented yet (and I'm not sure if it's possible to implement)
        return
endglobal

post_expand "handle_replace_mode(4)"
snippet date "YYYY-MM-DD" w
`!v strftime('%Y-%m-%d')`
endsnippet
```

There are two problems with it:
- I don't know how to get the length of the actual snippet trigger string from Python, so I hardcode it as the argument in the `handle_replace_mode(4)` call
- I don't know how to position the cursor correctly.  E.g. when I do the replacement as in the original issue description, the cursor ends up on top of the last digit, instead of on top of the closing quote.  And when I replace today's date with today's date (2016-12-14 => date-12-14 => 2016-12-14), the cursor is on top of the last digit of 2016 instead of one column after the 4.

**Comment by seletskiy** [comment]
@mgedmin: You can try to obtain length of actual snippet trigger by using regexp-based snippet and accessing `match.group(0)`.
