### ISSUE TITLE
How to escape quotes in snippet description

### ISSUE THREAD

**Issue by DasOhmoff** [SirVer/ultisnips#804]
Hello,
how do I display this characters in the description of a snippet ->    include "...".
This obviously does not work:
> snippet Inc "include "..."" b
> ...

**Comment by DasOhmoff** [comment]
*push*

By the way, of course I also tried
`snippet Inc "include \"...\""`

**Comment by seletskiy** [comment]
@DasOhmoff: If it doesn't work, it possibly require code modification, so if you feel wanting to fix it, I will gladly merge PR!

**Comment by DasOhmoff** [comment]
Well I don't know how to do that.
But thanks for asking.

**Comment by andreyorst** [comment]
By the first look to documentation
https://github.com/SirVer/ultisnips/blob/943156d8794772c23a0a0f6e5120c40b8c7981ec/doc/UltiSnips.txt#L741-L745
there is nothing stated about escaping quotes inside quoted string. Maybe that's not possible. I've run into the same issue too. @SirVer is it possible to escape quotes intside snippet description?

**Comment by SirVer** [comment]
@andreyorst @DasOhmoff No, there is no support for escaping inside the description thing. Fundamentally this would probably not be super hard to add, but it also seems that it is easy to work around.

**Comment by SirVer** [comment]
This seems not to be a highly requested feature and just not using quotes in snippet descriptions seems like an easy enough work around. Closing this as won't fix.
