### ISSUE TITLE
Conditional inclusion

### ISSUE THREAD

**Issue by bpj** [SirVer/ultisnips#805]
I have an embedded code in a snippet which should be empty unless a certain placeholder is non-empty. I tried the following but it doesn't seem to work:

```
`!p snip.rv = "foo" if t[3].len() else ""`
```

but it doesn't seem to work. 

Ideally there should be conditional inclusion logic like

```
${if:3}
Some longish piece of text if tab #3 is non-empty
${elsif:2/\bfoo*\b/}
Content if tab #2 matches the regex
${elsif:`!p t[1] > 2`}
You get the idea!
${else}
bar
${endif}
```

Having written my share of parsers I can however fully realize why it might not get implemented! :-)

**Comment by SirVer** [comment]
Your original suggestion works for me: https://asciinema.org/a/yVFNM8NQluvxq4gEwc9P9aNIe

And yes, the additional syntax in snippets will not be implemented. UltiSnips is already too complex as it is.
