### ISSUE TITLE
snippets with chinese

### ISSUE THREAD

**Issue by dengxqi** [SirVer/ultisnips#806]
when i am typing Chinese using snippets, there are some problems that bordered me, for example 

![1](https://cloud.githubusercontent.com/assets/8897835/21599766/d7182f98-d1ac-11e6-88f6-4f4d5f7bf8a2.gif)

and 

![2](https://cloud.githubusercontent.com/assets/8897835/21599778/e2f5c726-d1ac-11e6-86df-c0cd94440995.gif)

the snippets are listed below:

``` 
snippet title "Title" w
---
title: ${1:title}
date: `!v strftime("%Y-%m-%d %H:%M:%S")`
categories: ${2:categories}
---
endsnippet

```

and 

```
snippet def "def" w
def ${1:function}(${2:self}):
	${3:中文}
endsnippet
```

can anyone help me to check that?

**Comment by seletskiy** [comment]
@dengxqi: Yep, there is some problems in ultisnips regarding non-ASCII and I wonder why too. If you will help me dig down to the roots of the problem, I will be very glad.

**Comment by SirVer** [comment]
@dengxqi Could you post a few snippet definitions that are troublesome, so we can turn them into test cases?

**Comment by SirVer** [comment]
Dup of #168.
