### ISSUE TITLE
differences from neosnippet

### ISSUE THREAD

**Issue by nhooyr** [SirVer/ultisnips#807]
What makes this plugin different from neosnippet? They both seem very similar.

**Comment by seletskiy** [comment]
@nhooyr:

UltiSnips is far more powerfull. UltiSnips provides at least following features which are not implemented in neosnippet:

* interpolations for placeholders (code, that modifies placeholder values in realtime);
* pre-expand, post-expand, post-jump snippet actions (e.g. python code, which is evaluated before/after snippet expand or after jump to next placeholder; see https://github.com/SirVer/ultisnips/blob/master/doc/examples/tabstop-generation/README.md for example;
