### ISSUE TITLE
UltiSnips#FileTypeChanged problem with a bundle and some options

### ISSUE THREAD

**Issue by vonpupp** [SirVer/ultisnips#808]
Hello,

I am having the following problem when I open vim:

    Error detected while processing FileType Auto commands for "*":
    E117: Unknown function: UltiSnips#FileTypeChanged

I am using Arch Linux, and here are my [vim dotfiles]. I am [installing UltiSnips using vundle].

I narrow it down by commenting all my configs file by file (I have my vim configs separated and an autoloader for ~/.vim/config/*.vim), and I noticed the following:
- Incompatibility with bundle: [klen/python-mode]. This is a very popular python development bundle, so it might be caused by something else behind it.
- Incompatibility with option: [syntax on]. This looks very weird, it might be caused by something else behind it.
- Incompatibility with option: [filetype plugin indent on].

Any idea?

Thank you very much.

[vim dotfiles]: https://github.com/vonpupp/dotfiles-vim
[installing UltiSnips using vundle]: https://github.com/vonpupp/dotfiles-vim/blob/f1088c1ec815482e0ee0242e68b155e6b86112c9/home/.vim/config/python-bundle.vim#L59
[klen/python-mode]: https://github.com/vonpupp/dotfiles-vim/blob/f1088c1ec815482e0ee0242e68b155e6b86112c9/home/.vim/config/python-bundle.vim#L10
[syntax on]: https://github.com/vonpupp/dotfiles-vim/blob/f1088c1ec815482e0ee0242e68b155e6b86112c9/home/.vim/config/colorscheme.vim#L3
[filetype plugin indent on]: https://github.com/vonpupp/dotfiles-vim/blob/f1088c1ec815482e0ee0242e68b155e6b86112c9/home/.vim/config/options.vim#L62

**Comment by geo909** [comment]
I think I have the same problem with neovim 0.1.7 and pathogen.

Here are the contents of a minimal init.vim

```
execute pathogen#infect()
syntax on
filetype plugin indent on
```

This with only the Ultisnips installed in my bundle directory in ~/.config/nvim, produces the following problem if I run :UltiSnipsEdit from neovim:

[![error.png](https://s28.postimg.org/v7qizzu4t/error.png)](https://postimg.org/image/igccthkcp/)

(The long dropbox path is because I have linked my ~/.config/nvim folder to that dropboxfolder)

**Comment by vonpupp** [comment]
I could solve the problem.

I had installed the `vim-ultisnips` package with `pacman` and also with `vundle` without noticing it.

@geo909: I suggest you to start a fresh minimal environment using vagrant and then troubleshoot. That is how I discovered the problem. I also migrated to vim-plug instead of vundle since it seems easier and more versatile.
