### ISSUE TITLE
Using regex in post_jump

### ISSUE THREAD

**Issue by ColinKennedy** [SirVer/ultisnips#809]
I have just shy of a hundred snippets that follow a very rigid pattern:

post_jump "snip.expand_anon(get_dunder_method_snippet(name='str'))"
snippet "def \_\_str\_\_" "a generic dunder factory" rb
endsnippet

post_jump "snip.expand_anon(get_dunder_method_snippet(name='rmul'))"
snippet "def \_\_rmul\_\_" "a generic dunder factory" rb
endsnippet

The only part that varies in this case is the actual snippet definition, "def \_\_(.+)\_\_" and in the area for post_jump, where "name" would ideally gets passed whatever was matched in the snippet definition. Currently, I have every Python dunder method defined like this and I'd love to just get it down to one regex-powered snippet to handle all of this. 

I'm sure the solution is simple but I just can't seem to figure it out. Can you please point me in the right direction?

**Comment by seletskiy** [comment]
@ColinKennedy: somewhat ugly, but try this:

```
context "snip.context = {'name': None}"
post_jump "print(snip.context['name'])"
snippet "def __(.*)__" "regexp def" br
`!p snip.context['name'] = match.group(1)`
endsnippet
```

**Comment by ColinKennedy** [comment]
Hey, this worked perfectly, thank you so much!
