### ISSUE TITLE
UltiSnips for code generation

### ISSUE THREAD

**Issue by gergap** [SirVer/ultisnips#810]
Hi guys,

I have a question which is more related to vim than Ultisnups itself. Maybe somebody has a good idea.
What I'm doing at the moment is, that I have a snippet for a complete C file.
What I'm doing manually at the moement is creating a new buffer, trigger the snippet, enter the content for the placeholder and save the file. again and again.
If something in the snippet template was wrong, I have to start over.

I'm sure somehow it is possible to create a "source" buffer with content like this:
uint8_t
int8_t
uint16_t
int16_t
...
float
double
...

then let a smart script/macro do the steps above and insert the names from the "source" buffer and save the file with a name like int8.c, int16_t.
My approach would be to write a VimScript command which iterates over all lines in the "source" buffer and enter this for UltiSnips placeholders and to use this as filename.

Maybe somebody has a better, more simple and generic way of doing this. Maybe using :argdo?

regards,
Gerhard

**Comment by seletskiy** [comment]
@gergap: Ugly, but should do. Calling sophisticated code to modify buffer is tricky business.

```
:argdo py vim.command('exe "normal axxx\<C-R>=UltiSnips#ExpandSnippet()\<CR>\<Esc>:w\<CR>"')
```

Will expand `xxx` snippet in every argument you've passed to vim.

**Comment by gergap** [comment]
Great, this works!
Cool idea to use the evaluation register to glue the input together with the Ultisnips expand function.

The recipe now is as follows:
* populates args in vim, e.g. ":args foo.c bar.c"
this can be done also using wildcards by reading from file e.g. ":args `cat filelist.txt`"
* creates a snippet which uses python interpolation to extract the parameter from the file name
* use :argdo to expand the snippet in all files

Here is an example snippet:

```
snippet encoderdef "Encoder Definitions"
#ifndef _UAENCODER_${1/.*/\U$0\E/g}_H_
#define _UAENCODER_${1/.*/\U$0\E/g}_H_

#include <stdint.h>

/* forward declarations */
struct ua_encoder_context;
struct ua_decoder_context;
struct ua_buffer;
struct ua_${1:`!p snip.rv = re.sub(r'\..*', '', snip.fn)`};

int ua_encode_$1(struct ua_encoder_context *ctx, const struct ua_$1 *val);
int ua_decode_$1(struct ua_decoder_context *ctx, struct ua_$1 *val);
$0
#endif /* _UAENCODER_${1/.*/\U$0\E/g}_H_ */
endsnippet
```

Example execution:

I added "ggdG" to be able to start over if something goes wrong.

```
:argdo py vim.command('exe "normal ggdGaencoderdef\<C-R>=UltiSnips#ExpandSnippet()\<CR>\<Esc>:w\<CR>"')
```
