### ISSUE TITLE
ListSnippets not working 

### ISSUE THREAD

**Issue by anoopd** [SirVer/ultisnips#811]
My terminal won't allow the default mapping for listing snippets and i just changed the Settings as 

`let g:UltiSnipsListSnippets="<f5>"`

but when i tried to list snippets in insert mode by pressing f5 the error shown below emerged and after that it was just printing <F5>.

`UnicodeWarning: Unicode
 equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal`

I changed the mapping to 
`let g:UltiSnipsExpandTrigger="<C-a>"
let g:UltiSnipsListSnippets="<tab>"`

When i tried pressing 'tab' in insert mode it showed

`=UltiSnips#ExpandSnippet()`

and nothing else

I have no idea on what went wrong , thank you in advance for any help .

**Comment by seletskiy** [comment]
@anoopd: try latest master.

**Comment by anoopd** [comment]
Hi updated by cloning but with no effect  .......

**Comment by anoopd** [comment]
No i updated and it is working fine  ...... thank you
