### ISSUE TITLE
UltiSnips refuses to move to next tab stop after using YouCompleteMe semantic completion

### ISSUE THREAD

**Issue by ghost** [SirVer/ultisnips#822]
I am using UltiSnips together with YouCompleteMe, for writing C/C++ code. Both of the plugins work great, but whenever I am in the middle of a snippet (editing one of the tab stops), and I use YCM to, say, complete a field inside a struct, UltiSnips refuses to move to the next tab stop after that (maybe it considers the snippet complete??)

I am using `<tab>` for YouCompleteMe, and F12 as my key for UltiSnips.

To illustrate the problem, say I have a snippet like this:

```
snippet sc "strcmp"
strcmp($1, $2)
endsnippet
```

If I wanted to use it to write this:

```
strcmp(hello, world)
```

everything works fine. I type `sc`, press F12, snippet is expanded, cursor moves to `$1`, I write `hello`, press F12, cursor moves to `$2`, and I write `world`.

However, if I wanted to write something like:

```
strcmp(mystruct->label, other_label)
```

what happens is the following: I type `sc`, press F12, snippet is expanded, cursor moves to `$1`, I write `mystruct->`, the YCM completion menu shows up, I press `<tab>` to complete `label`, and then I want to move to the next tab stop, so I press F12 again, but nothing happens. The cursor stays where it is.

The problem only seems to occur with YCM completion menus for struct fields and such, and not with regular keyword completion; i.e I can type `co` and press `<tab>` to autocomplete `const`, and then UltiSnips still works fine, but when I am using semantic completion from YCM, UltiSnips breaks. Also,
when the YCM completion menu appears after I type `->`, I can still press F12 and move to the next tab stop successfully, as long as I haven't yet pressed `<tab>` to complete the struct field. Hence, the problem seems to be triggered by the completion operation when I press `<tab>`, rather than the displaying of the YCM completion menu.

My UltiSnips configuration options in my `~/.vimrc` are:
```
let g:UltiSnipsExpandTrigger="<F12>"
let g:UltiSnipsJumpForwardTrigger="<F12>"
let g:UltiSnipsJumpBackwardTrigger="<s-F12>"
```

I have not set any configuration options for YCM.

I have no idea what is causing this or how to fix it. Any ideas will be appreciated.

P.S: I didn't know if it was more appropriate to report this issue on the UltiSnips issues page or on the YCM issues page, so I am just posting it here.

**Comment by mseabold** [comment]
FWIW, this seems to be caused by YCM opening the preview window. A workaround would be either to configure YCM to not open the preview, or to change UltiSnips to remove preview from completeopt temporarily while snippet completion is active (which will stop YCM from opening the preview while in a snippet).

**Comment by andreyorst** [comment]
While I'm not using YCM, I'd like to say that using deopete dont prevent me form jumping to next tabstop, after popup. So issue may be realted to YCM only.  Con you please provide a docker repo, as described in [CONTRIBUTING.md#reproducing-bugs](https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs)?

**Comment by mseabold** [comment]
Do you have preview enabled in your completeopt? This is the root cause of the issue that I have seen (and have a workaround for. See the reference PR above)

**Comment by andreyorst** [comment]
Oh, that preview. I've misunderstood it, I thought that discussion about complete popup. 
> I write mystruct->, the YCM completion menu shows up, I press <tab> to complete label, and then I want to move to the next tab stop, so I press F12 again, but nothing happens.

No, preview was the first thing that I disabled as useless distracting piece of completion plugin, that should be lightning fast fuzzy as i type completion, and do not open any distracting windows anywhere that moves my code oh hides it from the eyes. So yes, no preview window. I've already forgot about this _"feature"_. Well when you open splits, Ultisnips also forgotens all the tabstops. Same issue will be with opening tagbar or nerd tree for example.
