### ISSUE TITLE
UltiSnips jumps to end of snippet after final JumpForwardTrigger

### ISSUE THREAD

**Issue by partounian** [SirVer/ultisnips#825]
Whenever I use any snippet after the last JumpForwardTrigger when I push tab it takes me to the end of the snippet. This is problematic when I try to use deoplete for autocompletion. My apologies if this is a dumb question, I couldn't find anything to see if this was the default behavior or if there is a setting for that.

My configuration for Deoplete and UltiSnips
```
" Let <Tab> also do completion
inoremap <silent><expr><Tab>  pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <silent><expr><s-tab> pumvisible() ? "\<C-p>" : "\<Tab>"
" Close the documentation window when completion is done
autocmd InsertLeave,CompleteDone * if pumvisible() == 0 | pclose | endif
" Allow UltiSnips to work with Deoplete
call deoplete#custom#set('ultisnips', 'matchers', ['matcher_fuzzy'])

let g:UltiSnipsExpandTrigger="<C-e>"
let g:UltiSnipsJumpForwardTrigger="<tab>"                                
let g:UltiSnipsJumpBackwardTrigger="<s-tab>" 
```

**Comment by seletskiy** [comment]
@partounian: If it's reproduceable only with using deoplete, you should fill appropriate issue in deoplete project.
