### ISSUE TITLE
ultisnips doesn't work with :set paste

### ISSUE THREAD

**Issue by doctorguile** [SirVer/ultisnips#826]
I found it by trial and error 

http://stackoverflow.com/questions/14896327/ultisnips-and-youcompleteme

I always have :set paste as I hate vim reformatting pasted content

however this prevents ultisnips from triggering.

Is this a limitation or there's a work around?

Thanks

**Comment by seletskiy** [comment]
@doctorguile: all mappings in insert mode are disabled (`:h paste`):

```
        When the 'paste' option is switched on (also when it was already on):
                - mapping in Insert mode and Command-line mode is disabled
```
