### ISSUE TITLE
[question] How can I expand even in a string?

### ISSUE THREAD

**Issue by ddickstein** [SirVer/ultisnips#832]
I have a snippet that expands correctly with the trigger `foo`, but if `foo` is in a string then the snippet will not expand.  This might be by design, but how can I disable this behavior for this snippet in particular, which I do want to expand inside strings?

`foo<TAB>` -> expands
`'foo<TAB>` -> does not expand

**Comment by ddickstein** [comment]
Seems like this can be done with regex.  Is that the right approach?

**Comment by dqgthb** [comment]
I guess you are talking about option 'i'?
snippet foo "foo" i 
read docs.txt about options (b, i, r, n, etc.)

**Comment by seletskiy** [comment]
@dqgthb is right.
