### ISSUE TITLE
feature request: add syntax to modeline

### ISSUE THREAD

**Issue by shibumi** [SirVer/ultisnips#834]
Hello,
it would be useful if you would add `syntax` to the vim modeline ultisnip.

**Comment by seletskiy** [comment]
@shibumi: Can you elaborate? I don't quite understand what do you mean, exactly?

**Comment by shibumi** [comment]
I mean that the snippet `modeline` should substitute to something like this:

`vim:set et sw=4 ts=4 tw=72 syntax=sh`

when I have set the syntax in the file manually..

**Comment by seletskiy** [comment]
@shibumi: I still don't quite get it. What do you mean by "snippet modeline"? Do you mean '*.snippet' file? If so, it will be very misleading setting it's syntax to `sh` or whatever else.

**Comment by polyzen** [comment]
https://github.com/honza/vim-snippets/blob/master/UltiSnips/all.snippets#L72

**Comment by shibumi** [comment]
@seletskiy https://github.com/honza/vim-snippets/blob/master/UltiSnips/all.snippets#L72 thats what I mean..

**Comment by shibumi** [comment]
@seletskiy why was this closed now?

**Comment by seletskiy** [comment]
@shibumi: Because I thought that you've been talking about modeline snippet. If no, then I still don't get what do you want, so either describe it or create pull request.
