### ISSUE TITLE
'SnippetUtil' object has no attribute 'column'

### ISSUE THREAD

**Issue by ap-0** [SirVer/ultisnips#835]
I am getting above error when playing around with a snippet that looks like this:
```
snippet foo
#`!p snip.rv = '-' * (80 - snip.column)`
endsnippet
```

The UltiSnips [documentation](https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt) (chapter 4.9) states that the global variable `snip` has the property `column` - yet I get a `AttributeError` exception thrown. I am doing something wrong? 

I am using UltiSnips with Python3. 

If the property is no longer available, is there another way to get the column number when the snippet was triggered? 

I have tryed the same with vim script code. But it caused odd behaviour.

**Comment by ap-0** [comment]
I have found a different way to get the current column of the cursor
```
snippet foo
#`!p snip.rv = '-' * (80 - vim.current.window.cursor[1])`
endsnippet
```

**Comment by seletskiy** [comment]
@ap-0: `snip.column`, which is described in the chapter 4.9 is only accessible from context expression (chapter 4.9 is called 'Context snippets').

I agree that it's quite easy to misunderstand documentation on that behalf.

**Comment by cuppajoeman** [comment]
For anyone else having this issue type `:help python` in vim for more information about what is available
