### ISSUE TITLE
better handling of supported python versions

### ISSUE THREAD

**Issue by yaojingguo** [SirVer/ultisnips#836]
I am using macvim 8.0.237 on MacOS 10.12.2 which preinstalls Python 10.12.2. After I used brew to install Python3, macvim GUI exits every time I issue `o` in vi normal mode. 

After spending several hours digging around, I found that the cause is the ultisnips' handling of python versions. macvim is not compiled by python3 support. But ultisnips recognizes Python3 installed by brew. 

Adding `let g:UltiSnipsUsePythonVersion = 2` to `.vimrc` solves this problem.

I think that it is better to show some error message instead of exit vim where there is some problem with the handling of Python version.

**Comment by seletskiy** [comment]
@yaojingguo: If vim 'exits immediately', it's possible crash in vim, not in ultisnips. Try to run console version of vim and see if there's any crash dump.

**Comment by yaojingguo** [comment]
@seletskiy Yes, it might be the problem of vim. But adding `let g:UltiSnipsUsePythonVersion = 2` to `.vimrc` solves my problem.

I find crash dumps in `~/Library/Logs/DiagnosticReports`.

**Comment by andreyorst** [comment]
Closing as solved. Reopen if needed

**Comment by SirVer** [comment]
See https://github.com/SirVer/ultisnips/issues/771#issuecomment-377815616. The crash likely happens because you try to load python2 and python3 in MacVim.
