### ISSUE TITLE
Conflicts with own `<tab>` maps in visual and/or select mode

### ISSUE THREAD

**Issue by unclechu** [SirVer/ultisnips#838]
I have my own hooks for `<tab>` in *visual* and *select* modes:
```viml
xnoremap <tab> <esc>
snoremap <tab> <esc>
```
**UltiSnipts** overwrites my `<tab>` map for *select* mode, so I disabled maps that came out-of-the-box:
```viml
let g:UltiSnipsExpandTrigger = "<Nop>"
let g:UltiSnipsListSnippets = "<Nop>"
```
But **UltiSnips** also trying to do `unmap` for my `<tab>` map even if it is set to different key, so I found a way to disable it too:
```viml
let g:UltiSnipsRemoveSelectModeMappings = 0
```
And I set this map that I found in **UltiSnips** sources:
```viml
inoremap <silent> <Tab> <C-R>=UltiSnips#ExpandSnippet()<CR>
```
But now if I press `<tab>` in insert mode without any snippet it doesn't insert indentation that normally happens as expected when I keep default settings of **UltiSnips**. My question is: how it's done? How I can copy that behavior with my own mapping avoiding conflicts with my `<tab>` maps?

**Comment by unclechu** [comment]
I believe unmapping happens [here](https://github.com/SirVer/ultisnips/blob/7549874758117f31609550c4fc60fe9497f12068/pythonx/UltiSnips/_vim.py#L269-L285). There keys including `<tab>` is hardcoded there.

**Comment by seletskiy** [comment]
@unclechu: Try to remove `<Nop>` assignments and remap keys you want with `map`.

**Comment by unclechu** [comment]
@seletskiy as I explained, my own remap will stop work in *select* mode in this case after I expand my first snippet. Look at the [link](https://github.com/SirVer/ultisnips/blob/7549874758117f31609550c4fc60fe9497f12068/pythonx/UltiSnips/_vim.py#L269-L285) I left earlier, it actually unmaps `<tab>` for *select* mode.

**Comment by unclechu** [comment]
@seletskiy anyway, if I keep `let g:UltiSnipsExpandTrigger = "<tab>"` unchanged along with my own maps when I select something and press `<tab>` it removes selected chunks and goes insert mode, like if I select something and press `c`.

**Comment by unclechu** [comment]
@seletskiy I [solved](https://github.com/unclechu/neovimrc/commit/21fc11416603fe96a74cf0429c2a199336d7943a) it, I have used solution from [this opened PR](https://github.com/SirVer/ultisnips/pull/790). I'd close this for myself since I solve my personal issue, but I think it kinda bug that **UltiSnips** unmaps hardcoded keys ([see](https://github.com/SirVer/ultisnips/blob/7549874758117f31609550c4fc60fe9497f12068/pythonx/UltiSnips/_vim.py#L269-L285)) even if I remap these keys to another. Also may be it should support optional maps for specific modes by settings. I'd prefer for example to just disable mapping (and unmapping) for `<tab>` in *visual* and *select* modes to solve my issue.

**Comment by andreyorst** [comment]
I'd rather close this issue as solved, because there is no point in issues that are just hanging around, but since there may be some design flaws, I wont do this. @SirVer Can you invesigate the problem here: https://github.com/SirVer/ultisnips/blob/8ec3a61ce80570d5ee73d4d3f8acfc81bce2b59d/pythonx/UltiSnips/_vim.py#L283-L297
Seem that it may cause problems to some users. I can't decide if is it a design flaw, or decided behavior.

**Comment by SirVer** [comment]
Vim doesn't really make it easy to have optional different functionalities on the same key. What could work, potentially. This works:

~~~
let g:ulti_expand_res = 0
function! g:UltiSnips_Expandable()
  call UltiSnips#ExpandSnippet()
  return g:ulti_expand_res
endfunction

 inoremap <expr> <Tab> (g:UltiSnips_Expandable() > 0) ? "" : "\<Tab>")
~~~

> I think it kinda bug that UltiSnips unmaps hardcoded key

I am confused. You already found the 
[option to completely disable that](https://github.com/SirVer/ultisnips/blob/7549874758117f31609550c4fc60fe9497f12068/pythonx/UltiSnips/_vim.py#L236). Also, UltiSnips only ever unmaps select mode mapping, which most Vim users do not even know what it is and did not seem to have affected you in this issue besides OP.

> I'd prefer for example to just disable mapping (and unmapping) for <tab> in visual and select modes to solve my issue.

Which you also can do: `UltiSnipsMappingsToIgnore` is a list of keys [that will be ignored](https://github.com/SirVer/ultisnips/blob/7549874758117f31609550c4fc60fe9497f12068/pythonx/UltiSnips/_vim.py#L253) and not unmapped. You can just configure tab in there and everything should be fine too.

**Comment by unclechu** [comment]
> I'd rather close this issue as solved

So, that PR with `isExpandable` function is merged? Good, I'm using my own fork https://github.com/unclechu/my-ultisnips with just this PR merged for a long time, now I could switch to the main branch.

**Comment by unclechu** [comment]
@SirVer `UltiSnips#SnippetsInCurrentScope()` returns all the snippets I have when I run it after some space symbol, so `IsExpandable` solution from help (checking for `!empty(UltiSnips#SnippetsInCurrentScope())`) doesn't work as expected, or at least as I am expecting it to work.

**Comment by unclechu** [comment]
@SirVer May be add some flag to not show all the snippets on white-space characters?

**Comment by unclechu** [comment]
@SirVer I customized that function, works for me:
https://github.com/unclechu/neovimrc/commit/af90c0dc5467dce2bd266f2b8af4c867b4b12fb9#diff-caf0edba92b7a9ab60ae28f403823bd0R31
