### ISSUE TITLE
Expanding markdown `---` and `===` only results in newlines

### ISSUE THREAD

**Issue by linduxed** [SirVer/ultisnips#842]
Let's assume I've opened a markdown file that has the following contents:
```markdown
Some headline
---|
```
Assuming that the `|` character is where the cursor is positioned and I invoke the snippet expansion mapping, then the [`---`-snippet](https://github.com/honza/vim-snippets/blob/2e5f7adc40bc666bad7375357337149f7fe6e6f6/snippets/markdown.snippets#L80-L83) will be invoked and I would expect this result:
```markdown
Some headline
-------------

|

```
What I instead get is this:
```markdown
Some headline


|

```
The line where the dashes should have been entered has been cleared out completely, as if a `dd` was run, but no content was inserted.

All of the above also applies to the [`===`-snippet](https://github.com/honza/vim-snippets/blob/2e5f7adc40bc666bad7375357337149f7fe6e6f6/snippets/markdown.snippets#L74-L77).

I'm not sure when this started to be a problem, and after a decent amount of digging, I don't even know *what* has changed to make this break. All I know is that I'm certain that this has worked at some point during the last year. With that in mind, these are the things that I've tried with no improvement in behaviour:

* Reduced the NeoVim installation to basically nothing but `UltiSnips`, configuration for `UltiSnips` and `vim-snippets`.
* Did the same thing with the latest stable version of Vim.
* Checked out a version of `UltiSnips` from early 2016.
* Checked out a version of `vim-snippets` from about a year ago.
* Compiled and ran a version of NeoVim from October last year, December and a couple from this year.
* Compiled and ran the `master` branch of NeoVim.
* Various combinations of the above.

`UltiSnips#ExpandSnipped()` doesn't do anything in versions of NeoVim from before August/September 2016 (I didn't do a full bisect, so I don't know exactly when), so I assume there's some incompatibility going on there, so I didn't back up in history further than that.

If I go into Insert-mode, place the cursor after dashes and do `<C-r>=repeat('-', strlen...` (where the ellipsis is the rest of the snippet) then it works the way it should, so clearly the individual commands of the snippet seem to work.

**Comment by linduxed** [comment]
Do you have an idea what I could try to figure out what the problem is?

**Comment by linduxed** [comment]
I decided to dissect the two snippets, inspecting the return values of each function call and found something interesting. Take this snippet:
```viml
snippet ---
	`repeat('-', strlen(getline(line(".") - 1)) - strlen(getline('.')))`

	${0}

```
This snippet is four lines long. Assuming `test.md` looks as follows (and `|` is where the cursor is placed):
```markdown
Foobar
---|
```
...then during the evaluation of the snippet, since `line('.')` evaluates to the position of the cursor and the cursor will be positioned where `${0}` lies, the function will evaluate to `4`.

This means that the current code expects that `line('.')` evaluates to the line on which the `---` is positioned, which is incorrect.

The current code also has an additional error that is simply a redundancy:

Because of the fact that the cursor will be placed where `${0}` lies, this means that `getline('.')` will always return an empty string, meaning that ` - strlen(getline('.'))` always be subtracting zero (making it a pointless addition).

What makes this even more redundant is the fact that it seems like the first thing the current version of UltiSnips does is delete the snippet abbreviation (`---` in this case) and only thereafter it evaluates the snippet contents. This means that while the purpose of ` - strlen(getline('.'))` was surely to ensure that however long the headline was it should add three less `-` than that because there are already three `-` there. With the current version of UltiSnips, that line is empty: the `---` are not there. The entire subtraction is redundant.

**Comment by andreyorst** [comment]
Snippets works for me now. Seems like it was vim-snippets problem, and it was fixed. Feel free to reopen this if you still expirience it in some way
