### ISSUE TITLE
Multi javacript.snippets make swap buffers slow! Happen only in Neovim.

### ISSUE THREAD

**Issue by PangPangPangPangPang** [SirVer/ultisnips#846]
When I swap buffers in my javacript project, it takes 200ms to finish the task.Then I try to delete other javascript.snippets, vim perfroms as usual.

**Comment by PangPangPangPangPang** [comment]
I try to merge all the javascript file together, it still perform bad. For not affect swap buffer performance, can this plugin support async load?

**Comment by andreyorst** [comment]
Neovim is not currently supported.
