### ISSUE TITLE
Error raised when editing any CMakeLists.txt file

### ISSUE THREAD

**Issue by Daniel-M** [SirVer/ultisnips#862]
Hey everyone. 

## System
* Linux 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2 (2017-06-12) x86_64 GNU/Linux  
* Python 2.7 installed  
* Python 3.5 installed  
* Neovim 0.1.7,
```
NVIM v0.1.7
Build type: Dev
Compilation: /usr/bin/cc -Wconversion -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/home/damejia/Repositories/src/github.com/neovim/neovim/build/config -I/home/damejia/Repositories/src/github.com/neovim/neovim/src -I/home/damejia/Repositories/src/github.com/neovim/neovim/.deps/usr/include -I/home/damejia/Repositories/src/github.com/neovim/neovim/.deps/usr/include -I/home/damejia/Repositories/src/github.com/neovim/neovim/.deps/usr/include -I/home/damejia/Repositories/src/github.com/neovim/neovim/.deps/usr/include -I/home/damejia/Repositories/src/github.com/neovim/neovim/.deps/usr/include -I/home/damejia/Repositories/src/github.com/neovim/neovim/.deps/usr/include -I/usr/include -I/home/damejia/Repositories/src/github.com/neovim/neovim/build/src/nvim/auto -I/home/damejia/Repositories/src/github.com/neovim/neovim/build/include
Compiled by damejia@ibuki

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/damejia/Repositories/src/github.com/neovim/neovim/share/nvim"
```

## UltiSnips configuration
I use Neovim as editor. Installed `ultisnips` with `vim-snippets` using `vim-plug` using this combination for about a month and a half without problems.  Updated and tested errors before posting this issue.

## Issue
Opened a `CMakeLists.txt` file with `neovim` just to edit a line and when entered the insert mode it showed the following error,  

``` sh
An error occured. This is either a bug in UltiSnips or a bug in a
snippet definition. If you think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

Following is the full stack trace:
Traceback (most recent call last):
  File "/home/damejia/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 16, in wrapper
    return func(self, *args, **kwds)
  File "/home/damejia/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 151, in snippets_in_current_scope
    snippets = self._snips(before, True)
  File "/home/damejia/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 575, in _snips
    source.ensure(filetypes, cached=autotrigger_only)
  File "/home/damejia/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 47, in ensure
    self._load_snippets_for(ft)
  File "/home/damejia/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 80, in _load_snippets_for
    self._parse_snippets(ft, fn)
  File "/home/damejia/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 93, in _parse_snippets
    file_data = compatibility.open_ascii_file(filename, 'r').read()
  File "/home/damejia/.config/nvim/plugged/ultisnips/pythonx/UltiSnips/compatibility.py", line 28, in open_ascii_file
    return open(filename, mode, encoding='utf-8')
IsADirectoryError: [Errno 21] Is a directory: '/cmake/mathgl2'
```

Which makes editing any `CMakeLists.txt` impossible since the error constantly shows up. Tried editing a bare new `CMakeLists.txt` from scratch and the same error occurs. The error doesn't seem to affect `*.txt` files so is not related to the `txt` extension.
I'm not sure why `/cmake/mathgl2` appears at the end since in neither case I'm using it (though I have it installed on my system)

I'm open to any way I can help to fix this

**Comment by MarenstainBear** [comment]
@Daniel-M I know this is an old thread. For what it's worth, I was encountering a very similar error (and that's how I stumbled across your post). It occurred to me that I was attempting to point UltiSnips to a more limited snippets directory by using `let g:UltiSnipsSnippetDirectories=$HOME.'/.vim/UltiSnips'` in my .vimrc. Once I commented out this line in my .vimrc and let UltiSnips search through my directories looking for an UltiSnips directory, this error went away.

**Comment by Daniel-M** [comment]
@MarenstainBear In fact, I'm using Neovim and the variable `UltiSnipsSnippetDirectories` is set to `$HOME/.config/nvim/plugged/vim-snippets/UltiSnips` which is somewhat similar your configuration, since I have that location defined in my `init.vim`(the equivalent to `.vimrc` for NeoVim). 
I don't know what solved the problem, it has been several updates to UltiSnips in the mean time, so I'm going to mark the issue as closed :+1:
