### ISSUE TITLE
Selecting one more character when using ${VISUAL}

### ISSUE THREAD

**Issue by J3soon** [SirVer/ultisnips#863]
When selecting words in Vim's Visual-Mode, it will put one more character (which isn't selected) in the `${VISUAL}` placeholder.

**Demo:**

![vim-ultisnips](https://user-images.githubusercontent.com/20457146/27464386-d2c7e49a-57ff-11e7-8c03-63ecec5f5d39.gif)

I'm using Vim 8.0 on 64-bit Windows 10

The snippet I use is: 

    snippet bold "Bold in markdown"
    **${1:${VISUAL}}**
    endsnippet

**Comment by J3soon** [comment]
This problem doesn't exist on 64-bit Ubuntu 16.04...

**Comment by laxtiz** [comment]
when i use the commit before ur PR. all ok
after update ultisnips with ur PR, i will miss ends char when expand a snippet with a VISUAL placeholder.
i don't know why

![snip](https://user-images.githubusercontent.com/3883767/29489993-1d3b8c00-8561-11e7-8a81-82b267e9cd9c.gif)

gvim x64 8.0.678 on windows 10, with python 3.6.2

**Comment by J3soon** [comment]
@laxtiz, the gif you posted seems to work fine.
The end char is the one with the black cursor on it.
Can you explain the problem more detailed?

**Comment by J3soon** [comment]
The correct behavior is shown in [UltiSnips Screencast - Ep 3 - What's new in Version 2.0?](https://youtu.be/hKrrOevbrxY?t=235)

**Comment by laxtiz** [comment]
I took two pictures from the gif. 
I guess I probably know the reason

this pic is your:
![pr1 141](https://user-images.githubusercontent.com/3883767/29500647-4c0977fa-8655-11e7-9d6d-c43af9aa2aad.png)

and my:
![my 6](https://user-images.githubusercontent.com/3883767/29500658-5ec37684-8655-11e7-8875-4f4649f8ca5e.png)

why your curosr style is **LINE** when gvim in visual mode.
see `:h guicursor` plz.

**Comment by J3soon** [comment]
@laxtiz Oh, so that's the problem...
I'd changed my cursor style to block and tested it, I found out that the char with black cursor on won't be included when using `${VISUAL}`.
However, if you look closely when selecting a text, you'll see the black cursor is blinking, indicating that the char is not selected. The `ve` key combination can show that too.
I think the char with black cursor on isn't meant to be selected, correct me if I'm wrong.

**Comment by laxtiz** [comment]
did your changed the `'selection'` option to `exclusive`?
should better to see `:h :behave`
i test that option on windows and centos, it look like your gif.

i think you test it with `$VIMRUNTIME\mswin.vim`, that file contain `behave mswin` in line 17. it will change `'selection'` to `exclusive`.

so now, open your gvim,  update ultisnips to the last commit.
and execute `:behave xterm`, 
are you lost last char of ${VISUAL}?

the better solution is check option `'selection'`.
```python
import vim
if vim.eval('&selection') == 'exclusive':
    text = self.text[:-1]
else
    text = self.text
endif
````

@J3soon don't use any other config for test.
@seletskiy i will take a PR fix it

**Comment by J3soon** [comment]
Yes, that's the problem, the code should be changed to your version with the `selection` option check.
@laxtiz sorry for the inconvenience.
