### ISSUE TITLE
Is there a way to disable autotrigger temporarily for the current snippet?

### ISSUE THREAD

**Issue by lizhenguo** [SirVer/ultisnips#874]
For example, I have define a snippet as follows:
```
snippet ii "parenthesis" iA
(${1})${0}
endsnippet
```
So when I write `atoii`, it will expand to `ato()`.    
But I want to disable the expansion for `ii` temporarily when I insert the first `ii` snippet. So that I can write `atoiii` which expands to `atoi()`.

**Comment by seletskiy** [comment]
@lizhenguo: The only way I can imagine in your case is to use context function which will return false in case of well known exceptions, like this:

```
global !p
def exclude_functions(snip):
    exceptions = ['atoi']
    for e in exceptions:
        print(snip.buffer[snip.line][:snip.column])
        if snip.buffer[snip.line][:snip.column].endswith(e):
            return False
    return True
endglobal

context "exclude_functions(snip)"
snippet ii "parenthesis" iAe
(${1})${0}
endsnippet
```

**Comment by lizhenguo** [comment]
Thanks. @seletskiy . Maybe it's the only way for now. But for my need, excluding one pattern is not adequate. Because what I want is pressing two `i`s to be expanded to `()`. Then I won't press `Shift` key to relax my little finger to some extent.
