### ISSUE TITLE
Snippets expand with 8 character tab, ignoring vim settings

### ISSUE THREAD

**Issue by jmml97** [SirVer/ultisnips#879]
When expanding a snippet from honza/vim-snippets it expands with a tab of 8 characters instead of 4 which is what I have defined in `.vimrc`. If I change `softtabstop` to 8, it continues to expand with a tab of 8 characters. Here's my [`.vimrc`](https://gist.github.com/jmml97/5fbadc871e28a89bc171f42272d75249).

**Comment by PratikBhusal** [comment]
@jmml97 

On vim, check the help file for tabstop (`:h tabstop`). For you, you fall in a bad location between scenario 1 and scenario 2. Here is what I would recommend:

- Add the line `set shiftwidth=4` to your vimrc and (optionally) change `tabstop` to `8`.

Try it out and see if that fixes the issue.

**Comment by jmml97** [comment]
@PratikBhusal Oh, using `set shiftwidth=4` worked perfectly! I'm so dumb! Thank you very much!
