### ISSUE TITLE
Error detected while processing 

### ISSUE THREAD

**Issue by xavierartot** [SirVer/ultisnips#880]
I have this error, when I'm using it:
```
Error detected while processing /Users/xavier/.vim/bundle/ultisnips/autoload/UltiSni
ps.vim:
line    7:
E887: Sorry
Error detected while processing /Users/xavier/.vim/bundle/ultisnips/autoload/UltiSni
Error detected while processing function UltiSnips#TrackChange:
line    1:
E887: Sorry, this command is disabled, the Python's site module could not be loaded.
```

**Comment by andreyorst** [comment]
Please provide docker repo, or vimrc file, wich can be applied to fresh vim installation, and issue can be reproduced. Ideally see [CONTRIBUTING.md#reproducing-bugs](https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs)
