### ISSUE TITLE
UltiSnips tabstops doesn't work with formatoptions+=a

### ISSUE THREAD

**Issue by purpleP** [SirVer/ultisnips#885]
This options allows vim to reformat paragraphs while in insert mode. I use it in markdown.
In markdown when snippet is expanded it gets reformatted and my cursor is no longer on tabstops. I've added `setlocal formatoptions-=a` in `UltisnipsEnterFirstSnippet` and restoring it back on exiting from snippet but now paragraph isn't reformatted after exiting snippet.

**Comment by andreyorst** [comment]
Can't reproduce it. Please provide docker repo, or at least a vimrc and a md file to test. Please see [CONTRIBUTING.md#reproducing-bugs](https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs)
