### ISSUE TITLE
UltiSnips doesn't work in javascript files

### ISSUE THREAD

**Issue by GingerN** [SirVer/ultisnips#887]
Hello, I've read a lot of issues, but can't find solution. I'm new to vim and I don't really understand for what signs of failed bahaviour to look for. Maybe something is not loading.
I've also loaded vim-snippets. And now UltiSnips vim-snippets are not working with javascript, with php UltiSnips vim-snippets are working.

I'm working in Windows and I use Pathogen. At first, I've installed UltiSnips and it worked fine. What I remember me doing is that I've executed command :UltiSnipsEdit in .js file, but I didn't like the custom-snippet path, then I've changed in .vimrc variable g:UltiSnipsSnippetsDir to $HOME."\\.vim\\vimsnippets\UltiSnips" and saved empty file javascript.snippets to this dir. I think after that snippets stopped working.

Then I've tried many things. There were only one time js-snippets worked:
I've added this var let g:UltiSnipsSnippetDirectories=["UltiSnips", $HOME."\\.vim\\vimsnippets\\UltiSnips", "C:\Users\MyUserName\.vim\bundle\vim-snippets\UltiSnips"]
and the third path even not properly set. Also before that I've deleted my javascript.snippets file. Then I've reloaded vim, set UltiSnips settings in .vimrc higher in file and UltiSnips stopped working in javascript, after returning position, again - not working. I've tried different paths, commenting all UltiSnips settings out, workarounds. Nothing changes. Please help me solve this problem, maybe I'm missing something obvious.

Note: I have not understood ftdetect part of documentation, what if this is important.
My .vimrc file:

`
" Важное
set nocompatible

" Кодировка
set fileencoding=utf-8
set encoding=utf-8
set langmenu=en_US.UTF-8

" Pathogen
if has('win32') || has('win64')
  set runtimepath=$HOME/.vim,$VIM/vimfiles,$VIMRUNTIME,$VIM/vimfiles/after,$HOME/.vim/after
endif
execute pathogen#infect()

" Поиск и замена
set hlsearch
set smartcase
set ignorecase
"set gdefault
set incsearch

filetype off
filetype on
filetype plugin indent on

" Для плагинов
" UltiSnips
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsListSnippets="<c-tab>"
let g:UltiSnipsJumpForwardTrigger="<c-j>"
let g:UltiSnipsJumpBackwardTrigger="<c-k>"
set runtimepath+=$HOME/.vim/mysnippets
set runtimepath+=$HOME/.vim/bundle/vim-snippets
let g:UltiSnipsUsePythonVersion = 3
let g:UltiSnipsEditSplit="horizontal"
"let g:UltiSnipsSnippetDir="~/.vim/UltiSnips"
let g:UltiSnipsSnippetDirectories=["~/.vim/UltiSnips", "~/.vim/bundle/vim-snippets/UltiSnips", "UltiSnips"]

"Настройки вида
syntax on
set number
set showcmd
"set foldmethod=marker
"set foldmarker={{{,}}}
set showmatch
"set list
if has("gui")
    "set guioptions+=
    set guioptions-=m "menu bar
    set guioptions-=T "tool bar
    set guioptions-=r "scrollbar
    set guifont=Consolas:h12:cRUSSIAN:qDRAFT
endif
set visualbell
set cursorline
"Устанавливает вертикальную линию, полезно при написании чего-то, что требует ограниченной ширины строк
"set colorcolumn=80
"Установить обалсть видимости при скроллинге
set scrolloff=5
set wildmenu
set statusline=%f\ \ line:%l/%L\ col:%c\ %p%%\ %y

" Настройка цветовой схемы
if filereadable(expand("~/.vimrc_background"))
  let base16colorspace=256
  source ~/.vimrc_background
endif
"set background=dark
"colorscheme badwolf
set background=light
colorscheme papercolor

" Манипуляции
"при увеличении/уменьшении, цифры с 0 должны быть decimal
set nrformats-=octal

" Настройка окон, настройка автоматического изменения высоты
set winwidth=84
set winheight=5
set winminheight=5
set winheight=999

" Для использования русскоязычной раскладки в нормальном режиме
"В режиме normal раскладку можно оставить системной английской,
"а переключаться в режиме insert по клавишам ctrl+6, (ctrl+^)
set keymap=russian-jcukenwin 
set iminsert=0
set imsearch=0
set wrap
set linebreak
set showbreak=>\ 
set breakindent
set breakindentopt=shift:2

" Работа с типами файлов
"filetype on
"filetype indent on
"Чтобы работали индивидуальные настройки для разных типов файлов в
"$HOME/.vim/ftplugin/
"filetype plugin on

" Значения для настройки отсупов
set autoindent
set tabstop=4
set softtabstop=4
set shiftwidth=4
set smarttab
set expandtab
set smartindent

" Клавиши
let mapleader = "," "По умолчанию <leader> - это \
"Лишить возможности действовать клавишами стрелок
noremap <left> <nop>
noremap <right> <nop>
noremap <up> <nop>
noremap <down> <nop>
"Включить нормальное поведение backspace в режиме insert
set backspace=indent,eol,start
"Сбросить подсветку после поиска
nnoremap <leader><space> :noh<cr>
"Смена языка
inoremap <leader><leader> <c-^>
"Заставляет избегать специальных символов при поиске
"nnoremap / /\v
"vnoremap / /\v
"nnoremap ? /\v
"vnoremap ? /\v
"Копировать до конца строки
nnoremap Y y$

" Группирование автоматических команд
"Сорсить .vimrc файл сразу после сохранения
augroup vimscript
    autocmd!
    autocmd BufWritePost $MYVIRC source $MYVIMRC
augroup END

"Выравнивать файл при его открытии
autocmd BufRead,BufWritePre *.html normal gg=G
augroup HtmlCmds
    autocmd!
    " Окружить комментарием 
    autocmd Filetype html nnoremap <buffer> <leader>c I<esc>
augroup END

augroup JavaScriptCmds
    autocmd!
    "Окружить комментарием //
    autocmd Filetype javascript nnoremap <buffer> <leader>c I//<esc>
augroup END

" Папки сохранения служебных файлов
set backup
set backupdir=$HOME\\.vim\\backup//
"Директория для swap-файла
set directory=$HOME\\.vim\\tmp//
"set noswapfile
"Позволяет отменять изменения и после закрытия файла
set undofile
set undodir=$HOME\\.vim\undo//

" Функции
"Функция вставки tab при начале строки
"и автодополнении при символах
"function! InsertTabWrapper()
"    let col = col(".") - 1
"    if !col || getline(".")[col - 1] !~ '\k'
"        return "\<tab>"
"    else
"        return "\<c-n>"
"endfunction
"inoremap <tab> <c-r>=InsertTabWrapper()<cr>
"inoremap <s-tab> <c-p>
`

**Comment by GingerN** [comment]
I've decided to use Vundle and reinstall gvim. But now I get error while proceeding PluginInstall command. Message says that it is a error in file C:\Users\ИмяПользователя\.vim\bundle\ultisnips\plugin\UltiSnips.vim. Line 55. Unknown function: UltiSnips#map_keys#MapKeys.
UltiSnipsEdit command function and other no working.

Is it problem with Vundle or UltiSnips? Please help to solve this.

My .vimrc file:

`
"Start Vundle
set nocompatible
set directory=$HOME\\.vim\\tmp//            
filetype off                  

set rtp+=~/.vim/bundle/Vundle.vim
set rtp+=$HOME/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'SirVer/ultisnips'
Plugin 'honza/vim-snippets'
Plugin 'tpope/vim-surround'

call vundle#end()            " required
filetype plugin indent on    " required
"End Vundle

syntax on

if has('win32') || has('win64')
  set runtimepath+=$HOME/.vim,$VIM/vimfiles,$VIMRUNTIME,$VIM/vimfiles/after,$HOME/.vim/after,$HOME/.vim/bundle
endif

let g:UltiSnipsUsePythonVersion=2
"let g:UltiSnipsSnippetsDir = $HOME.'/.vim/bundle/vim-snippets/UltiSnips'
let g:UltiSnipsExpandTrigger="<c-tab>"
let g:UltiSnipsListSnippets="<c-l>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"
`

**Comment by SirVer** [comment]
This seems to be a configuration mistake, not an UltiSnips bug. 

> set directory=$HOME\.vim\tmp//

`$HOME` is likely not defined in windows. You probably want something like `%userprofile`. 

> "let g:UltiSnipsSnippetsDir = $HOME.'/.vim/bundle/vim-snippets/UltiSnips'

This should be a list, either with one entry (an absolute path) or many entries of a single word. Please see the docs.
