### ISSUE TITLE
Feature request:  recognize the v:completed_item.snippet and v:completed_item.snippet_trigger for completion snippet expansion

### ISSUE THREAD

**Issue by roxma** [SirVer/ultisnips#888]
Hi, I'm the author of [nvim-completion-manager](https://github.com/roxma/nvim-completion-manager) (NCM)

Currently NCM uses ultisnips for function parameter expansion, and [snippets expansions from language server](https://github.com/autozimu/LanguageClient-neovim/pull/121)

[My current approach is quite hacky](https://github.com/roxma/nvim-completion-manager/commit/15020d66b85fd490cf33b1165f964bed1b50010f#diff-59c4af9a83eaf19fed761697d121e1beR71)

In short, NCM injects the snippet into ultisnips. And it remembers to cleanup the injected snippet afterwards.

As discussed in https://github.com/Shougo/neosnippet.vim/issues/398#issuecomment-326472600

###  While this approach has some disavantages.

- NCM has no control over the priority where there's name collision of snippets
- The point where ncm removes the injected snippet is not elegant, yet, I haven't seen the use case where this approach fails.

### Here's my proposal:

Things would be a lot easier if a common convension is set up so that snippet engines recognize the `v:completed_item.snippet` and `v:completed_item.snippet_trigger`. 

- Other auto-completion plugins may integrate with snippet engine more easily.
- And there's no need to cleanup the snippet after completion.

The `snippet_trigger` is useful, for example, in ncm, the popup menu looks like this when there's a file named `datetime.noww`.  A more complicated situation would be non-parameter-expansion snippets.

```
from datetime import datetime

now = datetime.now
     |         now  [+] now(cls, tz=None) |
     |datetime.noww [ ] ~buf              |
```

The completion items are 
```
[{
    'word': 'datetime.now',
    'snippet':'now($1)$0',
    'snippet_trigger': 'now',
    'abbr': '         now'
},  {
    'word': 'datetime.noww'
}]
```

Notice that the `now` method is left-padded with `datetime.` to be merged with the items from filepath completion. Without `snippet_trigger`, the engine may not be able to know it should replace `now` instead  of `datetime.now`.

This is also related to https://github.com/neovim/neovim/issues/7179, since vim doesn't forward custom field name like `snippet` and `snippet_trigger`. Currently ncm also uses some dirty hack to get this to work.

**Comment by andreyorst** [comment]
@SirVer You should look into this.

**Comment by andreyorst** [comment]
I've actually tried NCM with ultisnips for function parameter expansion, and it feels superfluent. Despite that approach is quite hacky for now, I think this function seems worth supporting in the future.

**Comment by SirVer** [comment]
@roxma What do you require that https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L454, i.e. `UltiSnips#Anon` does not give to you? 

Especially, it seems unnecessary to register or unregister any snippets if you just want to expand them.

**Comment by svanharmelen** [comment]
Seems this is implemented/supported by `neosnippet` (using https://github.com/Shougo/neosnippet.vim/commit/7121b95c9e7e3b45143f006eff3f31c149196c7d), would be so nice to have `UltiSnips` support this as well...

**Comment by roxma** [comment]
Sorry for the late reply, `UltiSnips#Anon`  is enough for me. Thanks @SirVer
