### ISSUE TITLE
Mirror dropped?

### ISSUE THREAD

**Issue by nyarly** [SirVer/ultisnips#893]
I have this snippet:

```viml
snippet spy "Define a spy pair"
type (
	${1/.*/\l$0/}Spy struct {
		spy *spies.Spy
	}

	${1/.*/\l$0/}Controller struct {
		*spies.Spy
	}
)

func New${1}Spy() (${1}, ${1/.*/\l$0/}Controller){
	spy := spies.NewSpy()
	return ${1/.*/\l$0/}Spy{spy: spy}, ${1/.*/\l$0/}Controller{Spy: spy}
}
endsnippet
```

When I apply it, it works great...mostly.

The problem is that I the name of the function remains "NewSpy" - in other words, the `${1}` between `New` and `Spy` never triggers.

**Comment by lacygoill** [comment]
Try to remove the curly braces in the tabstop. In other words, replace this line:

    func New${1}Spy() (${1}, ${1/.*/\l$0/}Controller){

With this line:

    func New$1Spy() (${1}, ${1/.*/\l$0/}Controller){

**Comment by jakobkogler** [comment]
Smaller example, which doesn't work:

    snippet test
    ${1} ${1}
    endsnippet

@nyarly You can get it to work, if you change the line to `func New$1Spy() (${1}, ...` or `func New${1}Spy() ($1, ...`.

**Comment by nyarly** [comment]
@jakobkogler Thanks - that's exactly what I needed to do.
