### ISSUE TITLE
Expand with VISUAL loses last char in GVIM

### ISSUE THREAD

**Issue by vanabel** [SirVer/ultisnips#897]
It is wired that the following configuration works for vim in cygwin, but not works for gvim on windows 7.

```vim
" vim: fdm=marker fdl=0 fdls=0
" Check the operating system {{{
if !exists( 'g:os' )
  if has( 'win32' ) || has( 'win64' )
    let g:os  = 'Windows'
  elseif has( 'win32unix' )
    let g:os = 'Cygwin'
  else
    let g:os  = substitute( system( 'uname' ), '\n', '', '')
    "g:os = Windows,Cygwin,Darwin,Linux
  endif
endif
" }}}
" User's variable {{{
" $VIMHOME {{{
if g:os != 'Windows'
  let  $VIMHOME = expand( $HOME . '/.vim/' )
else
  let $VIMHOME = expand( $HOME . '/vimfiles/' )
endif
" }}}
" $USRVIMD {{{
let $USRVIMD    =expand( $VIMHOME.'myvim/' )
" }}}
" }}}
" Plugin admin {{{
call plug#begin( $USRVIMD . 'plugged' )
" for snips
Plug 'Sirver/ultisnips'
call plug#end()
" }}}
" Configuration for Ultisnips {{{
set rtp +=$USRVIMD
let g:UltiSnipsSnippetsDir = $USRVIMD. 'UltiSnips'
" }}}
" Set tex as default formart {{{
au VimEnter,BufEnter *.tex set ft=tex
" }}}
```
Sorry for the redundant code, which makes vimrc fold correctly. I also add a system detect function, which will use plugin directory correctly. The plug manager is vim-plug.

If we only concern with UltiSnips, the above vimrc install it and set the Snippets directory, in which I have a `tex.snippets` containing only one snippet:

```vim
snippet frac "Fraction" wA
\frac{${1:${VISUAL:nom}}}{${2:denom}}
endsnippet
```

I test it with a new file called `test.tex`, in which I type `frac`, idearly which will expand to `\frac{nom}{denom}`, it is the case on cygwin's vim while it expands to `\frac{no}{denom}`, i.e., `nom` losses the last char, I can't figure why? is it a bug?

**Comment by asknet** [comment]
i'm facing the same issue in windows. I guess, it is something with line endings(CRLF)

**Comment by asknet** [comment]
After further reasearch, this is breaking in windows due to this incomplete fix
https://github.com/SirVer/ultisnips/issues/863

IMHO, above fix needs to rollback until there is a complete fix for handling vim option `selection`.

**Comment by SirVer** [comment]
fixed in linked PR.
