### ISSUE TITLE
Tab trigger in chars forms, such as "#!" for python file header, not working

### ISSUE THREAD

**Issue by xhchrn** [SirVer/ultisnips#898]
In vim-snippets' UltiSnips' 'python.snippets' file, the default snippet for python header is not working.

```
#! header
snippet #! "Shebang header for python scripts" b
#!/usr/bin/env python
# -*- coding: utf-8 -*-
$0
endsnippet
```

However,
  - if I change 'b' option to 'A', the snippet will expand automatically;
  - if I change the trigger to things like 'header', the trigger works well.

Similar things happened for '$$' trigger that I tried to set in tex file editing.

**Comment by andreyorst** [comment]
I've tried to open python file `test.py` entered `#!` and pressed my expand keybind. It expands normally.
Snippet definition:
```
#! header
snippet #! "Shebang header for python scripts" b
#!/usr/bin/env python
# -*- coding: utf-8 -*-
$0
endsnippet
```

As for tex: i didn't find the `$$` trigger in ultisnips and snipmate snippets
