### ISSUE TITLE
Some bug in UltiSnips

### ISSUE THREAD

**Issue by xahon** [SirVer/ultisnips#899]
I tried to expand `scu` react snippet, but i already had `honza/vim-snippets` and `justinj/vim-react-snippets`. US asked me that:

> 1: (scu) (/home/ilya/.vim/plugins/vim-snippets/snippets/javascript/javascript-react.snippets:76)                                                                                                           
> 2: (scu) (/home/ilya/.vim/plugins/vim-react-snippets/snippets/javascript.snippets:89)                                                                                                                      
> Type number and <Enter> or click with mouse (empty cancels):

I've typed `1`:

> An error occured. This is either a bug in UltiSnips or a bug in a
> snippet definition. If you think this is a bug, please report it to
> https://github.com/SirVer/ultisnips/issues/new.
> 
> Following is the full stack trace:
> Traceback (most recent call last):
>   File "/home/ilya/.vim/plugins/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 16, in wrapper
>     return func(self, *args, **kwds)
>   File "/home/ilya/.vim/plugins/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 138, in expand_or_jump
>     rv = self._try_expand()
>   File "/home/ilya/.vim/plugins/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 718, in _try_expand
>     self._do_snippet(snippet, before)
>   File "/home/ilya/.vim/plugins/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 624, in _do_snippet
>     self._setup_inner_state()
>   File "/home/ilya/.vim/plugins/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 380, in _setup_inner_state
>     _vim.command('silent doautocmd <nomodeline> User UltiSnipsEnterFirstSnippet')
>   File "/home/ilya/.vim/plugins/ultisnips/pythonx/UltiSnips/_vim.py", line 116, in command
>     return as_unicode(vim.command(as_vimencoding(cmd)))
> vim.error: Vim(call):E117: Unknown function: autocomplete#setup_mappings

After that US doesn't work anymore. Okay, let's reload vim and tried again with `2`

After I type 2:

> An error occured. This is either a bug in UltiSnips or a bug in a
> snippet definition. If you think this is a bug, please report it to
> https://github.com/SirVer/ultisnips/issues/new.
> 
> Following is the full stack trace:
> Traceback (most recent call last):
>   File "/home/ilya/.vim/plugins/ultisnips/pythonx/UltiSnips/err_to_scratch_buffer.py", line 16, in wrapper
>     return func(self, *args, **kwds)
>   File "/home/ilya/.vim/plugins/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 138, in expand_or_jump
>     rv = self._try_expand()
>   File "/home/ilya/.vim/plugins/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 718, in _try_expand
>     self._do_snippet(snippet, before)
>   File "/home/ilya/.vim/plugins/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 624, in _do_snippet
>     self._setup_inner_state()
>   File "/home/ilya/.vim/plugins/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 380, in _setup_inner_state
>     _vim.command('silent doautocmd <nomodeline> User UltiSnipsEnterFirstSnippet')
>   File "/home/ilya/.vim/plugins/ultisnips/pythonx/UltiSnips/_vim.py", line 116, in command
>     return as_unicode(vim.command(as_vimencoding(cmd)))
> vim.error: Vim(call):E117: Unknown function: autocomplete#setup_mappings

I don't think that both plugins is buggy. So i think it's US bug

`vim --version`:
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
Included patches: 1-1689
Extra patches: 8.0.0056
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org

`US` is latest
Installed using `Plug`

**Comment by SirVer** [comment]
Please post a minimal vimrc reproducing the problem.
