### ISSUE TITLE
How to avoid newline with VISUAL?

### ISSUE THREAD

**Issue by mMontu** [SirVer/ultisnips#908]
Is it possible to avoid including a new line when using the visual placeholder (`${VISUAL}`)?
For example, using the following snippet in a robot file, from [vim-snippets](https://github.com/honza/vim-snippets/blob/master/UltiSnips/robot.snippets#L132):

```
snippet wuks "Wait Until Keyword Succeeds"
Wait Until Keyword Succeeds    ${1:10x}    ${2:2s}    ${3:${VISUAL:Some Keyword}}
endsnippet
```

Starting with the following text,

```
        aaa
        bbb
        ccc
```

, after visually selecting the `bbb` and typing <tab>wuks I'd like to have this
  
```
        aaa
        Wait Until Keyword Succeeds    10x    2s    bbb
        ccc
```
  
```
instead of

        aaa
        Wait Until Keyword Succeeds    10x    2s    bbb

        ccc

```

**Comment by andreyorst** [comment]
Fixed by #926
