### ISSUE TITLE
Enhancement Request

### ISSUE THREAD

**Issue by IstiCusi** [SirVer/ultisnips#909]
Dear developers, 

a great feature would be to have not only default values for the jump positions but also options from 
a list. AKA: My name is ${1:Susi <Rudi, Leo, Hans, Franz, Fish>}

Kind regards, 
Stephan

**Comment by lacygoill** [comment]
@IstiCusi I think you can do this with the following code:

    global !p
    def complete(base, candidates):
        if base:
            candidates = [ m[len(base):] for m in candidates if m.startswith(base) ]
        if len(candidates) == 1:
            return candidates[0]
        return '[' + '|'.join(candidates) + ']'
    endglobal
    
    snippet name "" bm
    My name is $1`!p snip.rv = complete(t[1], ['Susi', 'Rudi', 'Leo', 'Hans', 'Franz', 'Fish'])`
    endsnippet

**Comment by SirVer** [comment]
Closing as answered. Thanks @lacygoill !
