### ISSUE TITLE
Add a command to adapt an existing snippet

### ISSUE THREAD

**Issue by languitar** [SirVer/ultisnips#910]
Sometimes I am pretty fine with an existing snippet (for instance from vim-snippets), but I want to adapt it slightly. In that case it would be nice there was a command which automatically copies the definition over to my local modifications file (usually opened with `:UltiSnipsEdit`) and places the cursor in there so that I can start modifying the snippet without having to look it up first.

**Comment by i-give-up** [comment]
I wanted a quick way to view a snippet's definition and ended up writing [a user-defined command](https://gist.github.com/i-give-up/ee3d2ea47d0311042dd366fabf680944) to do that. It should be fairly straightforward to go from there to copying the definition to your private snippet file, I think.

**Comment by SirVer** [comment]
This is out of scope for ultisnips, i.e. I consider this to fringe a feature to implement & support it. Thanks for the suggestion though!

**Comment by languitar** [comment]
So if I have to adapt for instance the template for a new python method to the code style of certain projects, what would be your proposed solution to achieve this? I wouldn't be able to remember the snippet name with variations for three different code styles.

**Comment by SirVer** [comment]
@languitar Here are two ways I achieve this, depending on what is more appropriate:

1) just use the same snippets and use automatic code formatting after the fact. I use this for golang, python (black formatter), rust, C and C++ projects.

2) Use project specific snippets. I add new entries into `b:UltiSnipsSnippetDirectories` or `g:UltiSnipsSnippetDirectories` and have for example `~/.vim/UltiSnips_lyft` or `~/.vim/UltiSnips_google` directories that contain specific snippets.

Besides, using `:UltiSnipsEdit!` with a bang is usually a reasonably quick way to find the snippet you are interested in for copy & pasting.
