### ISSUE TITLE
Is it possible to filter the snippet completion  list by filetype?

### ISSUE THREAD

**Issue by michael-coleman** [SirVer/ultisnips#911]
So for example, if you are in a php ( or any filetype which has multiple snippet files associated with it) and you want completion for a partial trigger, e.g. the line of text might be

    call<C-l>
        ^^^ get list of matching snippets beginning with `call`

This will generate a list of matching snippets from PHP  but you will also get matching snippets for 

* html
* sql
* all

I know that in general this is what you want, but I was wondering if  there anyway to filter or momentarily disable completion listings for the filetypes you are not interested in at that point in time?

**Comment by lacygoill** [comment]
I'm not sure this is what you want, but you could try this:

    ino  <silent>  <c-l>  <c-r>=<sid>list_snippets_for_current_ft_only()<cr>

    fu! s:list_snippets_for_current_ft_only() abort
        if empty(UltiSnips#SnippetsInCurrentScope(1))
            return ''
        endif
        let word_to_complete = matchstr(strpart(getline('.'), 0, col('.') - 1), '\S\+$')
        let l:Is_relevant = {i,v ->
        \      stridx(v, word_to_complete)>=0
        \&&    matchstr(g:current_ulti_dict_info[v].location, '.*/\zs.\{-}\ze\.') ==# &ft}
        let l:Build_info = { i,v -> {
        \     'word': v,
        \     'menu': '[snip] '. g:current_ulti_dict_info[v]['description'],
        \     'dup' : 1,
        \ }}
        let candidates = map(filter(keys(g:current_ulti_dict_info), l:Is_relevant), l:Build_info)
        let from_where = col('.') - len(word_to_complete)
        if !empty(candidates)
            call complete(from_where, candidates)
        endif
        return ''
    endfu

**Comment by fenetikm** [comment]
This works awesomely - thanks @lacygoill .

**Comment by SirVer** [comment]
Closed as answered. Thanks @lacygoill !
