### ISSUE TITLE
can not exapnd snips

### ISSUE THREAD

**Issue by R7R8** [SirVer/ultisnips#914]
Sorry to ask one questions. Thank you very much.

When I type ```errp```, and type ```shift+tag```, it just select ```errp <snip> Error panic```, but does not expand the snip.

Below is my configuration.
my ~/.vimrc configuration is just below
```
 92 let g:UltiSnipsExpandTrigger = "<s-tab>"
 93 let g:UltiSnipsJumpForwardTrigger = "<c-b>"
 94 let g:UltiSnipsJumpBackwardTrigger = "<c-z>"
```

Excecute ```verbose imap <s-tab>?```, vim shows
```
i  <S-Tab>     * pumvisible() ? "\<C-P>" : "\<S-Tab>"
        Last set from ~/.vim/bundle/YouCompleteMe/autoload/youcompleteme.vim
```

**Comment by Shougo** [comment]
Because `<S-Tab>` mapping is already overwritten by YouCompleteMe.
It is not UltiSnips issue.

**Comment by R7R8** [comment]
Thank you for your reply.
it's a vim-go-tutorial's problem. 
https://github.com/fatih/vim-go-tutorial/issues/47
