### ISSUE TITLE
use word instead of WORD

### ISSUE THREAD

**Issue by GCorbel** [SirVer/ultisnips#915]
Hello,

I have this snippet : 

```
snippet blabla
Hi
endsnippet
```

When is type `blabla<c-tab>` I have `Hi` which is what I want but when I do `console.log(blabla<c-tab>`  the completion is not triggered so I have `console.log(blabla`. I have to add a space to trigger the completion.

I checked in the code but I didn't understand how to fix that.

Is there a way to do that ?

**Comment by Shougo** [comment]
https://github.com/SirVer/ultisnips/blob/6d2a2b81cd24d5360c9af36ec8b0aa11983a2faf/doc/UltiSnips.txt#L690

**Comment by GCorbel** [comment]
It works thanks.
