### ISSUE TITLE
Deadly SEGV

### ISSUE THREAD

**Issue by natemarks** [SirVer/ultisnips#916]
I have 
let g:UltiSnipsListSnippets="<s-tab>"
when i open a .py file and look at the snippet list, then hit <esc> to get out of it I get a deadly SEGV

**Comment by SirVer** [comment]
Please post a minimal, complete vimrc to repro that problem and the exact keystrokes you run to create the crashs.

**Comment by SirVer** [comment]
Likey https://github.com/SirVer/ultisnips/issues/771#issuecomment-377815616. Closing.
