### ISSUE TITLE
Endsnippet is missing from the snip + <tab> autocompletion

### ISSUE THREAD

**Issue by andrewhylee** [SirVer/ultisnips#918]
Hello!

I have this problem of endsnippet not appearing when I try the snip + <tab> completion in the :UtilSnipsEdit.

![endsnippet-missing](https://user-images.githubusercontent.com/34400321/33797339-33715b7e-dcd4-11e7-9e94-134dc919a338.gif)

This is my vimrc:
`execute pathogen#infect()
let g:UltiSnipsSnippetDirectories = ['~/.vim/bundle/UltiSnips', 'UltiSnips']`

please let me know if you need anything else!

**Comment by pandude** [comment]
@andrewhylee perhaps it's snippets from vim-snippets, see [this](https://github.com/honza/vim-snippets/blob/master/snippets/snippets.snippets#L2)

**Comment by pandude** [comment]
@andrewhylee use `usnip` instead of `snip` if you want to use UltiSnips format

https://github.com/honza/vim-snippets/blob/master/UltiSnips/snippets.snippets#L5
