### ISSUE TITLE
More than one ${VISUAL}

### ISSUE THREAD

**Issue by gilfuser** [SirVer/ultisnips#920]
Hi.
First of all, thank for sharing your plugin with the world. I'm a Vim beginner and I feel lucky to have found it soon enough. I'm sticking with it to make some live-coding using Tidal Cycles really fast.
Second, sorry for using this space to make a question rather then reporting a bug. I couldn't find a proper communication channel for that.

I would like to ask you if there is a way to have more than one piece of text or code in - probably - different buffers and when expanding a snippet using also more than one ${VISUAL}, to have them inserted in the respective places.

best regards,
Gil

**Comment by SirVer** [comment]
Vim does not support more than one visual selection. But you can yank into registers and access these registers in a python interpolation block.
