### ISSUE TITLE
$VISUAL placeholder is cut off by one character

### ISSUE THREAD

**Issue by ap-0** [SirVer/ultisnips#921]
Hello.

for the following simple snippet example:
```
snippet foo
if foo: ${1:${VISUAL:bar}}
endsnippet
```
the placeholder `bar` (or any other) will lose it's last character. Expanden it looks like
`if foo: ba`

In some situations I have snippets where I would like to keep the placeholder when I have no visual text selected. 

I am on Windows using Vim8.0 and Python 3.6.4. UltiSnips is the latest version updated today with Vundle.

I have found this commit that removes the last character for windows. But I do not know the reason
https://github.com/SirVer/ultisnips/commit/5a7ec5cea2824f443fbd9b70f67ab67fd8b47a54

**Comment by SirVer** [comment]
Should be fixed in latest master.
