### ISSUE TITLE
vmap for <tab> is overrided by ultisnips

### ISSUE THREAD

**Issue by yehuohan** [SirVer/ultisnips#924]
my vmap for <tab> is overrided by ultisnips, because my g:UltiSnipsExpandTrigger = `<tab>`
Is there an options to only cancel ultisnips's vmap for g:UltiSnipsExpandTrigger?

**Comment by lacygoill** [comment]
Try to add this code, in your `vimrc`, after you have defined your `Tab` mapping in visual mode:

    let s:vtab_save = maparg('<tab>', 'v', 0, 1)
    augroup restore_visual_tab
        au!
        au VimEnter * call s:restore_visual_tab(s:vtab_save) | unlet! s:vtab_save
    augroup END

    fu! s:restore_visual_tab(maparg) abort
        let maparg = a:maparg
        exe maparg.mode
        \. (maparg.noremap ? 'noremap   ' : 'map ')
        \. (maparg.buffer  ? ' <buffer> ' : '')
        \. (maparg.expr    ? ' <expr>   ' : '')
        \. (maparg.nowait  ? ' <nowait> ' : '')
        \. (maparg.silent  ? ' <silent> ' : '')
        \.  maparg.lhs
        \. ' '
        \. substitute(
        \             substitute(maparg.rhs, '<SID>', '<SNR>'.maparg.sid.'_', 'g'),
        \             '|', '<bar>', 'g')
    endfu

**Comment by yehuohan** [comment]
Thank you and i'll try.
