### ISSUE TITLE
Can't see highlighted fields after expansion

### ISSUE THREAD

**Issue by hosfordryan** [SirVer/ultisnips#925]
How can I change the highlight and text color for the fields that you can change after expanding a snippet.
For example, if I use a "for" snippet, it highlights the terminating value with the same color as the text.

Is there a way to change the highlight color?
I'm sorry if I didn't explain my issue very well.

Here is a screenshot of the problem.
![image](https://user-images.githubusercontent.com/12596931/35081655-f513bfe0-fbda-11e7-89f6-a3943afe162e.png)

**Comment by lacygoill** [comment]
Try this code:

     augroup custom_visual_hg
         au!
         au User UltiSnipsEnterFirstSnippet call s:setup_visual_hg()
         au User UltiSnipsExitLastSnippet   call s:teardown_visual_hg()
     augroup END

     fu! s:teardown_visual_hg() abort
         let [ctermfg, guifg] = [matchstr(s:hg_visual_save, 'ctermfg=\zs\S\+'),
         \                       matchstr(s:hg_visual_save, 'guifg=\zs\S\+')]
         let [ctermfg, guifg] = [!empty(ctermfg) ? 'ctermfg='.ctermfg : '',
         \                       !empty(guifg)   ? 'guifg='.guifg     : '']
         exe printf("hi Visual %s %s", ctermfg, guifg)
     
         let [ctermbg, guibg] = [matchstr(s:hg_visual_save, 'ctermbg=\zs\S\+'),
         \                       matchstr(s:hg_visual_save, 'guibg=\zs\S\+')]
         let [ctermbg, guibg] = [!empty(ctermbg) ? 'ctermbg='.ctermbg : '',
         \                       !empty(guibg)   ? 'guibg='.guibg     : '']
         exe printf("hi Visual %s %s", ctermbg, guibg)
     endfu
     
     fu! s:setup_visual_hg() abort
         let s:hg_visual_save = execute('hi Visual')
         hi! link Visual IncSearch
     endfu

Replace `IncSearch` with the name of the highlighting you want to use.

**Comment by andreyorst** [comment]
Can you see text while you're using select mode? to enter select mode, first enter visual mode then press <kbd>Ctrl</kbd>+<kbd>G</kbd>
