### ISSUE TITLE
Enter replace mode at tab stop.

### ISSUE THREAD

**Issue by codybuell** [SirVer/ultisnips#928]
Is there a way to enter into Replace mode at a tab stop?

I have a comment block snippet:

```vim
snippet // "comment block" b
////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// ${0}  <---- want to add bits here while keeping this aligned right ---->   //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////
endsnippet
```

Tried the following with no success:

```
${0}`!v execute("normal! R")`
```

As well as:

```vim
post_expand "vim.command(\"exe ':normal R'\")"
snippet // "comment block" bm
////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// ${0}                                                                       //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////
endsnippet

**Comment by ColinKennedy** [comment]
I'd also like to know that answer to this, though for a slightly different purpose. I want a snippet that returns back to Normal mode, once its done expanding. I've tried several methods and syntaxes - using post_expand, post_jump, using vimscript or using python to call vimscript. I haven't found a method to do it yet.

For reference, this is the kind of syntax I was expecting, which is nearly the same as @codybuell 's code.

    post_expand "vim.command('stopinsert')
    snippet test "A test snippet"
    testout
    endsnippet
    
or maybe something like
    
    snippet test2 "Another test"
    testout`!v execute("normal! \<esc>")`
    endsnippet

**Comment by lacygoill** [comment]
@codybuell Try this:

    post_expand "vim.command('call timer_start(0, {-> feedkeys(\"\eR\", \"in\")})')"
    snippet // "comment block" b
    ////////////////////////////////////////////////////////////////////////////////
    //                                                                            //
    // ${0}  <---- want to add bits here while keeping this aligned right ---->   //
    //                                                                            //
    ////////////////////////////////////////////////////////////////////////////////
    endsnippet

Or maybe this:

    post_jump "if snip.tabstop == 0: vim.command('call timer_start(0, {-> feedkeys(\"\eR\", \"in\")})')"
    snippet // "comment block" b
    ////////////////////////////////////////////////////////////////////////////////
    //                                                                            //
    // ${0}  <---- want to add bits here while keeping this aligned right ---->   //
    //                                                                            //
    ////////////////////////////////////////////////////////////////////////////////
    endsnippet

@ColinKennedy 

Try this:

    post_expand "vim.command('call timer_start(0, {-> feedkeys(\"\e\", \"in\")})')"
    snippet test "A test snippet"
    testout
    endsnippet

**Comment by ColinKennedy** [comment]
Works and also runs in realtime. This is perfect. Thank you!

**Comment by codybuell** [comment]
@lacygoill Ah, clever!  Works very well!

**Comment by reportaman** [comment]
@lacygoill What is the reason for ``timer_start``, why can't one just call use ``feedkeys`` in ``vim.command``?

**Comment by lacygoill** [comment]
I don't know.  But if something doesn't work at the time it's run, while it would work now, then there's a good chance that delaying it fixes the issue.  Maybe ultisnips resets the mode to insert mode at the end of the post_expand callback.

**Comment by SirVer** [comment]
@reportaman The timer guarantees reproducably when the feedkeys is executed. If you do it while inside the python invocation directly, it happens somewhere in between UltiSnips doing its work and Vim doing its work. It depends on your snippet when and how it is executed and it can confuse UltiSnips greatly.
