### ISSUE TITLE
Applying python code while typing

### ISSUE THREAD

**Issue by 3e4** [SirVer/ultisnips#933]
Hello,

I am using UltiSnips and love it. Recently I am learning c++ and write a lot of small shell programs. I thought it would be nice to have a "banner" in each program, shown when executing the program. Something like 

    ***************************
    * A two line comment      *
    * This is the second line *
    ***************************

The actual code for this looks like this:

    std::cout << "***************************" << std::endl;
    std::cout << "* A two line comment      *" << std::endl;
    std::cout << "* This is the second line *" << std::endl;
    std::cout << "***************************" << std::endl;

So after long tinkering, I found a way to do this with UltiSnips and the `post_jump` directive. My full snippet looks like this:

```
global !p
import vim
import re

def banner(text):
	'''
	This function re-formats the multiline banner
	'''
	if len(text) == 3:
		# Its a single line of text so we leave handling to UltiSnips
		return text
	else:
		# This is multiline entry. So we need some modification.
		# 1) get indentation
		mtch = re.match(r'^(\s*).*', text[0])
		indent = mtch.groups()[0]

		# 2) Extract user input text
		temptext = []
		for i,line in enumerate(text[1:-1]):
			line = re.sub(r'^\s*', '', line)
			if i == 0:
				temptext.append(re.sub(r'std::cout << "\* ', '', line))
			elif i == (len(text)-3):
				temptext.append(re.sub(r' \*" << std::endl;$', '', line))
			else:
				temptext.append(line)

		# 3) Get length of upper and lower frame line
		width = max([len(l) for l in temptext]) + 2

		# 4) Construct output array
		out = []
		out.append(indent + 'std::cout << "*' + width*'*' + '*" << std::endl;')
		for line in temptext: # The actual typed text
			padding = width - len(line) - 2
			out.append(indent + 'std::cout << "* ' + line + padding*' ' + ' *" << std::endl;')
		out.append(indent + 'std::cout << "*' + width*'*' + '*" << std::endl;')
		return out

endglobal

post_jump "if snip.tabstop == 0: snip.buffer[snip.snippet_start[0]:snip.snippet_end[0]] = banner(snip.buffer[snip.snippet_start[0]:snip.snippet_end[0]])"
snippet banner "A framed banner to cout that can span multiple lines" b
std::cout << "**`!p snip.rv = getwidth(t[1])*'*'`**" << std::endl;
std::cout << "* ${1:${VISUAL:Banner}} *" << std::endl;
std::cout << "**`!p snip.rv = getwidth(t[1])*'*'`**" << std::endl;
$0
endsnippet
```

*Usage*: ``<tab>banner<tab>Line 1<Enter>Line 2<C-j>``
*Result*: (note the indentation of the whole block corresponding to the first <tab>)
```
    std::cout << "**********" << std::endl;
    std::cout << "* Line 1 *" << std::endl;
    std::cout << "* Line 2 *" << std::endl;
    std::cout << "**********" << std::endl;
    
```

I feel this is a bad hack and it requires the final jump to ``$0``. So is there any other/better way in UltiSnips to implement such a snippet? One that shows the final output live?

I have looked at Transformations, but this doesn't seem to help here?

**Comment by SirVer** [comment]
You might find inspiration in https://github.com/honza/vim-snippets/blob/master/UltiSnips/all.snippets#L22 which draws nice boxes and is quite similar to what you want.
