### ISSUE TITLE
cst same line doesn't work

### ISSUE THREAD

**Issue by dylnmc** [SirVer/ultisnips#941]
`:call feedkeys("cstt" . "canvas" . "\<cr>")` (illustratively) or `csttcanvas<cr>` (in practice)

on code such as

```
<[d]iv id="imACanvas" width="1" height="1></div>
```

(`[d]` is just `d` but the cursor is on it) __will do nothing__.

Fix needed. This is impractical and should not go ignored. (I couldn't find an issue regarding this, but it's a fix  worth second spent fixing it.)

**Comment by andreyorst** [comment]
I'm not sure what sould be done, and how it is connected to ultiisnips. Assuming that filetype is `html`, i've tryed to reproduce it with and without Ultisnips, and the result of manually typing `csttcancas<cr>` is visually selected line:
![image](https://user-images.githubusercontent.com/19470159/38452945-88e145e4-3a56-11e8-89e2-755284f71546.png)

Can you please provide more clean explanations of what should happen, what happens instead, and what fix you asking? Ideally see [CONTRIBUTING.md#reproducing-bugs](https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs), and if possible provide a docker repo, that can show working `csttcanvas<cr>` on some code.

**Comment by dylnmc** [comment]
I think I meant to put this in the `surround.vim` plugin by tpope. Sorry
