### ISSUE TITLE
When expanding trigger in Visual mode, the last character gets truncated

### ISSUE THREAD

**Issue by i-give-up** [SirVer/ultisnips#943]
Environment: Windows 8.1, Vim 8.0, UltiSnips commit https://github.com/SirVer/ultisnips/commit/423f264e753cec260b4f14455126e6db7ba429af

Example snippet

```
snippet t
<tag>${VISUAL}</tag>
```

Input: `hello whirl`

Expected output: `<tag>hello whirl</tag>`

Actual output: `<tag>hello whir</tag>` (i.e. `l` at the end is truncated)

## Cause

In [this commit](https://github.com/SirVer/ultisnips/commit/5a7ec5cea2824f443fbd9b70f67ab67fd8b47a54), code was added to remove the last character of visual-selected text

https://github.com/SirVer/ultisnips/blob/5a7ec5cea2824f443fbd9b70f67ab67fd8b47a54/pythonx/UltiSnips/text_objects/_visual.py#L46-L50

I don't know why it was added but it causes this issue. 

## Solution

Change the if-else block with a single line

    text = self._text

I have to restart Vim for the change to take effect.

**Comment by andreyorst** [comment]
Don't give up! Can ypu please propose a PR?

**Comment by j3soon** [comment]
I think this is fixed in #926.

**Comment by andreyorst** [comment]
gently ping @i-give-up. Can you please test lastest master, with #926 merged?

**Comment by i-give-up** [comment]
Yes. It's fixed. Thanks guys.

**Comment by dbatten5** [comment]
Is anyone else experiencing this issue again? 
Environment: nvim 0.8, MacOS 11.5.2, UltiSnips commit e99fdf15cd55a4a8e0cb0a80a6810c1867a5c401

**Comment by RiccardoBarbieri** [comment]
Yes, I just noticed the issue and stumbled upon this thread. I'm at the same commit as @dbatten5

**Comment by dbatten5** [comment]
@RiccardoBarbieri as a workaround i ended up commenting out this line in `pythonx/UltiSnips/text_objects/visual.py`
```python
line 56:            # text = text[:-1]  # Strip final '\n'
```
and that fixed the issue
