### ISSUE TITLE
UltiSnips#CursorMoved() slow in combination with CtrlP after a snippet is loaded

### ISSUE THREAD

**Issue by paulgeringer** [SirVer/ultisnips#944]
Note: See edit at the bottom for deeper debugging.

This feels like a strange report, as it's a combination of two different plugins. If this should go in as an issue with kien/CtrlP instead, let me know.

Steps:
1. Open vim in a project
2. Expand a snippet
3. Open CtrlP and try to look up a file
  a. Observe sluggishness

After I expand a snippet, if I open up CtrlP to search for a file, CtrlP grinds to a halt and Vim becomes nearly unresponsive for a period of time. I noticed this particularly with a large python snippet, but was able to reproduce with a small snippet, shown here (case 1):

```
snippet test
do a thing $1
do a thing again $1
endsnippet
```
After running this with profiling in vim, the main noteworth thing I see is:

```
FUNCTION  UltiSnips#CursorMoved()
Called 15 times
Total time:   6.053575
 Self time:   6.053575

count  total (s)   self (s)
   15              6.053555     exec g:_uspy "UltiSnips_Manager._cursor_moved()"
```

As a check, if I _don't_ open up CtrlP and just move around and type a bit after expanding the snippet, I don't see a performance hit, and vim is responsive (case 2):

```
FUNCTION  UltiSnips#CursorMoved()
Called 13 times
Total time:   0.006513
 Self time:   0.006513

count  total (s)   self (s)
   13              0.006503     exec g:_uspy "UltiSnips_Manager._cursor_moved()"
```

The bigger the snippet (or possibly the more tabstops within a snippet), the more time this function takes. 

Let me know if you want me to attach the full profile log (nothing seems to be called significantly more/differently between the two cases _besides_ this single slow function call).

**Edit**:
I did a bit more debugging (with some super gross print statements and inspecting `:messages` output) and was able to find that the majority of time was spent [calculating this diff](https://github.com/SirVer/ultisnips/blob/5352d98f212e273b3e8b1d84efdbe2d6a6d557e9/pythonx/UltiSnips/snippet_manager.py#L333) (up to several seconds in some cases). The code around that diff function looks to be quite complex, but I'll try to dive in there tomorrow (3/21/18) and see if I can't further narrow this down and possibly find something that can be refactored.

**Comment by SirVer** [comment]
Very likely that Ctrl-P does not trigger an event on Window exit, which will confuse the hell out of UltiSnips and trigger an expensive diff operation on every move. I consider this a bug in CtrlP. Closing as Won't fix.
