### ISSUE TITLE
how to directly autocompletion when I typed <cr>

### ISSUE THREAD

**Issue by werckdd** [SirVer/ultisnips#945]
How to directly autocompletion when I typed <cr>? when i typed <cr> ,the annoying messages below just showed.I can't get the expand expression until i typed 1. I can't find solution from doc.
![1](https://raw.githubusercontent.com/werckdd/PhotosRpo/master/2018%3A3%3A23/QQ20180323-000107.png)
here is my nvim configure
```
" fzf.vim and ultisnips-------------------------------------------------------------------{{{

  set rtp+=/usr/local/opt/fzf

  " ultisnips
    let g:UltiSnipsSnippetDirectories = ['/Users/qj/.config/nvim/UltiSnips']
  " set rtp+=/Users/qj/.config/nvim/ultisnips
  " Trigger configuration. Do not use <tab> if you use https://github.com/Valloric/YouCompleteMe.
        let g:UltiSnipsExpandTrigger = '<C-j>'
	let g:UltiSnipsJumpForwardTrigger = '<C-f>'
	let g:UltiSnipsJumpBackwardTrigger = '<C-b>'
	" let g:UltiSnipsListSnippets="<c-s-j>"
	" If you want :UltiSnipsEdit to split your window.
	let g:UltiSnipsEditSplit="vertical"
"}}} 
```

**Comment by SirVer** [comment]
The screenshot also shows some sort of completion engine, so the vimrc is at best partial. This cannot be reproduced without further data.
