### ISSUE TITLE
Custom snippets doesn't work

### ISSUE THREAD

**Issue by notaduck** [SirVer/ultisnips#948]
It seems that my own snippets added with `UtilSnipsEdit` doesn't work, however snippets from `hpnza/vim-snippets` works just fine.

- NeoVim => `0.2.2` 
- Plugin manager => vim-plug   
  

pice of init.vim:
```
 " UtilSnips {{{

let g:UltiSnipsSnippetDirectories = ['~/.vim/UltiSnips', 'UltiSnips']

 " Trigger configuration. Do not use <tab> if you use https://github.com/Valloric/YouCompleteMe.

let g:UltiSnipsExpandTrigger="<a-tab>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"

" If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit="vertical"

	" }}}

```

```
$ ls UltiSnips/
xml.snippets
```

```
$ cat xml.snippets 
snippet tagc "description"
<OSMWayType> $1 </OSMWayType>
$0 
```

According to me it looks like everything should be okay, however if I type `tagc` in a `.xml` file and `A-tab` nothing happends.

**Comment by andreyorst** [comment]
I'm expiriencing the same issue. For two weeks already.
I've installed ultisnips, created some snippets, and nothing happened. I've double checked documentation, and even vimcasts, on youtube, but still nothing. I already started to think that Ultisnips isn't workiing at all, until I've installed `hpnza/vim-snippets`, and ultisnips started to work with them, but not with my own snippets.

I'm using `neovim` from master branch with `Vundle` as a plugin manager.
![image](https://user-images.githubusercontent.com/19470159/37961753-c914863c-31c1-11e8-86a9-d166f7f1fd39.png)
I have pretty huge config for ultisnips, so I'll [post a link to it](https://github.com/andreyorst/dotfiles/blob/7393f7c209677d4b7b3ede57c2914a4e5c3cbcb1/config/nvim/plugin_configs.vim#L122), rather then copypaste it here.

This also can be reproduced with minimal `init.vim` containing only Ultisnips plugin and [theese recomendations](https://github.com/SirVer/ultisnips#quick-start)

**Comment by andreyorst** [comment]
@notaduck I guess the project is dead or unmaintained. Last commit 423f264 was on Jun 2017, almost a year. As stated in 3.0 release notes, current maintainer is @seletskiy, but it was back in 2015.

As a quick solution for this issue, I can recommend adding your own snippets directly into `hpnza/vim-snippets` plugin files, it's not great solution, but it works, at last.

**Comment by andreyorst** [comment]
@notaduck Or as a better solution, you can symlink your `ft.snippet` file to `path/to/honza's/plugin/vim-snippets/UltiSnips/` as `ft_my.snippets`. It will work too. However it iis still a silly workaround.

**Comment by bartekb81** [comment]
I had a similar issue... I took a look at the source code (`bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/ultisnips.py`) and there was nothing suspicious there. And then I thought about replacing the tilde in the path with full path (and adjust the case of 'UltiSnips' suffix):

```
let g:UltiSnipsSnippetDirectories = ['/home/bartek/.vim/ultisnips']
```

it helped, my custom snippets are loading now.

**Comment by andreyorst** [comment]
indeed. It works. Strange. I thought I've tried that. However `~/` should also work, because `:UltiSnipsEdit` opend file corectly.

**Comment by notaduck** [comment]
Thanks guys! using the absolute path worked for me as well!
However I do belive `~/` should work as @andreyorst  says

**Comment by pingsoli** [comment]
I found the Ultisnips works perfectly when youcompleteme enabled.

I don't know what happen ?

**Comment by Gluzifer** [comment]
For me UltiSnips will find my custom snippets only if I specify the whole path in for `:UltiSnipsSnippetDirectories`.
However for `:UltiSnipsSnippetsDir` using `~/` works fine for me.

So it now looks someting like this in my (nvim) config:
`let g:UltiSnipsSnippetsDir = '~/myUltiSnips/'
  2 let g:UltiSnipsSnippetDirectories=["/home/username/myUltiSnips", "UltiSnips"]`

**Comment by aranmohyeddin** [comment]
I have no idea what is going on. none of these solutions worked for me then at some point it started working. maybe after I added this: `let g:UltiSnipsSnippetsDir = '~/myUltiSnips/'` but then I removed every config line! and it's still working even after a restart.

**Comment by mar-muel** [comment]
@aranmohyeddin The exact same thing happened to me. I'm not claiming to fully understand what's going on but what eventually worked for me was to remove the `g:UltiSnipsSnippetsDir` option and just add
```
let g:UltiSnipsSnippetDirectories=[$HOME.'/dotfiles/snippets', 'UltiSnips']
```
Also I made my first snippet not contain any interpreted code and made it very simple (however, I'm not sure if that made a difference in the end).

Hope this helps whoever comes across this!

**Comment by SirVer** [comment]
For everybody being confused in this thread, please go and read `How snippets are loaded`: https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L535. Unfortunately, the semantics of `g:UltiSnipsSnippetsDir` and `g:UltiSnipsSnippetDirectories` are not a bit intertwined and convoluted, but it is all spelled out there. 

I still think #1085 makes sense.

**Comment by solomonxie** [comment]
My approach is like:

```vim
let $HOME = expand('~')
let g:UltiSnipsSnippetsDir = $HOME."~/.vim/mysnippets"
let g:UltiSnipsSnippetDirectories=[$HOME.'/.vim/mysnippets']
```

Notice that, it will NOT work if you expand & assign at the same time:
```vim
let g:UltiSnipsSnippetDirectories=[expand('/.vim/mysnippets')]
```
