### ISSUE TITLE
UltiSnips Errors in Some Files with either NameError: or ImportError:

### ISSUE THREAD

**Issue by abair** [SirVer/ultisnips#958]
# Search Strings for this Issue

This is likely the issue for you, if you're searching for either of these two error messages:

1. `NameError: name 'UltiSnips_Manager' is not defined`
2. `ImportError: No module named UltiSnips`

# Symptoms

This issue may occur:
* only in some files,
* upon some different ways of invoking Vim (I.e. `git commit`),
* or every single time Vim is used,
* but it's going to be consistently reproducible once it's encountered.

An error message will be triggered:
* either on every keystroke while in Insert Mode,
* or any time an attempt is made to expand a snippet via the expand trigger (default <tab>).

The error will always contain a Python error such as a NameError or ImportError.  The full text of the two specific errors I've seen before is included below.

Here is the complete error message generated by Vim that includes search string 1 from above:

```
Error detected while processing function UltiSnips#TrackChange:
line    1:
Traceback (most recent call last):
Press ENTER or type command to continue

Error detected while processing function UltiSnips#TrackChange:
line    1:
  File "<string>", line 1, in <module>
Press ENTER or type command to continue

Error detected while processing function UltiSnips#TrackChange:
line    1:
NameError: name 'UltiSnips_Manager' is not defined
Press ENTER or type command to continue
```

... And here is the complete error message generated by Vim that includes search string 2 from above:

```
Error detected while processing /Users/username/.vim/bundle/ultisnips/autoload/UltiSnips.vim:
line    8:
Traceback (most recent call last):
Press ENTER or type command to continue

Error detected while processing /Users/username/.vim/bundle/ultisnips/autoload/UltiSnips.vim:
line    8:
  File "<string>", line 1, in <module>
Press ENTER or type command to continue

Error detected while processing /Users/username/.vim/bundle/ultisnips/autoload/UltiSnips.vim:
line    8:
ImportError: No module named UltiSnips
Press ENTER or type command to continue

















Error detected while processing function UltiSnips#TrackChange:
line    1:
Traceback (most recent call last):
Press ENTER or type command to continue

Error detected while processing function UltiSnips#TrackChange:
line    1:
  File "<string>", line 1, in <module>
Press ENTER or type command to continue

Error detected while processing function UltiSnips#TrackChange:
line    1:
NameError: name 'UltiSnips_Manager' is not defined
Press ENTER or type command to continue
```

# Current Understanding

I've been reading through the issue tracker trying to find a solution.  There are several similar issues, and reading lots of them has lead me to the conclusions in this issue report.  It kind of feels like a dup, but I don't know exactly which issues it's a dup of, and I hope this issue becomes a solution instead of more noise.

When this issue presents itself, it is because Python can't find a Python module for UltiSnips.  Since I'm using macOS High Sierra, this is almost certainly not an UltiSnips bug, per se, but another classic frustration of macOS, its system binaries, package manager packages, etc.  It may turn out to be an UltiSnips "bug" in that there may be something UltiSnips can do about it.  I'm unsure of that as I don't know much about Vim plugins and whatever Vim's PythonX is.

As for environment, I'm using:
* macOS High Sierra
* Homebrew Vim with +python3
  - I've tried with both python3 and python2.
* UltiSnips latest as of Tue Apr 3, 2018

It appears that the root cause is sometimes launching a different version of Vim without realizing it.  This is consistent with the many reports of the issue appearing or not appearing when using Vim vs GVim vs MacVim vs NeoVim, and could be the cause of the issue on other platforms as well.  (I.e. Linux and Windows.)

Also, don't forget that a system can have not only multiple flavors of Vim installed, such as GVim and Vim, but also multiple versions of each flavor.  This means that running `vim --version` will NOT necessarily tell you what version of Vim is causing the trouble, if the trouble is being caused by a particular flavor, or worse, a particular version of a given flavor of Vim.

# Solution

It seems, for now, that the root of the problem for me is that I use Vim via the CLI most of the time, but, occasionally, I'll allow another command to invoke vim for me, such as `git commit`.  So `vim --version` would give the version info for when UltiSnips is working correctly.  I need to open Vim in such a way as to cause the error to occur, and grab that Vim's version.  Below is the output of `:version` from a working Vim session followed by the output from a buggy one that was started by Git via `git commit`.

### Works Fine

```
:version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 30 2018 07:37:16)
macOS version
Included patches: 1-1650
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               -dnd               +listcmds          +postscript        +timers
+arabic            -ebcdic            +localmap          +printer           +title
+autocmd           +emacs_tags        -lua               +profile           -toolbar
-autoservername    +eval              +menu              -python            +user_commands
-balloon_eval      +ex_extra          +mksession         +python3           +vertsplit
+balloon_eval_term +extra_search      +modify_fname      +quickfix          +virtualedit
-browse            +farsi             +mouse             +reltime           +visual
++builtin_terms    +file_in_path      -mouseshape        +rightleft         +visualextra
+byte_offset       +find_in_path      +mouse_dec         +ruby              +viminfo
+channel           +float             -mouse_gpm         +scrollbind        +vreplace
+cindent           +folding           -mouse_jsbterm     +signs             +wildignore
-clientserver      -footer            +mouse_netterm     +smartindent       +wildmenu
+clipboard         +fork()            +mouse_sgr         +startuptime       +windows
+cmdline_compl     -gettext           -mouse_sysmouse    +statusline        +writebackup
+cmdline_hist      -hangul_input      +mouse_urxvt       -sun_workshop      -X11
+cmdline_info      +iconv             +mouse_xterm       +syntax            -xfontset
+comments          +insert_expand     +multi_byte        +tag_binary        -xim
+conceal           +job               +multi_lang        +tag_old_static    -xpm
+cryptv            +jumplist          -mzscheme          -tag_any_white     -xsmp
+cscope            +keymap            +netbeans_intg     -tcl               -xterm_clipboard
+cursorbind        +lambda            +num64             +termguicolors     -xterm_save
+cursorshape       +langmap           +packages          +terminal
+dialog_con        +libcall           +path_extra        +terminfo
+diff              +linebreak         +perl              +termresponse
+digraphs          +lispindent        +persistent_undo   +textobjects
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -
D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/open
ssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -framework AppKit
  -mmacosx-version-min=10.13 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.26.1/li
b/perl5/5.26.1/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc  -L/usr/local/opt/python/Frameworks/P
ython.framework/Versions/3.6/lib/python3.6/config-3.6m-darwin -lpython3.6m -framework CoreFoundation  -lru
by.2.5.1 -lobjc
Press ENTER or type command to continue
```

### Buggy

```
:version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul 26 2017 19:10:24)
Included patches: 1-503, 505-642
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
+acl             -clipboard       +dialog_con      +file_in_path    +job             -lua             -mouse_sgr       +path_extra      -rightleft       +tag_old_static  +user_commands   +writebackup
-arabic          +cmdline_compl   +diff            +find_in_path    +jumplist        +menu            -mouse_sysmouse  -perl            +ruby/dyn        -tag_any_white   +vertsplit       -X11
+autocmd         +cmdline_hist    +digraphs        +float           -keymap          +mksession       -mouse_urxvt     +persistent_undo +scrollbind      -tcl             +virtualedit     -xfontset
-balloon_eval    +cmdline_info    -dnd             +folding         +lambda          +modify_fname    +mouse_xterm     +postscript      +signs           -termguicolors   +visual          -xim
-browse          +comments        -ebcdic          -footer          -langmap         +mouse           +multi_byte      +printer         +smartindent     +terminfo        +visualextra     -xpm
+builtin_terms   -conceal         -emacs_tags      +fork()          +libcall         -mouseshape      +multi_lang      -profile         +startuptime     +termresponse    +viminfo         -xsmp
+byte_offset     +cryptv          +eval            -gettext         +linebreak       -mouse_dec       -mzscheme        +python/dyn      +statusline      +textobjects     +vreplace        -xterm_clipboard
+channel         +cscope          +ex_extra        -hangul_input    +lispindent      -mouse_gpm       +netbeans_intg   -python3         -sun_workshop    +timers          +wildignore      -xterm_save
+cindent         +cursorbind      +extra_search    +iconv           +listcmds        -mouse_jsbterm   +num64           +quickfix        +syntax          +title           +wildmenu
-clientserver    +cursorshape     -farsi           +insert_expand   +localmap        -mouse_netterm   +packages        +reltime         +tag_binary      -toolbar         +windows
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L/usr/local/lib -o vim        -lm -lncurses  -liconv -framework Cocoa
Press ENTER or type command to continue
```

Notice the good session is "Compiled by Homebrew" and has -python and +python3 while the bad version is "Compiled by root@apple.com" and has -python3 and +python/dyn.

I'll try to fix the issue for me by ensuring Vim is always launched as the correct version from tools like `git commit`.  If there's any way UltiSnips can work in other versions of Vim, that'd be great, but I doubt that.  It'd be nice to have some kind of detection that disables UltiSnips for the session with a message when it's going to run into odd Python issues, though.  I'm not sure that's doable either.

# Other

One issue suggested turning off UltiSnips auto command in ~/.vimrc, but I found that it isn't available to be disabled at the time the rc is sourced.  Setting `au! UltiSnips_AutoTrigger` in .vimrc results in the following error message at startup:

```
Error detected while processing /Users/username/.vimrc:
line  176:
E216: No such group or event: UltiSnips_AutoTrigger
Press ENTER or type command to continue
```

However, once Vim is open, the command `:au! UltiSnips_AutoTrigger` can be executed.  This will allow typing in Insert Mode without the Python error on every keystroke.  An error is still triggered if an attempt is made to expand a snippet.

**Comment by abair** [comment]
# This Solved it for Me

Ok, so forcing other tools to choose the correct version of Vim fixed the issue for me.  Digging around to figure out why some tools were using system Vim instead of Homebrew's Vim uncovered a silly mistake on my part.  My $EDITOR environment variable was unset!  Adding `export EDITOR=vim` to my shell's RC file resolved the issue in every case where I was seeing it.

I hope everyone eles is seeing this simple issue, or, at least, that the above info about versions and such helps find the root of your issue, too.

**Comment by evans** [comment]
@abair Thank you so much for investigating! Saved my 🥓
