### ISSUE TITLE
Snippet expanding problem

### ISSUE THREAD

**Issue by akemrir** [SirVer/ultisnips#970]
It doesn't expand all inline snippets, even if they are declared same way.

**Steps to reproduce**

`.vimrc`
```
if &compatible
  set nocompatible
endif

filetype plugin indent on

set rtp=~/.vimdebug

call plug#begin('~/.vimdebug/plugged')
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
Plug 'vim-ruby/vim-ruby'
call plug#end()

let g:UltiSnipsExpandTrigger="<C-s>"
let g:UltiSnipsJumpForwardTrigger="<C-j>"
let g:UltiSnipsJumpBackwardTrigger="<C-k>"
```

I`am testing on snippet declarations in ruby set.
edit .vimdebug/plugged/vim-snippets/snippets/ruby.snippets
delete all of them and paste this
```
snippet ea
	each { |${1:e}| ${0} }
snippet sel
	select { |${1:e}| ${0} }
```

1. create test.rb file
2. test.rb
3. type obj.ea`<c-s>`
4. it expands
5. type obj.sel`<c-s>`
6. it doesn't expand

ea expands even if line is very long
obj.each { |e|  }.each { |e|  }.each { |e|  }.ea`<c-s>`

I`ve checked without custom expand trigger, this problem persists.

Operating System:  Arch Linux
Vim: 
  VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb 26 2018 23:00:19)
  Zadane łaty: 1-1542
UltiSnips: 
  git rev-parse origin/master
  943156d8794772c23a0a0f6e5120c40b8c7981ec
Python inside VIM:
  3.6.4 (default, Jan  5 2018, 02:35:40)
  [GCC 7.2.1 20171224]
  2.7.14 (default, Jan  5 2018, 10:41:29)
  [GCC 7.2.1 20171224]

**Comment by andreyorst** [comment]
for me none of them expands.

**Comment by akemrir** [comment]
Don't forget to `:PlugInstall` after vim launch.

**Comment by SirVer** [comment]
Awesome repro steps!

vimSnippets does not support in word expanding. You actually never expand any of the snippets you present in your OP. When expanding `obj.ea`, you actually trigger https://github.com/honza/vim-snippets/blob/master/UltiSnips/ruby.snippets#L137.

You can verify by typing `obj.ea` and then hit the trigger key for listing snippets `<c-tab>` by default. Note that this key might be swallowed by your terminal, so you might need to set it to something else.

**Comment by akemrir** [comment]
SirVer you are completely right.
It looks mapping is not the case.
`.sel` expansion, similar to this you've pointed, was never there for UltiSnips.
Thanks for sorting this out.
