### ISSUE TITLE
NeoVim + UltiSnips don't work well

### ISSUE THREAD

**Issue by omtcvxyz** [SirVer/ultisnips#974]
**Steps to reproduce**

1. I wasn't able to build a minimalistic example of the issue, but here's my vimrc. Basically, install ultisnips, although I'm not sure anything else isn't interfering.

[first vimrc](https://github.com/SirVer/ultisnips/files/1911108/vimrc.txt) -- it uses Deoplete and actually misses few lines from the default config suggestions (like mapping `<tab>` to expand key), one might simply add few these lines, but it works even without those.
[second vimrc](https://github.com/SirVer/ultisnips/files/1911174/vimrc_updated.txt) -- this one doesn't have Deoplete at all, like described below.

2. `nvim file.cpp`
3. Try to expand a snippet. E.g. `ans<tab>`

My `~/.vim/UltiSnips/cpp.snippets` content is:
```
snippet ans "anonymous namespace"
namespace {
  ${VISUAL}$0
} // namespace
endsnippet
```

Hence, I expect the macro to expand. In fact, nothing happens.

4. Try `vim file.cpp` and do the same: `ans<tab>` -> The snippet expands!

Okay, that's weird. I first blamed it on Deoplete, but in fact even completely removing Deoplete and everything related and/or remapping snippet expansion key to e.g. `<Up>` or anything else does not change anything.

5. One more strange thing: install `honza/vim-snippets`. After that, the expansion works (using the same `<tab>` key, i.e. the only change from the config I posted is basically installed `honza/vim-snippets`). Not only the snippets brought by the plugin work, but my snippets (e.g. `ans`) work aswell.

All in all, I would very much like to have UltiSnips working without having to install `honza/vim-snippets`, because I don't really need it and I like calling my snippets using similar or same names.

-----
- **Operating System**: Arch Linux
- **Vim Version**: NeoVim v0.2.2, Vim 8.0 (Included patches: 1-1542)
- **UltiSnips Version**: HEAD: 64a023a7ec28d85a00badcaa9abe7490563597ed
- **Python inside Vim**:
```
3.6.4 (default, Jan  5 2018, 02:35:40)
[GCC 7.2.1 20171224]
```

**Comment by andreyorst** [comment]
[Neovim is currently not supported](https://github.com/SirVer/ultisnips/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22neovim+only%22+). However I'm using neovim with ultisnips, and it works for me without vim-snippets. I'm not seeing configured path to search snippets in your vimrc files. You saying that your snippet located in `~/.vim/UltiSnips/cpp.snippets`. Try to add ` let g:UltiSnipsSnippetDirectories=[$HOME.'/.vim/UltiSnips']` to your vimrc, and try again.

**Comment by SirVer** [comment]
Have you've done this? https://neovim.io/doc/user/nvim.html#nvim-from-vim. my guess is your Snippets are not found because they are not on the search path for NeoVim. Closing as this is quite definitley a neovim config issue, not an UltiSnips issue.

**Comment by acro5piano** [comment]
Hi, I had the same problem, and tried @andreyorst then fixed. Thanks!

**Comment by jdhao** [comment]
If you only use your own snippets, the answer by @andreyorst  may be ok. But if you also use vim-snippets,  you will find that a lot of snippets becomes inactive. 

For example, if you create a `markdown.snippets` under that directory and add the following snippet:

```
snippet kbd "keyboard tag"
<kbd>${1:KEY}</kbd>$0
endsnippet
```

Open a markdown file and the `kbd` snippet is available.  But many snippets provided [here](https://github.com/honza/vim-snippets/blob/master/UltiSnips/markdown.snippets) for markdown file by vim-snippets are invalid now.
