### ISSUE TITLE
Completion menu flickering

### ISSUE THREAD

**Issue by vimeitor** [SirVer/ultisnips#978]
Let me preface this by saying that I also use YouCompleteMe.

Since commit 4eac979, the completion menu flickers every time I press a key. There's a longstanding vim bug related to this (reported and with no progress, unfortunately), but the mentioned commit makes it 10x worse. I'm not completely sure how much of the issue Ultisnips is responsible for, because I also got asked to recompile YCM, and the issue appeared after recompiling it. I tried reverting YCM to an older version to no avail, so I have no idea what could be going on. Disabling ultisnips removes the flicker almost completely. Have you experienced anything similar? I'm tempted to open an issue on their repo, but I need to at least be able to point to some commit on their side.

- **Operating System**: Arch
- **Vim Version**: 8.0. Included patches: 1-1542                                                                                                                                                                                             
- **UltiSnips Version**: 30e651f
- **Python inside Vim**: 2.7.14, 3.6.5

**Comment by andreyorst** [comment]
I'll try to install YCM (eeegh) and repro it later this day. Does this still happens with minimal rc? I.E. with only ultisnips and ycm plugins enabled, and set?

**Comment by vimeitor** [comment]
Honestly, it's much harder to see with a minimal config. My theory is that there has got to be some sort of change in the main YCM repo that caused the flickering and that is exacerbated by that specific commit; otherwise, I'm lost. The thing is there's still some flickering sometimes, even if ultisnips is disabled; it's not nearly as bad as with ultisnips, but the flickering is there, and worst of all is I would swear it wasn't there before I compiled the new YCM.

**Comment by andreyorst** [comment]
I've seen a lot of issues in other completion plugins refered to popup flickering. It was stated somewhere that it is a problem of popup. 
> Honestly, it's much harder to see with a minimal config.

Then probably I wouldn't be able to repro it. because It may well be related to your whole work environment. Does there are other plugins who try to add theit item to completion poput except ycm and UltiSnips?

**Comment by vimeitor** [comment]
> Does there are other plugins who try to add theit item to completion poput except ycm and UltiSnips?

Not that I can tell.

> Then probably I wouldn't be able to repro it.

Do not worry about it. I really appreciate your time :-). I will git checkout the commit previous to the one I mentioned and will work with that.

**Comment by andreyorst** [comment]
This still may be a bug, so I'll reopen it if I could repro

**Comment by ashishtibrewal** [comment]
I'm facing a similar issue. I just checked with a minimal vimrc setup. YCM completion menu doesn't flicker at all when not using UlitSnips but flickers a lot when using it. Any help/suggestions on how to fix this would be appreciated. Thanks! 😊

![ycm](https://user-images.githubusercontent.com/8990952/48560570-093e4c80-e8e6-11e8-8030-3d51dd2327a9.gif)
