### ISSUE TITLE
include snippets in visual selection

### ISSUE THREAD

**Issue by ColinRyan** [SirVer/ultisnips#979]
I'd like to be able to run the command: `[v`]
and visually select everything input by my a snippet + everything I type out manually. 

**Expected behavior:**
run the command `[v`] and the snippet + everything we type out manually

**Actual behavior:**
only the input we've typed is selected

**Steps to reproduce**
enter insert mode, use a snippet, type a little, exit insert mode, run the command: `[v`]
see that it doesn't select the text input by the snippet

**Comment by SirVer** [comment]
I think it is questionable if a snippet expansion should still count to the current edit you do vs if it should be an edit on its own. Right now it is the latter.

However, even if one would decide that it should be folded together with your own typing, this is fairly hard to implement.

At this point I consider this a feature request and a not very popular one and tend to not think it is worthwhile trying to implement this. Thanks for the suggestion!
