### ISSUE TITLE
Snippets should get default spaces/tabs of vim on completion.

### ISSUE THREAD

**Issue by danbruegge** [SirVer/ultisnips#983]
**Expected behavior:**
Snippets should get default spaces/tabs of vim on completion. For example if my snippet has an indentation of 4 spaces but my current vim setting is for 2 spaces, the snippet should adjust this on the fly.

**Actual behavior:**
Snippet will use spaces/tabs defined in snippet.

**Comment by KabbAmine** [comment]
Use literal tabs in the snippet with `<C-v><Tab>` (`h i_Ctrl-v`), and they will be expanded as expected.

**Comment by danbruegge** [comment]
Wow, really nice. Thank you. :)

**Comment by unphased** [comment]
Thanks! I had some snippets that i created from scratch and ended up having 4-space tabs in them and got expanded literally. I had a suspicion that changing them to standard tabs would see the plugin expand them correctly.
