### ISSUE TITLE
ultisnips does wierd things with custom tab mappings

### ISSUE THREAD

**Issue by purpleP** [SirVer/ultisnips#984]
I've made a [video](https://youtu.be/Ei8kdykJOEA)

My config to reproduce cab be found [here](https://github.com/purpleP/vimconf). Relevant files  to reproduce I think are 
https://github.com/purpleP/vimconf/blob/master/dotvim/autoload/autocomplete.vim
https://github.com/purpleP/vimconf/blob/master/dotfiles/vimrc

I don't use `supertab`.

I've tried to debug this as much as I could, seems like `JumpForwards` functions doesn't work correctly. After the last tabstop it jumps to the wrong place while it shouldn't have jumped anywhere and as you can see `g:ulti_jump_forward_res` has wrong value.
Also I've stumbled on this about a year ago, so it's not a recent bug (if it is a bug).

**Comment by SirVer** [comment]
Cannot reproduce, this is what I tried:

```
make repro
cd
rm -rf ~/.vim
git clone https://github.com/purpleP/vimconf.git
ln -s /root/vimconf/dotfiles/vimrc /root/.vimrc
ln -s /root/vimconf/dotfiles/vimrc /root/.vimrc
vim
Error detected while processing function <SNR>8_AutoHighlight:
line    5:
E216: No such event: TextYankPost * call <SID>TurnOffOrKeepHL()
Error detected while processing /root/vimconf/dotvim/after/plugin/denite.vim:
line    2:
E117: Unknown function: denite#custom#source
line    3:
E117: Unknown function: denite#custom#map
line    4:
E117: Unknown function: denite#custom#map
line    5:
E117: Unknown function: denite#custom#map
line    6:
E117: Unknown function: denite#custom#map
line    8:
E117: Unknown function: denite#custom#var
line    9:
E117: Unknown function: denite#custom#source
line   10:
E117: Unknown function: denite#custom#var
line   11:
E117: Unknown function: denite#custom#var
line   12:
E117: Unknown function: denite#custom#var
Press ENTER or type command to continue
```

Seems like your configuration is incomplete and at least denite is missing. Please provide a fully reproducible example, ideally using the approach explained in https://github.com/SirVer/ultisnips/blob/master/CONTRIBUTING.md#reproducing-bugs or if not possible with a minimal `vimrc` and snippets files and an exact sequence of key strokes that trigger the bug.
