### ISSUE TITLE
ModuleNotFoundError:No Module Named 'ultisnipts'

### ISSUE THREAD

**Issue by SeAL80s** [SirVer/ultisnips#985]
**Expected behavior:**

**Actual behavior:**
In the Insert mode ,type anything will trigger error output .

:message output 

line    8:                                                                              
**ModuleNotFoundError: No module named 'UltiSnips'**                                 
Error detected while processing function UltiSnips#TrackChange:                         
line    1:                                                                              
Traceback (most recent call last):                                                      
Error detected while processing function UltiSnips#TrackChange:                         
line    1:                                                                              
  File "<string>", line 1, in <module>                                                  
Error detected while processing function UltiSnips#TrackChange:                         
line    1:                                                                              
**NameError: name 'UltiSnips_Manager' is not defined**

**Steps to reproduce**
In Insert mode ,type anything .

-----

- **Operating System**:ArchLinux x86_64 Python 2.7.15 and 3.6.5 
- **Vim Version**: vim 8.0-1838
- **UltiSnips Version**: 'git rev-parse origin/master' ==6fdc3647f72e0a1f321ea6bd092ecd01f7c187ba
- **Python inside Vim**: Python inside vim 2.7.15 and 3.6.5
- **Docker repo/vimrc**:https://gist.github.com/SeAL80s/202d3d2cca3b4938aee7563771b66863

**Comment by SeAL80s** [comment]
Problem magically gone after system reboot ,don't know why .

**Comment by storyn26383** [comment]
Dear @SeAL80s, 

Very useful for me, thanks a lot.
Problem magically gone after system reboot too...
