### ISSUE TITLE
Triggers not working

### ISSUE THREAD

**Issue by mrbig033** [SirVer/ultisnips#987]
**Expected behavior:** trigger should expand snippet

**Actual behavior:** triggers does nothing. I tested it with various mappings, other plugins disabled, other mappings and without any options.

**Steps to reproduce**

1. Use
```
let g:UltiSnipsExpandTrigger="<c-h>"
let g:UltiSnipsJumpForwardTrigger="<c-j>"
let g:UltiSnipsJumpBackwardTrigger="<c-k>"
let g:UltiSnipsEditSplit="vertical"

```
2. Snippet
```
snippet asciitable
[caption=""]
[width=$1{50}]
[cols=$2{2}*^,options=header]
.$3{title}
|===
| $4{Key}     | $5{Description}
| $6{Item1}   | $7{Descrition}
|===
$0
endsnippet
```

3. open an `*.adoc` file. Type `asciitable`. Hit \<c-h\>.

-----
- **Operating System**: MX LINUX 17
- **Vim Version**: NVIM v0.3.0-1029-g48967695c, Build type: RelWithDebInfo
- **UltiSnips Version**: 3.1. 
- **Python inside Vim**: 2.7.13 / 3.5.3.
- [init.vim](https://gitlab.com/mrbig/dotfiles/blob/master/nvim/init.vim)
- [dotfiles](https://gist.github.com/mrbig033/63fd7f4f51b6a8ae379abae74c52aff2)

**Comment by shmcgrath** [comment]
@mrbig033 Have you found any solutions? I am having the same issue. Snippets in the right place, when I run the edit, the snippet file is found. When I type out iitest, <tab>, nothing happens. Been banging my head against the wall all night.

**Comment by mrbig033** [comment]
Hello, @shmcgrath. I switched to Emacs shortly after I created this issue, so I'm afraid I can't provide any useful input. Good luck.

**Comment by diversemix** [comment]
I have the same issue too ... I've checked my filetype is `javascript` and `javascript.snippets` contains:

```
  1 snippet wow
  2 Wow!
  3 endsnippet
```
I enter insert mode and type `wow` then the sequence in `g:UltiSnipsExpandTrigger` and nothing happens :sob:

**Comment by lacygoill** [comment]
@diversemix 

What's your plugin manager?
In which directory is UltiSnips installed?
What's the sequence stored in `g:UltiSnipsExpandTrigger`?

**Comment by SirVer** [comment]
Please post a minimal vim setup, this has too little information to understand what might be wrong.

**Comment by arilebedey** [comment]
My issue with this was `let g:UltiSnipsSnippetDirectories=[$HOME.'/.config/nvim/Ultisnips']`
