### ISSUE TITLE
use of $VISUAL to override $1 having a default

### ISSUE THREAD

**Issue by unphased** [SirVer/ultisnips#988]
I have this snippet which was working great and now I've augmented it with a $VISUAL: 

```
snippet ok "Object.keys(object).map" !w
Object.keys(${VISUAL}${1:obj}).map(${3:k} => {
    var v = ${2:${VISUAL}$1[$3]};
    return v;
});

```

What happens here is when it is used with visual, the $1 is defaulted to `obj` and expanded. 

I would like to be able to have the $1 default to `obj` when not using visual, and when using visual to "override" that. So that if I use this on a visual of `m.collection` it doesn't produce: 

```
Object.keys(m.collectionobj).map(k => {
    var v = m.collectionobj[k];
    return v;
});
```

Hope that makes sense. I wonder if this capability is possible. As a workaround I would be editing my `${1:obj}` back to `$1`.

**Comment by tpoliaw** [comment]
If I'm understanding what you want to do correctly, I think you can use 

    snippet ok "Object.keys(object).map" !w
    Object.keys(${1:${VISUAL:obj}}).map(${3:k} => {
        var v = ${2:$1}[$3]};
        return v;
    });
    endsnippet

This will use the visual selection as the default for `$1` if in visual, and the value of `$1` for the default for `$2`

**Comment by unphased** [comment]
Thanks! Tricky logic, elegant implementation. I’ll close this once I confirm this works, nontrivial amount of test cases here 😀
