### ISSUE TITLE
How to make ultisnips ignore the indentations of a snippet?

### ISSUE THREAD

**Issue by LvChengbin** [SirVer/ultisnips#989]
I am writing my own snippets, and I want to add indents before the content of each snippet to make it more readable, for example, if there were a snippet like this:
```
snippet cls
    class ${1} {
        ${0:${VISUAL}}
    }
endsnippet
```
The result of this snippet will include the spaces before each line. How can I ask ultisnips to ignore that?
By the way, I found the snippets in `vim-snippets` can do what I want, but I don't know how.

**Comment by lacygoill** [comment]
Try to indent the lines inside your snippet with real tab characters. You can insert a tab character by pressing in insert mode `C-v` then `Tab`.

If you don't press `C-v` before `Tab`, Vim may expand your tab in a sequence of spaces if `'expandtab'` is set.

You can check whether your lines are indented with spaces by executing `:set list` to set the `'list'` option. A tab character should then be represented by `^I`, or by any character you have used in `'listchars'`.

For more information, see:

    :h UltiSnips-snippet-options

In particular, read the description of the `t` option:

    t   Do not expand tabs - If a snippet definition includes leading tab
        characters, by default UltiSnips expands the tab characters honoring
        the Vim 'shiftwidth', 'softtabstop', 'expandtab' and 'tabstop'
        indentation settings. (For example, if 'expandtab' is set, the tab is
        replaced with spaces.) If this option is set, UltiSnips will ignore the
        Vim settings and insert the tab characters as is. This option is useful
        for snippets involved with tab delimited formats.

It explains that UltiSnips expands the tab characters honoring the `'shiftwidth'`, `'softtabstop'`, `'expandtab'`, and `'tabstop'` settings.

If you have other usage questions, try to visit https://vi.stackexchange.com/ and tag your question with [plugin-ultisnips](https://vi.stackexchange.com/questions/tagged/plugin-ultisnips).

**Comment by SirVer** [comment]
UltiSnips does not have the feature of ignoring whitespace at the beginning of your snippet definitions.
