### ISSUE TITLE
Use Snippets from non-interactive Python script

### ISSUE THREAD

**Issue by andreashappe** [SirVer/ultisnips#991]
(sorry if I overlooked something in the documentation).

I'm writing technical reports with lots of ultisnips snippets. Currently I'm investigating the usage of python+mako to generate some of those reports and want to reuse my existing snippets during this generation step.

I've looked into the documentation and found ` 3.2.4 Direct use of Python API *UltiSnips-use-python-api*`. This seems to be the pythonic call of the completion method. What I rather would need is something like a python function/method that I can call with the snippet-name and a list of snippet-parameters and which then would return the filled out snippet (more or less a non-interactive version of Ultisnips).

Is this possible with the current python API? If not, could you give me a hint how to re-use my existing snippet library? Or is this something for which Ultisnips was never intended to be used? Thank you in Advance, Andreas

**Comment by SirVer** [comment]
No, this is currently not possible. UltiSnips is very tightly coupled to Vim, so you'd need a vim instance to actually get to the snippet output. My assumption is that you could put together a Vim script that uses `feedkeys` to execute a snippet & write it to a file and exit, but this is as good as it gets.
