### ISSUE TITLE
How to use snip.mkline with indent?

### ISSUE THREAD

**Issue by coaxial** [SirVer/ultisnips#992]
This is a question.

I can't figure out how to use `snip.mkline`:

```
snippet mysnip "Contrived example"
this is a line
`!p snip.rv = snip.mkline("Indented line", indent=2) if t[100] else ""`
${100:Hai}
endsnippet
```

But this results in an error. I also tried with `2` as a string: `"2"`.

This is most likely a result of my ignorance when it comes to Python. Nevertheless, how do I make a line that is indented by 2?

From here: https://github.com/SirVer/ultisnips/blob/64a023a7ec28d85a00badcaa9abe7490563597ed/pythonx/UltiSnips/text_objects/_python_code.py#L127 it looks as if when indent isn't `None`, it simply concatenates `indent + line`. Is it a bug or am I using it wrong?

**Comment by dileep-kishore** [comment]
@coaxial I think `indent` is supposed to take a string value.

For example, this adds a tab indentation:
`snip.mkline("Indented line", indent='\t')`

You can also try `snip >> 2`. This indents everything that follows the statement with two indent levels. Hope that helps!

**Comment by coaxial** [comment]
Thanks @dileep-kishore, I ended up using the `>> 2` trick.
