### ISSUE TITLE
DeprecationWarning: The imp module is deprecated in favour of importlib;

### ISSUE THREAD

**Issue by 9mm** [SirVer/ultisnips#996]
* Macvim 8.1-149_1
* VIM - Vi IMproved 8.1

**Expected behavior:**

Zero warnings

**Actual behavior:**

Upon typing any key after going into insert mode, it gives this warning.

**Steps to reproduce**

Open vim, enter insert mode, type any key.

**Comment by alaaibrahim** [comment]
This will happen when running any python3 (while using python3.7) in vim. not specific to Ultisnips.

See https://github.com/vim/vim/issues/3117

**Comment by dbmrq** [comment]
To anybody else who's having this issue, I think [this](https://github.com/vim/vim/issues/3117#issuecomment-402622616) is the best workaround:

> Regardless of installed plugins, silently execute python3 once on the top of your vimrc:
> 
> ```vim
> if has('python3')
>   silent! python3 1
> endif
> ```

**Comment by lacygoill** [comment]
The issue has been fixed in Vim with the [patch 8.1.0201](https://github.com/vim/vim/releases/tag/v8.1.0201).
