### ISSUE TITLE
Don't always call `UltiSnips#map_keys#MapKeys`

### ISSUE THREAD

**Issue by mitchellwrosen** [SirVer/ultisnips#999]
Would it be possible to add an option that configures whether or not UltiSnips calls `UltiSnips#map_keys#MapKeys` when loaded? Personally, I prefer to set all of my hotkeys manually. (I know you can override the default key bindings, but I actually don't want any key mappings to happen at all)

Much appreciated :)

**Comment by SirVer** [comment]
No, this is not easily possible. The background is that the way keys are mapped has changed over the years multiple times and actually contained bugs, see for example ba772b0d1 or bac9f17bac. If user create their own mappings, these bugs would permeate and lead to really cryptic bug reports against UltiSnips. 

The correct solutions are to provide `\<Plug>` mappings, which are younger than UltiSnips and therefore not incorporated. Also, they are buggy in Vim (see #1102 for the last attempt of using them and the bugs that we found it Vim with them). 

In the meantime, you can use a `~/.vim/after` script to unmap UltiSnips keys and remap them in that file again if your really want to. I would not recommend doing that as it only adds fragility.
